### ISSUE TITLE
how to set next's _config.yml when using hexo-renderer-pandoc [pandoc's config must be in root Hexo config]

### ISSUE THREAD

**Issue by sli1989** [theme-next/hexo-theme-next#10]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

hexo generate successfully and completely display equation

### Actual behavior 

when using `hexo-renderer-pandoc` (new version 0.2.1) in next (version 5.1.4 and 6.0.0), adding `if(config.template) args.push("--template=" + config.template);`  in `index.js` leads to `TypeError: Cannot read property 'template' of undefined` when `hexo generate`...  
Remove the `if(config.template) args.push("--template=" + config.template);`, it works.  
On the other hand,  according to the guideline in [hexo-renderer-pandoc](https://github.com/wzpan/hexo-renderer-pandoc) how to set pandoc `_config.yml` to avoid the undefined of  `template`   , thank you for your help.

```
pandoc:
  filters:
  extra:
  template:
  meta:
  mathEngine:
```
---
the guideline in [hexo-renderer-pandoc](https://github.com/wzpan/hexo-renderer-pandoc):

* `template` is a template file you wish to use when pandoc generates your posts:

```
template: dir/.../template.html
```

will be passed to pandoc as `--template=dir/../template.html`

The path of the template should be relative to the root of your blog.

For example, the very simple template

```
$if(toc)$
<div id="$idprefix$TOC">
$toc$
</div>
$endif$
$body$
```

prepends table of contents to all your posts if variable `--toc` is also passed. To enable TOC, add to your `_config.yml`:

```
pandoc:
  \# other options
  extra:
    - toc: \# will be passed as `--toc`. Note the colon
  template: dir/../template.html
```

---

besides, the menu bar & it's icon/Site'description/pages toc are all gone in next (version 6.0.0) may due to personalized setting...

the lists of personalized setting in next：

    - `next/layout/_macro/post.swig`
    - `next\layout\_layout.swig`
    - `\next\layout\_my`，
    - `next/layout/_third-party/search/localsearch.swig`
    - `next\layout\_partials\head.swig`
    - `next/layout/_partials/share/baidushare.swig`
    - `\next\layout\_partials\footer.swig`
    - `next/source/css/_variables/base.styl`
    - `next/source/css/_custom/custom.styl`
    - `next/source/css/_common/components/post/post-expand.styl`
    - `next/source/css/_common/components/post/post-reward.styl`
    - `next/languages/zh-hans`
    - `next/source/js/custom.js`

### Steps to reproduce the behavior 
1.  npm uninstall hexo-renderer-marked --save
2.  npm install hexo-renderer-pandoc --save
3.  `TypeError: Cannot read property 'template' of undefined` when `hexo generate`
4.  npm uninstall hexo-renderer-pandoc --save
5.  npm install hexo-renderer-marked --save
6.  successfully when `hexo generate`

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
"hexo": {
    "version": "3.4.4"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-generator-topindex": "^0.3.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-pandoc": "^0.2.1",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^3.0.2"
```

### Hexo Information

```

```

### Package dependencies Information

```

```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[x] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
Can u please provaide all possible links to same issue from @iissnan repo to close them later?

**Comment by sli1989** [comment]
@iissnan the lists of opened issues: [#2024](https://github.com/iissnan/hexo-theme-next/issues/2024)，[#1637](https://github.com/iissnan/hexo-theme-next/issues/1637)，[#2058](https://github.com/iissnan/hexo-theme-next/issues/2058)

**Comment by ivan-nginx** [comment]
@sli1989 Thank you!

**Comment by ivan-nginx** [comment]
So, what about here?

**Comment by sli1989** [comment]
still need to Romove the `if(config.template) args.push("--template=" + config.template);` in `hexo\node_modules\hexo-renderer-pandoc\index.js`.
i think it's the problem of the new version of `hexo-renderer-pandoc`, undefined of template

**Comment by ivan-nginx** [comment]
@sli1989 so, we can post this issue in [`hexo-renderer-pandoc`](https://github.com/wzpan/hexo-renderer-pandoc) and explain this, right? I can't to edit external repositories. :smiley:

**Comment by sli1989** [comment]
i have report the issue in that repo.

**Comment by sli1989** [comment]
in the new version of `hexo-renderer-pandoc`, a `template` option is [added](https://github.com/wzpan/hexo-renderer-pandoc/commit/8424495593f8c0ca0b5ef0d6cf6e8cd322c2f26d) in  configuration .
is there any possible to add corresponding settings in next? like set pandoc in theme's `_config.yml`.

**Comment by ivan-nginx** [comment]
This is only readme commit. Need to see [this](https://github.com/wzpan/hexo-renderer-pandoc/commit/abec925265a6fa81f0f7e2e0cb7222b220001877).

And as i see need just to comment `template` option to pass this. Try it.

**Comment by sli1989** [comment]
still `Cannot read property 'template' of undefined`.
the [templates instruction](https://pandoc.org/MANUAL.html#templates) in pandoc.

**Comment by ivan-nginx** [comment]
Try to change this:

```diff
- if(config.template) args.push("--template=" + config.template);
+ if(config.template) {
+    args.push("--template=" + config.template);
...
}
```

**Comment by sli1989** [comment]
if change the file, just comment it.
the problems is that i want to add configuration in theme's `_config.yml` to realize the ci automatically.
thank u your help, maybe need to wait author's response.

**Comment by sli1989** [comment]
@ivan-nginx you can close the issue.
if you want to use `hexo-renderer-pandoc`(new version) in hexo , you must add default configuration in the **site**'s _config.yml not the theme's. I would never have thought of doing that.

```
pandoc:
  filters:
  extra:
  template: 
  meta:
  mathEngine:
```

**Comment by ivan-nginx** [comment]
@sli1989 so, all works as i saw before? Let me repeat this steps:

1. Add in **root Hexo** `_config.yml`:
    ```
    pandoc:
      filters:
      extra:
      template: 
      meta:
      mathEngine:
    ```
2. No need to comment **`template:`** option in this configuration.
3. No errors at generation. All works fine in accorduance with #19 issue.

That's right?

**Comment by sli1989** [comment]
yes, just Add default configuration in root Hexo `_config.yml` and ensure that mathjax's cdn is working.
i think it's just need a definition, even comment `template:` option, it works as well.
