### ISSUE TITLE
Titlebar in codeblocks

### ISSUE THREAD

**Issue by maddovr** [theme-next/hexo-theme-next#100]
Is it possible to have a titlebar in codeblocks like the one in gists(preferably with an option to decide whether to have it at the top or at the bottom).

Example
Current codeblock: https://abload.de/img/codeblocktitlebarxbq0w.png
Gist snippet(cannot be styled by config file): https://abload.de/img/gistsnippetr5png.png

Of course I don't want it to be active at all times, but only if %title% is provided.

Example for octopress: http://octopress.org/docs/blogging/code/

**Comment by sli1989** [comment]
using [codeblock tag plugin](https://hexo.io/docs/tag-plugins.html).
recommend use
``` [language] [title] [url] [link text] code snippet ```

**Comment by ivan-nginx** [comment]
Fix and feature added in PR #194.
Released in NexT [v6.1.0](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.1.0) version.
