### ISSUE TITLE
Couldn't find post_copyright

### ISSUE THREAD

**Issue by AloneAlive** [theme-next/hexo-theme-next#1016]
My next theme is Gemini.
I couldn't found below info in my _config.yml.
post_copyright:
  enable: true 
  author: hiekay 
  copyright_text:

Thanks very much

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/blob/9f2d56af713bf873d59f11d525b1f5676c502a60/_config.yml#L88-L97

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/blob/9f2d56af713bf873d59f11d525b1f5676c502a60/_config.yml#L68-L69

**Comment by 1v9** [comment]
Use `creative_commons`, `post_copyright` has been removed.

**Comment by AloneAlive** [comment]
hi, @1v9 @stevenjoezhang 

Thanks very much for your quick reply.
I will modify it at night.
Let's close this issue.

Best Regards,
wizzie

**Comment by qzi** [comment]
> Use `creative_commons`, `post_copyright` has been removed.

There is a bug in link to  https://creativecommons.org/licenses/by-nc-nd/4.0/null/
Please double check

**Comment by stevenjoezhang** [comment]
@qzi Thanks for reminding

**Comment by qzi** [comment]
> @qzi Thanks for reminding

and also the auto-gen link in the current attach with the link for creative-common is wrong.
It looks like "https://github.com/https://github.com/theme-next/hexo-theme-next/issues/1016"
