### ISSUE TITLE
Want to have choice that if the wordcount information displayed in the index page

### ISSUE THREAD

**Issue by MartinMa94** [theme-next/hexo-theme-next#1018]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
At present, if I set "symbols" or "time" true in site config file, the wordcount information will display both in index page and posts pages. But when that shows under the title for each section in the index page,  it is superfluous, I think. I just want to display it in post page only.

So, could you add a feature that I can set if the wordcount information displayed in the index page or post pages?

Hexo version: 3.9.0
Next version: 7.2.0
hexo-symbols-count-time version: 0.6.0

### Actual behavior 
if I set "symbols" or "time" true in site config file, the wordcount information will display both in index page and posts pages.

### Steps to reproduce the behavior 
None

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

**Comment by 1v9** [comment]
![批注 2019-07-26 175636](https://user-images.githubusercontent.com/29083921/61943761-bcf7f000-afce-11e9-83d5-7dab849e3e8c.jpg)

**Comment by MartinMa94** [comment]
Thx so much!
