### ISSUE TITLE
I wonder if next theme support configuration visual width of article

### ISSUE THREAD

**Issue by XiaochenCui** [theme-next/hexo-theme-next#102]
I wonder if next theme support configuration visual width of article. If not, I suppose add this future to next.

For example, on the big screen, the article area looks too wide, and I want to make it narrower

### I agree and want to create new issue

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by tsanie** [comment]
What scheme are you using?
The Gemini will expand the content width along with the window width, it's the feature of it.
And the others all have a maximum width that wouldn't be so wide.

You can choose the scheme which you like.

**Comment by XiaochenCui** [comment]
Sorry for not mention the scheme I use, I don't know it's scheme-related.
I am using gemini and don't want switch to other scheme, is there any solutions?

Thanks

**Comment by tsanie** [comment]
@XiaochenCui Yeah, I think it is possible. Upvote for this feature.

**Comment by tsanie** [comment]
Maybe you can try with the newest branch, click [this](https://github.com/theme-next/hexo-theme-next/pull/103) for details.

**Comment by tsanie** [comment]
I'll close this issue, if there is still a problem you could reopen it later. :)
