### ISSUE TITLE
如何开启帖子的在线编辑功能？

### ISSUE THREAD

**Issue by suyin-long** [theme-next/hexo-theme-next#1021]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: https://theme-next.org/docs/theme-settings/sidebar
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.16.0
6.9.0

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "eslint": "^6.1.0",
    "hexo": "^3.9.0",
    "hexo-blog-encrypt": "^2.2.2",
    "hexo-deployer-git": "^1.0.0",
    "hexo-filter-optimize": "^0.2.5",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-calendar": "github:theme-next/theme-next-calendar",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-indexed": "^0.1.1",
    "hexo-generator-json-content": "^2.2.0",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-migrator-rss": "^0.1.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.6.0",
    "hexo-wordcount": "^6.0.1",
    "shelljs": "^0.8.3"
  }
}

```

#### Hexo version

```
hexo: 3.9.0
hexo-cli: 2.0.0
os: Windows_NT 10.0.18362 win32 x64
http_parser: 2.8.0
node: 10.16.0
v8: 6.8.275.32-node.52
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 4
openssl: 1.1.1b
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```
![32](https://user-images.githubusercontent.com/49554285/61974934-56002880-b01a-11e9-90e2-264f40194307.png)
![23](https://user-images.githubusercontent.com/49554285/61974941-5ac4dc80-b01a-11e9-85fc-91212d051e6d.png)

### Other Information 

问题描述：
想开通帖子的在下编辑功能，但是看了一些教程文档后，还是有点不明白该怎么弄。不知道配置文件中的URL该怎么写？请大佬指点！谢谢！
[参考链接](https://theme-next.org/docs/theme-settings/posts)
[参考链接](https://github.com/hexojs/hexo-deployer-git)

**Comment by stevenjoezhang** [comment]
你需要把博客的源代码放到github上，包括所有markdown文件

**Comment by suyin-long** [comment]
已经放到github上了

**Comment by stevenjoezhang** [comment]
你指的是这个吗

https://github.com/suyin-long/suyin-long.github.io

不是html，需要markdown源代码

**Comment by suyin-long** [comment]
不是这个，那个仓库我设置了私有，您应该看不到。仓库设置为私有可以开启你贴子在线编辑功能吗？
不行的话，我再把仓库改为公有。
暂时把仓库公开了，链接：https://github.com/suyin-long/Hexo

**Comment by stevenjoezhang** [comment]
在线编辑功能的设计初衷是让大家都能够编辑，比如文档网站，其他人看到之后，就可以点击这个按钮，修改和发布Pull Request。因此要求源代码存在公开的仓库中。

如果您是个人网站的话，可能不需要这个功能。

**Comment by suyin-long** [comment]
好的，谢谢！
