### ISSUE TITLE
RSS如何正确设置？

### ISSUE THREAD

**Issue by suyin-long** [theme-next/hexo-theme-next#1028]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.16.0
6.9.0

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "eslint": "^6.1.0",
    "hexo": "^3.9.0",
    "hexo-blog-encrypt": "^2.2.2",
    "hexo-deployer-git": "^1.0.0",
    "hexo-filter-optimize": "^0.2.5",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-calendar": "github:theme-next/theme-next-calendar",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-indexed": "^0.1.1",
    "hexo-generator-json-content": "^2.2.0",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-migrator-rss": "^0.1.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.6.0",
    "hexo-wordcount": "^6.0.1",
    "shelljs": "^0.8.3"
  }
}

```

#### Hexo version

```
hexo: 3.9.0
hexo-cli: 2.0.0
os: Windows_NT 10.0.18362 win32 x64
http_parser: 2.8.0
node: 10.16.0
v8: 6.8.275.32-node.52
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 4
openssl: 1.1.1b
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

### Other Information 

问题描述：
如何才能正确设置RSS，自己参考链接设置的RSS并不能正常使用，仅仅是出来一个图标而已！
还望指点一二，谢谢！
参考链接：https://theme-next.org/docs/theme-settings/
https://github.com/hexojs/hexo-generator-feed

**Comment by stevenjoezhang** [comment]
加个群吧，交流效率高：https://t.me/theme_next

**Comment by jiangtj** [comment]
Or join chinese group https://t.me/theme_next_chinese

**Comment by suyin-long** [comment]
好的，谢谢！

**Comment by sli1989** [comment]
```yml ~/hexo/themes/next/_config.yml
rss: /atom.xml
```
