### ISSUE TITLE
What about use jsDelivr to deliver our third-party plugins?

### ISSUE THREAD

**Issue by wafer-li** [theme-next/hexo-theme-next#105]
Recent days, I found out the [jsDelivr](https://www.jsdelivr.com) is a really good CDN.

It does not only crawl the js files from npm packages, and it crawls from the **GitHub Releases**!

Therefore, we could use it to deliver some of our third-party plugins.

Here is the simple step:

Go to the third-party plugin repo, publish a Release.

And it is done!

Then we could use the following link to reference the js files, just as other CDNs.

```
https://cdn.jsdelivr.net/gh/user/repo@version/file
```

And it could automatically minify the JS and CSS files, even if you don't have the minified version.
Just use the `filename.min.js` or the `filename.min.css` to replace the `file` above.

Using the [jsDelivr](https://www.jsdelivr.com) comes with 2 advantages:

1. The user doesn't need to manually clone repos, just change the `vendors` config, and it is done.

2. We could apply a CDN to some of our third-party plugins which are not included in CDNs such as the [needmoreshare2](https://github.com/theme-next/theme-next-needmoreshare2)

You could take https://github.com/wafer-li/theme-next-needmoreshare2 and https://github.com/wafer-li/wafer-li.github.io/blob/2b47f5c8bfd0ccad163486030951e2ab1a3db2ce/source/_data/next.yml#L1092-L1093

as an example.

**Comment by xuchengpeng** [comment]
试了下真得很快，有必要把 theme-next下插件都发布release
https://github.com/theme-next/theme-next-needmoreshare2

**Comment by sli1989** [comment]
Can publish a release of [needMoreShare2](https://github.com/revir/need-more-share2)?

**Comment by ivan-nginx** [comment]
Author @LEAFERx of this module. Answer to him please.

**Comment by LEAFERx** [comment]
https://github.com/theme-next/theme-next-needmoreshare2/releases/tag/v1.0.0
needmoreshare2 is now released v1.0.0

**Comment by LEAFERx** [comment]
@wafer-li 
anything else to do?
or close this issue
