### ISSUE TITLE
Problem with v7.3

### ISSUE THREAD

**Issue by gapplef** [theme-next/hexo-theme-next#1050]
1. Font size changes
`Site title`:  20px  ->  22px(1.375em), it's ok.
`Headlines`:  22px  ->  28px, I think the headlines is too big.
And after I set the headlines font size to 1.375, it become 20px. Why it's not 22px?

2. Font family of the block quotes not follow the global font I set.
Before:
![Screenshot 1](https://user-images.githubusercontent.com/5604665/62412066-8e61c100-b62f-11e9-8667-439b7586646b.png)
After:
![Screenshot 2](https://user-images.githubusercontent.com/5604665/62412067-8e61c100-b62f-11e9-9847-832bc85d8f57.png)

3. Wrong style of the of categories page
Before:
![Screenshot 4](https://user-images.githubusercontent.com/5604665/62412069-9883bf80-b62f-11e9-833c-5de629be5994.png)
After:
![Screenshot 3](https://user-images.githubusercontent.com/5604665/62412068-97eb2900-b62f-11e9-8b55-7c49ce61151e.png)

**Comment by stevenjoezhang** [comment]
1. Because em is relative font-size
2. Fixed in https://github.com/theme-next/hexo-theme-next/commit/8b6078f9251627d6745d4d172fac800722411c0d
3. Fixed in https://github.com/theme-next/hexo-theme-next/commit/e2c7e1d89f6f6ffe26e672f94c6fcbd975f792b5

**Comment by gapplef** [comment]
@stevenjoezhang Thanks, problem solved with master branch. 
As for the first problem
> Because em is relative font-size

relative to what? Isn't the base font 16px? With 1.375em, I get 20px, that means the base font is 14.545454...

**Comment by stevenjoezhang** [comment]
Oh, that's a matter of algorithms for calculating font sizes:
```styl
$font-size-headings-base = 1.375em
$font-size-headings-step = .125em;
$font-size-h1 = $font-size-headings-base - $font-size-headings-step * 1
$font-size-h2 = $font-size-headings-base - $font-size-headings-step * 2

/* and so on... */
```

Therefore, `$font-size-h1` is equal to 1.375 - 0.125 = 1.25em = 20px

**Comment by ivan-nginx** [comment]
@stevenjoezhang u said in pull with fonts no changes there, but similar changes was in my monitor too. For example, icons:

New changes:
![image](https://user-images.githubusercontent.com/16944225/62429648-7bbfb880-b711-11e9-9eb3-eb4e244e491d.png)

Old changes (how must be):
![image](https://user-images.githubusercontent.com/16944225/62429666-b164a180-b711-11e9-8447-a1e0f4d39da5.png)

See on RSS to → Icons must be separated.

Pencil in post must be bigger
Single code blocks must be smaller
Post titles must be bigger than H1 in that titles, but for now it's vice versa...

New changes:
![image](https://user-images.githubusercontent.com/16944225/62429699-38197e80-b712-11e9-90e1-5f7beccd654c.png)

Before:
![image](https://user-images.githubusercontent.com/16944225/62429702-47003100-b712-11e9-8a0c-bb0cd56e77cb.png)

***

Also, there is bug with active menu item: not only current menu must be highlighted, but all child sub-menu's too, see on screen above. I think this changes provided by PJAX.

**Comment by stevenjoezhang** [comment]
@ivan-nginx https://github.com/theme-next/hexo-theme-next/pull/1060
