### ISSUE TITLE
最新版tag_icon: false #号显示为图片

### ISSUE THREAD

**Issue by pzb568** [theme-next/hexo-theme-next#1071]
# Use icon instead of the symbol # to indicate the tag at the bottom of the post

tag_icon: false

**Comment by pzb568** [comment]
预览地址https://pzb568.github.io/

**Comment by pzb568** [comment]
![](https://b2.bmp.ovh/imgs/2019/08/4d20b5d2f45ae76d.jpg)

**Comment by stevenjoezhang** [comment]
Have you encountered this issue: https://github.com/theme-next/hexo-theme-next/issues/877

**Comment by stevenjoezhang** [comment]
![屏幕快照 2019-08-09 下午11 39 08](https://user-images.githubusercontent.com/16272760/62791034-ef413b80-bafe-11e9-9c4c-9e2435bcde18.png)
@pzb568 似乎问题解决了？所以发生了什么……

**Comment by pzb568** [comment]
我感觉可能是mathjax的问题，所有的mathjax的插件我都安装过了，可能是多个插件造成的问题，只有如文章中的方法安装公式才能显示，并且没有这个问题 文章地址https://pzb568.github.io/posts/97f2042f.html

**Comment by stevenjoezhang** [comment]
NexT主题自带mathjax/katex支持，无需使用hexo-math，只用在`_config.yml`中设置`math`相关参数即可～
