### ISSUE TITLE
Mist主题手机端搜索结果不能点击跳转

### ISSUE THREAD

**Issue by budaig** [theme-next/hexo-theme-next#1078]
Demo：[https://zhinuo.site/](https://zhinuo.site/)
Mist主题手机端
搜索下 结果不能点击跳转 如图
![scrnli_2019_8_9 下午5-07-11](https://user-images.githubusercontent.com/18586226/62771205-462f1c80-bacf-11e9-9c91-4feadf29b62d.jpg)
点击即回到菜单
![scrnli_2019_8_9 下午5-59-51](https://user-images.githubusercontent.com/18586226/62771325-868e9a80-bacf-11e9-8b0b-454a97e59223.jpg)

点击任意地方 也会回到菜单

PC端无此问题

切换成Muse主题手机端亦无此问题。

**Comment by sli1989** [comment]
please provide online demo for your problem.

**Comment by budaig** [comment]
@sli1989 你好 已添加网站链接。
