### ISSUE TITLE
Question: Problem with leancloud_visitors

### ISSUE THREAD

**Issue by gapplef** [theme-next/hexo-theme-next#1082]
I use `leancloud_visitors` to show number of visitors of each article, and `valine` to enable comment. Everything works fine.

Recently, I moved from Leancloud CN Server to US server, so I changed the `appid` and `appkey`.
After the change, the comment system works just fine, but the visitor number do not work.

What can I do?

**Comment by stevenjoezhang** [comment]
![屏幕快照 2019-08-11 下午2 43 44](https://user-images.githubusercontent.com/16272760/62830759-7ea53680-bc46-11e9-9fe2-df37b16403cb.png)

Seems that you didn't set `leancloud_visitors.app_id` and `leancloud_visitors.app_key`

**Comment by gapplef** [comment]
Problem solved, thanks @stevenjoezhang 

To set the ID and Key, keywords used by `valine` is `appid` and `appkey`, while the keywords used by  `leancloud_visitors` is `app_id` and `app_key`.

I direct copy the setting lines of  `valine` and paste under `leancloud_visitors` field, which cause the problem due to the wrong keywords name.
