### ISSUE TITLE
Site overview reload on every page with PJAX enabled.

### ISSUE THREAD

**Issue by gapplef** [theme-next/hexo-theme-next#1084]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

`Site Overview` in the sidebar is keep unchanged in most cases, like all the pages under home, the archive page, the about page, the tags page, the categories pages and all the post pages without `Table of Contents(ToC)`.

Actually, only for posts with `ToC`, the `Site Overview` will combined with `ToC`, thus need to refresh. But with PJAX turn on, the `Site Overview` always reload on every page.

Is it possible to only reload the `Site Overview` when necessary?

**Comment by stevenjoezhang** [comment]
It's feature.

**Comment by gapplef** [comment]
@stevenjoezhang  Why would it considered as a feature?
I mean `Site Overview` is unchanged in most cases, why it need to be reload?

Reload `Site Overview` while keep `Menu` fixed is counter-intuition, as both are unchanged!
The user experience would be better to reload the `Site Overview` only when necessary.

**Comment by stevenjoezhang** [comment]
You can follow your ideas and open a pull request~

**Comment by gapplef** [comment]
Only if I know how to deal with all those JS/CSS stuff :joy: 

Anyway, really appreciate your active work on NexT theme :+1: @stevenjoezhang

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/hexo-theme-next/pull/1113
