### ISSUE TITLE
Font size are not adaptive change with v7.3

### ISSUE THREAD

**Issue by gapplef** [theme-next/hexo-theme-next#1086]
Before v7.3, font size of post body and title would auto adapt to the screen size.
For example, on my laptop, font size of post body and title are 16px and 22px, while on my phone, they change to 14px and 18px, respectively.

With v7.3, font size are fixed at 16px and 29px, and not  adapt to the screen size anymore.

**Comment by stevenjoezhang** [comment]
Use custom style:
```styl
body {
  +mobile() {
    font-size: $font-size-small;
    padding-right: 0 !important;
  }
  +desktop-large() {
    font-size: $font-size-large;
  }
}
```

**Comment by stevenjoezhang** [comment]
Please join our telegram chat. You can get quick response instead of spamming the repo.
Thanks.

**Comment by stevenjoezhang** [comment]
Would you like to join our telegram chat: https://t.me/theme_next_chinese

**Comment by gapplef** [comment]
Somethings still wrong in here.
With current master branch, the font size of post body adapt to the screen size properly. But the font size of the post title keep fixed, I guess this is not as expected.

I try to fixed the problem, and add the following file:
`_data/next.yml`
```yml
custom_file_path:
  style: source/_data/styles.styl
```
`_data/styles.styl`
```css
body {
  +tablet-mobile() {
    font-size: $font-size-small;
    padding-right: 0 !important;
  }
  +desktop-largest() {
    font-size: $font-size-large;
  }
}
```
With the custom style,  font size of the post title also adaptive change, but the problem is the menu size also adaptive change, and become a bit hard to read on mobile device. I don't know if this is the expected behaviour.
