### ISSUE TITLE
Hexo NexT新增哈林摇特效，嗨起来😜

### ISSUE THREAD

**Issue by leafjame** [theme-next/hexo-theme-next#1088]
[链接地址](https://leafjame.github.io)
点击首页的 High~，页面开始晃动起来。。。😜
![image](https://user-images.githubusercontent.com/29299658/62913066-3fe5bc80-bdbd-11e9-9934-220547489372.png)
![image](https://user-images.githubusercontent.com/29299658/62913073-46743400-bdbd-11e9-8fef-23574c1a4b8a.png)

由于之前加的样式有点多，造成排版样式有点乱，慌的效果七零八碎😭。。。
有谁有好的优化方案

**Comment by stevenjoezhang** [comment]
![屏幕快照 2019-08-13 上午11 37 08](https://user-images.githubusercontent.com/16272760/62913469-be8f2980-bdbe-11e9-8f47-0af5123252de.png)

请合理使用GitHub issue，谢谢～

**Comment by stevenjoezhang** [comment]
如果您继续通过发表无意义内容以达到推广您自己网站的目的，我们将向GitHub举报您的滥用行为。

**Comment by stevenjoezhang** [comment]
拜读了一下您的文章，里面有大量直接修改swig模版的教程。这是不推荐的行为，建议您了解一下theme-inject特性。
