### ISSUE TITLE
最新commit 搜索按钮 点击 无反应

### ISSUE THREAD

**Issue by budaig** [theme-next/hexo-theme-next#1097]
最新commit 搜索按钮 点击 无反应

Mist主题 Pisces主题 Muse主题上
PC端 手机端
都是如此。

**Comment by sli1989** [comment]
please provide your online demo for debug.

**Comment by budaig** [comment]
@sli1989 你好 
这次是本地测试，没有上传服务器

**Comment by stevenjoezhang** [comment]
清空缓存了吗？

**Comment by budaig** [comment]
清空了
chrome 换 firefox
chrome关闭后
都是这个问题

**Comment by stevenjoezhang** [comment]
你新开一个github公开仓库部署上去吧

**Comment by budaig** [comment]
@stevenjoezhang 已部署
链接 [https://zhinuo.site/](url)

**Comment by 1v9** [comment]
@budaig Update, it should be fixed.

**Comment by budaig** [comment]
@1v9 it's fixed now. thanks.
however, the search results show only post titles, have no post contents, and there are strange characters "]]>" after the titles.

![scrnli_2019_8_16 下午4-19-31](https://user-images.githubusercontent.com/18586226/63154248-c52dd300-c042-11e9-8aa3-c0ccb02b5007.jpg)

已修复，谢谢。
不过，搜索结果只显示文章标题， 不显示文章内容。文章标题后跟有"]]>"字符。

![scrnli_2019_8_16 下午4-29-15](https://user-images.githubusercontent.com/18586226/63154377-0aea9b80-c043-11e9-8ba6-0befcb15ee56.jpg)

**Comment by stevenjoezhang** [comment]
安装hexo-generator-search 卸载searchdb

**Comment by budaig** [comment]
非常感谢
可以了
