### ISSUE TITLE
Ubuntu18.04配置的hexo+next，网页不能显示本地图片

### ISSUE THREAD

**Issue by tuoniaoren** [theme-next/hexo-theme-next#1103]
采用{%asset_img example.jpg examplename%}依然不能显示图像，在win10下可以。

**Comment by stevenjoezhang** [comment]
换个主题试试，比如默认的landscape。如果问题依然存在，就去找Hexo解决问题。

**Comment by tuoniaoren** [comment]
> 换个主题试试，比如默认的landscape。如果问题依然存在，就去找Hexo解决问题。
感谢回复

**Comment by liolok** [comment]
> `{% asset_img example.jpg This is an example image %}`

这是[官方文档](https://hexo.io/zh-cn/docs/asset-folders.html "资源文件夹 | Hexo")里的用法，是不是在百分号里面加上空格就好了呢？

**Comment by tuoniaoren** [comment]
> > `{% asset_img example.jpg This is an example image %}`
> 
> 这是[官方文档](https://hexo.io/zh-cn/docs/asset-folders.html)里的用法，是不是在百分号里面加上空格就好了呢？

ubuntu下的nodejs是6.几的，我下载了nodejs10的源代码编译安装了，之后就没问题了。

**Comment by liolok** [comment]
@tuoniaoren 环境配置环节就有问题了可还行

**Comment by stevenjoezhang** [comment]
Hexo v4.0开始要求node >= 8.6
