### ISSUE TITLE
How to turnoff auto expand article on mainpage。如何关闭主页展开文章

### ISSUE THREAD

**Issue by AnkiKong** [theme-next/hexo-theme-next#1108]
主页就把所有的文章展开了，导致主页异常的长。翻了好几遍doc都找不到解决方案，所以请教如何关闭文章自动展开。
All article expand on mainpage，leads to long page length。I have tried to find how to turnoff it in doc without any progress. So I come here to ask，how can i turn off auto expand。

**Comment by stevenjoezhang** [comment]
使用`<!-- more -->`标记即可

**Comment by stevenjoezhang** [comment]
可以加一下telegram群，交流更方便：https://t.me/theme_next_chinese

**Comment by AnkiKong** [comment]
> 使用`<!-- more -->`标记即可
> 
> https://theme-next.org/docs/theme-settings/posts#Preamble-Text

可以了，谢谢！

**Comment by khoint0210** [comment]
But the auto_excerpt not working I don't want to use `<!-- more -->`
