### ISSUE TITLE
代码块“#“顶格开头语句无法选中

### ISSUE THREAD

**Issue by MakiseVon** [theme-next/hexo-theme-next#1110]
如题
![Problem](https://i.loli.net/2019/08/18/vXUYBKHWCZuTSVs.png)

**Comment by stevenjoezhang** [comment]
我佛了，有人要选中，有人要禁止选中：https://github.com/theme-next/hexo-theme-next/issues/448
你们打一架吧😂

**Comment by stevenjoezhang** [comment]
你的代码块设置了语言吗？给个链接吧

**Comment by stevenjoezhang** [comment]
看上去highlight.js将整行`#include`均标记为meta
可以通过删除themes/next/source/css/_common/components/highlight/highlight.styl 125行解决

**Comment by MakiseVon** [comment]
> 我佛了，有人要选中，有人要禁止选中：#448
> 你们打一架吧😂

😂

**Comment by stevenjoezhang** [comment]
可以加一下telegram群：https://t.me/theme_next_chinese 交流更方便

**Comment by stevenjoezhang** [comment]
Fixed in next-theme/hexo-theme-next@9fdaba2

**Comment by egcn** [comment]
> 看上去highlight.js将整行`#include`均标记为meta
> 删除themes/next/source/css/_common/components/highlight/highlight.styl 125行能够解决此问题
> 
> 不过这样设计也是合理的：通过设置`codeblock.copy_button.enable: true`即可一键复制代码

然而 $ 也一起复制过去了

**Comment by stevenjoezhang** [comment]
markdownlint recommends that don't use dollar signs before commands without showing output.

https://github.com/DavidAnson/markdownlint/blob/main/doc/md014.md

<blockquote><img src="https://opengraph.githubassets.com/1dbae02031c071c26b5e2cd7a0d8632646b97887c731a5333dc4691f091d76cc/DavidAnson/markdownlint" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/DavidAnson/markdownlint/blob/main/doc/md014.md">markdownlint/doc/md014.md at main · DavidAnson/markdownlint</a></strong></div><div>A Node.js style checker and lint tool for Markdown/CommonMark files. - DavidAnson/markdownlint</div></blockquote>
