### ISSUE TITLE
A single category or tag page doesn't show year devision?

### ISSUE THREAD

**Issue by GARENFEATHER** [theme-next/hexo-theme-next#112]
I'm not sure if it was kind of a bug or just the designed style.
A single page like '.com/categories/tech/' or '.com/tags/tech/' will show a timeline of related post but with no year devided? The style of the timeline almost looks the same with archives page but only the month and day has been shown?
:cry:why no year there ?

**Comment by ivan-nginx** [comment]
Year appear on archives page only for now, but no on categories or tags pages.
![image](https://user-images.githubusercontent.com/16944225/35856598-91fc61c4-0b47-11e8-8505-8dbc3969aa58.png)

**Comment by GARENFEATHER** [comment]
@ivan-nginx so why? I think they use almost the same template right?

**Comment by ivan-nginx** [comment]
Not quite. There is sorting. And year/month/week — this is just only for posts (for archives).

**Comment by stevenjoezhang** [comment]
Fixed in #1061
