### ISSUE TITLE
md文件与该文件引用图片放入同名文件夹，生成的图片地址错误，应该哪里修改呢？

### ISSUE THREAD

**Issue by zhengchu1994** [theme-next/hexo-theme-next#1120]
在md文件与同名文件夹同一级时，放入文件夹中的图片可以通过相对地址引用成功：
比如：`test.md` 中引用`test/pic.png`
因为想把`md`文件放到同名文件夹内，这时候引用的图片地址为：`pic.png`会出错，最后生成的图片地址链接结尾为`test/test/pic.png`
请问如何修改使得上述引用成功？

**Comment by jiangtj** [comment]
这篇文档可能对你有帮助
https://hexo.io/zh-cn/docs/asset-folders

**Comment by zhengchu1994** [comment]
> 这篇文档可能对你有帮助
> https://hexo.io/zh-cn/docs/asset-folders
> 
> > <img alt="" height="14" src="/icon/favicon-32x32.png"> Hexo**[资源文件夹](https://hexo.io/zh-cn/docs/asset-folders.html)**资源（Asset）代表 source 文件夹中除了文章以外的所有文件，例如图片、CSS、JS 文件等。比方说，如果你的Hexo项目中只有少量图片，那最简单的方法就是将它们放在 source/images 文件夹中。然后通过类似于 ![](/images/image.jpg) 的方法访问它们。 文章资源文件夹对于那些想要更有规律地提供图片和其他资源以及想要将他们的资源分布在各个文章上的人来说，Hex

好的，虽然还没找到解决方法，thx。

**Comment by stevenjoezhang** [comment]
确实可以试试Hexo的`asset_img`标签。另见 https://github.com/theme-next/hexo-theme-next/issues/1103

**Comment by stevenjoezhang** [comment]
有其他问题欢迎加群讨论：https://t.me/theme_next_chinese

**Comment by zhengchu1994** [comment]
好的，感谢~

**Comment by liolok** [comment]
https://liolok.github.io/zh-CN/如何为-Hexo-博文加入图片/
