### ISSUE TITLE
新版的Next主题怎么自定义文章字体行距等的格式？

### ISSUE THREAD

**Issue by YouthFaith** [theme-next/hexo-theme-next#1131]
以前的版本是修改custom.styl文件的，那现在呢？

**Comment by stevenjoezhang** [comment]
见 https://github.com/theme-next/hexo-theme-next/issues/1010
可以加telegram群，交流更方便：https://t.me/theme_next_chinese

**Comment by YouthFaith** [comment]
Thank you very much！------------------ 原始邮件 ------------------
发件人: "support[bot]"<notifications@github.com>
发送时间: 2019年8月28日(星期三) 凌晨0:19
收件人: "theme-next/hexo-theme-next"<hexo-theme-next@noreply.github.com>;
抄送: "YouthFaith"<1581727244@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [theme-next/hexo-theme-next] 新版的Next主题怎么自定义文章字体行距等的格式？ (#1131)



 @YouthFaith, we use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our support channels to get help with the project.
 
&mdash;

**Comment by stevenjoezhang** [comment]
更新说明加到这里了，欢迎关注：https://github.com/theme-next/hexo-theme-next/issues/1217

**Comment by stevenjoezhang** [comment]
更新说明加到这里了，欢迎关注：https://github.com/theme-next/hexo-theme-next/issues/1217
