### ISSUE TITLE
Request add-bilibili-icon

### ISSUE THREAD

**Issue by xuan512** [theme-next/hexo-theme-next#1137]
### I agree and want to create new issue 

- [X ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.
***

**NexT Scheme:**

- [ X] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

Request to add bilibili built-in icon.
I have found the bilibili-icon on https://fontawesome.com/.
but I didn't find it.
I want to have a built-in icon instead of a third party, or homemade

**Comment by stevenjoezhang** [comment]
https://blog.dlzhang.com/posts/89dad1c1/

**Comment by stevenjoezhang** [comment]
See also https://github.com/FortAwesome/Font-Awesome/issues/9789
