### ISSUE TITLE
sidebar cannot automatically locate top

### ISSUE THREAD

**Issue by winsky94** [theme-next/hexo-theme-next#114]
In the details page, the article is pulled to the bottom, and then refresh the page, then the left sidebar can not be automatically locate top
My Blog： [http://blog.winsky.xyz/2018/02/04/hello-world/#more](http://blog.winsky.xyz/2018/02/04/hello-world/#more)

![image](https://user-images.githubusercontent.com/35768501/35787161-1c60a0f0-0a67-11e8-9fe8-0556a83aa480.png)

Version：Latest Release version.
Scheme：Pisces

**Comment by ivan-nginx** [comment]
![image](https://user-images.githubusercontent.com/16944225/35855773-243aed88-0b45-11e8-8fbe-c92d5721c5ac.png)

Mb trouble in your browser?

**Comment by winsky94** [comment]
Er.. I try again and find that the problem always exists in chrome. 
But it's ok when I open in the Safari.

**Comment by maple3142** [comment]
It also happens to my blog on Firefox.
[video](https://streamable.com/eodle)

**Comment by xkniu** [comment]
I has the same problem in Chrome, and it could be reproduced easily be these steps:

1. Open one post
2. Scroll to the bottom of the page
3. Click the area of the content or the blank space under the content (Sometimes needn't this step)
4. Refresh the page

I try this either after clearing the cache or in incognito window, the problem still exists.

**Comment by xkniu** [comment]
I met the same problem in Chrome, and still had the problem after clean cache or in incognito window. And i found this only occurs in **Scheme - Pisces**, **Scheme - Gemini** won't have the problem.

It could be easily reproduced by these steps:

1. Open one post
2. Scroll to the bottom of the post
3. Click the area of the post or under the post (sometimes this step is unnecessary)
4. Refresh the page

@ivan-nginx

**Comment by ivan-nginx** [comment]
@xkniu @maple3142 @winsky94 fixed in #418.
