### ISSUE TITLE
Unhandled promise rejection Error: "Velocity: First argument (transition.slideDownIn) was not a property map, a known action, or a registered redirect. Aborting.

### ISSUE THREAD

**Issue by syshlang** [theme-next/hexo-theme-next#1144]
Unhandled promise rejection Error: "Velocity: First argument (transition.slideDownIn) was not a property map, a known action, or a registered redirect. Aborting.

**Comment by stevenjoezhang** [comment]
Any URLs?

**Comment by syshlang** [comment]
> 
> 
> Any URLs?

it happen when i  Introducing third-party plug-ins，example daovoice.

**Comment by stevenjoezhang** [comment]
Sorry, we can't debug based on the information you provided.
About `daovoice`: https://github.com/theme-next/awesome-next/issues/5

**Comment by stevenjoezhang** [comment]
Don't worry, we are looking for alternatives to `Velocity`, this problem will be completely solved then

**Comment by syshlang** [comment]
> 
> 
> Don't worry, we are looking for alternatives to `Velocity`, this problem will be completely solved then

ok,thank  you  for your help！
