### ISSUE TITLE
How to order posts in category's list?

### ISSUE THREAD

**Issue by aprz512** [theme-next/hexo-theme-next#1157]
Now, it seems like the post list in category order by date.

For example, i have 4 posts, it shows like below:

https://xxxxx/categories/xxx/

\----------
|
· 2019
|
· 0001-post
|
· 0003-post
|
· 0004-post
|
· 0002-post
|
\---------

I want it ordered by post's title, it should be like this:
\----------
|
· 2019
|
· 0001-post
|
· 0002-post
|
· 0003-post
|
· 0004-post
|
\---------

or 

\----------
|
· 2019
|
· 0004-post
|
· 0003-post
|
· 0002-post
|
· 0001-post
|
\---------

**Comment by stevenjoezhang** [comment]
Please ask Hexo for help. The order of posts in specified categories is not controlled by theme NexT.
