### ISSUE TITLE
Add lang attribute to article tag when specified in front matter

### ISSUE THREAD

**Issue by alaaosh** [theme-next/hexo-theme-next#1160]
### I agree and want to create new issue 

- [x] I have already viewed [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/).
- [x] I have searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) which does not help me.

***

### Expected behavior 

lang attribute should be added to **article** tag if lang is specified in front matter

### Actual behavior 

lang attribute is added to the **body** tag, this is useful but only works in post page. in an index page showing posts with multiple languages (not uncommon for bilingual bloggers) post language is not expressed in the html at all.

### Steps to reproduce the behavior 
1. add post and put lang: ar in front matter
2. add another post and put lang: en in front matter
3. on homepage the language data is lost, we can't use css attribute selectors to do language specific styling for instance (important for RTL languages).

* Link to demo site with this feature: N/A
* Link(s) to source code or any usefull link(s): N/A

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by alaaosh** [comment]
I just realized next already supports setting direction in front matter (undocumented). I still think adding lang attribute would be useful though.

**Comment by stevenjoezhang** [comment]
> we can't use css attribute selectors to do language specific styling for instance (important for RTL languages)

Front-matter:
```
direction: rtl
```
CSS:
```css
.rtl { /* CSS Code */ }
```

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/hexo-theme-next/pull/1199
