### ISSUE TITLE
v7.4.0 font issue

### ISSUE THREAD

**Issue by kneep** [theme-next/hexo-theme-next#1165]
### I agree and want to create new issue 

- [x] I have confirmed that this bug only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT bug, not a bug from Hexo.
- [x] I have already viewed [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/).
- [x] I have searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) which does not help me.

***

### Actual behavior 
The font size of posts built with v7.4.0 is much larger than before.

### Steps to reproduce the behavior 
1. Build a site with v7.4.0
2. N/A
3. N/A

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```
3.9.0
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

### Other Information 
v7.3.0 is OK.
I noticed the font size of https://theme-next.org/ is also very large. Maybe it looks OK for English but not for Chinese.

**Comment by kneep** [comment]
Another thing I noticed was that from v7.2.0 to v7.3.0, font size of post title was increased but not the that of the body. I'm not sure whether these size changes were inadvertent. Anyway I think the font size from earlier version to v7.2.0 worked better for me.

BTW, I tried the override the font size of body in _config.yml but seemed not work.
```
# Font settings for posts (.post-body).
  posts:
    external: true
    family:
    size: 0.9
```

**Comment by stevenjoezhang** [comment]
I'm not sure whether these size changes were inadvertent.

#1005, #1006, https://github.com/theme-next/hexo-theme-next/issues/1086

**Comment by kneep** [comment]
@stevenjoezhang Hi Steven. I mean the font size of a post-body is relatively large compared to other parts. How can I adjust the post-body font size independently in _config.yml?

**Comment by stevenjoezhang** [comment]
Use custom stylesheet:
```css
.post-body { font-size: /*  */; }
```

**Comment by kneep** [comment]
@stevenjoezhang 

Hi Steven.

I did some test for this. Seems it is caused by the following code:

```source/css/_common/components/post/post.styl```
```styl
  +desktop-large() {
    font-size: $font-size-large;
  }
```

If I changed ```font-size-large``` to ```font-size-medium```, everything was OK.

So I took a look at the definition:

```source/css/_mixins/base.styl```
```styl
desktop-large() {
  @media (min-width: 1200px) {
    {block};
  }
}
```

So the problem here is: my screen was 1366*768, how did I get into the 1200px config?

**Comment by stevenjoezhang** [comment]
Don't worry, we're dealing with it: https://github.com/theme-next/hexo-theme-next/pull/1190

**Comment by stevenjoezhang** [comment]
Font size has been adjusted in v7.4.1

**Comment by kneep** [comment]
I just tested v7.4.3 and don't think it fixed my problem.

I think the problem is:
```source/css/_common/components/post/post.styl```
```
+desktop-large() {
    font-size: $font-size-large;
  }
```
where the font-size-large is too large for a laptop.

**Comment by lingjiameng** [comment]
I found this error too for zh-CN
![image](https://user-images.githubusercontent.com/23097439/70864603-90993c00-1f8e-11ea-8089-18eabcc7c0cb.png)

**Comment by LemniscateX** [comment]
> I just tested v7.4.3 and don't think it fixed my problem.
> 
> I think the problem is:
> `source/css/_common/components/post/post.styl`
> 
> ```
> +desktop-large() {
>     font-size: $font-size-large;
>   }
> ```
> 
> where the font-size-large is too large for a laptop(either normal or high resolution screen).
> I have to change it to font-size-medium to make it look better.

I feel the same.🙌🏻
My solution is to change the `$font-size-large` value from `1.125em` to `1em`, just to prevent manually change EVERY content from `$font-size-large` to `$font-size-medium`, which is less easier.
