### ISSUE TITLE
垃圾

### ISSUE THREAD

**Issue by maplesugarr** [theme-next/hexo-theme-next#1174]
你们可以随意调侃和关闭issue，但改变不了你们垃圾的本质。
一共就7个页面。每次发版都这么多bug。
是的，我会自己滚得。

**Comment by jiangtj** [comment]
我们维护这个主题并未接受任何的资助，仅仅靠热情。所以请尊重每个贡献者。
如果你遇到了问题？可以在github上提交相关问题，或者在Telegram上联系我们。
