### ISSUE TITLE
左侧菜单栏的Netlify是如何添加的？谁知道

### ISSUE THREAD

**Issue by w698** [theme-next/hexo-theme-next#1181]
左侧菜单栏的Netlify是如何添加的？谁知道

**Comment by stevenjoezhang** [comment]
源码都在这：https://github.com/theme-next/theme-next.org

**Comment by stevenjoezhang** [comment]
具体来说可以看这个commit: https://github.com/theme-next/theme-next.org/commit/4afac08ec9549346a60d2f8c14344a8182d29c18

**Comment by w698** [comment]
可以可以，👍发自我的iPhone------------------ 原始邮件 ------------------发件人: ᴍɪᴍɪ  <notifications@github.com>发送时间: 2019年9月28日 11:24收件人: theme-next/hexo-theme-next <hexo-theme-next@noreply.github.com>抄送: biUbiUbiU <wanghl698@gmail.com>, Author <author@noreply.github.com>主题: 回复：[theme-next/hexo-theme-next] 左侧菜单栏的Netlify是如何添加的？谁知道 (#1181)具体来说可以看这个commit: theme-next/theme-next.org@4afac08

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/theme-next/hexo-theme-next/issues/1181?email_source=notifications\u0026email_token=AFKBYHUCAZDVRRJGZ7YZRD3QL3E6JA5CNFSM4I3D53EKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD72PVWA#issuecomment-536148696",
"url": "https://github.com/theme-next/hexo-theme-next/issues/1181?email_source=notifications\u0026email_token=AFKBYHUCAZDVRRJGZ7YZRD3QL3E6JA5CNFSM4I3D53EKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD72PVWA#issuecomment-536148696",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
