### ISSUE TITLE
Affix bug

### ISSUE THREAD

**Issue by Olvi73** [theme-next/hexo-theme-next#1186]
## Issue Checklist 

- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: https://olvi73.github.io/2019/09/28/Sublime%20Text%203%E6%BF%80%E6%B4%BB%E6%96%B9%E6%B3%95/
https://olvi73.github.io/about/
- Links to repository or source code of the blog:  https://github.com/Olvi73/Olvi73.github.io

## Steps to reproduce the behavior 
1. PC端打开issue里的网页
2. 鼠标拉到最下端会自动回弹回去（无法拉到最低）
3. 使用了tag cloud的功能，在很短文章中才会出现这种情况，在长文章中不会出现
4.关闭tag cloud后，不管长文章或者短文章都不会出现

### Package dependencies Information

```

```

### Hexo Version

```
hexo: 3.9.0
hexo-cli: 2.0.0
os: Windows_NT 10.0.18362 win32 x64
http_parser: 2.8.0
node: 10.16.3
v8: 6.8.275.32-node.54
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.39.2
napi: 4
openssl: 1.1.1c
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
```

## Other Information 
关于tag cloud的设置
blog的_config.yml
#tag_cloud:  
    textFont: Trebuchet MS, Helvetica
    textColor: '#333'
    textHeight: 25
    outlineColor: '#E2E1D1'
    maxSpeed: 0.1 

themes\next\layout\_macro\sidebar.swing
        {% if site.tags.length > 1 %}
<script type="text/javascript" charset="utf-8" src="/js/tagcloud.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/tagcanvas.js"></script>
<div class="widget-wrap">
    <h3 class="widget-title">Tag Cloud</h3>
    <div id="myCanvasContainer" class="widget tagcloud">
        <canvas width="250" height="250" id="resCanvas" style="width=100%">
            {{ list_tags() }}
        </canvas>
    </div>
</div>
{% endif %}

**Comment by stevenjoezhang** [comment]
是的，这是已知问题，已在Roadmap中提及。见 https://github.com/theme-next/hexo-theme-next/issues/809
