### ISSUE TITLE
Menu语言配置为中文后不生效，7.4.0版本

### ISSUE THREAD

**Issue by CoolLittle** [theme-next/hexo-theme-next#1188]
## Issue Checklist 

- [ ] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [ ] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [ ] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [ ] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***
![图片](https://user-images.githubusercontent.com/22491342/65831299-b34e7980-e2ea-11e9-982a-694b864197f6.png)

## Expected behavior 
预期首页显示中文

## Actual behavior 

![图片](https://user-images.githubusercontent.com/22491342/65831307-c19c9580-e2ea-11e9-9305-97d368d0aed3.png)
不显示中文，一直是英文
- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Package dependencies Information

![图片](https://user-images.githubusercontent.com/22491342/65831339-1fc97880-e2eb-11e9-9f30-84d73b783bca.png)

### Hexo Version

![图片](https://user-images.githubusercontent.com/22491342/65831332-088a8b00-e2eb-11e9-8cb0-567d6503fbb3.png)

### Hexo Configuration

无变更，初始文件

### NexT Configuration

```yml
无改动
## Other Information <!-- (Like Browser, System, Screenshots) -->

**Comment by stevenjoezhang** [comment]
之前也有人遇到了这个问题，英语变德语了……目前原因未知，需要研究

![屏幕快照 2019-09-29 下午7 22 04](https://user-images.githubusercontent.com/16272760/65831659-c4998500-e2ee-11e9-9e94-2e4c88d734e5.png)

**Comment by jiangtj** [comment]
试试在hexo s/g之前运行hexo cl

**Comment by OpensourceHU** [comment]
> 请确认一下Issue的检查单，谢谢。
> 
> 之前也有人遇到了这个问题，英语变德语了……目前原因未知，需要研究

我也是出现德语的问题,把站点config文件和next主题文件的语言都改成zh-CN了 依旧是这个问题
