### ISSUE TITLE
设置侧边栏社交链接，报错 NOENT: no such file or directory

### ISSUE THREAD

**Issue by Williamren97** [theme-next/hexo-theme-next#1189]
## Issue Checklist 

- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
成功设置侧边栏社交链接，hexo g无过程中error产生
## Actual behavior 

在hexo g无过程有error生成。
NOENT: no such file or directory, open '/Users/WilliamRen/williamren97.github.io/themes/next/layout/_scripts/schemes/.swig'

- Links to demo site with this feature: https://williamren97.github.io/
- Links to repository or source code of the blog: https://github.com/Williamren97/Williamren97.github.io

## Steps to reproduce the behavior 
1. 打开terminal，修改主题_config.yml
2. 去掉#social:
  #GitHub: https://github.com/williamren97前面的符號#
3. 使用hexo g，報以上錯誤。
謝謝

**Comment by jiangtj** [comment]
可能scheme未定义，检测下这个配置参数，应该为mist muse p什么来着 或者gemini

**Comment by stevenjoezhang** [comment]
感觉这个问题不简单：https://github.com/theme-next/hexo-theme-next/issues/874

**Comment by Williamren97** [comment]
> 可能scheme未定义，检测下这个配置参数，应该为mist muse p什么来着 或者gemini

这个我已经定义好了，

**Comment by stevenjoezhang** [comment]
能否提供博客的全部源代码（非*.github.io）

**Comment by Williamren97** [comment]
> ## Issue Checklist
> * [x]  I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
> * [x]  I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.
> 
> ## Expected behavior
> 成功设置侧边栏社交链接，hexo g无过程中error产生
> 
> ## Actual behavior
> 在hexo g无过程有error生成。
> NOENT: no such file or directory, open '/Users/WilliamRen/williamren97.github.io/themes/next/layout/_scripts/schemes/.swig'
> 
> * Links to demo site with this feature: https://williamren97.github.io/
> * Links to repository or source code of the blog: https://github.com/Williamren97/Williamren97.github.io
> 
> ## Steps to reproduce the behavior
> 1. 打开terminal，修改主题_config.yml
> 2. 去掉#social:
>    #GitHub: [https://github.com/williamren97前面的符號#](https://github.com/williamren97%E5%89%8D%E9%9D%A2%E7%9A%84%E7%AC%A6%E8%99%9F#)
> 3. 使用hexo g，報以上錯誤。
>    謝謝

**Comment by Williamren97** [comment]
# 此問題現在已經關閉

## 解決方法：
* 我將版本從5升級到6，現在相關功能已經可以正常使用，很抱歉，在這裏做了一些微笑的工作
