### ISSUE TITLE
menu 显示错误

### ISSUE THREAD

**Issue by osenberg-x** [theme-next/hexo-theme-next#1195]
我的 menu 显示如下：
 
<i class="fa fa-fw fa-home"></i>Home

css 的源码也显示出来了。

不知应该怎么解决

**Comment by stevenjoezhang** [comment]
暂时可以用这个分支：https://github.com/theme-next/hexo-theme-next/pull/1175

**Comment by stevenjoezhang** [comment]
另见 https://github.com/hexojs/hexo/issues/3729
