### ISSUE TITLE
Body width too big

### ISSUE THREAD

**Issue by kuretru** [theme-next/hexo-theme-next#1196]
## Issue Checklist 

- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
![Expected behavior](https://user-images.githubusercontent.com/13750214/65954148-fe49c780-e477-11e9-913e-2f393115180d.gif)

## Actual behavior 

![Actual behavior](https://user-images.githubusercontent.com/13750214/65954133-f8ec7d00-e477-11e9-8979-ed3a4ad2edf4.gif)

## Steps to reproduce the behavior 
1. hexo init blog && cd blog && yarn install
2. git clone https://github.com/theme-next/hexo-theme-next themes/next
3. Set NexT schema to Pisces or Gemini

### Node.js and NPM Information

```
yarn -v
> 1.19.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-server": "^0.3.3"
  }
}
```

### Hexo Version

```
hexo: 3.9.0
hexo-cli: 2.0.0
os: Darwin 18.7.0 darwin x64
node: 12.10.0
v8: 7.6.303.29-node.16
uv: 1.31.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 4
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1c
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
```

### Hexo Configuration

```yml
theme: next
```

### NexT Configuration

```yml
 # Schemes
 #scheme: Muse
 #scheme: Mist
 #scheme: Pisces
 scheme: Gemini
```

## Other Information 

* This problem has occurred since [b6939a389fc146b103dab8f00c1018c22f16856a](https://github.com/theme-next/hexo-theme-next/commit/b6939a389fc146b103dab8f00c1018c22f16856a).
* And only occurred in Pisces and Gemini.

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/hexo-theme-next/commit/5b6dbe78e059e62327184ab546bfdab86a0a10dc
