### ISSUE TITLE
clean duoshuo plugin

### ISSUE THREAD

**Issue by maskleo** [theme-next/hexo-theme-next#12]
Message plug-ins `duoshuo` has been discontinued on June 1, 2017.I think it's time to remove the related code to keep it clean and avoid misleading newbies.

**Comment by zhuzhuyule** [comment]
this [push](https://github.com/theme-next/hexo-theme-next/pull/14) clear about duoshuo server.

**Comment by ivan-nginx** [comment]
Merged in [remove-duoshuo](https://github.com/theme-next/hexo-theme-next/tree/remove-duoshuo) branch.

Thank's! :+1:
