### ISSUE TITLE
ERROR in changing the theme to Mist

### ISSUE THREAD

**Issue by MatthewXY01** [theme-next/hexo-theme-next#1201]
After changing the theme to Mist  and refresh 'http://localhost:4000/'  
ERROR: 'failed to locate @import file_logo.styl'  
It seems that the folder 'Mist' of the new version is missing the file '_logo.styl' which exists under the 'Mist' folder of the previous version.

**Comment by stevenjoezhang** [comment]
Can't reproduce.

Since you did not complete the Issue as required, we will not be able to investigate.
