### ISSUE TITLE
The problem of custom files when upgrade from v7.1.1 to v7.4.1

### ISSUE THREAD

**Issue by AlexHex7** [theme-next/hexo-theme-next#1203]
In v7.1.1, I , I have two custom files
- themes/next/source/css/_custom/custom.styl
- themes/next/source/css/_variables/custom.styl

After I upgrade to v7.4.1, What should I modify? I can not find the details in releases...

I try to change **#style: source/_data/styles.styl** to **style: source/_data/styles.styl**. And I find there is no **_data/** directory in **source/**. So I create one, move the **source/css/_custom/custom.styl** into it and rename it. But the style of all pages is mess. It looks like v7.4.1 does not way any more...

**Comment by stevenjoezhang** [comment]
#982, #1010, #1162

**Comment by AlexHex7** [comment]
@stevenjoezhang 

您好,我的问题并没有解决.
按照如下操作
https://github.com/theme-next/hexo-theme-next/issues/973#issuecomment-511168511
重新编译后, 所有样式都没了.
![image](https://user-images.githubusercontent.com/30361851/66383166-19c04f80-e9ef-11e9-854e-6397266a5b54.png)

更新hexo以后, source文件夹下并没有**_data/**文件夹. 手动创建该文件夹,放入custom.styl, 重命名. 无法重新编译与否, 最终的页面样本都没了.

**Comment by stevenjoezhang** [comment]
如果有报错信息：请提供报错信息
如果没有：尝试执行`hexo clean`

**Comment by AlexHex7** [comment]
问题已解决, 谢谢. _data/路径放错了. https://github.com/theme-next/hexo-theme-next/issues/973#issuecomment-511205222
文件太多,没注意到前面的错误...抱歉

**Comment by stevenjoezhang** [comment]
网站上也有文档来着，但是还没翻译成中文，所以可能会有些不太清楚的地方

感谢您的支持。

**Comment by stevenjoezhang** [comment]
更新说明加到这里了，欢迎关注：https://github.com/theme-next/hexo-theme-next/issues/1217
