### ISSUE TITLE
Uncaught ReferenceError: pangu is not defined

### ISSUE THREAD

**Issue by edsion1107** [theme-next/hexo-theme-next#1206]
![2018-05-11 11 56 55](https://user-images.githubusercontent.com/1925286/39906012-d8ca3e0e-5512-11e8-879f-c1c76e9ebf11.png)
![2018-05-11 11 57 28](https://user-images.githubusercontent.com/1925286/39906016-d955a4c6-5512-11e8-9e71-e4458670a9c0.png)

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/hexo-theme-next/pull/1105
