### ISSUE TITLE
顶部加载进度条设置无效(Invalid top load progress bar setting)

### ISSUE THREAD

**Issue by JiangJiangJiang98** [theme-next/hexo-theme-next#1224]
## Steps to reproduce the behavior 
1. cd themes/next
$ git clone https://github.com/theme-next/theme-next-pace source/lib/pace
2. 修改配置文件如下(_config)
# Progress bar in the top during page loading.
# Dependencies: https://github.com/theme-next/theme-next-pace
# For more information: https://github.com/HubSpot/pace
pace:
  enable: true
  # Themes list:
  # big-counter | bounce | barber-shop | center-atom | center-circle | center-radar | center-simple
  # corner-indicator | fill-left | flat-top | flash | loading-bar | mac-osx | material | minimal
  theme: minimal
3. hexo clean ->hexo g ->hexo s

## Environment Information
Hexo v3.9.0 主题Next.Pisces v7.4.1

**Comment by stevenjoezhang** [comment]
?
