### ISSUE TITLE
busuanzi计数显示不稳定

### ISSUE THREAD

**Issue by Bigwode** [theme-next/hexo-theme-next#1229]
我修改了next的_config,yml文件中关于这部分的设置：
busuanzi_count:
  enable: true
  total_visitors: true
  total_visitors_icon: user
  total_views: true
  total_views_icon: eye
  post_views: true
  post_views_icon: eye
希望在页面上显示出访问量，但是没有显示。

**Comment by stevenjoezhang** [comment]
请按照格式要求填写 Issue，否则我们无法解决问题，并将直接关闭此 Issue。事实上，您的描述没有提供任何有效信息。

**Comment by stevenjoezhang** [comment]
看上去您遇到了和这个PR相同的问题：https://github.com/theme-next/hexo-theme-next/pull/1233
这是live2d插件造成的bug，NexT主题不对此负责。
