### ISSUE TITLE
启动项目后中文没有生效，边栏不展示文章目录，TOC 配置为默认配置

### ISSUE THREAD

**Issue by 6westboy9** [theme-next/hexo-theme-next#1236]
刚刚搭建的项目

### Node.js and NPM Information

```
➜  Hexo node -v && npm -v 
v12.3.1
6.9.0
```

### Package dependencies Information

```
➜  Hexo cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-server": "^1.0.0"
  }
}%
```

### Hexo Version

```
➜  Hexo hexo -v
hexo: 4.0.0
hexo-cli: 2.0.0
os: Darwin 19.0.0 darwin x64
node: 12.3.1
v8: 7.4.288.27-node.18
uv: 1.29.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.38.0
napi: 4
llhttp: 1.1.3
http_parser: 2.8.0
openssl: 1.1.1b
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
```

### Hexo Configuration

```
language: zh-Hans
theme: next
```

### NexT Configuration

默认

**Comment by stevenjoezhang** [comment]
我们的官方文档中从未出现`zh-Hans`这一语言选项。不知您是从哪里得知的这一错误用法？

https://theme-next.org/docs/getting-started/#Choosing-Language

原则上 GitHub Issue 不用于解答此类问题，欢迎加群讨论：https://github.com/theme-next/hexo-theme-next/issues/1204

**Comment by 6westboy9** [comment]
> 我们的官方文档中从未出现`zh-Hans`这一语言选项。不知您是从哪里得知的这一错误用法？
> 
> https://theme-next.org/docs/getting-started/#Choosing-Language
> 
> 原则上 GitHub Issue 不用于解答此类问题，欢迎加群讨论：#1204
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/bdace7f514668f8392073068c6df47f493380b19/68747470733a2f2f7468656d652d6e6578742e6f72672f696d616765732f646f63732f6e6578742d64656661756c742d736368656d652d6c696e75782e706e67"><img alt="" height="14" src="/images/favicon-16x16-next.png?v=7.4.2"> NexT**[Getting Started](https://theme-next.org/docs/getting-started/index.html)**NexT User Docs – Starting to Use
