### ISSUE TITLE
部署到远程后底部的“翻页”出现问题

### ISSUE THREAD

**Issue by 1am-one** [theme-next/hexo-theme-next#1237]
my blog -> https://chralpha.com

底部翻页页面出现问题：

![](https://raw.githubusercontent.com/1am-one/imgbagX/beta/hexo-next-page-bug-2.PNG)

**Comment by 1am-one** [comment]
其他页面的翻页也出现类似问题，求助！

![](https://raw.githubusercontent.com/1am-one/imgbagX/beta/hexo-next-page-bug-3.PNG)

**Comment by jiangtj** [comment]
如果你使用最新的hexo（4.0.0），需要将主题升级至最新的release（7.4.2）

**Comment by 1am-one** [comment]
> 
> 
> 如果你使用最新的hexo（4.0.0），需要将主题升级至最新的release（7.4.2）

由于用到 GitHub 仓库备份博客源代码，主题中没有用 git clone 的形式安装，所以无法使用readme中的git pull 进行升级

请问该如何无痛升级，主题中的自定义配置挺多的，要一个个转移吗？

**Comment by 1am-one** [comment]
![](https://raw.githubusercontent.com/1am-one/imgbagX/beta/hexo-next-page-bug-4.PNG)

侧边的这些按钮也失效

![](https://raw.githubusercontent.com/1am-one/imgbagX/beta/hexo-next-page-bug-5.PNG)

但同时这些按钮又还可以正常使用

**Comment by stevenjoezhang** [comment]
请按照要求填写 Issue。
请在发 Issue 之前搜索一下已有的 Issue： https://github.com/theme-next/hexo-theme-next/issues/1216
求助请加群，已经在 Issue 中置顶了，为什么不看一下呢：https://github.com/theme-next/hexo-theme-next/issues/1204

**Comment by stevenjoezhang** [comment]
问题已解决。升级到最新版本即可。
