### ISSUE TITLE
 font.global.family 中如何配置多个字体

### ISSUE THREAD

**Issue by buker2012** [theme-next/hexo-theme-next#1238]
![image](https://user-images.githubusercontent.com/22735530/67416568-a545fd00-f5f9-11e9-9074-15103fc974d2.png)
这样好像不行。

**Comment by stevenjoezhang** [comment]
这样是可以的。`enable`选项可能有一定的误导性，会在未来解决：https://github.com/theme-next/hexo-theme-next/pull/1058
