### ISSUE TITLE
v7.4.2 主题在手机浏览器显示空白

### ISSUE THREAD

**Issue by phpha** [theme-next/hexo-theme-next#1240]
Hexo v4.0.0
NexT.Muse v7.4.2 
[测试网址](https://blog.phpha.com/)
手机端打开一片空白

**Comment by stevenjoezhang** [comment]
测试无问题，与 NexT 主题无关。

**Comment by phpha** [comment]
> 测试无问题，与 NexT 主题无关。

`Android` 手机浏览器无问题，`iPhone ( iOS 12.1.1 ) Safari` 及微信 `APP` 内打开，均为空白，只能显示最底部的版权相关信息。

![](http://qiniu.static.homike.com/bug/1.jpeg)
![](http://qiniu.static.homike.com/bug/2.jpeg)

**Comment by stevenjoezhang** [comment]
目前最新的 iOS 系统为 13.1.3，升级系统即可；有其他问题欢迎发邮件咨询 Apple 客服。

**Comment by 1v9** [comment]
据我所知微信安卓端可以调整浏览器内核，iOS 端不太了解。

**Comment by stevenjoezhang** [comment]
其它解决方案：
- 禁用 motion
- 使用 7.3.0 或之前的 NexT 主题

**Comment by phpha** [comment]
> 其它解决方案：
> 
>     * 禁用 motion
> 
>     * 使用 7.3.0 或之前的 NexT 主题

禁用 `motion` 后解决了  Thks.
