### ISSUE TITLE
希望可以在next配置文件里加入更改书签位置的设置！！！

### ISSUE THREAD

**Issue by suyin-long** [theme-next/hexo-theme-next#1244]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

建议：
next 7.4.2版本中书签和Follow me on github 的位置都是右上角，这样在使用这两个功能的时候，两者图标会重叠，希望可以在配置文件中加入更改书签位置的设置，比如将书签更改到左上角。

**Comment by stevenjoezhang** [comment]
默认不在右上角哦，可以根据sidebar位置变的。
`_config.yml`已经1000多行了，这些通过一行CSS就能自定义的选项暂时是不会考虑加的。祝您使用愉快。
