### ISSUE TITLE
auto_excerpt功能无法正常使用？？？

### ISSUE THREAD

**Issue by suyin-long** [theme-next/hexo-theme-next#1245]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
v10.16.0
6.9.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "canvas-nest.js": "^2.0.4",
    "gitalk": "^1.5.0",
    "hexo": "^4.0.0",
    "hexo-blog-encrypt": "^3.0.3",
    "hexo-deployer-git": "^2.0.0",
    "hexo-filter-emoji": "^2.0.2",
    "hexo-filter-optimize": "^0.2.7",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-related-popular-posts": "^3.0.6",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-symbols-count-time": "^0.6.3",
    "hexo-tag-plugin": "github:theme-next/hexo-tag-plugin",
    "hexo-theme-next-anchor": "^1.0.3",
    "shelljs": "^0.8.3"
  }
}
```

### Hexo Version

```
hexo: 4.0.0
hexo-cli: 2.0.0
os: Windows_NT 10.0.18362 win32 x64
http_parser: 2.8.0
node: 10.16.0
v8: 6.8.275.32-node.52
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 4
openssl: 1.1.1b
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml
# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: true

# Automatically excerpt description in homepage as preamble text.
excerpt_description: true

# Automatically excerpt (Not recommend).
# Use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 150
```

## Other Information 

问题：
7.4.2版本中auto_excerpt: 设置后变成了全文都显示，而不是截取文章指定的长度？
以前用的7.2.x的版本就没问题。

以前的版本length的值设置为150刚好，现在设置为150就是全文显示，现在只能设置15，但是15显示的只有个段落名。如下图所示：
![示意图](https://user-images.githubusercontent.com/49554285/67632776-2d225480-f8e3-11e9-97cd-d265afe872d4.png)

**Comment by suyin-long** [comment]
图片放成了配置图，应该是这张图：
![示意图](https://user-images.githubusercontent.com/49554285/67632813-97d39000-f8e3-11e9-9356-5bf75dc2af5c.jpg)

**Comment by stevenjoezhang** [comment]
请  不  要  重  复  提  交  Issue
https://github.com/theme-next/hexo-theme-next/issues/1164

**Comment by stevenjoezhang** [comment]
根据约定，
「请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。」
我们将在不进行调查的情况下关闭您的 Issue。

**Comment by stevenjoezhang** [comment]
If you are using NexT 7.6.0 and later, please install the plugin: https://github.com/chekun/hexo-excerpt
