### ISSUE TITLE
标签和分类功能无法显示

### ISSUE THREAD

**Issue by GCPD123** [theme-next/hexo-theme-next#1251]
按照文档操作后发现标签和分类显示的是“暂无标签”，可是我创建的标签和分类的index页面，在文章中也加入了tags和category属性，并且有相应的内容，可是仍然无法显示，请问还可能有哪些原因导致？

**Comment by stevenjoezhang** [comment]
有很多原因都可能导致这个问题。请提供源码。

**Comment by stevenjoezhang** [comment]
为节省时间，提高效率，请将主题换为默认主题，然后确认问题是否仍然存在。

**Comment by GCPD123** [comment]
这是站点的配置文件：
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

这是默认主题的配置文件：
# Header
menu:
  Home: /
  Archives: /archives
  tags: /tags
  categories: /categories
rss: /atom.xml


这是生成的标签页的内容：
---
title: tags
date: 2019-10-31 14:10:12
type: "tags"
---


这是文章头部属性：
---
title: xxxx
date: 2019-10-31 10:30:00
tags: 
 - 123
categories: 
 - 333
---

请问还有哪些要注意的地方？

**Comment by stevenjoezhang** [comment]
你可以对照文档看一下： https://theme-next.org/docs/theme-settings/custom-pages

**Comment by GCPD123** [comment]
感谢 问题解决了
