### ISSUE TITLE
基于 Data Files 如何引入自定义的 js 文件?

### ISSUE THREAD

**Issue by Dueot** [theme-next/hexo-theme-next#1254]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [ ] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

#### 这不是一个错误。这只是一个问题？或者一个想法
- 我想引入自定义的 js 文件（与文章无关）以实现更多的功能，比如 [鼠标点击特效](https://emoii.me/)
- 查阅文档之后，发现需要把资源放在``theme 比如 Next `` 的静态资源目录中，事实上，在这之前我一直是这么做的；
- 我发现您使用的 ``Data Files`` 是一个非常棒的功能，可以平滑升级``Next``而无需任何改动；
- 我查阅了[hexo 关于 Data Files 的文档](https://hexo.io/docs/data-files)，但没有任何思路。

基于以上，想向您请教它是如何实现的，亦或者是它已经实现而我没能发现并使用它。

感谢您的帮助。

**Comment by stevenjoezhang** [comment]
在您想要脚本加载的地方加入：

```html
<script src="path_to_your_js_file.js"></script>
```

**Comment by Dueot** [comment]
感谢您的回答，我遇到了下列问题：
- 我不想改动``Next``的任何东西，因为会影响它的平滑升级；
- 我尝试把文件放在 ``source`` 目录中引入，但编译之后无法识别；
- 如何可以使自定义文件使用到您的``Data Files``功能？

感谢您的帮助。🙏

**Comment by stevenjoezhang** [comment]
不客气，感谢您的支持。

> 我不想改动Next的任何东西，因为会影响它的平滑升级；

不用担心，您可以在不改动任何NexT原始模版的情况下实现这一功能。

> 我尝试把文件放在 source 目录中引入，但编译之后无法识别；

无法识别的情况有很多种。您需要更详细的描述，比如提供报错信息？

另外，您不需要基于Hexo的Data Files特性来实现；NexT主题已经对其进行了封装。请查看在Issue页面置顶的说明： https://github.com/theme-next/hexo-theme-next/issues/1217 ，里面详细地描述了custom_file_path用法
