### ISSUE TITLE
leancloud visitor didn't be ignored from localhost

### ISSUE THREAD

**Issue by xuejiaW** [theme-next/hexo-theme-next#1258]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 

leancloud visitor ignore visit from localhost

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

localhost visit will still be counted into leancloud visitor

## Steps to reproduce the behavior 

1. hexo s to generate local website
2. access one page
3. the visits count was increased

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Version

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
We're working on it: https://github.com/theme-next/hexo-theme-next/compare/localhost
