### ISSUE TITLE
the Post wordcount display settings of netx's  scheme Mist can't display in the middle of  bottom while other scheme ok

### ISSUE THREAD

**Issue by kkonghao** [theme-next/hexo-theme-next#1259]
- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
![Expected behavior](https://kankan-myblog.oss-cn-shenzhen.aliyuncs.com/img/20191106033540.png)

## Actual behavior 

![Actual behavior](https://kankan-myblog.oss-cn-shenzhen.aliyuncs.com/img/20191106033627.png)
- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
chang Mist scheme to other scheme

**Comment by stevenjoezhang** [comment]
" I have already viewed the latest Roadmap on GitHub and searched for current issues, which does not help me."

https://github.com/theme-next/hexo-theme-next/issues/992

**Comment by jiangtj** [comment]
Add this style in custom style file
```css
.footer-inner {
  text-align: center;
}
```
