### ISSUE TITLE
7.5版本社交栏Email地址不能正常解析

### ISSUE THREAD

**Issue by mghcool** [theme-next/hexo-theme-next#1260]

**Comment by stevenjoezhang** [comment]
收到，会尽快修复。

![截屏2019-11-06下午12 40 39](https://user-images.githubusercontent.com/16272760/68268835-a283e700-0092-11ea-9669-fb3c94375040.png)
另外，我们的Issue检查单是否还写得不够清楚？

**Comment by mghcool** [comment]
个人感觉检查单后面在加一句删除空格的提示就好了

**Comment by lookis** [comment]
Same problem,
问题在于 hexo-util 里 url_for 无法正确检测 mailto 地址，导致在 mailto 前面加了 /context-path，刚提了一个issue在那边
https://github.com/hexojs/hexo-util/issues/122

**Comment by mghcool** [comment]
> 同样的问题，
> 问题在于hexo-util里url_for无法正确检测mailto地址，导致在mailto前面加了/ context-path，刚提了一个问题在那边
> [hexojs / hexo-util＃122](https://github.com/hexojs/hexo-util/issues/122)

请问该怎么解决，里面写的没看懂啊

**Comment by lookis** [comment]
> > 同样的问题，
> > 问题在于hexo-util里url_for无法正确检测mailto地址，导致在mailto前面加了/ context-path，刚提了一个问题在那边
> > [hexojs / hexo-util＃122](https://github.com/hexojs/hexo-util/issues/122)
> 
> 请问该怎么解决，里面写的没看懂啊

这是一个bug，无法通过配置的方式解决，如果想快速解决的话就自己fork一个hexo-util，然后把
https://github.com/hexojs/hexo-util/blob/master/lib/url_for.js#L28-L31
这三行里第二个if判断去掉，直接在第一个if判断成功之后就 return path，

因为mailto已经算是站外链接了，但mailto取不到origin

**Comment by lookis** [comment]
或者可以试一下在hexo的config里把 root: 设置空出来，不要填 /，这样 context + path 就是 '' + mailto:xxx

**Comment by stevenjoezhang** [comment]
等`hexo-util`那边解决就行了。
