### ISSUE TITLE
ReferenceError: Can't find variable: IntersectionObserver

### ISSUE THREAD

**Issue by cycjimmy** [theme-next/hexo-theme-next#1261]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
MacOS Safari下不报错

## Actual behavior 
Safari 下报错 ReferenceError: Can't find variable: IntersectionObserver

- Links to demo site with this issue: 
  - https://muse.theme-next.org/
  - https://mist.theme-next.org/
  - https://pisces.theme-next.org/
  - https://theme-next.org/

## Steps to reproduce the behavior 
直接使用Safari访问上述站点，查看console

## Environment Information
系统: MacOS Mojave 10.14.2
浏览器: Safari Version 12.0.2 (14606.3.4)

**Comment by stevenjoezhang** [comment]
最新的macOS是10.15。请升级系统，或使用其它浏览器。
