### ISSUE TITLE
7.5.0 主页自动摘录

### ISSUE THREAD

**Issue by JonSnows** [theme-next/hexo-theme-next#1262]
auto_excerpt:
  enable: true
  length: 150
之前是可以的，升级到7.5.0不生效。
还有，如何才能只显示文章标题，而不显示内容。和归档不同的是，根据hexo站点配置显示文章数量。

**Comment by jiangtj** [comment]
Try install https://github.com/theme-next/hexo-auto-excerpt

> 还有，如何才能只显示文章标题，而不显示内容。和归档不同的是，根据hexo站点配置显示文章数量。

归档也可以配置每页的文章数的 https://github.com/hexojs/hexo-generator-archive

**Comment by stevenjoezhang** [comment]
由于您拒绝按照要求填写Issue，我们将直接关闭，请知悉。祝您使用愉快。
