### ISSUE TITLE
社交栏图标hover上去的title里右箭头被转义了，无法正确显示

### ISSUE THREAD

**Issue by lookis** [theme-next/hexo-theme-next#1264]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
当鼠标hover在图标上时，&rarr; 显示为右箭头

## Actual behavior  
显示为 &amp;rarr;

- Links to demo site with this issue: https://mghcool.github.io/
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Version

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

## Other Information 
https://github.com/theme-next/hexo-theme-next/blob/master/scripts/helpers/next-url.js#L66
这里在使用 htmlTag 时， escape参数只控制 text里是否转义，而attrs 里会强制转义，可以参考 htmlTag 源码：
https://github.com/hexojs/hexo-util/blob/master/lib/html_tag.js#L23-L33

**Comment by 1v9** [comment]
你可以暂时在模板里直接用右箭头符号，不会被转义。

**Comment by stevenjoezhang** [comment]
`hexo-util`改变了`html_tag`的行为，但如果NexT主题跟进的话，会破坏所有没有升级Hexo到4.0版本的用户的体验。我们已经最大程度地做出了改变： https://github.com/theme-next/hexo-theme-next/pull/1175

其它问题应该由`hexo-util`解决。至少，不向下兼容这一点是非常糟糕的。
