### ISSUE TITLE
couldn't use baidushare

### ISSUE THREAD

**Issue by bmxbmx3** [theme-next/hexo-theme-next#1270]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***
I wan't to use baidushare when follow [the tutorial](https://asdfv1929.github.io/2018/05/25/baidu-share/) for sharing but have failed.How to fix it?
p.s. my hexo theme is from your repository,not from iissnan/hexo-theme-next.

**Comment by stevenjoezhang** [comment]
Baidu share has been removed.

https://github.com/theme-next/hexo-theme-next/pull/967

**Comment by bmxbmx3** [comment]
why has baidushare been removed?I have read #967 but don't know the reason was.

**Comment by stevenjoezhang** [comment]
Because we have our own plugins: https://github.com/theme-next/hexo-next-share
Baidu share is not a good choice for bloggers in 2019.

**Comment by bmxbmx3** [comment]
so if I wan't to improve my blog for seo,how to do?

**Comment by stevenjoezhang** [comment]
Your references are outdated. Please take a look at the description of #967

If you still believe that Baidu share is important, please modify the source code yourself.

**Comment by bmxbmx3** [comment]
Thanks
