### ISSUE TITLE
代码开启高亮后，复制后没有缩进了，如何解决？

### ISSUE THREAD

**Issue by wanghkkk** [theme-next/hexo-theme-next#1271]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [ ] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [ ] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 

在开启代码高亮后，复制到word的时候能够保持代码格式，比如缩进，因为对于一些要求代码索引的python，如果没有缩进了基本上没法看，在关闭hexo代码高亮的时候，复制是有代码缩进的。

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Version

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
我们没有遇到过你描述的情况。虽然不太清楚为什么你要把代码复制到word，但看上去复制后缩进完全正常。也许你可以试试换个浏览器，或者复制后粘贴到什么别的地方。

另外，为了帮大家节省时间，请按照要求完成Issue Checklist中的**所有事项**。Issue Checklist是精心设计的，只有你按要求填写，我们才能进行调查。至少需要提供截图或者网址，因为单纯的文字描述没有提供任何有效信息，也不能作为依据。

**Comment by wanghkkk** [comment]
很抱歉。
当复制到oneNote，已经没有了缩进。但是word还是OK的，看来是onenote的问题。

**Comment by stevenjoezhang** [comment]
似乎确实如此，这是Onenote一直存在的问题： https://blog.csdn.net/github_15459469/article/details/51495735

**Comment by wanghkkk** [comment]
嗯嗯，确实的，十分感谢

**Comment by stevenjoezhang** [comment]
不客气，有其它问题欢迎提出 😊
