### ISSUE TITLE
新版本，transition动画对侧边栏站点block无效，scheme=Gemini

### ISSUE THREAD

**Issue by alyssaasa** [theme-next/hexo-theme-next#1273]
motion:
  enable: true
  async: false
  transition:
    # Transition variants:
    # fadeIn | flipXIn | flipYIn | flipBounceXIn | flipBounceYIn
    # swoopIn | whirlIn | shrinkIn | expandIn
    # bounceIn | bounceUpIn | bounceDownIn | bounceLeftIn | bounceRightIn
    # slideUpIn | slideDownIn | slideLeftIn | slideRightIn
    # slideUpBigIn | slideDownBigIn | slideLeftBigIn | slideRightBigIn
    # perspectiveUpIn | perspectiveDownIn | perspectiveLeftIn | perspectiveRightIn
    post_block: fadeIn
    post_header: slideDownIn
    post_body: slideDownIn
    coll_header: slideLeftIn
    # Only for Pisces | Gemini.
    sidebar: slideDownIn

这里不管怎么改，侧边栏的站点block都不会变

**Comment by stevenjoezhang** [comment]
请按要求发 Issue。为了避免大家浪费时间，不按格式发一律不处理。

**Comment by alyssaasa** [comment]
> 请按要求发 Issue。为了避免大家浪费时间，不按格式发一律不处理。

sorry, 没注意格式，重新发一下。

**Comment by stevenjoezhang** [comment]
不要重新发，Issue是可以编辑的。请至少提供一下网址。

**Comment by stevenjoezhang** [comment]
OK，大概知道问题了
