### ISSUE TITLE
请问是否有知乎和简书的图标？

### ISSUE THREAD

**Issue by GeneralLi95** [theme-next/hexo-theme-next#1276]
个人介绍栏可否加上知乎和简书的图标，谢谢。

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/issues/1137

不客气。

**Comment by stevenjoezhang** [comment]
我们将在近期迁移至 Font Awesome 5，届时将支持「知乎」图标，请注意升级： https://github.com/theme-next/hexo-theme-next/pull/1438
谢谢关注。
