### ISSUE TITLE
样式表.post相关

### ISSUE THREAD

**Issue by npuwkh** [theme-next/hexo-theme-next#1278]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
文章内容和标题出现在一个阴影框中

## Actual behavior 

网上大多教程都用到custom.styl 我参考新版本没有custom.styl的方法进行操作：
在next主题的配置文件中 取消了style: source/_data/styles.styl的注释 在D:\blog\themes\next\source_data下创建了同名文件 （在blog目录下也创建了_data都不行
加入代码
.post {
margin-top: 60px;
margin-bottom: 60px;
padding: 25px;
-webkit-box-shadow: 0 0 5px rgba(202, 203, 203, .5);
-moz-box-shadow: 0 0 5px rgba(202, 203, 204, .5);
}
不能实现文章阴影框
请大佬帮助（hexo clean过了）
---------------------------------------------------------------------
但是在themes\next\source\css\_common\components\post\post.styl中de 
.post-body中添加以上代码能实现文章主题出现在阴影框中
在.post_header.styl中添加以上代码能实现标题出现在阴影框中
**但是标题和文章不在一个阴影框**
- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

**Comment by jiangtj** [comment]
@npuwkh 能否提供博客的源码？

 styles.styl文件需要创建在 `${hexo-dir}/source/_data/styles.styl`

**Comment by stevenjoezhang** [comment]
> 但是标题和文章不在一个阴影框

这靠的是您自己写样式表，如何实现是您自己的工作，NexT主题没有义务为您解决个人问题，请知悉，谢谢！
一个成功的方法可以看官网的源码： https://github.com/theme-next/theme-next.org

**Comment by stevenjoezhang** [comment]
另外，如果是报告bug，请按照bug的模版填写。这里面会指导您如何通过执行`hexo clean`等方式解决问题。造成

> 不能实现文章阴影框

的原因有很多。您不按照模版填写Issue，给出必要的信息，我们没有任何办法debug。
祝您使用愉快。

**Comment by npuwkh** [comment]
不好意思各位 第一次用 给各位大佬造成麻烦了  谢谢各位 我自己找找问题 下次按照要求进行提问 对不起

**Comment by stevenjoezhang** [comment]
目录结构是这样就没问题：

![截屏2019-11-18下午7 55 42](https://user-images.githubusercontent.com/16272760/69050482-18962f80-0a3d-11ea-867e-7d497d0f9cce.png)

按照您说的

> 在next主题的配置文件中 取消了style: source/_data/styles.styl的注释 在D:\blog\themes\next\source\\_data下创建了同名文件

这是正确的操作方法。

**Comment by npuwkh** [comment]
![image](https://user-images.githubusercontent.com/57609063/69051625-d0c4d780-0a3f-11ea-886e-6ca9bd44b093.png)这样吧

**Comment by npuwkh** [comment]
谢谢各位
