### ISSUE TITLE
有方法可以使category的菜单实现折叠吗

### ISSUE THREAD

**Issue by fkxie** [theme-next/hexo-theme-next#1282]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [ ] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
预期能够折叠category中的分类目录
若是category中分类较多的话（包括多级目录），会使得category较长，导致查阅起来不方便

Thanks in advance.

## Actual behavior 

- Links to demo site with this issue: https://leeyenxie.github.io/categories/
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
node -v: v12.13.0
npm -v: 6.12.0
```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

## Other Information

**Comment by stevenjoezhang** [comment]
> 若是category中分类较多的话（包括多级目录），会使得category较长，导致查阅起来不方便

您应该考虑到，如果折叠的话，会导致查阅起来**更不方便**

**Comment by stevenjoezhang** [comment]
您可以思考一下这个问题：折叠之后怎么展开呢？
或者，更具体地说：Talk is cheap. Show me the code.

**Comment by fkxie** [comment]
您好，我觉得您说的有道理，我会考虑一下。
我觉得应该无法直接从`_config.yaml`中标签来实现这个功能了，需要自己去改一下源码

**Comment by fkxie** [comment]
您好，我觉得可以通过再次点击展开。
不过这应该需要直接对源码进行修改，我会尝试一下

**Comment by stevenjoezhang** [comment]
> 通过再次点击展开

那不就是我之前说的，会导致查阅起来**更不方便**
本来只用滑动就行了，现在不只要滑动，还要点击。

**Comment by fkxie** [comment]
我觉得您说的有道理，一般情况下的确会造成不便。您看有没有这种情况，就是一级目录下有很多子目录，这样分类这一栏会比较长。一般是先找到一级目录的情况下，再去找相应的子目录，这种情况下子目录能够折叠到一级目录的情况下可能会好一些。这样的话，分类界面显示的都是一级目录，然后找到之后再去找子目录。不过这种情况应该比较小众，哈哈。--    发自新浪邮箱客户端
在 11月23日 10:42，ᴍɪᴍɪ <notifications@github.com> 写道：


通过再次点击展开



那不就是我之前说的，会导致查阅起来更不方便


本来只用滑动就行了，现在不只要滑动，还要点击。



&mdash;

**Comment by stevenjoezhang** [comment]
分类可以尽量少写一点，标签多一点。典型的，一篇文章有一个分类和三个标签就很不错。
这种与用户习惯相关的东西很难由主题来控制。

**Comment by fkxie** [comment]
感谢您的建议！

**Comment by sqduan** [comment]
我也希望能出一个使菜单折叠的功能，用户可以自由选择是否折叠，希望开发者可以考虑一下这个功能，谢谢了！
