### ISSUE TITLE
set social media for e-mail but the url direct to a path

### ISSUE THREAD

**Issue by ChongzhengZhao** [theme-next/hexo-theme-next#1285]
#1260

**Comment by ChongzhengZhao** [comment]
@1v9 Ummmm. I think it is not a duplicate question because I cannot search any issues indicating this problem. Can you refer it?

**Comment by 1v9** [comment]
@ChongzhengZhao Before I closed this issue I have edited it.

**Comment by stevenjoezhang** [comment]
Duplicate of https://github.com/hexojs/hexo-util/issues/122
