### ISSUE TITLE
分页栏图标没有显示

### ISSUE THREAD

**Issue by huangjianxian** [theme-next/hexo-theme-next#1286]
在换一台电脑部署之后，分页图标不显示了，直接显示<i class="fa fa-angle-right"></i>
请问这个是什么原因呢

**Comment by 1v9** [comment]
我没看懂你的意思，省略了太多

**Comment by xhp281** [comment]
我的分页显示： <i class="fa fa-angle-left"></i>

**Comment by stevenjoezhang** [comment]
请升级到7.4.2或7.5.0。请在发Issue前搜索一下已有Issue。
