### ISSUE TITLE
导航栏点击一级标题显示不全

### ISSUE THREAD

**Issue by 6westboy9** [theme-next/hexo-theme-next#1288]
**确定是按  Issue 的要求验证的！！！**

## Question

一级标题定位显示过于考上，字体显示不全

![image](https://user-images.githubusercontent.com/39526241/69617452-3550e980-1073-11ea-8ee7-fa9d007658cd.png)

二级或者其他三级、四级标题定位没有问题

![image](https://user-images.githubusercontent.com/39526241/69617461-3a159d80-1073-11ea-87a0-1d9b101ea6ca.png)

### Node.js and NPM Information

```
v12.3.1
6.9.0
```

### Package dependencies Information

```
├── hexo@4.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0
```

**Comment by stevenjoezhang** [comment]
> 确定是按 Issue 的要求验证的！！！

感谢您的反馈。您能否提供页面的链接，以及使用的是什么系统、什么浏览器？能否换其它浏览器试试？

**Comment by 6westboy9** [comment]
> > 确定是按 Issue 的要求验证的！！！
> 
> 感谢您的反馈。您能否提供页面的链接，以及使用的是什么系统、什么浏览器？能否换其它浏览器试试？

使用的 macOs 系统，使用 Google 浏览器和自带的 Safari 都是这样子的，暂时没有部署在外网提供不了页面链接

**Comment by stevenjoezhang** [comment]
请您部署一下。

**Comment by 6westboy9** [comment]
好的，明天部署了，发您链接

**Comment by stevenjoezhang** [comment]
似乎是因为h1没有`padding-top: 10px;`造成的。这是预期行为，因为h1只用在文章的大标题中。
为了您网站的SEO考虑，建议您不要再正文中使用一级标题。

**Comment by 6westboy9** [comment]
查看链接：https://6westboy9.github.io/2019/11/12/Tomcat-%E5%A4%9A%E7%A7%8D%E9%83%A8%E7%BD%B2%E6%96%B9%E6%A1%88/，好的，非常感谢

**Comment by stevenjoezhang** [comment]
修复了： https://github.com/theme-next/hexo-theme-next/commit/6a81dd2a2ab8fade46fa0fcada99215c1cdb9821
