### ISSUE TITLE
怎么加快HEXO访问速度呢？请问有什么解决方案吗？

### ISSUE THREAD

**Issue by huangjianxian** [theme-next/hexo-theme-next#1290]
你好，我现在搭建的网站采用hexo+githubpages，图片是用的阿里云OSS，但是感觉访问速度还是有点慢，请问有什么方法可以加速网站访问吗？

**Comment by stevenjoezhang** [comment]
没有问题是氪金解决不了的。买一个国内的VPS或者虚拟主机，部署上去就行😆

**Comment by stevenjoezhang** [comment]
有其它问题欢迎向Hexo提问： https://github.com/hexojs/hexo/issues
