### ISSUE TITLE
valine评论可以不显示浏览器版本和系统版本吗

### ISSUE THREAD

**Issue by huangjianxian** [theme-next/hexo-theme-next#1297]
你好，请问valine评论可以不显示浏览器版本和系统版本吗，如下图，能不显示红色部分吗，感觉有些突兀
![image](https://user-images.githubusercontent.com/18608444/69954706-e3a6d400-1536-11ea-9bf2-9c67b42ac9ba.png)

**Comment by stevenjoezhang** [comment]
https://github.com/xcss/valine/issues

**Comment by huangjianxian** [comment]
已解决，[hexo-Next主题valine评论系统不显示浏览器版本和操作系统版本](https://hjxlog.com/posts/20191203a1.html)
