### ISSUE TITLE
Can not open https://theme-next.org

### ISSUE THREAD

**Issue by Maples7** [theme-next/hexo-theme-next#13]
Error message of Chrome: 

theme-next.org didn’t send any data. 
ERR_EMPTY_RESPONSE

**Comment by ivan-nginx** [comment]
Yes, site is not ready yet. Will ready ASAP.

**Comment by jdhao** [comment]
I am curious how will build the new next official site compare to the old site [here](http://theme-next.iissnan.com/).

**Comment by ivan-nginx** [comment]
I'll see this. And yes, u are very curious guy. :smiley:

**Comment by Maples7** [comment]
Comment to keep this issue open cause the official website is not ready yet.

**Comment by jdhao** [comment]
When will the new site be ready? Can we make any contributions?

**Comment by ivan-nginx** [comment]
@jdhao @Maples7 site is ready now. Here is repo: https://github.com/theme-next/theme-next.org

**Comment by jdhao** [comment]
But the webpage [here](https://theme-next.org/) still shows the counting-down sign.

**Comment by ivan-nginx** [comment]
Mb need 2 await some time...
