### ISSUE TITLE
Arrow after link

### ISSUE THREAD

**Issue by Icatream** [theme-next/hexo-theme-next#1300]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

### scheme
- [ ] `Muse`
- [x] `Mist`
- [ ] `Pisces`
- [ ] `Gemini`

## Expected behavior 
The default URL style is not so clear.
I found the URLs in <https://theme-next.org/> have an arrow behind.
I want to make my own blog like that.
Then i went to <https://github.com/theme-next/theme-next.org>, i suppose it's the source of <https://theme-next.org/>.
The URLs are just markdown URL tag, but i didn't find the setting to display URLs with a arrow behind.

**Comment by stevenjoezhang** [comment]
Set `exturl: true`

**Comment by Icatream** [comment]
> Set `exturl: true`

That works, thanks.
