### ISSUE TITLE
为什么我用v7.6.0的creative_commons时生成的本文链接点击提示出错

### ISSUE THREAD

**Issue by fakerpawnno1** [theme-next/hexo-theme-next#1301]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [ ] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [ ] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [ ] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
不确定，你升级到最新的master分支试试。

**Comment by fakerpawnno1** [comment]
跳转时会把链接的绝对地址加到我在站点config中设置的url后面，地址栏会变成https:/******.github.io/https:/*******.github.io/posts/4a17b156/，就会有 Cannot GET /https:/f*******.github.io/posts/4a17b156/的提示信息。我不知道是url设置出问题了？

**Comment by stevenjoezhang** [comment]
有可能。我没有遇到过你说的这个情况，所以不能确定。你可以找个配置正确的Hexo博客看看源码，比较一下。

**Comment by LuchaoQi** [comment]
碰到了同样的问题

**Comment by stevenjoezhang** [comment]
@fakerpawnno1 @LuchaoQi This is a bug from hexo-util and has now been fixed. You may need to wait for a new version of Hexo to be released. https://github.com/hexojs/hexo-util/pull/147

**Comment by qzi** [comment]
我也发现了这个问题，footer后面的两个链接都不对

**Comment by stevenjoezhang** [comment]
这个修复没有被包含到Hexo 4.1.0中。只能等待hexo-util的下一个版本了。

**Comment by stevenjoezhang** [comment]
Fixed in Hexo v4.1.1

**Comment by Azjhong** [comment]
使用命令 
npm i hexo@4.1.1 
更新到 hexo 4.1.1 已解决问题
