### ISSUE TITLE
最新版百度sitemap的依赖和配置变化

### ISSUE THREAD

**Issue by qzi** [theme-next/hexo-theme-next#1302]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [ ] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [ ] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [ ] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
看到了一些添加百度sitemap的教程，安装了 

npm install hexo-generator-sitemap --save
npm install hexo-generator-baidu-sitemap --save
配置了
# hexo sitemap网站地图
sitemap:
path: sitemap.xml
baidusitemap:
path: baidusitemap.xml

但是我看到_config.yml 是不是已经默认原生支持了，我是不是啥都不安装只是默认解开注释就好了

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```
npm install hexo-generator-sitemap --save
npm install hexo-generator-baidu-sitemap --save
```

### Hexo Configuration

```yml
# hexo sitemap网站地图
sitemap:
path: sitemap.xml
baidusitemap:
path: baidusitemap.xml
```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
不清楚，第三方插件不归我们管。

> 看到了一些添加百度sitemap的教程

也许你应该找写教程的人问问。

**Comment by qzi** [comment]
> 不清楚，第三方插件不归我们管。
> 
> > 看到了一些添加百度sitemap的教程
> 
> 也许你应该找写教程的人问问。

那我把他那个插件卸载了吧，其实我想知道原生的是不是就够了，够了的话我就用原生的加入robot.txt去开百度的sitemap

**Comment by stevenjoezhang** [comment]
原生的是这个： https://github.com/hexojs/hexo-generator-sitemap

第三方插件也有很多： https://www.npmjs.com/search?q=hexo%20sitemap

我没有测试过不同的插件对于SEO的影响，这些皆是玄学
