### ISSUE TITLE
hexo-next-v6.7.0 首页 和 归档 按钮出现乱码

### ISSUE THREAD

**Issue by Azjhong** [theme-next/hexo-theme-next#1304]
![Snipaste_2019-12-08_17-15-35](https://user-images.githubusercontent.com/46050133/70387428-345b7880-19e0-11ea-8545-1bea17c3e59f.png)

**Comment by stevenjoezhang** [comment]
旧版的主题将不再维护，请您升级到NexT 7.5.0以上，即可解决此问题。

**Comment by stevenjoezhang** [comment]
或者您对照这个Pull Request 自行修改源码： https://github.com/theme-next/hexo-theme-next/pull/1175

**Comment by Azjhong** [comment]
谢谢，OK了。
