### ISSUE TITLE
local search  localhost显示正常，deploy之后不正常

### ISSUE THREAD

**Issue by wadmes** [theme-next/hexo-theme-next#1310]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Actual behavior 

https://wadmes.github.io/2019/11/01/OPENMPL/
![image](https://user-images.githubusercontent.com/20320821/70621265-26159280-1c54-11ea-9b77-c50527fc3d10.png)

localhost显示正常：
![image](https://user-images.githubusercontent.com/20320821/70621673-19de0500-1c55-11ea-9c04-25d58f587cb9.png)

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
第一张截图显示的是 CSS 的问题，导致搜索框的位置错误。

**Comment by greedymonkey** [comment]
请问楼主解决了吗，我也遇到了这个问题

**Comment by stevenjoezhang** [comment]
看上去这一行的`if`返回了`false`。请检查配置或者全部重新生成。
https://github.com/theme-next/hexo-theme-next/blob/294da6ddf3ef3bc244b761251db82464efbc09c7/source/css/_common/components/third-party/third-party.styl#L3
