### ISSUE TITLE
MathJax v3.0

### ISSUE THREAD

**Issue by reuixiy** [theme-next/hexo-theme-next#1313]
> MathJax version 3 is a complete rewrite from the ground up, with the goal of modernizing MathJax’s internal infrastructure, bringing it more flexibility for use with contemporary web technologies, making it easier to use with NodeJS for pre-processing and server-side support, and making it faster to render your mathematics.
>
> — *https://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html*

**Comment by stevenjoezhang** [comment]
Please review our roadmap before submitting new Issues

https://github.com/theme-next/hexo-theme-next/issues/809#issuecomment-539901972
