### ISSUE TITLE
是否可以提供参数设置文章图片是否居中显示

### ISSUE THREAD

**Issue by nekolr** [theme-next/hexo-theme-next#1317]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
提供参数设置文章图片居中显示

## Actual behavior 

- Links to demo site with this feature: https://blog.nekolr.com/
- Links to repository or source code of the blog: https://github.com/nekolr/nekolr.github.io

## Steps to reproduce the behavior 
使用了 Mist 主题，但是发现文章中的图片全部靠左显示，查看控制台发现是 `source\css\_schemes\Mist\_posts-expand.styl` 文件中的：

```
  .post-body img {
    margin-left: 0;
  }
```
影响了图片居中显示，能否提供一个变量控制呢？

**Comment by stevenjoezhang** [comment]
不可以，Mist主题就是这么设计的。请使用自定义CSS。

另，请不要提交重复的 Issue。你已经发过了一个相同的 Issue： https://github.com/theme-next/hexo-theme-next/issues/1316
