### ISSUE TITLE
how to set "archive page" to be "index page"

### ISSUE THREAD

**Issue by dslztx** [theme-next/hexo-theme-next#1320]
I want to set "archive page" to be "index page" , i.e. I will see the archive page when I enter the blog site in the browser

**Comment by stevenjoezhang** [comment]
Duplicate of https://github.com/theme-next/hexo-theme-next/issues/400

**Comment by dslztx** [comment]
At last, I have found a solution myself.That is use `archive.swig` file under `themes/next/layout` subdirectory to override the `index.swig` file in the same directory.

**Comment by dslztx** [comment]
@stevenjoezhang thank  you anyway for your reply.And I think this issue could be closed.

**Comment by jiangtj** [comment]
> @stevenjoezhang thank you anyway for your reply.And I think this issue could be closed.

You can also close the issue 😂

**Comment by GeneralLi95** [comment]
> At last, I have found a solution myself.That is use `archive.swig` file under `themes/next/layout` subdirectory to override the `index.swig` file in the same directory.

I think this is a better solution than the recommended one
