### ISSUE TITLE
incompatible with Google Chrome 79.0.3945.88 in Ubuntu

### ISSUE THREAD

**Issue by dslztx** [theme-next/hexo-theme-next#1321]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
render the blog site normally using Google Chrome 79.0.3945.88 in Ubuntu

## Actual behavior 

- https://dslztx.github.io/blog/

the rendered font is very small,using firefox does not reproduce the problem.Is the generated html/css/js source code incompatible with Google Chrome 79.0.3945.88 in Ubuntu?
Thanks very much

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
There is no evidence of a problem with the CSS of the NexT theme. You can ask the chrome maintainers for help.

**Comment by dslztx** [comment]
@stevenjoezhang  OK, thanks any way

**Comment by stevenjoezhang** [comment]
See also https://support.google.com/chrome/answer/95315?co=GENIE.Platform%3DDesktop&hl=en
