### ISSUE TITLE
The icon of side does not display  //侧边图标显示不出来

### ISSUE THREAD

**Issue by z1027001** [theme-next/hexo-theme-next#1323]
![image](https://user-images.githubusercontent.com/47052972/71251718-17b72d00-235e-11ea-90b8-95e1d1820c6e.png)
like this  
the v7.6 is OK  but I need use v7.0.
When I change theme to v7.0 
the icon can't show
I don't know how to solve

7.6可以  7.0就不行了 我因为一些问题需要用7.0
改变主题以后就不能正常显示图标了
我不晓得该咋办

**Comment by stevenjoezhang** [comment]
看看这个： https://github.com/theme-next/hexo-theme-next/issues/1304

**Comment by z1027001** [comment]
> 看看这个： #1304

很感谢您的答复 但是我不知道怎么对照您给的那个1175的pull request 修改源码 我没有看到相关源码 应该是我的个人看不懂的问题 我太小白了  您能稍微再教我一下下码
