### ISSUE TITLE
Creative Commons 4.0链接包含了一个null,是链接出错了还是本来就有一个null?

### ISSUE THREAD

**Issue by jiayaoO3O** [theme-next/hexo-theme-next#1327]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 

> https://creativecommons.org/licenses/by-nc-nd/4.0/

## Actual behavior 

![image](https://user-images.githubusercontent.com/22891632/71335748-2fb9c700-257f-11ea-90a6-ff3e3284239d.png)

## Steps to reproduce the behavior 
![image](https://user-images.githubusercontent.com/22891632/71335773-4d872c00-257f-11ea-91a8-b0cac746b87a.png)

**Comment by jiayaoO3O** [comment]
我发现了,要在language位置添加deed.zh,才能让链接后面跟一个

> deed.zh

![image](https://user-images.githubusercontent.com/22891632/71336015-70661000-2580-11ea-8238-10903f49e60d.png)
不知道这个位置能不能在language为空的时候,自动读取_config.yml识别为当前语言呢?
![image](https://user-images.githubusercontent.com/22891632/71336070-a2777200-2580-11ea-9e61-936a14a3d0b4.png)

**Comment by stevenjoezhang** [comment]
已经在月初修复，请等待新版发布： https://github.com/theme-next/hexo-theme-next/commit/6b635c93248410ed25073df4dbb9d66e9b7a9ce1
