### ISSUE TITLE
enabling pjax and schedule at the same time causes bug

### ISSUE THREAD

**Issue by Songkeys** [theme-next/hexo-theme-next#1328]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
When enabling pjax and schedule, clicking schedule will display the timetable.

## Actual behavior 

- Links to demo site with this issue: <https://songkeys.github.io/>
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior

Please try clicking the "日程表" (schedule) at the sidebar. The site doesn't call the google calendar api. But if you refresh the page manually, it does.

点击侧边栏的“日程表”，网站不会调用 API。但是手动刷新页面后，可以调用 API 并正常显示。

(Perhaps the "pushing state" feature caused this behaviour?)

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/hexo-theme-next/commit/0787ec0c273b64cf13ee08a4d517a735961bf489
