### ISSUE TITLE
I can't copy java annotation(Can't selected) in code block.

### ISSUE THREAD

**Issue by Smith-Cruise** [theme-next/hexo-theme-next#1329]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [X] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [X] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [X] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
When I can to copy my java code, I find that java annotaion can't be selected.

## Actual behavior 

![image](https://user-images.githubusercontent.com/18729228/71356462-43841e00-25bd-11ea-8c7b-fe9cc484911d.png)

- Links to demo site with this issue: https://www.inlighting.org/2019/spring-boot-security-thymeleaf.html

### Node.js and NPM Information

```
6.11.3
```

### Package dependencies Information

```
"hexo": "^4.0.0",
    "hexo-deployer-sftp": "^0.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
```

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/pull/977

**Comment by Smith-Cruise** [comment]
If I want to solve this problem, what should I do next?

**Comment by stevenjoezhang** [comment]
Remove this line:
https://github.com/theme-next/hexo-theme-next/blob/982d243d1e9d9c29a6b0ad30c9f9303c913362c5/source/css/_common/scaffolding/highlight/highlight.styl#L121

**Comment by Smith-Cruise** [comment]
Thanks, It works now. Maybe you should provide an option for this.

**Comment by stevenjoezhang** [comment]
You're welcome.
> Maybe you should provide an option for this.

Related issues are still under discussion.

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/hexo-theme-next/commit/9fdaba295a2c6c707a7d96d331762ab571b89c1a
