### ISSUE TITLE
如何创建一个不带目录的page

### ISSUE THREAD

**Issue by sev7e0** [theme-next/hexo-theme-next#1330]
是否支持在一个指定的page页面关闭目录，即使是按照Markdown格式书写的。

**Comment by xyyuhans** [comment]
disable toc in the [Front-matter](https://hexo.io/zh-cn/docs/front-matter), such as:
```
title:
date: 
categories:
tags:
toc:
  enable: false
```

**Comment by sev7e0** [comment]
Thanks！
@xyyuhans
