### ISSUE TITLE
运行乱码

### ISSUE THREAD

**Issue by hooray** [theme-next/hexo-theme-next#1334]
有的文章页面可以正常访问，有的文章页面则无法显示，打开查看源码发现乱码

![](https://i.loli.net/2019/12/25/Zct465Vz2wBgNYX.png)
![](https://i.loli.net/2019/12/25/ZOxCTnSYqEA1eDr.png)
![](https://i.loli.net/2019/12/25/MmSUB7K2xQXiF6R.png)

感觉像是被截断了

hexo: 3.9.0
next: 7.6.0

**Comment by stevenjoezhang** [comment]
Issue 的模版是为了让你填的，你直接删了，我们无法 debug。

**Comment by hooray** [comment]
@stevenjoezhang 抱歉，那我明天重新开一个 issue 吧

**Comment by stevenjoezhang** [comment]
没事，你可以先把 Hexo 和 NexT 主题都升级到最新试试。(Hexo 4.2.0 和 NexT 7.6.0)
另外可以检查以下这个 bug 出现在本地（hexo s）还是部署之后（hexo d）？

**Comment by hooray** [comment]
@stevenjoezhang 本地运行乱码，但部署之后就正常了，我还是关掉这个 issue 吧，部署正常就先不管了。另外 hexo 升级 4.2.0 后会出现白屏，这个我自己再研究下，不行再另开 issue 寻求帮助吧。

**Comment by stevenjoezhang** [comment]
好的，解决了就好。可以加一下Telegram群，讨论更方便： https://t.me/theme_next_chinese
