### ISSUE TITLE
next版本7.x过后在config.yml中设置阅读全文失效

### ISSUE THREAD

**Issue by Jackwew** [theme-next/hexo-theme-next#1336]
_config.yml中的设置如下： 
# 设置阅读全文
auto_excerpt:
  enable: true
  length: 150 #到多少字数后不显示

**Comment by stevenjoezhang** [comment]
不看更新说明就升级，造成的后果我们一概不负责。

https://github.com/theme-next/hexo-theme-next/issues/1217

**Comment by xhj** [comment]
@stevenjoezhang 今天启用尘封已久的旧博客时发现很多地方都broken了，看了一下这些issue后的主观感觉是（肯定不是事实）：现在你们的维护开发思路很有点自以为是了。

把很多功能都从核心程序中移除，希望用插件来解决，单纯从技术逻辑的角度来看无疑是正确的，但是像我这样的使用者期待的是开箱即用，并不希望投入太多的时间和精力，你们在技术上的正确决定多多少少有点只顾自己爽的味道，事实上已经加大了使用者的使用成本。

有些开源提交的结果是节约许多人的时间，有些开源提交的结果是许多人不得不为之作相应的修改，创造价值和增加负担之间，应有恰当的平衡。

当然，开源开发本身就是作贡献，使用者作为你们劳动成果的受益者，只有用或不用的选择，并没有质疑的权利，感谢你们无私的付出，仅仅只是想提醒一下：技术上的正确决定就一定是全局中的正确决定吗？

再次感谢，顺祝新年快乐！

**Comment by stevenjoezhang** [comment]
> 现在你们的维护开发思路很有点自以为是了。
> 你们在技术上的正确决定多多少少有点只顾自己爽的味道，事实上已经加大了使用者的使用成本。

我只是想提醒您：过去几个版本的 Roadmap 全部是由社区讨论而不断完善： https://github.com/theme-next/hexo-theme-next/issues/67
一些关键的改动都经过了投票表决： https://github.com/theme-next/hexo-theme-next/issues?q=is%3Aissue+label%3A%22%F0%9F%93%8A+Polls%22+is%3Aclosed
我们作出对于大部分人有益的决定，这些决定显然无法让所有人满意。您提到「今天启用尘封已久的旧博客」，而当我们在讨论这些问题时，您参与了吗？如果您更多地发表自己的意见，就不会产生大家「只顾自己爽」的错觉了。

> 把很多功能都从核心程序中移除，希望用插件来解决

许多 NexT 主题中「开箱即用」的功能，是其它 Hexo 主题从来都不具有的。即便移除部分功能，NexT 主题仍然拥有比其它任何 Hexo 主题多得多的功能。1000多行的配置文件已经足够说明问题。

移除部分旧功能的目的非常简单：它们带来的麻烦已经超过了价值。翻看 https://github.com/iissnan/hexo-theme-next 中的一些 Pull Request 就可以看出，许多功能都没有经过足够广泛的讨论，代码质量也没有保障。至少这一代的开发者为了修补以前的问题重构了不少代码。

> 很多地方都broken了

Hexo 本身的升级就会出现不向下兼容的情况，这会导致某些版本的 NexT 主题出现问题。

> 创造价值和增加负担之间，应有恰当的平衡。

在过去的两年中，`_config.yml` 中的配置项总体在增加。我们始终聆听社区的声音，新增了许多功能，并相应的对已有功能进行了精简（否则配置文件会继续膨胀，反而会「加大了使用者的使用成本」）。这个 Issue 讨论的`auto_excerpt`就是一例。这本来就是一个插件的工作，而不是主题应当负责的。遗憾的是，这变成了一个「升米恩，斗米仇」的悲剧。

总而言之，开源项目的初衷是集思广益使主题变得更加完善。可惜仍然有不少用户抱着「又要马儿跑，又要马儿不吃草」的想法。网上不知看了什么教程，胡乱操作一番，出了问题就跑到 NexT 主题的 Issue 下「求助」；大家在 GitHub、Telegram 上讨论问题时不见人影，等版本升级了、更新公告发了、功能改动了，发现自己的「博客」不好使了，就开个 Issue 大肆批判一番。维护开源项目是非常辛苦的工作，将时间浪费在争论这种事情上是非常可惜的。

新年快乐！

**Comment by xhj** [comment]
@stevenjoezhang 谢谢您的回复。「升米恩，斗米仇」是不存在的，评论时因为费了点力气去修复，带得有点情绪倒是真的，我并不清楚这些修改的前因后果，抱歉是我自己有点自以为是了，对不起！

我真正想表达的意思是，向下兼容实际上是需要非常多妥协和折衷的，见过太多的开发者倾向开发“完美”的代码，却不愿意作任何的妥协和折衷。这里实际上有两个非常关键问题需要慎重考虑：

1、重构是要有利于项目开发者的维护，还是要有利于使用者的方便？
2、重构是要有利于新用户还是要用利于老用户？

这两个问题如果不作恰当的平衡，开发者就很容易自嗨，无法做到与某一部分「升米恩，斗米仇」的用户共情。

再次向您道歉，真诚地感谢您无私的奉献与付出！

**Comment by stevenjoezhang** [comment]
不不不，您不需要道歉。我们的工作确实存在很多不足。这是需要每一个人共同思考的问题，可以使更多的用户受益。

> 1. 重构是要有利于项目开发者的维护，还是要有利于使用者的方便？
> 2. 重构是要有利于新用户还是要用利于老用户？

最初版本的 NexT 主题在2015年左右发布。在过去的数年间，CSS3和ES6等标准普及，与更多的主流浏览器兼容。许多重构都是出于这样的目的：比如，以前通过计算 Magic Number 来给某个菜单的组件定位，而现在借助于 flex 布局，可以使用更少的代码获得鲁棒性更好的结果。

再一个较大的改动是由于 swig 引擎失去维护，我们迁移到了 nunjucks。两者语法相似，但也略有不同。如果老用户用 swig 的语法自定义了部分内容，升级到新版就可能会出现问题。

其它的改进很大程度上来自于 Hexo 的变化。Hexo 4.0版本的一些 API 是不向下兼容的，这导致主题本身需要作出改变。我们的确作出了妥协和折衷——目前 NexT 主题同时支持新版和旧版的 Hexo。

总的来说，过去一段时间出现的数次重大改动都经过了慎重考虑、广泛讨论，并**明确地在更新说明中指出，且提供了完整的解决方案**：
#1217
https://github.com/theme-next/hexo-theme-next/releases
这对于一个开源项目来说，已经仁至义尽了。我们不是客服，没有义务手把手的教所有用户使用。可惜的是，即使我们已经提供了 Telegram / Gitter / Riot ，以及 GitHub Issue 这些沟通渠道，仍然无法与用户有效交换意见。**如何做到与某一部分用户共情？** 我回答不了。可能大家都太忙，没有时间看 Release Notes 罢。

感谢您的意见和建议！

**Comment by xhj** [comment]
@stevenjoezhang 听您这么一说，真的是我自己自以为是了。所有的误解都来自于信息掌握不全的情况下按照自己的思维方式自行脑补。妥协和折衷说起来轻松，做起来的确需要付出巨大的努力，感谢您的付出，感谢您的回复，再次谢谢您！

**Comment by 1v9** [comment]
建议此 issue 裱起来作为交流模范 😁
