### ISSUE TITLE
why you do it on commit 6c42709137d4203e43cc68dea7b609f977e07431

### ISSUE THREAD

**Issue by Githubwyb** [theme-next/hexo-theme-next#1338]
I have update my theme to v7.6.0, but find index page show all contents of every blog. I find a commit 6c42709137d4203e43cc68dea7b609f977e07431 on your repos, may I know why you remove the auto_excerpt config?

**Comment by stevenjoezhang** [comment]
Why not read this first? https://github.com/theme-next/hexo-theme-next/issues/1217
