### ISSUE TITLE
It is not okay indent the first line two spaces now！

### ISSUE THREAD

**Issue by syshlang** [theme-next/hexo-theme-next#1340]
It is okay to use symbols ‘&ensp’ to indent the first line two spaces before 7.6.0，But now it's ok only on the homepage！Is there something wrong with  the way I use？

**Comment by stevenjoezhang** [comment]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.

https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#quick-debug-instructions

**Comment by syshlang** [comment]
？

**Comment by syshlang** [comment]
what happened？

**Comment by jiangtj** [comment]
Look fine to me

![image](https://user-images.githubusercontent.com/15902347/71576435-a6c8ff80-2b2b-11ea-8dd3-e6e4c8fa44ef.png)

![image](https://user-images.githubusercontent.com/15902347/71576443-b0526780-2b2b-11ea-99b0-fc5e4f4de5c4.png)

So can you provide more information ?

**Comment by stevenjoezhang** [comment]
I believe you see the following in the Issue template:
> If you delete this template, we may close your issue without conducting an investigation.
> 如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

You deleted the Issue template so we will not waste time helping you.

**Comment by syshlang** [comment]
> 
> 
> Look fine to me
> 
> ![image](https://user-images.githubusercontent.com/15902347/71576435-a6c8ff80-2b2b-11ea-8dd3-e6e4c8fa44ef.png)
> 
> ![image](https://user-images.githubusercontent.com/15902347/71576443-b0526780-2b2b-11ea-99b0-fc5e4f4de5c4.png)
> 
> So can you provide more information ?

![TIM截图20191230185432](https://user-images.githubusercontent.com/8163995/71579109-0debb180-2b36-11ea-9cf2-868314c1b99c.png)
![TIM截图20191230185507](https://user-images.githubusercontent.com/8163995/71579110-0debb180-2b36-11ea-9cf9-24376ac0ef5d.png)


> 
> 
> Look fine to me
> 
> ![image](https://user-images.githubusercontent.com/15902347/71576435-a6c8ff80-2b2b-11ea-8dd3-e6e4c8fa44ef.png)
> 
> ![image](https://user-images.githubusercontent.com/15902347/71576443-b0526780-2b2b-11ea-99b0-fc5e4f4de5c4.png)
> 
> So can you provide more information ?

![20191230185432](https://user-images.githubusercontent.com/8163995/71579204-763a9300-2b36-11ea-9910-b704e011feaf.png)
![20191230185507](https://user-images.githubusercontent.com/8163995/71579205-76d32980-2b36-11ea-80ad-68db18f51126.png)

**Comment by syshlang** [comment]
> 
> 
> Look fine to me
> 
> ![image](https://user-images.githubusercontent.com/15902347/71576435-a6c8ff80-2b2b-11ea-8dd3-e6e4c8fa44ef.png)
> 
> ![image](https://user-images.githubusercontent.com/15902347/71576443-b0526780-2b2b-11ea-99b0-fc5e4f4de5c4.png)
> 
> So can you provide more information ?

 hexo: 4.2.0
 node：12.14.0
 npm：6.13.4
thank you！

**Comment by jiangtj** [comment]
Which markdown render and version you use?

**Comment by syshlang** [comment]
> Which markdown render and version you use?

Thank you very much for your attention and help, it has returned to normal after I updated the version of node！
