### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by syshlang** [theme-next/hexo-theme-next#1341]
Unhandled rejection TypeError: Cannot read property 'replace' of null，I found through debugging that it was caused by a symbol ‘<’，As follows：
```java
for ( int i=0; i<tuple.length; i++ ) {
    
}
```
If I remove the symbol, it returns to normal！
please help me，thanks！

**Comment by stevenjoezhang** [comment]
I believe you see the following in the Issue template:
> If you delete this template, we may close your issue without conducting an investigation.
> 如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

You deleted the Issue template so we will not waste time helping you.

**Comment by stevenjoezhang** [comment]
According to your description, this is a bug from Hexo.

Next time I hope you can respect other users and maintainers, fill in Issue according to the Issue template. Thank you.

**Comment by syshlang** [comment]
> 
> 
> According to your description, this is a bug from Hexo.
> 
> **Next time I hope you can respect other users and maintainers, fill in Issue according to the Issue template. Thank you.**

i`m sorry about that， I will I will correct my mistake next time，Thank you！

**Comment by stevenjoezhang** [comment]
You can try to upgrade Hexo and Hexo plugins to the latest version, or reinstall all node_modules. Hope this helps.

**Comment by syshlang** [comment]
> You can try to upgrade Hexo and Hexo plugins to the latest version, or reinstall all node_modules. Hope this helps.

UM...My problem has been solved by your method,Thank you for your help !
