### ISSUE TITLE
启用pjax导致无法正常加载公益404界面？

### ISSUE THREAD

**Issue by suyin-long** [theme-next/hexo-theme-next#1342]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
点击侧栏的公益404按钮显示对应的404界面

## Actual behavior 

点击侧栏的公益404按钮，不会正常显示对应的404界面，除非自己手动刷新页面。

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 将网站开启pjax功能
2.点击侧栏“公益404”按钮

### Node.js and NPM Information

```
v12.14.0
6.13.4
```

### Package dependencies Information

```
+-- hexo@4.2.0
+-- hexo-baidu-url-submit@0.0.6
+-- hexo-deployer-git@2.1.0
+-- hexo-enhancer@1.0.7
+-- hexo-filter-emoji@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.2.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.2.0
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-symbols-count-time@0.7.0
+-- live2d-widget-model-hijiki@1.0.5
`-- shelljs@0.8.3
```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml
pjax: true
```

**Comment by stevenjoezhang** [comment]
请手动为`script`标签加一个`pjax`属性。
