### ISSUE TITLE
Is the website（https://theme-next.org/） still working?

### ISSUE THREAD

**Issue by BigPotatoPeng** [theme-next/hexo-theme-next#1344]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***
I  can not access the website(https://theme-next.org/), so I wanna ask if it is still online?

**Comment by stevenjoezhang** [comment]
Nope.

**Comment by Ellean** [comment]
I got an answer from the admin of Telegram Group.

> Known issue

Waiting with patience.

**Comment by stevenjoezhang** [comment]
https://hexo-theme-next.netlify.com/
