### ISSUE TITLE
特性：支持多标签过滤

### ISSUE THREAD

**Issue by mzgcz** [theme-next/hexo-theme-next#1345]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
可以通过点选多个标签，过滤出同时包含点选标签的文章

## Actual behavior 

点选一个标签后，不能点选其他标签
- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

**Comment by jiangtj** [comment]
这个特性对于静态博客来说可能难以实现

**Comment by stevenjoezhang** [comment]
标签是由这个插件生成的： https://github.com/hexojs/hexo-generator-tag
请在这里开 Feature Request。Hexo 不提供 API，主题则无法实现此功能。

**Comment by mzgcz** [comment]
谢谢

> 
> 
> 标签是由这个插件生成的： https://github.com/hexojs/hexo-generator-tag
> 请在这里开 Feature Request。Hexo 不提供 API，主题则无法实现此功能。
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/6375567?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[hexojs/hexo-generator-tag](https://github.com/hexojs/hexo-generator-tag)**Tag generator plugin for Hexo. Contribute to hexojs/hexo-generator-tag development by creating an account on GitHub.
