### ISSUE TITLE
将主页 sidebar 中的 头像及社交图标 移动到那些 分类和标签 上面

### ISSUE THREAD

**Issue by HanleyLee** [theme-next/hexo-theme-next#1347]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ x ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ x ] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [ x ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
我想将我主页 sidebar 中的 **头像及社交图标** 移动到那些 **分类和标签** 上面

## Actual behavior 

我自己尝试了很久, 网上的信息我基本都搜完了没找到想要的结果, 然后我把 NexT 主题中的所有文件都打开看了一遍, 我似懂非懂, 因为不是从事前端, 所以那些语法我找不出哪些是作为 **页面排序布局** 的

我非常希望有人能指点我一下, 我确实很希望能将我的头像挪至上方.

非常感谢!

**Comment by stevenjoezhang** [comment]
修改这个文件： https://github.com/theme-next/hexo-theme-next/blob/master/layout/_partials/sidebar/site-overview.swig
可以任意改变 sidebar 中元素的顺序

**Comment by HanleyLee** [comment]
首先, 非常感谢你的回复, 我按照你的指点仔细查看了 [https://github.com/theme-next/hexo-theme-next/blob/master/layout/_partials/sidebar/site-overview.swig](https://github.com/theme-next/hexo-theme-next/blob/master/layout/_partials/sidebar/site-overview.swig) 这个文件, 我最终发现这个文件只是对于个人简介区域起到了排序布局的作用. 如下: ↓

![himg](https://hanleylee.oss-cn-shanghai.aliyuncs.com/HKMS/2020-01-09-062909.png) 

但是我想要的效果是将整个 **个人简介区域** 放置到菜单区域之上, 如下: ↓

![himg](https://hanleylee.oss-cn-shanghai.aliyuncs.com/HKMS/2020-01-09-063941.png)

除了这个文件, 我又看了其他的文件, 最后找到了[https://github.com/theme-next/hexo-theme-next/blob/master/source/js/schemes/pisces.js](https://github.com/theme-next/hexo-theme-next/blob/master/source/js/schemes/pisces.js)这个文件, 好像最终答案就在这里面, 但是我按照我的思路进行的修改全部都导致显示不正确

请问能进一步地指导我解决这个问题吗?

**Comment by stevenjoezhang** [comment]
抱歉，我之前理解有误。

虽然看上去交换这两个区域并不复杂，但它们涉及到大量的脚本和样式，不是把几行代码换位置就能解决的。特别是，还要考虑到手机浏览时，页面的布局会发生变化，这也会导致问题。

**Comment by HanleyLee** [comment]
好的, 我也意识到了完成这个简单目标需要大量修改, 既然这样我就先暂时用着这样的样式吧, 以后理解深入了再进行尝试. 

谢谢你的回复!
