### ISSUE TITLE
where is 'scroll_to_more: false' ?

### ISSUE THREAD

**Issue by iceice** [theme-next/hexo-theme-next#1352]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
It has been removed. That's all.

**Comment by iceice** [comment]
How can I disable automatically scroll page to section which is under  mark？
Thanks

**Comment by stevenjoezhang** [comment]
You can modify the source code:

https://github.com/theme-next/hexo-theme-next/blob/7bf7e06422f602bc8e1355086bf78e41d9964d1f/layout/_macro/post.swig#L198

Of course, I personally don't recommend you do this. Scrolling to `read more` is the default behavior for any Hexo theme, this is why we removed this option.
