### ISSUE TITLE
Tag Plugin is not rendering properly

### ISSUE THREAD

**Issue by hujinbo** [theme-next/hexo-theme-next#1353]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
When I used the video tag and other tags in the same markdown file, only the video tag rendered successfully and the other tags cannot be rendered. But if you remove the video tag, it will render properly.

## Actual behavior 

- Links to demo site with this issue: 
- Links to repository or source code of the blog: 

## Steps to reproduce the behavior 
1. add post `tagPluginTest.md`
```
---
title: 标签测试
---

## 居中引用

    {% cq %}你所做的事情，也许暂时看不到成功，但不要灰心，你不是没有成长，而是在扎根。{% endcq %}


显示效果如下所示：  

{% cq %}你所做的事情，也许暂时看不到成功，但不要灰心，你不是没有成长，而是在扎根。{% endcq %}


## 插入视频

    {% video https://cdn.hujinbo.me/video/demo.mp4 %}

显示效果如下所示：

{% video https://cdn.hujinbo.me/video/demo.mp4 %}

```
2. run `hexo server`
3. open http://localhost:4000

### Node.js and NPM Information

```
v10.16.0
6.9.0
```

### Package dependencies Information

```
+-- hexo@4.2.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0
```

### Hexo Configuration

```yml
theme: next
```

### NexT Configuration

```yml
no change
```

## Other Information 
![1](https://user-images.githubusercontent.com/29507557/72537031-576a2980-38b6-11ea-939a-398ef1e04124.png)
![2](https://user-images.githubusercontent.com/29507557/72537048-5df8a100-38b6-11ea-8ed8-eb0ad8b7a57c.png)

**Comment by stevenjoezhang** [comment]
Can't reproduce.

<img width="1027" alt="截屏2020-01-16下午11 27 09" src="https://user-images.githubusercontent.com/16272760/72537798-baa88b80-38b7-11ea-941e-0d0b48c5d580.png">

You can try to upgrade theme NexT to the latest version.

**Comment by hujinbo** [comment]
> 无法复制。
> 
> <img alt="截屏2020-01-16下午11 27 09" width="1027" src="https://user-images.githubusercontent.com/16272760/72537798-baa88b80-38b7-11ea-941e-0d0b48c5d580.png">
> 
> 您可以尝试将主题NexT升级到最新版本。



I have upgraded to the latest version, you can clone the source code of this blog  for reproduction: https://github.com/hujinbo/hexo-next-test
![3](https://user-images.githubusercontent.com/29507557/72625369-a5009800-3983-11ea-9802-99a3260b48d9.png)

**Comment by hujinbo** [comment]
> Can't reproduce.
> 
> <img alt="截屏2020-01-16下午11 27 09" width="1027" src="https://user-images.githubusercontent.com/16272760/72537798-baa88b80-38b7-11ea-941e-0d0b48c5d580.png">
> 
> You can try to upgrade theme NexT to the latest version.


I have upgraded to the latest version, you can clone the source code of this blog  for reproduction: https://github.com/hujinbo/hexo-next-test
![3](https://user-images.githubusercontent.com/29507557/72625870-923a9300-3984-11ea-9c74-3238108d8f6f.png)

**Comment by stevenjoezhang** [comment]
Use backtick code blocks:

<img width="709" alt="截屏2020-01-18上午8 28 39" src="https://user-images.githubusercontent.com/16272760/72654884-88d51900-39cc-11ea-9caa-f4aa95819753.png">

It's a bug of Hexo, please report it here: https://github.com/hexojs/hexo/issues
