### ISSUE TITLE
next7.6版本代码高亮问题

### ISSUE THREAD

**Issue by Jackwew** [theme-next/hexo-theme-next#1355]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

## Other Information 

我有一个问题，我在项目的配置文件中设置了代码高亮，部分代码如下：
```bash
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

highlight:
  enable: true
  hljs: true
  line_number: true
  auto_detect: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

```
在next主题的配置文件中是这样设置的，部分代码如下： 
```bash

codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  # See: https://github.com/chriskempson/tomorrow-theme
  highlight_theme: normal
  # 设置是否开启代码块复制按钮
  copy_button:
    enable: true
    # 是否显示复制成功信息
    show_result: true
    # Available values: default | flat | mac
    style: mac
```
但是我blog上的代码块并没有出现高亮的语法，你们能帮我看看我哪儿设置有错，还是需要另外引入其他的cdn文件，谢谢！

**Comment by stevenjoezhang** [comment]
请提供：博客页面的Markdown源码，以及博客的网站链接

**Comment by Jackwew** [comment]
博客地址：http://47.106.122.45:8081/
markdown源码：
```js
/* 替换历史记录 */
history.replaceState(state, title, URL);
/* 新增历史记录 */
history.pushState(state, title, URL);
```

**Comment by stevenjoezhang** [comment]
可以执行一下 `hexo clean` 试试。
看上去你对于主题的自定义样式太多了，我们有理由怀疑是自定义的过程导致了问题。你可以尝试在全新安装的 NexT 主题上复现这个 bug。

**Comment by Jackwew** [comment]
好的，我试试新的next主题。谢谢！
我还有一个问题是项目报错找不到prettify.js这个文件，定位到报错文件是_layout.swig这个文件。文件部分代码如下： 
```js
{%- if theme.pjax %}
    <div id="pjax">
  {%- endif %}
  {% include '_third-party/math/index.swig' %}
  {% include '_third-party/quicklink.swig' %}

  {{- next_inject('bodyEnd') }}
  {%- if theme.pjax %}
    </div>
  {%- endif %}
  <script type="text/javascript" src="/js/ /prettify.js"></script>
  <script type="text/javascript">
  window.load = function(){
    document.querySelector('pre').addClass('prettyprint linenums').attr('style', 'overflow:auto;');
    prettyPrint();
  }
  </script>
```
浏览器控制台提示找不到```js<script type="text/javascript" src="/js/ /prettify.js"></script>```。
谢谢！

**Comment by stevenjoezhang** [comment]
我不知道这是哪来的，因为 NexT 主题早已经把所有 `"text/javascript"` 删除了，这在 HTML5 中是不必要的。建议删除所有自定义的内容，由于你自定义而导致的问题我们无法解答。

**Comment by Jackwew** [comment]
好吧，谢谢！

**Comment by stevenjoezhang** [comment]
不客气。看上去`/js/ /prettify.js`是一个错误的路径，你可以检查在博客目录下是否存在`/js/prettify.js`文件，并进行修改。

**Comment by Jackwew** [comment]
谢谢，我找到原因了是我以前使用了谷歌的代码高亮风格js文件导致的。next 7版本过后使用来隐藏文章阅读全文跳转后滚动条不是在顶部的位置，总是距离顶部有一定的距离，这个能更改一下吗？很多人的阅读习惯还是喜欢从底部开始阅读。我找了很久没有找到如何更改这个。

**Comment by stevenjoezhang** [comment]
事实上，任何 Hexo 主题的默认行为都是跳转到「Read More」的位置；其它的主流博客框架，例如 WordPress 也是如此。这是符合逻辑的设计，即使它与部分用户的阅读习惯冲突，我们也暂时不考虑进行更改。

**Comment by Jackwew** [comment]
方便指导一下怎么修改这个功能吗？如果不方便也没关系的。还是谢谢你为我解答这么多问题，最后祝新年快乐！

**Comment by stevenjoezhang** [comment]
找到并修改这一行代码：

https://github.com/theme-next/hexo-theme-next/blob/7bf7e06422f602bc8e1355086bf78e41d9964d1f/layout/_macro/post.swig#L198

**Comment by stevenjoezhang** [comment]
新年快乐！

这个 Issue 先关了，有其他问题欢迎提出。

**Comment by Jackwew** [comment]
新年快乐
