### ISSUE TITLE
Posts containing embedded gist causes the sidebar to appear over the post

### ISSUE THREAD

**Issue by hmemcpy** [theme-next/hexo-theme-next#1356]
- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***
A post containing an embedded gist causes the sidebar to appear on top of the post during scrolling:
![Jan-23-2020 12-56-13](https://user-images.githubusercontent.com/601206/72979129-51a5a400-3de0-11ea-8190-38a0f8bb8a12.gif)

Using Next Gemini theme v7.7.0.

## Expected behavior 
Sidebar appearing on the left side.

## Actual behavior 

Sidebar appears on top of the post (see image)

- Links to demo site with this issue: https://hmemcpy.com/2011/04/modifying-windows-live-writer-blog-content-in-publishnotificationhook-plugins-onprepublish/
- Links to repository or source code of the blog: https://github.com/hmemcpy/hmemcpy.com

## Steps to reproduce the behavior 
1. Create a post with the following content: https://gist.github.com/hmemcpy/37b2a524318640d062a443cef479f8bc
2. run `hexo serve`, load the post, then scroll down

### Node.js and NPM Information

```
v12.6.0
6.13.6
```

### Package dependencies Information

```
hexo-site@0.0.0
├── hexo@4.2.0
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0
```

**Comment by hmemcpy** [comment]
Ok, I updated to the lastest `master` (8aa5b29b03bdbdf69bab1eb8cf5ba73ce740dc8d), and the problem seems to have been resolved!

**Comment by stevenjoezhang** [comment]
Yes, we have recently made changes to some related CSS code, so the browser cache needs to be cleared to ensure that no errors occur

**Comment by hmemcpy** [comment]
Yep, I can confirm it works now! Thank you very much for the wonderful theme!

**Comment by stevenjoezhang** [comment]
You're welcome!
In addition, we are sorry that the bot is not working properly, we will check its configuration.
