### ISSUE TITLE
Font Awesome icon doesn't load

### ISSUE THREAD

**Issue by yifan121461** [theme-next/hexo-theme-next#1375]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [ x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
加载一个叫laptop-code的fontawesome图标

## Actual behavior 
在菜单栏里的project左边应该有一个图标，但是没加载出来

- yifan121461.github.io 

## Steps to reproduce the behavior 

menu:
  Home: / || home
  #about: /about/ || user
  Tags: /tags/ || tags
  #categories: /categories/ || th
  Archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
  Resume: /Resume/ || file
  Project: /project/ || laptop-code  

### Node.js and NPM Information

```v12.14.1   


```6.13.4

### Package dependencies Information
<!-- Paste output from `npm ls --depth 0` (粘贴 `npm ls --depth 0` 输出的信息) -->
```├── hexo@4.2.0
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0 

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
目前用的是 Font Awesome 4.7.0，所以没有这个图标。我们会考虑更新 Font Awesome 版本，或使用其它的图标加载方式。

**Comment by stevenjoezhang** [comment]
建议暂时用一个 4.7.0 版本的图标代替。关于 Font Awesome 的讨论请移步这里： https://github.com/theme-next/hexo-theme-next/issues/505

**Comment by stevenjoezhang** [comment]
我们将在近期迁移至 Font Awesome 5，届时将支持「laptop-code」图标，请注意升级： https://github.com/theme-next/hexo-theme-next/pull/1438
谢谢关注。
