### ISSUE TITLE
首页文章增多，头像会出现悬浮bug，头像会脱离原先位置悬浮到文章内容上。

### ISSUE THREAD

**Issue by zjj1019** [theme-next/hexo-theme-next#1376]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
<img width="1319" alt="截屏2020-02-09下午8 57 51" src="https://user-images.githubusercontent.com/16272760/74102495-d897a200-4b7e-11ea-8c9c-e360b3ccd9da.png">

如果你指的是这个： https://zjj1019.github.io/ 
看上去没有任何问题。请提供你的操作系统版本，浏览器版本和屏幕截图。

**Comment by zjj1019** [comment]
> <img alt="截屏2020-02-09下午8 57 51" width="1319" src="https://user-images.githubusercontent.com/16272760/74102495-d897a200-4b7e-11ea-8c9c-e360b3ccd9da.png">
> 
> 如果你指的是这个： https://zjj1019.github.io/
> 看上去没有任何问题。请提供你的操作系统版本，浏览器版本和屏幕截图。
> 
> > <img alt="" height="14" src="/images/favicon-16x16-next.png"> GraceJunk**[GraceJunk](http://zjj1019.coding.me/index.html)**狮子从来不必在意绵羊的看法

哈哈 那是我刚刚减少了文章数在测试的页面 现在我增加到16个 您再去看看头像会出现悬浮 操作系统: win10  浏览器: chrome 版本 78.0.3904.108   麻烦了

**Comment by stevenjoezhang** [comment]
问题是这样的：你的其中一篇文章，内容包含一些 html 元素（可能是示例代码）。它们没有被转义，导致浏览器将这些代码解析了，造成 html 标签不闭合，sidebar 出现在了一篇文章里，因此位置不正确。首页文章数量较少时，出错的文章在第二页，所以首页看上去没有问题。

<img width="1904" alt="截屏2020-02-09下午9 28 57" src="https://user-images.githubusercontent.com/16272760/74102981-3af2a180-4b83-11ea-80d8-f0c853cf4b95.png">


<img width="691" alt="截屏2020-02-09下午9 26 44" src="https://user-images.githubusercontent.com/16272760/74102929-e3eccc80-4b82-11ea-9978-4cf05f2581f4.png">
