### ISSUE TITLE
valine not shown on some browsers

### ISSUE THREAD

**Issue by Wegome** [theme-next/hexo-theme-next#138]
hi, just found that valine comment do not show on some browsers, while it shows on firefox, chrome.

pc: ie.
android mobile: via and x browser

![2018_02_13_11 03 54](https://user-images.githubusercontent.com/6015834/36132308-6b101ac8-10b1-11e8-864b-84f47d6c954d.jpg)

does anybody find the same problem?

my blog [布袋小知诺](https://www.zhinuo.site)

**Comment by tsanie** [comment]
emmm, there is an arrow function in the file [valine.swig#L8](https://github.com/theme-next/hexo-theme-next/blob/master/layout/_third-party/comments/valine.swig#L8), that couldn't be supported by the IE.

That should be replaced by `.filter(function (item) { return GUEST.indexOf(item) > -1; });`

**Comment by Wegome** [comment]
@tsanie thanks very much, it worked.

**Comment by LEAFERx** [comment]
Problem solved #139 . Close Issue.
