### ISSUE TITLE
the left and right margins of the description that shown on the homepage are zero

### ISSUE THREAD

**Issue by asdf2014** [theme-next/hexo-theme-next#1382]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 

The left and right margins of the description that shown on the homepage should be non-zero

## Actual behavior 

the left and right margins of the description that shown on the homepage are zero

![image](https://user-images.githubusercontent.com/8108788/74748603-c1099900-52a3-11ea-9c09-81ef28bdb337.png)

- Links to demo site with this issue: https://yuzhouwan.com/
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. Open https://yuzhouwan.com/ on iPhone

### Node.js and NPM Information

```
v12.14.0
6.13.7
```

### Package dependencies Information

```
├── @babel/core@7.8.4
├── babel-core@6.26.3
├── babel-preset-env@1.7.0
├── browser-sync@2.26.7
├── gulp@4.0.2
├── gulp-htmlclean@2.7.22
├── gulp-htmlmin@5.0.1
├── gulp-imagemin@7.1.0
├── gulp-install@1.1.0
├── gulp-minify-css@1.2.4
├── gulp-uglify@3.0.2
├── hexo@4.2.0
├── hexo-abbrlink@2.0.5
├── hexo-autonofollow@1.0.1
├── hexo-deployer-git@2.1.0
├── hexo-filter-flowchart@1.0.4
├── hexo-filter-github-emojis@2.1.0
├── hexo-filter-mermaid-diagrams@1.0.5
├── hexo-fs@2.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-searchdb@1.2.0
├── hexo-generator-sitemap@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-inject@1.0.0
├── hexo-related-popular-posts@4.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-kramed@0.1.4
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
├── hexo-symbols-count-time@0.7.0
├── hexo-tag-mermaid@1.0.0
├── hexo-util@1.8.1
├── mermaid@8.4.7
├── natives@1.1.6
└── phantomjs@2.1.7
```

### Hexo Configuration

N/A

### NexT Configuration

N/A

## Other Information 
N/A

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/hexo-theme-next/commit/e69a4ecb785524db7eb15c02bde1c104618b96ae

**Comment by asdf2014** [comment]
@stevenjoezhang Thank you so much! :+1:
