### ISSUE TITLE
Integrate web push notification

### ISSUE THREAD

**Issue by glazec** [theme-next/hexo-theme-next#1388]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

Can I try to integrate web push notification serveice into NEXT? Then readers can receive notificaiton of latest post.

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo-generator-feed

**Comment by glazec** [comment]
Sorry, I do not mean the rss feed. I mean the web push notification https://developers.google.com/web/fundamentals/push-notifications.

**Comment by stevenjoezhang** [comment]
I read your article https://github.com/glazec/glazec.github.io/blob/master/posts/98ae9e55/index.html
Enabling web push notification is a great idea, and I believe this feature will be welcomed by bloggers.
Since it only requires javascript, and does not depend on HTML and CSS, it is more suitable to be made into a Hexo plugin than be integrated in a certain theme e.g. NexT.
If you are interested, you can implement this plugin and open a Pull Request here: https://github.com/hexojs/site . All Hexo users, not just users of the theme NexT, can benefit from this plugin. Thank you!

**Comment by glazec** [comment]
Do you mean inject the necessary <script>to enable the web push notification</script> code to the rendered HTML using https://github.com/hexojs/hexo-inject?

**Comment by stevenjoezhang** [comment]
There is an easier way: replace `</head>` with `<script>//Some thing...</script></head>` using regular expression:

https://github.com/hexojs/hexo/blob/a97bd2f11e67ca2ffb6186b5d61521fcb58f4a1a/lib/plugins/filter/after_render/meta_generator.js#L10

```js
hexo.extend.filter.register('after_render:html', data => {
  return data.replace(/<head>(?!<\/head>).+?<\/head>/s, str => str.replace('</head>', `<script>//Some thing...</script></head>`));
});
```

**Comment by glazec** [comment]
Thanks for your suggestions. I am working on it.

**Comment by glazec** [comment]
@stevenjoezhang I just wonder your Regex. Why do we need to match both <body> and </body>? Can we just match </body>?

**Comment by glazec** [comment]
I think I made it https://github.com/glazec/hexo-web-push-notification.
