### ISSUE TITLE
gitalk doesn`t work | gitalk用不了了

### ISSUE THREAD

**Issue by alienyan** [theme-next/hexo-theme-next#1390]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
在gitalk那里点登陆后应该跳转到授权页面然后回到文章页面

## Actual behavior 

当我点击登陆后没跳转到github的授权页面，直接跳转到我的首页。
控制台提示：GET https://api.github.com/user 401 (Unauthorized)    xhr.js:178 

- Links to demo site with this issue: https://qghost.gitee.io/blog/
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 打开第一篇文章
2. 拉到最下面点击 “使用GitHubH登陆”

### Node.js and NPM Information

```
v12.16.0
6.13.4
```

### Package dependencies Information

```
+-- hexo@4.1.1
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0

```

### Hexo Configuration

N/A

### NexT Configuration

N/A

## Other Information 
N/A

**Comment by Jackwew** [comment]
因为你没有创建初始的issue，你要自己每篇文章都创建一个issue，反正比较麻烦。推荐使用valine评论系统。博客地址： http://47.106.122.45/

**Comment by alienyan** [comment]
> 因为你没有创建初始的issue，你要自己每篇文章都创建一个issue，反正比较麻烦。推荐使用valine评论系统。博客地址： http://47.106.122.45/

其实问题不是出在这里，问题在于不能进行登陆，好像前几周开始一直github一直给我发邮件说不能再使用OAuth登录了，要用那个Basic Authentication来代替，然后就近这几天好像就用不了了，如果真的没办法解决那就换一个吧。

**Comment by Jackwew** [comment]
目前我bolg上是可以使用的
> http://47.106.122.45/2020/01/17/email/

**Comment by stevenjoezhang** [comment]
如果设置了Gitalk的CDN，请删除以使用默认的最新版本。

**Comment by alienyan** [comment]
> > 因为你没有创建初始的issue，你要自己每篇文章都创建一个issue，反正比较麻烦。推荐使用valine评论系统。博客地址： http://47.106.122.45/
> 
> 其实问题不是出在这里，问题在于不能进行登陆，好像前几周开始一直github一直给我发邮件说不能再使用OAuth登录了，要用那个Basic Authentication来代替，然后就近这几天好像就用不了了，如果真的没办法解决那就换一个吧。
> 
> > <img alt="" height="14" src="/images/favicon-16x16-next.png"> 爱生活，爱代码**[爱生活，爱代码](http://47.106.122.45:8081/index.html)**

你的我试了几次有一次是跟我的一样，有一次登录成功了，其他都是Error: Network Error
![TIM截图20200226134027](https://user-images.githubusercontent.com/13297495/75336402-0d696000-58c6-11ea-9cfd-0e0774d6a41e.png)
可能是我的网络问题吧

**Comment by alienyan** [comment]
> 如果设置了Gitalk的CDN，请删除以使用默认的最新版本。

可能是我的网络有问题吧

**Comment by alienyan** [comment]
> 如果设置了Gitalk的CDN，请删除以使用默认的最新版本。

没设置过CDN，可能是我的网络问题

**Comment by stevenjoezhang** [comment]
嗯，你用的 Gitalk 确实是最新版。只是有部分文章的评论没有初始化
https://github.com/alienyan/blog-talk/issues

**Comment by alienyan** [comment]
> 嗯，你用的 Gitalk 确实是最新版。只是有部分文章的评论没有初始化
> https://github.com/alienyan/blog-talk/issues
> 
> > <img alt="" width="48" src="https://avatars2.githubusercontent.com/u/13297495?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[alienyan/blog-talk](https://github.com/alienyan/blog-talk)**Contribute to alienyan/blog-talk development by creating an account on GitHub.

https://qghost.gitee.io/blog/%E5%B9%B2%E8%B4%A7/music-download/
这篇文章是有初始化的，请问能否试一下看看能不能登录

**Comment by stevenjoezhang** [comment]
嗯，复现出了你说的bug，跳转到首页。你可以在这里开个Issue看看能否得到解答： https://github.com/gitalk/gitalk/issues

**Comment by alienyan** [comment]
> 嗯，复现出了你说的bug，跳转到首页。你可以在这里开个Issue看看能否得到解答： https://github.com/gitalk/gitalk/issues
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/29697133?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[gitalk/gitalk](https://github.com/gitalk/gitalk)**Gitalk is a modern comment component based on Github Issue and Preact. - gitalk/gitalk

已经开了，不过貌似没人回

**Comment by stevenjoezhang** [comment]
最近Gitalk改动挺频繁的，因为GitHub的策略也在不断更新。我自己用的是Valine，所以无法提供帮助。看看Gitalk的维护者能否尽快处理这个问题吧

**Comment by alienyan** [comment]
> 最近Gitalk改动挺频繁的，因为GitHub的策略也在不断更新。我自己用的是Valine，所以无法提供帮助。看看Gitalk的维护者能否尽快处理这个问题吧

好的，谢谢大佬

**Comment by Jackwew** [comment]
国内用户还是使用Valine好得多

**Comment by stevenjoezhang** [comment]
看上去问题和主题无关，这个 Issue 先关了。
可以在这里继续讨论： https://github.com/gitalk/gitalk/issues/359
