### ISSUE TITLE
无法正确安装百度统计

### ISSUE THREAD

**Issue by chaoren2357** [theme-next/hexo-theme-next#1392]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 

百度统计官方代码安装检查通过
## Actual behavior 

百度统计官方代码安装检查显示代码未生效

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 百度统计注册账号
2. 复制教程中指示的your_id
3. 在next/_config.yml的baidu_analytics后面添加了your_id, 且已经注意冒号后面空一格

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

## Other Information 
部署过程显示正常，但是百度统计处得不到信息

**Comment by stevenjoezhang** [comment]
仅凭「部署过程显示正常，但是百度统计处得不到信息」无法证明这是 bug。请提供更多信息，例如模版中的

Links to demo site with this issue: N/A
Links to repository or source code of the blog: N/A
