### ISSUE TITLE
External links on the website doesn't work as expected

### ISSUE THREAD

**Issue by maple3142** [theme-next/hexo-theme-next#1393]
# Issue Checklist

When I try to middle click any external link on the website, it won't open in newtab like regular link, which is really bad for UX.
What's more, it opens a **window** instead of newtab when I left click on it.
Video: https://streamable.com/w5lwa

**Comment by stevenjoezhang** [comment]
Related Issues:
https://github.com/theme-next/hexo-theme-next/issues/589
https://github.com/iissnan/hexo-theme-next/pull/1438

**Comment by stevenjoezhang** [comment]
@theme-next/next How do you like this?

```diff
   registerExtURL: function() {
     document.querySelectorAll('.exturl').forEach(element => {
-      element.addEventListener('click', event => {
-        var exturl = event.currentTarget.dataset.url;
-        var decurl = decodeURIComponent(escape(window.atob(exturl)));
-        window.open(decurl, '_blank', 'noopener');
-        return false;
-      });
+      let link = document.createElement('a');
+      let exturl = element.dataset.url;
+      link.href = decodeURIComponent(escape(window.atob(exturl)));
+      link.rel = "noopener";
+      link.target = "_blank";
+      link.innerHTML = element.innerHTML;
+      element.parentNode.replaceChild(link, element);
     });
   },
```

**Comment by stevenjoezhang** [comment]
Or how about creating a External link warning / redirect page?

Like this one: https://hackerone.com/redirect?signature=29d3c9436788e01c4f620505cc5b7a641b1f3259&url=https%3A%2F%2Fgithub.com%2Flodash%2Flodash%2Fcommit%2F90e6199a161b6445b01454517b40ef65ebecd2ad
