### ISSUE TITLE
当前版本baidu、google等站点标签检验处代码错误

### ISSUE THREAD

**Issue by BestReder** [theme-next/hexo-theme-next#1405]
文件`./layout/_partials/head/head.swig`
比如添加google-site-verification的代码为：
```<meta name="google-site-verification" content="{{ theme.google_site_verification }}">```
请注意，在google官方给出的检验代码为：```<meta name="google-site-verification" content="{{ theme.google_site_verification }}" />```
这里就可以发现next的代码少了一个`/`

**Comment by stevenjoezhang** [comment]
少一个 `/` 不影响。

**Comment by BestReder** [comment]
亲身体验，如果不修改，站点检验失败，以google为例


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mimi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 中午11:36
收件人： &nbsp;“ theme-next / hexo-theme-next” <hexo-theme-next@noreply.github.com&gt;;
抄送： &nbsp;“ 重做 ” <997594560@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题:&nbsp;Re: [theme-next/hexo-theme-next] 当前版本baidu、google等站点标签检验处代码错误 (#1405)




少一个 / 不影响。
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by sli1989** [comment]
大佬考虑检查下，google统计在12月更新中失效。

**Comment by stevenjoezhang** [comment]
我用的 google_site_verification 没有失效。如果 google 无法识别 HTML 语法，只认 XHTML，就需要考虑别的验证方式了。

google 统计与这个 google_site_verification 不同，我想你说的是这个 PR https://github.com/theme-next/hexo-theme-next/pull/1283/files
如果域名设置不正确，则 google 统计不会生效。此举是为了过滤来自 localhost 的流量。

我个人没有兴趣研究这个问题。祝好运。

**Comment by stevenjoezhang** [comment]
@sli1989 确认了。在配置文件中设置的域名是 sli1989.github.io 因此通过 http://saili.science 访问自然不会记入 google 统计。和这个 Issue 无关  😢

<img width="1039" alt="截屏2020-03-11下午3 51 43" src="https://user-images.githubusercontent.com/16272760/76394308-3d2d6300-63b0-11ea-8eba-944cdedb186f.png">

**Comment by sli1989** [comment]
> @sli1989 确认了。在配置文件中设置的域名是 sli1989.github.io 因此通过 http://saili.science 访问自然不会记入 google 统计。和这个 Issue 无关 😢
> 
> <img alt="截屏2020-03-11下午3 51 43" width="1039" src="https://user-images.githubusercontent.com/16272760/76394308-3d2d6300-63b0-11ea-8eba-944cdedb186f.png">

嗯。。好吧，以前也是这样，但可以统计。
谢啦

**Comment by stevenjoezhang** [comment]
嗯，印象中当时有很多关于统计不准确的 Issue，即使屏蔽了 localhost，还是有用户抱怨 127.0.0.1:4000 没有被屏蔽。所以就一刀切了，与设置的域名不相同的流量全部无效。
