### ISSUE TITLE
站点标签检验处代码问题

### ISSUE THREAD

**Issue by BestReder** [theme-next/hexo-theme-next#1406]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

## Other Information 

# 其上模板用不习惯，反映问题如下：
文件：`./layout/_partials/head/head.swig`
比如添加google站点标签检查时代码为：
```<meta name="google-site-verification" content="{{ theme.google_site_verification }}">```
而google官方给出的代码为：
```<meta name="google-site-verification" content="{{ theme.google_site_verification }}" />```
可以发现next主题少了一个`/`

**Comment by stevenjoezhang** [comment]
已经在 #1405 回复你了，这个 `/` 不影响。谢谢反馈。
