### ISSUE TITLE
site-nav不显示

### ISSUE THREAD

**Issue by maplesugarr** [theme-next/hexo-theme-next#1408]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
在屏幕宽度够的情况下，site-nav总是显示。

## Actual behavior 

在屏幕宽度够的情况下，site-nav不总是显示。

## Steps to reproduce the behavior 
1. 打开chrome开发者选项，调整网站宽度，观察响应布局。
2. 小于991px的时候，通过左面的toggle按钮，把site-nav打开，再关闭。
3. 调整网站宽度，大于991px的时候，site-nav不再显示。
4. 考虑到用户不是这么皮，我也不知道算不算bug。但是有的next主题用户已经自己修复了。

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
> 但是有的next主题用户已经自己修复了。

请提供链接证明您的观点，谢谢！

**Comment by stevenjoezhang** [comment]
似乎这个问题只在启用 `motion` 时会出现。由于 Velocity.js 停止维护，我们会在未来重构有关代码，因此不用担心。

**Comment by maplesugarr** [comment]
我用的7.4版本，就有这个问题。今天想升级版本，发现这个问题还在。我想自定义css就能解决，但是我懒得做。期待你们的更新，谢谢。

**Comment by maplesugarr** [comment]
补充：出现问题的是scheme: Gemini，这种两栏布局。
