### ISSUE TITLE
关于NexT7.7.2缺少busuanzi-counter.swig文件

### ISSUE THREAD

**Issue by 01Lv** [theme-next/hexo-theme-next#1417]
请教下，为啥在版本为7.7.2的路径\themes\next\layout\_third-party\analytics下找不到busuanzi-counter.swig文件？
求解答，谢谢！

**Comment by sli1989** [comment]
remember open the issue following the issue template, unless be cosed automatically.
[busuanzi-counter.swig](https://github.com/theme-next/hexo-theme-next/tree/master/layout/_third-party/statistics) is exsited.
so can you elaborate your problem in detail.
