### ISSUE TITLE
If chinese, english and mathjax all in a section,  some whitespace will appear 

### ISSUE THREAD

**Issue by chena1982** [theme-next/hexo-theme-next#142]
hexo 3.5.0
next 6.0.4
pandoc 2.1.1

![test](https://user-images.githubusercontent.com/5953033/36352328-35ebeecc-14f2-11e8-8168-10cf93f535ca.png)

Does i setup something wrong?
Thanks.

**Comment by wafer-li** [comment]
https://github.com/theme-next/hexo-theme-next/issues/24#issuecomment-357003155

This might help you.

**Comment by chena1982** [comment]
It works, Thanks.

**Comment by wafer-li** [comment]
duplicated with #24
