### ISSUE TITLE
app-router.leancloud.cn is deprecated

### ISSUE THREAD

**Issue by zhangnew** [theme-next/hexo-theme-next#1421]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

Add a optional parameter to set customize domain for leancloud analytics.
[hexo-leancloud-counter-security](https://github.com/theme-next/hexo-leancloud-counter-security) is support to set `server_url`, this can reduce one network request.

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: https://github.com/theme-next/hexo-theme-next/blob/5c7926718e72c64535c8e391804ff7d213b14fb3/layout/_third-party/statistics/lean-analytics.swig#L72

lean-analytics.swig use `app-router.leancloud.cn` to fetch api server, but [this api is deprecated](https://forum.leancloud.cn/t/app-router-leancloud-cn/22429).

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

**Comment by stevenjoezhang** [comment]
Confirmed https://github.com/leancloud/javascript-sdk/blob/master/changelog.md#400-2019-10-31

**Comment by stevenjoezhang** [comment]
Can you help test this pull request #1426 ? Thank you!

**Comment by zhangnew** [comment]
@stevenjoezhang Thank you! this pr is test passed, LGTM.
