### ISSUE TITLE
设置 codeblock 的 highlight_theme 的时候多添加一个暗黑模式的选项。

### ISSUE THREAD

**Issue by AemonCao** [theme-next/hexo-theme-next#1422]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
设置 `codeblock` 的 `highlight_theme` 的时候多添加一个暗黑模式的选项。
两个模式可以分别设置 `highlight_theme`。

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

**Comment by stevenjoezhang** [comment]
已经有一个和你的请求完全相同的 Issue： https://github.com/theme-next/hexo-theme-next/issues/1395
请在这里讨论，谢谢！

**Comment by stevenjoezhang** [comment]
已添加此功能： https://github.com/next-theme/hexo-theme-next/commit/03e50d01ac59d136d8d9ccda187d898c0e424332
