### ISSUE TITLE
如何修改插件页面元素的顺序？

### ISSUE THREAD

**Issue by Giresharu** [theme-next/hexo-theme-next#1428]
Other Information 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
比如说我想把推荐文章插件放在打赏和版权信息后面。

我不太懂前端的东西，试着用styles.styl去改了hexo-related-popular-posts插件元素的Position和Top属性，想让他排在post的版权信息之后。
不过因为排序原因，就算视觉上放到了版权信息的下面，只要点了打赏按钮，就会发现他没有跟着移动，而是被打赏挪动的版权信息元素给覆盖住。
所以我想需要被更改的应该是<div>之间的关系，但是不知道在NexT中需要修改什么，才能控制各个插件的顺序？

**Comment by stevenjoezhang** [comment]
需要改模版才行。这些改动是破坏性的，可能会导致未来难以升级，不建议这样做。
