### ISSUE TITLE
底部分页处前一页后一页的fa图标无法展示

### ISSUE THREAD

**Issue by peijie-sh** [theme-next/hexo-theme-next#1429]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
底部分页处前一页后一页应该展示的是箭头图标

## Actual behavior 

底部分页处前一页后一页的fa图标无法正常解析展示，而是展示为 <i class="fa fa-angle-right"></i>

- Links to demo site with this issue: [demoSite](http://peijie2016.gitee.io/blog/page/2/)
- Links to repository or source code of the blog: [版本5.1.4](https://github.com/iissnan/hexo-theme-next/releases)

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
你用的是 5.1.4，最新版是 7.7.2。
