### ISSUE TITLE
Add a button in sidebar to turn on/off dark mode

### ISSUE THREAD

**Issue by lei2rock** [theme-next/hexo-theme-next#1437]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

Not all readers like to visit our blog in a dark mode. So it may be better to provide a button in sidebar to turn on/off dark mode, just like what [this blog](https://raincal.com) does (although it is powered by Gatsby).

## Actual behavior 

- Links to demo site with this feature: https://raincal.com
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

**Comment by stevenjoezhang** [comment]
http://github.com/1v9/hexo-next-nightmode

**Comment by lei2rock** [comment]
> http://github.com/1v9/hexo-next-nightmode

Thanks! I just tried and it doesn't work well for PJAX. And the style also does not work well even for default css settings (I tried under both system's light and dark mode).

**Comment by stevenjoezhang** [comment]
This plugin is open source under the MIT license, you can modify it yourself.

> Not all readers like to visit our blog in a dark mode.

Change the color scheme with the operating system settings is the current trend, so don't worry, the latest versions of iOS, Android, Windows and macOS will help most users to accept the dark mode.

**Comment by lei2rock** [comment]
All right, thanks for your reply. I will try to modify it.
