### ISSUE TITLE
Custom page layout(gallery and product page)

### ISSUE THREAD

**Issue by maddovr** [theme-next/hexo-theme-next#144]
It's me, again! 
I wanted to create a layout for two custom pages, one being a gallery(not a slideshow or pictures embedded on a post, but a kind like a product selection), with an animation like [this one](https://www.w3schools.com/howto/howto_css_image_overlay_slide.asp), and the second being a product page, which should have a db-like appearance like [this one](https://www.animeclick.it/manga/20675/bokutachi-wa-benkyou-ga-dekinai). How do I go about this and where would I put them in the hierarchy? Also, for the second page, is it possible to create a skeleton to fill in instead of the proper page(like, having the db stuff parsed in the front matter or something)?

**Comment by stevenjoezhang** [comment]
I'm not sure if the style of these pages is the same as NexT, but your suggestion has already added to the Roadmap. You can create these pages manually, and enable them under the `menu` section in `_config.yml`
