### ISSUE TITLE
【mist样式】右下角展开个人信息点击日志链接怎么配置跳转到归档页面

### ISSUE THREAD

**Issue by StackJonSnow** [theme-next/hexo-theme-next#1443]
点击日志链接预期
<img width="1624" alt="截屏2020-04-01下午12 54 52" src="https://user-images.githubusercontent.com/26576532/78100928-8190a980-7418-11ea-9b82-24db1bc7d881.png">

但实际显示如下，跳转链接不对，麻烦问下这个在哪里配置
<img width="1792" alt="截屏2020-04-01下午12 56 48" src="https://user-images.githubusercontent.com/26576532/78100984-a84ee000-7418-11ea-9a0b-a5a3b4af5589.png">

**Comment by stevenjoezhang** [comment]
请将主题更新到 7.5.0 或更高版本。
