### ISSUE TITLE
No response when clicking the search button

### ISSUE THREAD

**Issue by nekolr** [theme-next/hexo-theme-next#1445]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
搜索按钮能够正常点击

## Actual behavior 

搜索按钮点击后控制台报错：`Uncaught TypeError: Cannot read property 'addEventListener' of null
    at local-search.js:278`
- Links to demo site with this issue: <https://blog.nekolr.com>
- Links to repository or source code of the blog: <https://github.com/nekolr/nekolr.github.io>

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
v12.16.1
6.13.4
```

### Package dependencies Information

```
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.2.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.2.1
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0
```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
<img width="1076" alt="截屏2020-04-02 上午1 14 40" src="https://user-images.githubusercontent.com/16272760/78166425-555c4380-747f-11ea-856b-bdf4f2e3ad6d.png">

Can't reproduce.

**Comment by nekolr** [comment]
> 
> 
> <img alt="截屏2020-04-02 上午1 14 40" width="1076" src="https://user-images.githubusercontent.com/16272760/78166425-555c4380-747f-11ea-856b-bdf4f2e3ad6d.png">
> 
> Can't reproduce.

Sorry, it's a browser cache issue
