### ISSUE TITLE
Chrome cpu 占用过高

### ISSUE THREAD

**Issue by fuyunliu** [theme-next/hexo-theme-next#1446]
我的网站只使用了鼠标点击特效和打字特效，无背景特效，但是观察发现任何next主题的网站chrome的cpu占用在100%到200%之间，Mac风扇狂转。切换到其他非next的网站，cpu占用在10%左右，对比非常明显，不知问题所在。

![image](https://user-images.githubusercontent.com/13273942/78212644-ea445880-74e2-11ea-939f-61ffdea150ab.png)

**Comment by stevenjoezhang** [comment]
请控制变量以得出科学的结论：
- 这是 Chrome 的问题吗？其它浏览器表现如何？
- 这是主题的问题吗？「鼠标点击特效和打字特效」不是 NexT 主题自带的功能，它们是否消耗过多资源？
- 「任何next主题的网站chrome的cpu占用在100%到200%之间」然而本主题官网 theme-next.org CPU占用 3%（Intel Core i9-9980HK @2.4GHz），是 CPU 性能问题？
<img width="1495" alt="截屏2020-04-02 下午1 24 44" src="https://user-images.githubusercontent.com/16272760/78213464-545dfd00-74e5-11ea-8d78-b12e204aebb0.png">

**Comment by fuyunliu** [comment]
多谢，我自己排查一下原因。

**Comment by fuyunliu** [comment]
确实是这2个特效的原因，去掉恢复正常，和其他网站一般占用率。
