### ISSUE TITLE
如何区别显示中英文字体

### ISSUE THREAD

**Issue by MakerGYT** [theme-next/hexo-theme-next#1448]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
中英文字体区别显示，如英文`Times New Roman`，中文`SimHei`

### NexT Configuration

```yml
font:
  host: 
  enable: true
  posts:
    family:  # 这里好像也不支持多字体，不能先英文后中文字体
```

**Comment by stevenjoezhang** [comment]
你好，已经有一个完全相同的 Issue，请到这里讨论： https://github.com/theme-next/hexo-theme-next/issues/1444
谢谢
