### ISSUE TITLE
Color of `.sidebar-nav li` in dark mode

### ISSUE THREAD

**Issue by lei2rock** [theme-next/hexo-theme-next#1449]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
![Xnip2020-04-03_20-06-51](https://user-images.githubusercontent.com/19180725/78358976-b4889800-75e6-11ea-8ad4-b8b8c3c57ae1.jpg)

## Actual behavior 

![Xnip2020-04-03_20-06-36](https://user-images.githubusercontent.com/19180725/78358997-be120000-75e6-11ea-86aa-4c9e5655aae8.jpg)

- Links to demo site with this issue: https://blog.dlzhang.com/more/share/
- Links to repository or source code of the blog: https://github.com/lei2rock/blog

I temporarily set css as follows to fix it.

```CSS
.sidebar-nav li {
  color: var(--link-color);
}
```

**Comment by stevenjoezhang** [comment]
Sorry, a color scheme design issue should not be considered as a bug. If you have suggestions for better colors, please submit a pull request. Thanks!
