### ISSUE TITLE
TOC can‘t work correctly when lazyload is enabled

### ISSUE THREAD

**Issue by bipy** [theme-next/hexo-theme-next#1452]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

Nav-toc should locate correctly

## Actual behavior 

- Links to demo site with this issue:  it can be found in every hexo-theme-next site which enables lazylaod
- Links to repository or source code of the blog: N/A

 The nav-toc can't locate the right position when lazyload is enabled

## Steps to reproduce the behavior 

1. Enable lazyload in \_config.yml
2. Open a long post with many pictures
3. Click the last tag on toc bar
4. Then it will stop before get to the correct position

### Node.js and NPM Information

```
6.13.4
```

### Package dependencies Information

```
hexo-site@0.0.0
+-- core-js@3.6.4
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.3.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-pandoc@0.3.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-util@1.9.0
`-- save@2.4.0
```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml
lazyload: true
```

**Comment by sli1989** [comment]
can u provide a live demo?
