### ISSUE TITLE
social_icons need support local images!!!社交图标请支持使用本地图片资源

### ISSUE THREAD

**Issue by hongxii** [theme-next/hexo-theme-next#1461]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
Just want this format can effect
```yml
social:
  bilibili: https://space.bilibili.com/666 || bilibili
social_icons:
  bilibili: /images/bilibili.ico
```
OR (▲ import and first  ▼ less)
```yml
social:
  bilibili: https://space.bilibili.com/666 || AUTO
```
AUTO means this can get "https://space.bilibili.com" 's favico autoly

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

- As Expected behavior

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A
As Expected behavior

## Other Information 
老实说，如果图标库里没有我们想用的图标时（中国的知乎，bilibili,豆瓣，头条，抖音，soul等），对于我们而言，我们又需要依赖其他的图标库（中国的图标库），修改过程及其曲折，而且这也仅仅只能解决一部分问题，图标库的更新速度总是不尽人意，我们更多想用自己PS的图标，为什么不支持本地图片呢？

To be honest, if there is no icon we want to use in the icon library (China ’s Zhihu, bilibili, Douban, Toutiao, Douyin, soul, etc.), for us, we need to rely on other icon libraries (Chinese icons Library), the revision process and its twists and turns, and this can only solve part of the problem. The update speed of the icon library is always unsatisfactory. We want to use our own PS icons more. Why do n’t we support local pictures?

**Comment by stevenjoezhang** [comment]
Docs updated: https://github.com/next-theme/theme-next-docs/commit/342e332b309627d0e151e8d06ae54448fffe3363
https://theme-next.js.org/docs/theme-settings/custom-files.html#Custom-Icon-Image
