### ISSUE TITLE
Something goes wrong with comments when I add Aplayer to my blog | 评论系统在加入APlayer后出现问题

### ISSUE THREAD

**Issue by tnrzy** [theme-next/hexo-theme-next#1465]
评论系统在next主题的div id为“comment-***”，但是当我往博客引入[APlayer](https://github.com/MoePlayer/APlayer) ，即：

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.10.0/dist/APlayer.min.css">
<div id="aplayer"></div>
<script src="https://cdn.jsdelivr.net/npm/aplayer@1.10.0/dist/APlayer.min.js"></script>
```
[_layout.zip](https://github.com/theme-next/hexo-theme-next/files/4468688/_layout.zip)

后，博客就会出现当点开有评论页面时自动跳转到默认评论那一行，即本应为：

>http://localhost:4000/……/

一点开就会自动变成

>http://localhost:4000/……/#comment-(你的默认评论系统）

我尝试去寻找了原因，发现这个bug出现在的默认评论上，如果你默认评论并未开启，那么似乎就不会出现问题，是不是该考虑修改一下？或者把APlayer做成一个第三方插件加入Next，毕竟它在博客放音乐还挺好用。

**Comment by sli1989** [comment]
能不能多提供点信息。或者在线demo

> 发现这个bug出现在的默认评论上

你使用的哪个评论。

**Comment by tnrzy** [comment]
~~抱歉似乎打字时有点差错。这是我第一次发issue，发得不具体请见谅~~

---

>请问是中文标题无法跳转么。类似issue

请别理会这个，我不小心在那里发了这里的链接上去

---

是这样，我发现这个问题时用了两个评论系统：valine、utterance，当时默认调了valine，然后就出现了点开有评论的页面`http://localhost:4000/……`（无论是page还是post）自动跳转到`http://localhost:4000/……/#comment-valine`。

当时我发现我保留了

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.10.0/dist/APlayer.min.css">
<div id="aplayer"></div>
<script src="https://cdn.jsdelivr.net/npm/aplayer@1.10.0/dist/APlayer.min.js"></script>
```

就会出现问题。

我也不会改js代码，就在本地试试可不可以避免。

- 我在不改动**默认valine**的情况下，把**valine关了**，然后就不会自动跳转了。

- 当我把默认改为剩下的utterance时，又会自动跳转了……

- 我把两个评论都打开，默认是utterance，它不出我所料会自动跳转，但是是从`http://localhost:4000/……`跳转到`http://localhost:4000/……/#comment-utterance`。

因此，我觉得这个bug出现在默认评论上

**Comment by tnrzy** [comment]
引入Aplayer（PS：即使左下角不弄那个播放音乐的框，也会有问题）：

![Snipaste_2020-04-15_07-59-20](https://user-images.githubusercontent.com/38524670/79285183-61b8b580-7eef-11ea-87bb-e3930a3d7c33.jpg)

关闭Aplayer：

![Snipaste_2020-04-15_08-00-42](https://user-images.githubusercontent.com/38524670/79285233-8dd43680-7eef-11ea-8904-9cacbaa7de5e.jpg)

**Comment by tnrzy** [comment]
@sli1989 If you can't read Chinese well, speaking in English is OK.

**Comment by tnrzy** [comment]
现在的next似乎并不能很好地支持aplayer，即使是插件hexo-tag-aplayer在使用时也会出现以上的情况。但我有个朋友用Butterfly主题就没任何问题。

Now Next can't support APlayer well. Although I use hexo-tag-aplayer, it also have the same problem. However, one of my friends who use theme Butterfly can run it without any problems.

**Comment by tnrzy** [comment]
而且，即使忽略以上的问题，Next主题内音乐进度条居然不能滑动

Also,  the progress bar doesn't work well when I try to drag it.

**Comment by sli1989** [comment]
哈哈，爱莫能助。建议到Aplayer repo也问问。

**Comment by tnrzy** [comment]
万分感谢，改天我会仔细浏览一番。

---

如果你不介意的话，我打算把你博客的链接放在我博客的link上
