### ISSUE TITLE
发现一个bug就是一级标题无法点击链接进行跳转

### ISSUE THREAD

**Issue by XuxuGood** [theme-next/hexo-theme-next#1466]

**Comment by tnrzy** [comment]
@XuxuGood 我这里并没有任何问题

**Comment by XuxuGood** [comment]
你是next-7.8.0嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tnrzy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 上午7:47
收件人:&nbsp;"theme-next/hexo-theme-next"<hexo-theme-next@noreply.github.com&gt;;
抄送:&nbsp;"我是土豆又土又逗🙈"<22476705@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [theme-next/hexo-theme-next] 发现一个bug就是一级标题无法点击链接进行跳转 (#1466)





 
@XuxuGood 我这里并没有任何问题

**Comment by tnrzy** [comment]
嗯

**Comment by tnrzy** [comment]
可能是因为你装了其他东西和这东西冲突了？

**Comment by XuxuGood** [comment]
那有可能是安装其他的插件冲突了，二级往下的目录都好用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tnrzy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 上午8:13
收件人:&nbsp;"theme-next/hexo-theme-next"<hexo-theme-next@noreply.github.com&gt;;
抄送:&nbsp;"我是土豆又土又逗🙈"<22476705@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [theme-next/hexo-theme-next] 发现一个bug就是一级标题无法点击链接进行跳转 (#1466)





 
可能是因为你装了其他东西和这东西冲突了？

**Comment by tnrzy** [comment]
我就在加入APlayer后遇到了奇妙问题 https://github.com/theme-next/hexo-theme-next/issues/1465
