### ISSUE TITLE
source/_data/*.styl文件不生效

### ISSUE THREAD

**Issue by sweetcoffee520** [theme-next/hexo-theme-next#1467]
我尝试在styles.stly文件中添加背景图片，尽管我已经在_config.yml中取消了其中相关的注释，但是在hexo g是没有生成与此相关的文件。不论我如何修改文件，hexo g都不会显示有改动。

**Comment by tnrzy** [comment]
@sweetcoffee520 经我检验，实测有效，是您的问题

**Comment by tnrzy** [comment]
请问您有没有解除 `next：config.yml` 的 `/_data/*.styl` 的注释

**Comment by sweetcoffee520** [comment]
![2020-04-14_101018](https://user-images.githubusercontent.com/17106124/79179019-4be8b900-7e39-11ea-88c2-69e805f1748a.png)
![2020-04-14_101432](https://user-images.githubusercontent.com/17106124/79179071-628f1000-7e39-11ea-8a37-df67f41772f9.png)
我已经修改了了override为true并取消了style的注释，然后添加了如下内容
![2020-04-14_101044](https://user-images.githubusercontent.com/17106124/79179148-910ceb00-7e39-11ea-8db1-44fc13ed539b.png)
之后hexo g的终端显示
![2020-04-14_101307](https://user-images.githubusercontent.com/17106124/79179182-a08c3400-7e39-11ea-9723-9e71a0f07dea.png)
即使我删除styles中的内容
![2020-04-14_101417](https://user-images.githubusercontent.com/17106124/79179244-d0d3d280-7e39-11ea-9ec4-ce4a2139c6f0.png)
再次hexo g，并没有任何变化
![2020-04-14_101455](https://user-images.githubusercontent.com/17106124/79179291-e648fc80-7e39-11ea-9b27-4d2d0f2819fc.png)

**Comment by tnrzy** [comment]
hexo clean ~~（sublime不错）~~

**Comment by sweetcoffee520** [comment]
我就是先hexo clean再hexo g的

**Comment by tnrzy** [comment]
所以你重新hexo clean->g->s 之后，改动实现了吗

**Comment by sweetcoffee520** [comment]
没有实现，因为这个问题，我还仔细检查名字有没有输错，此外以*.styl结尾的三个文件，我取消注释都没有影响，*.swig就有效。~~我用的是vscode~~:smile:

**Comment by tnrzy** [comment]
~~VSC怎么变成你这样的~~ 似乎以前有人提到过，这是hexo优先级的问题，你可以去翻翻之前的issue

**Comment by sweetcoffee520** [comment]
好的，谢谢你。~~就是加了一些主题插件~~

**Comment by sli1989** [comment]
```
body {
  background-image: url(/images/favicon.png);
  background-repeat: repeat;
  background-attachment: fixed;
}
