### ISSUE TITLE
Valine加入了新的配置,望及时更新配置文件及valine模板

### ISSUE THREAD

**Issue by Geniucker** [theme-next/hexo-theme-next#1475]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
![image](https://user-images.githubusercontent.com/61449208/80194795-81697f80-864d-11ea-90c8-a323b3f1058e.png)
Valine加入了新的配置,望及时更新配置文件及valine模板

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

**Comment by Druadach** [comment]
please merge the latest Valine too.

**Comment by sli1989** [comment]
看@xCss 大佬有没有空帮忙PR一下。

**Comment by xCss** [comment]
@sli1989 我尝试添加评论失败了，在`/layout/_partials/comments.swig` 文件中存在的`theme.injects` 属性在[_config.yml](https://github.com/theme-next/hexo-theme-next/blob/master/_config.yml) 并不存在，请先修复~

https://github.com/theme-next/hexo-theme-next/blob/ca19a9d82dba6521ee7b9cb2befda51c6a1bd063/layout/_partials/comments.swig#L2-L5 

-------------
Ps: 我看好像是改了属性名，直接去掉了上层`injects`

**Comment by Geniucker** [comment]
我之前直接改valine的模板,浏览器控制台报错了

**Comment by sli1989** [comment]
fixed in https://github.com/next-theme/hexo-theme-next/pull/62
