### ISSUE TITLE
tab若添加图标后，点击图标无法跳转

### ISSUE THREAD

**Issue by wzzxx7** [theme-next/hexo-theme-next#1476]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Other Information 

**你好，如果tab页设置了图标的话，点击时，仅点击文字能正常跳转，点击图标无效。
如果点击图标也能跳转的话，这样体验会不会好些**

![image](https://user-images.githubusercontent.com/38744714/80299945-278ec400-87cb-11ea-9642-0578cea0399e.png)

**Comment by aixiu** [comment]
@wzzxx7 我的好像没你说的问题，你可以看这里[示例：跳转](http://blog.ynxiu.com/2018/hexo-theme-next-test.html)

**Comment by wzzxx7** [comment]
不好意思，我环境没说明，我用的另一位作者的主题，而他的`tab`是拷贝的你的，
他还没弄清楚你的实现，所以来问下，我查看了生成后的页面代码，一致的，只是点击切换时使用的元素不同，如下图
**无法点击的**
![image](https://user-images.githubusercontent.com/38744714/80327775-ca008300-886f-11ea-8f5e-f87067ccf701.png)
**可正常点击的**
![image](https://user-images.githubusercontent.com/38744714/80327813-df75ad00-886f-11ea-9976-6328bbb6bd69.png)

**Comment by wzzxx7** [comment]
他那边找到原因了，谢谢解答
