### ISSUE TITLE
请问7.x版本之后文章链接怎么修改，不想地址栏出现中文

### ISSUE THREAD

**Issue by Jiyue-Qin** [theme-next/hexo-theme-next#1478]
请问7.x版本之后文章链接怎么修改，不想地址栏出现中文，之前用permalink设置可以改掉，现在找不到这个选项了

**Comment by sli1989** [comment]
修改你的post标题或者使用第三方编码插件。

**Comment by Jiyue-Qin** [comment]
谢谢解答，是我弄错了，已经用第三方插件hexo-addrlink解决。
