### ISSUE TITLE
为hexo-theme-next添加折叠式容器。

### ISSUE THREAD

**Issue by XuxuGood** [theme-next/hexo-theme-next#1480]
大佬们好，我以实现为next添加折叠式容器，希望大佬们能采纳。:v:
示例图
![image](https://user-images.githubusercontent.com/45960164/80664760-2e1e8380-8aca-11ea-9f57-433e05d323d7.png)
具体实现思路还请大佬们看下我的文章  https://hasaik.com/posts/d0bc4f5d.html

**Comment by jiangtj** [comment]
We look forward to your PR :smile:
