### ISSUE TITLE
Home Page is 404 now

### ISSUE THREAD

**Issue by maoqyhz** [theme-next/hexo-theme-next#1492]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Other Information 

can not access the [Hexo-Next home page](https://theme-next.org/).

The HTTP header is as follow:
```
Request URL: https://theme-next.org/
Request Method: GET
Status Code: 404 
Remote Address: 134.209.106.40:443
Referrer Policy: no-referrer-when-downgrade
```

**Comment by sli1989** [comment]
thanks. noted.

**Comment by sli1989** [comment]
because of the technical issue, ths site is unreachable for now. be patient.
for help, u may look into the files in repo.

**Comment by sli1989** [comment]
temp access: https://hexo-theme-next.netlify.app/

**Comment by sli1989** [comment]
https://github.com/next-theme/hexo-theme-next/issues/4#issuecomment-626205848
