### ISSUE TITLE
站点目录的文件能否覆盖 Next 主题内的相应文件？

### ISSUE THREAD

**Issue by Nimnahc2020** [theme-next/hexo-theme-next#1494]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

能否在站点某个文件里创建 `type` 模板如 `page.swig` 或 `categories.swig` 来覆盖主题中 `layout` 下的`page.swig` 或 `categories.swig`。

## Actual behavior 

我是使用 Git 的 `submodule` 方式安装的 Next 主题，以及通过持续集成部署博客。但这样导致我在本地修改的网页样式无法作用于博客。
举个例子：当我修改 `tage.swig` 中的内容以完成有关样式的修改，但持续部署调用的是 `submodule` 
内的 Next 仓库，而 `submodule` 中的有关内容是没有修改的。
所以我在想有没可能实现站点目录的文件覆盖主题内的相应文件。
若有大佬尤其它解决方案，恳请告知。🙏

**Comment by sli1989** [comment]
为啥不自己clone后修改，设置为submodule。
部分文件支持inject和data file。

**Comment by Nimnahc2020** [comment]
很感谢您的回答！我只是想看看有无能不修改主题文件内容而达到目的的方法。我提的这个问题的确可以这样解决！谢谢！

**Comment by sli1989** [comment]
data files 应该可以满足部分要求。你可以试试。
