### ISSUE TITLE
PJAX开启后，如何设置才能自动加载评分与addthis分享

### ISSUE THREAD

**Issue by Cold-Card** [theme-next/hexo-theme-next#1500]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
启动PJAX后，能够在不刷新网页的情况下，到达新文章页面，评分和AddThis分享功能正常加载

## Actual behavior 
需要刷新才能正常加载

- Links to demo site with this issue: https://coldcard.wang

## Steps to reproduce the behavior 
1. 进入一篇文章
2. 通过文章底部的上一篇与下一篇按钮切换文章
3. 评分和addthis分享不加载，需要刷新网页

### Package dependencies Information

```
  "dependencies": {
    "gulp": "^4.0.2",
    "gulp-clean-css": "^4.3.0",
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^5.0.1",
    "gulp-uglify": "^3.0.2",
    "hexo": "^4.0.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-deployer-git": "^2.1.0",
    "hexo-filter-nofollow": "^2.0.2",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.3.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-reference": "^1.0.4",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-symbols-count-time": "^0.7.1"
}

```

**Comment by XuxuGood** [comment]
我也遇到这个问题了，希望解决能告知一下

**Comment by aixiu** [comment]
@XuxuGood  @Cold-Card 作者好久没上线了，[请移步这里讨论](https://github.com/next-theme/hexo-theme-next/issues)
[三大理由](https://github.com/next-theme/hexo-theme-next/issues/4#issuecomment-626205848)

**Comment by jiangtj** [comment]
Pjax I'm not too familiar, waiting for others. 😦
