### ISSUE TITLE
Improve the color of tags in dark mode

### ISSUE THREAD

**Issue by jiangtj** [theme-next/hexo-theme-next#1506]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

In dark mode, the color is changed

## Actual behavior 

![image](https://user-images.githubusercontent.com/15902347/81646990-dcc5ab00-945e-11ea-8c09-ab59b991a5d1.png)
![image](https://user-images.githubusercontent.com/15902347/81647000-e0f1c880-945e-11ea-9e50-19bd6870e663.png)

Since the color is generated by the tagcloud plugin, and the start and end colors are clearly specified, the color is not modified in different modes

https://github.com/theme-next/hexo-theme-next/blob/a7a948a08f48dbe48879e277703d75706aec18e5/layout/page.swig#L41-L43

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/hexo-theme-next/commit/cbcd3f04abfbc15c82f1cf430eca15591015fadc
