### ISSUE TITLE
A fork or a new home for the theme?

### ISSUE THREAD

**Issue by rexwangcc** [theme-next/hexo-theme-next#1508]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

Hi! I have been using next for a few months and am pretty grateful to the elegant design and all of the features it provides. Today I came across the updates from the theme routinely and noticed a new v8 release, while I was excited to see that, it confused me since the one I found is under a different [Github org umbrella](https://github.com/next-theme/hexo-theme-next/releases). I see very little difference between that one and this repo, which is the one I have been following. It would be great to know what's the reason behind it and which one should we follow down the road. 

_(I also understand sometimes things don't work out smoothly, and please feel free to close this issue if you don't think you need to spend time to answer this)_

Thanks a lot!!

**Comment by sli1989** [comment]
well, thanks.
the site your mentioned is a user-customed repo realted with Next.
U can try if u like.

**Comment by kuretru** [comment]
You can see this [https://github.com/next-theme/hexo-theme-next/issues/4#issuecomment-626187669](https://github.com/next-theme/hexo-theme-next/issues/4#issuecomment-626187669)

**Comment by rexwangcc** [comment]
Thanks for the response and pointer! I'm closing the issue now.
