### ISSUE TITLE
不蒜子页面计数不准确

### ISSUE THREAD

**Issue by bianyukun1213** [theme-next/hexo-theme-next#1510]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
不蒜子页面计数如常显示。

## Actual behavior 

不蒜子页面计数显示的并不是本篇文章的阅读量。似乎所有文章共享同一个阅读量。

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by bianyukun1213** [comment]
似乎是 Microsoft Edge Dev 导致的问题。其他浏览器下正常。

**Comment by sli1989** [comment]
需要联系不蒜子开发者
