### ISSUE TITLE
How to make my homepage with menu " home: /" in "theme/next/_config.yml" looks like a page？

### ISSUE THREAD

**Issue by lipcaty** [theme-next/hexo-theme-next#1516]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Question
如何实现让主页(menu: home: / )的显示效果像一个page而不是显示post中的文章。换句话说，如何去掉post的文章的title在鼠标指针停靠时显示的下划线（跳转链接）。效果同网站<http://www.wwli.url.tw/>，点击自动跳转到http://www.wwli.url.tw/index.php/zh-CN/

因为我的_post文件夹中只有一篇index.md的文章，想要做成主页中的内容，但我不希望在主页上显示文章title的链接。用文档中的话来说好像是 disable the function "Preamble Text" ?

我的网址是<https://lipcaty.github.io/>

## Capture
![SharedScreenshot](https://user-images.githubusercontent.com/59415826/83596790-24d87900-a598-11ea-8cdb-b4b12c0b99f9.jpg)

**Comment by jiangtj** [comment]
1 修改index_generator path
```yml
index_generator:
  path: 'other'
```
2 在source文件夹下创建一个index.md，写

**Comment by lipcaty** [comment]
> 1 修改index_generator path
> 
> ```yaml
> index_generator:
>   path: 'other'
> ```
> 
> 2 在source文件夹下创建一个index.md，写

🙇 👍 谢谢！
