### ISSUE TITLE
关于Artitalk

### ISSUE THREAD

**Issue by Drew233** [theme-next/hexo-theme-next#1518]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
-  [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
-  [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
为next主题添加一个可实时发布说说 （微语）的页面

## Actual behavior 

- Links to demo site with this feature: N/A
https://artitalk.js.org/demo.html
- Links to repository or source code of the blog: N/A
https://github.com/Drew233/Artitalk

## Steps to reproduce the behavior 
1. N/A
在leancloud中配置相关应用并设置权限

## Other Information 
Artitalk.js是一个基于leancloud实现的可实时发布说说/微语的js，不知道next是否愿意将它整合进去。

**Comment by Drew233** [comment]
如果你们觉得可以的话，我可以将它添加进去并提起pr

**Comment by jerryc127** [comment]
你应该去https://github.com/next-theme/hexo-theme-next提PR了

**Comment by hayschan** [comment]
这个进度怎么样？

**Comment by Drew233** [comment]
暂时停了

**Comment by hayschan** [comment]
> 暂时停了

这个项目不是最新版的theme-next，他的仓库名和文件名很迷惑

**Comment by jiangtj** [comment]
> 这个项目不是最新版的theme-next，他的仓库名和文件名很迷惑

😂 团队不合，不过我仍然在，做些简单维护（bug修复）
