### ISSUE TITLE
How to disable the "Um..! XX posts in total. Keep on posting." comment in Archive page

### ISSUE THREAD

**Issue by xiaoxiang-ma** [theme-next/hexo-theme-next#1533]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. In original theme
![sc](https://user-images.githubusercontent.com/38440774/88750346-4f235e80-d123-11ea-9545-52db3edf13a6.png)

2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment]
Docs here: https://theme-next.js.org/docs/theme-settings/custom-files.html#Overriding-Default-Style

**Comment by xiaoxiang-ma** [comment]
> Docs here: https://theme-next.js.org/docs/theme-settings/custom-files.html#Overriding-Default-Style
> 
> > <img alt="" height="14" src="/images/favicon-16x16-next.png"> NexT**[Custom Files](https://theme-next.js.org/docs/theme-settings/custom-files.html)**NexT User Docs – Theme Settings - Custom Files

Solved, thank you!

**Comment by libinruan** [comment]
Hello, is there any quick solution to this issue? By the way, the doc link is dead.

**Comment by stevenjoezhang** [comment]
New URL: https://theme-next.js.org/docs/advanced-settings/custom-files.html#Overriding-Default-Style
