### ISSUE TITLE
default table style ---  table-layout: fixed;

### ISSUE THREAD

**Issue by xu-song** [theme-next/hexo-theme-next#154]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

 [expected table style](https://github.com/xu-song/xu-song.github.io/issues/1)  

why do you set [default table style](https://github.com/theme-next/hexo-theme-next/blob/master/source/css/_common/scaffolding/tables.styl#L8) as: 
```css
  table-layout: fixed;
```
This style seems not good.

### Actual behavior 

[actual table style](https://blog.eson.org/2018/02/23/network/%E7%BD%91%E7%BB%9C%E5%8D%8F%E8%AE%AE-OSI%E4%B8%83%E5%B1%82%E6%A8%A1%E5%9E%8B/%E7%BD%91%E7%BB%9C%E5%88%86%E5%B1%82/)   with `table-layout: fixed;`

If you disable this attribute, table looks better. It occurs in many cases.

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version -
```

**Comment by ivan-nginx** [comment]
IDK, this was a long time ago as default style, i think.
You can add pull request for it.

**Comment by ivan-nginx** [comment]
#155.
