### ISSUE TITLE
中文目录无法跳转，英文可以跳转

### ISSUE THREAD

**Issue by wtlizzz** [theme-next/hexo-theme-next#1543]
![屏幕快照 2020-08-04 下午5 05 56](https://user-images.githubusercontent.com/30118316/89275423-d701ef00-d674-11ea-92f8-6bcb4f29e2af.png)

![屏幕快照 2020-08-04 下午5 07 03](https://user-images.githubusercontent.com/30118316/89275510-f0a33680-d674-11ea-99e1-7fdcb862d9cb.png)

## Environment Information
package.json
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.0.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-admin": "^2.3.0",
    "hexo-asset-image": "^1.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-searchdb": "^1.3.2",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it-plus": "^1.0.4",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-symbols-count-time": "^0.7.1",
    "hexo-wordcount": "^2.0.1"
  }
}
```

## Other Information 

[LINK](https://wtlizzz.gitee.io/)(https://wtlizzz.gitee.io/)

**Comment by wtlizzz** [comment]
Plz.I need help.

**Comment by wtlizzz** [comment]
![屏幕快照 2020-08-04 下午5 15 55](https://user-images.githubusercontent.com/30118316/89276457-44fae600-d676-11ea-82f8-d71966edc247.png)
报错显示

**Comment by wtlizzz** [comment]
已解决。
<img width="1409" alt="屏幕快照 2020-08-04 下午7 50 13" src="https://user-images.githubusercontent.com/30118316/89290642-bdb86d00-d68b-11ea-98d8-5ee8c17c0aa0.png">
将
  var target = document.getElementById(event.currentTarget.getAttribute('href').replace('#', ''));
 改为：
 var target = document.getElementById(decodeURI(event.currentTarget.getAttribute('href').replace('#', '')));

**Comment by wtlizzz** [comment]
在下面return部分也要加上，不然选中的话，还是不能显示选中的中文目录。。
～～～
你们都没有这个问题 吗，我怀疑我配置有问题了，呜呜呜～

**Comment by alvisdeng** [comment]
我刚刚在 butterfly 也遇到了这个问题, 但是我是因为使用了 Aplayer...

**Comment by ousugo** [comment]
我也遇到了这个问题，现象以及报错和你的完全一样。然后我看了下你的博客，发现也是升级到了 Hexo 5.0，我怀疑是不是因为升级到了 5.0 导致的，因为之前都是正常的，而最近没有做其他修改。
