### ISSUE TITLE
set `language: zh-Hans` invalid

### ISSUE THREAD

**Issue by zwwtj2014** [theme-next/hexo-theme-next#157]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

The theme is displayed in Chinese

### Actual behavior 

theme is still in English

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

#### Hexo version

```
hexo: 3.6.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

#### Hexo Configuration

```yml
language: zh-Hans
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

#### NexT Configuration:

```yml

```

### Other Information 

**I found only `zh-CN.yml` in the language folder, so I tried to add file `zh-Hans.yml` in the language folder and it is ok.**
**So I configured wrong or really missing the file `zh-Hans.yml` ?**

**Comment by Raincal** [comment]
https://github.com/theme-next/hexo-theme-next/releases/tag/v6.0.3

**Comment by zwwtj2014** [comment]
@Raincal 👍 thank you!
