### ISSUE TITLE
how to set the figure's indent in post

### ISSUE THREAD

**Issue by sli1989** [theme-next/hexo-theme-next#158]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 

The spacing seems too small.

sample1:

![qq 20180304142512](https://user-images.githubusercontent.com/8521181/36942856-5f1420be-1fb8-11e8-8bd7-02498670cd34.png)

sample2:
![qq 20180304143015](https://user-images.githubusercontent.com/8521181/36942864-9fa61416-1fb8-11e8-87ac-6658c0f325b7.png)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by ivan-nginx** [comment]
Live demo?

**Comment by sli1989** [comment]
http://saili.science/2018/02/14/artificial-intelligence/

**Comment by ivan-nginx** [comment]
Can u show part of MD source here:
![image](https://user-images.githubusercontent.com/16944225/36945851-11215ab8-1fc5-11e8-82f5-087004f06464.png)

**Comment by sli1989** [comment]
```
![](https://wx1.sinaimg.cn/large/006V2m65gy1fogaif6xatj30hs0auab7.jpg)

> [深入理解人工智能和机器学习](https://medium.com/swlh/artificial-intelligence-vs-machine-learning-is-it-confusing-3ace59aa0d19)

工程师Narasimha Prasanna HN撰写的技术博文“[what-is-artificial-general-intelligence](https://mp.weixin.qq.com/s/em1NisiFmXwLmwH7_UXwWw)”主要介绍人工智能的概念，当前人工智能的水平，以及什么是强人工智能，当前实现强人工智能的方向。

随着计算机的帮助和互联网上足够大的可用的数据集，所谓的机器学习就出现了。机器学习不等同于人工智能，而是人工智能的一个重要部分，是一种实现人工智能的方法。机器学习提供了一套使用AI的数学概念，可以在现实世界中实施。

为此，机器学习主要关注于模式识别。机器学习有助于识别数据集内的模式，并因此尝试根据现有数据进行预测。[深度学习](https://sli1989.github.io/2017/05/15/deep-learning-1/)是一种实现机器学习的技术[^2888249]。

![](https://wx2.sinaimg.cn/large/006V2m65gy1foo3vai8r0j30h2090glt.jpg)

![](https://wx1.sinaimg.cn/large/006V2m65gy1fogasefrboj312g1wtk0l.jpg)
```

**Comment by ivan-nginx** [comment]
So, need to add `margin-bottom` to `figure` class? I think there was added it in old Vi's repo, but later remaked to 0.

**Comment by sli1989** [comment]
i just found this, but it doesn't working.

https://github.com/theme-next/hexo-theme-next/blob/e12bb0b27e16072eb82baa4c7dda1c41c8de7264/source/css/_common/scaffolding/normalize.styl#L203-L205

**Comment by ivan-nginx** [comment]
MB here? https://github.com/iissnan/hexo-theme-next/pull/1862/files

**Comment by ivan-nginx** [comment]
```css
.posts-expand .post-body img {
    margin-bottom: 10px;
```

**Comment by sli1989** [comment]
FIXED IN [PR](https://github.com/theme-next/hexo-theme-next/pull/161).

**Comment by ivan-nginx** [comment]
Merged.
