### ISSUE TITLE
theme-next 组织是不是迁移到了 next-theme？

### ISSUE THREAD

**Issue by BladeCode** [theme-next/hexo-theme-next#1581]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

当前项目：https://github.com/theme-next/hexo-theme-next 停留在 v7.8.0版本
截止当前：https://github.com/next-theme/hexo-theme-next 项目已经更新到 v8.0.2

请问
1. 当前theme-next 组织下的 hexo-theme-next 项目是否还继续迭维护？
2. [theme-next](https://github.com/theme-next) 组织和 [next-theme](https://github.com/next-theme) 组织间有什么区别？

**Comment by ours1984** [comment]
同问
