### ISSUE TITLE
 Cannot find the canvas-nest dynamic background in the next theme configuration？

### ISSUE THREAD

**Issue by yunjicangtian** [theme-next/hexo-theme-next#1585]
What should I do if the canvas-nest dynamic background cannot be found in the next theme configuration？

**Comment by howiezhao** [comment]
@yunjicangtian Starting from NexT v8.0.0, [canvas_nest has been removed](https://github.com/next-theme/hexo-theme-next/releases/tag/v8.0.0-rc.2). If you want to use canvas_nest, you can refer to this [installation guide](https://github.com/theme-next/theme-next-canvas-nest#install).
