### ISSUE TITLE
如何修改照片下的文字

### ISSUE THREAD

**Issue by RuoyuChen10** [theme-next/hexo-theme-next#1591]
![image](https://user-images.githubusercontent.com/39595892/102313359-759b4680-3fab-11eb-971a-574e56e378e4.png)
你好，照片下文字是1he和posts，我想知道这两项如何进行修改，谢谢

**Comment by stevenjoezhang** [comment]
设置 `site_state: false`

https://github.com/theme-next/hexo-theme-next/blob/d24c48efb1ff1182b23926a3835e350f9c3ab6eb/_config.yml#L173
