### ISSUE TITLE
TOC link error [nested `a` elements]

### ISSUE THREAD

**Issue by iwyy** [theme-next/hexo-theme-next#16]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.org).
- [] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Hexo Information

```

```

### Package dependencies Information

```

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
請用英文寫。

**Comment by iwyy** [comment]
The article directory where my article jump can only click on the front number, and the text has no jump effect.

**Comment by ivan-nginx** [comment]
Screens? Live demo?

**Comment by iwyy** [comment]
@ivan-nginx 
http://www.iwyy.top/2017/hello-world/#more

**Comment by ivan-nginx** [comment]
![image](https://user-images.githubusercontent.com/16944225/34640344-eb9cd91a-f301-11e7-9b5d-8bda30ab2e94.png)
This trouble?

**Comment by iwyy** [comment]
yes
@ivan-nginx

**Comment by ivan-nginx** [comment]
This is [`hexo-renderer-marked`](https://github.com/hexojs/hexo-renderer-marked) bug.
See [here](https://github.com/iissnan/hexo-theme-next/issues/2035) or [here](https://github.com/iissnan/hexo-theme-next/issues/2046) for details and how to resolve.

If solved, close it.
