### ISSUE TITLE
beian url is wrong in v7.8.0

### ISSUE THREAD

**Issue by yiGmMk** [theme-next/hexo-theme-next#1604]
## Issue Checklist 

- [x ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
In v7.8.0 the beian url is "http://www.beian.miit.gov.cn" which is wrong that doesn't work(it point to a wrong path resulting in 404). Correct url should be "https://beian.miit.gov.cn/"

In branch master it is correct.

## Actual behavior 

In v7.8.0 the beian url is "http://www.beian.miit.gov.cn"
- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by sli1989** [comment]
solved in #1553
