### ISSUE TITLE
为 cc 添加 标准 或 紧凑 的图标样式，并且可以 修改宽度

### ISSUE THREAD

**Issue by mrluffya** [theme-next/hexo-theme-next#1605]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
**Note:**
Since the theme usually uses **git submodules** for maintenance, it is hoped that **only the theme configuration file can be modified** to achieve this function **without changing the theme/next file**.
注意：
由于 主题 通常使用 **git 子模块** 进行维护，因此希望 **仅修改 主题配置文件** 即可实现此功能，而 **无需更改 theme/next 中的文件。**

Idea source:
[Please select the style you want to display on the page: **standard** or **compact**](https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=zh)
想法出处：
[请选择要在网页上显示的图标样式：**标准** 或 **紧凑**](https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=zh)

Creative commons sidebar style, hope is standard style and modify the width, for example:
Creative commons 侧边栏图标样式，希望是 **标准** 的图标样式，并且 **可以修改宽度**，例如：
![Creative Commons License Agreement](https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg)

## Actual behavior 

Actually provides **compact** style. 实际上是 **紧凑** 的图标样式。

- Links to demo site with this feature: https://mrluffya.github.io/
- Links to repository or source code of the blog: https://github.com/theme-next/hexo-theme-next/blob/master/source/images/cc-by.svg

## Steps to reproduce the behavior 
1. edit `_config.next.yml`  编辑 `_config.next.yml` 
```yml
creative_commons:
  license: by
  sidebar: true
  post: true
  language: deed.zh
```

2. start service 启动服务
```sh
$ hexo s --incremental --draft
```

## Other Information 
OS: macOS 10.13.6 (High Sierra)
Browser: Firefox 84.0.2
hexo-theme-next: 7.8.0

**standard** **标准**
<img width="96" alt="standard" src="https://user-images.githubusercontent.com/23006292/105700290-9d36e480-5f43-11eb-9c6d-7840bb32b25d.png">

**compact** **紧凑**
<img width="103" alt="compact" src="https://user-images.githubusercontent.com/23006292/105700281-9ad48a80-5f43-11eb-8a09-dec7025fc866.png">

## Coding 代码
see PR https://github.com/theme-next/hexo-theme-next/pull/1606

**Comment by jiangtj** [comment]
May contribute to https://github.com/next-theme/hexo-theme-next ?
