### ISSUE TITLE
Theme Pisces Sidebar Bug

### ISSUE THREAD

**Issue by yangyang0507** [theme-next/hexo-theme-next#162]
when sidebar option is true, like this:
```
  sidebar:
    b2t: true
    scrollpercent: true
```
site sidebar will be like this:
![_ _20180306154653](https://user-images.githubusercontent.com/5666807/37020096-a2925bf0-2155-11e8-87af-8b182c578545.png)

normal:
![_ _20180306154606](https://user-images.githubusercontent.com/5666807/37020120-b50625a0-2155-11e8-9614-0b58504a411c.png)

**P.S. all config write in `next/config.yml`**

**Comment by sli1989** [comment]
It works fine in my V605. Did u have any custom setting?

**Comment by geekrainy** [comment]
This occurs when the network is slow to load, displaying the full menu after the full load is successful.

**Comment by ivan-nginx** [comment]
In last month i do big refactoring for sidebar in Pisces / Gemini. And i think this bug already solved.

**Comment by stevenjoezhang** [comment]
The modification of the animation sequence will ensure that such bugs will not happen again
