### ISSUE TITLE
似乎没有找到黑暗模式的演示网站

### ISSUE THREAD

**Issue by GanZhiXiong** [theme-next/hexo-theme-next#1644]
我找了下，没有看到黑暗模式的Demo，我想先看看效果如何。

黑暗模式会越来越主流，GitHub最近也出了黑暗模式，体验非常好。
**所以如果还不支持黑暗模式的话，我很期待能添加这个功能！**

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/pull/1386

**Comment by GanZhiXiong** [comment]
👍 Good
