### ISSUE TITLE
Open post in new tab

### ISSUE THREAD

**Issue by cnvirus** [theme-next/hexo-theme-next#1649]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
Open a post in new tab

## Actual behavior 

Post is opend in current tab.
The "external_link" setting only work for the outside link not for the link of the blog.

**Comment by luiselullgar23** [comment]
Your ready
