### ISSUE TITLE
fancybox and add this symbol invisible

### ISSUE THREAD

**Issue by chy9002** [theme-next/hexo-theme-next#165]
master version.
some symbol cannot visible in page, such as fancybox 3 and addthis.
Please see this snipshot:
<img width="1258" alt="snipaste_2018-03-13_10-10-40" src="https://user-images.githubusercontent.com/7344772/37318690-d512e2a6-26a6-11e8-9dce-c356462c3735.png">

**Comment by geekrainy** [comment]
These options are configurable and are currently not configured, pending confirmation.

**Comment by chy9002** [comment]
@geekrainy I already set `fancybox: true`, and download fancybox3 via theme-next-fancybox3. but the icon still not visible, is there other setting for it?
```yaml
# Fancybox. There is support for old version 2 and new version 3.
# Please, choose only any one variant, do not need to install both.
# For install 2.x: https://github.com/theme-next/theme-next-fancybox
# For install 3.x: https://github.com/theme-next/theme-next-fancybox3
fancybox: true
```

**Comment by geekrainy** [comment]
It belongs to the built-in option of fancybox and I will release a fix.

**Comment by chy9002** [comment]
@geekrainy Thanks!
