### ISSUE TITLE
【Typora下的md扩展语法不支持】无法使用md扩展语法“文本高亮”

### ISSUE THREAD

**Issue by Shawdox** [theme-next/hexo-theme-next#1650]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

![image](https://user-images.githubusercontent.com/60968667/122157393-59fef300-ce9d-11eb-9da1-d526a22c5ac1.png)
![image](https://user-images.githubusercontent.com/60968667/122157419-65521e80-ce9d-11eb-8475-f5fd5953503e.png)
使用高亮语法后，预期文本会出现高亮。
## Actual behavior 

![image](https://user-images.githubusercontent.com/60968667/122157462-7864ee80-ce9d-11eb-874d-6807ab9dac79.png)
无法显示高亮，请问如何解决？
- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by jiangtj** [comment]
这不属于md语法，且建议反馈给Typora
