### ISSUE TITLE
next-theme fork and theme next future

### ISSUE THREAD

**Issue by noraj** [theme-next/hexo-theme-next#1663]
## Issue Checklist

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

## Other Information

It was so confusing at first, but I finally figured it out.

It seems that there are two hexo-theme-next repositories.

theme-next org (you) started this theme the Dec 31, 2017 and maintained it until Sep 2, 2020. Your last version by git tag is 7.8.0 and announced on your website is 7.7.2.

The the development stopped.

It seems next-theme (fork) forked this project by creating a new repository and erasing the git history about in April 2020. Since then they have created a new 8.x.x major release (last is 8.7.0), they have created a true user documentation (better than [this](https://github.com/theme-next/hexo-theme-next/tree/master/docs)), took over the control of the npm package https://www.npmjs.com/package/hexo-theme-next, and PRed the hexo website to point towards the fork version (see https://github.com/hexojs/site/pull/1588/files).

So it seemed to me like theme-next org abandoned the project and next-theme org took the relay.

But suddenly 8 days ago (Jul 30, 2021) there is a new commit on theme-next original version.

I can tell which is the original project and which is the fork, but now what about the future? Will theme-name come back? Currently next-theme fork is more up to date and well-spread, it is more than one year of dev ahead (~ 500 commits).

Can someone explain me what happened and what is going to happen?

Source repository | Website
---|---
[theme-next/hexo-theme-next][theme-next] | https://theme-next.org/
[next-theme/hexo-theme-next][next-theme] | https://theme-next.js.org/

[theme-next]:https://github.com/theme-next/hexo-theme-next
[next-theme]:https://github.com/next-theme/hexo-theme-next

**Comment by ljcbaby** [comment]
https://github.com/next-theme/hexo-theme-next/issues/4#issuecomment-626205848

This is the answer you asked for, but it is described in Chinese.

**Comment by noraj** [comment]
Yeah translated it here: https://github.com/next-theme/hexo-theme-next/issues/340#issuecomment-894336353
