### ISSUE TITLE
sidebar 目录中自动追加的章节号能否移除

### ISSUE THREAD

**Issue by yunnysunny** [theme-next/hexo-theme-next#1672]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Actual behavior 

[sidebar](https://theme-next.js.org/docs/theme-settings/sidebar#Sidebar-Style) 组件中的目录列表会强制追加章节号，且无法移除。

![](https://silian.whyun.com/images/sidebar_contents.png)

**Comment by yunnysunny** [comment]
具体效果参见这张图片 https://silian.whyun.com/images/sidebar_contents.png

**Comment by zongchengLi** [comment]
在 `next\_config.yml` 中，有一个 `toc` 下的 `number` 改成 `false` 即可。

**Comment by yunnysunny** [comment]
谢谢指导
