### ISSUE TITLE
Leancloud's Error

### ISSUE THREAD

**Issue by rqy1458814497** [theme-next/hexo-theme-next#169]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

let `theme.leancloud_visitors.enable` be `true` and show visitors.

### Actual behavior 

it makes an javascript error because of some unescaped single quotes.

### Steps to reproduce the behavior 

No steps. 

the code in [lean-analytics.swig](https://github.com/theme-next/hexo-theme-next/blob/master/layout/_third-party/analytics/lean-analytics.swig).

line 80, the single quotes in the string should be escaped.

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by sli1989** [comment]
leancloud-counter-security has been added in new branch. If you donnot want use it, please set the `security: false`, and else follow [this instruction](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md).

**Comment by LEAFERx** [comment]
fix in #171

**Comment by ivan-nginx** [comment]
@rqy1458814497 close it if solved. Thank's!
