### ISSUE TITLE
Hide the post under certain categories in "home page" and display them in some other customized pages.

### ISSUE THREAD

**Issue by Enigmatisms** [theme-next/hexo-theme-next#1691]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

### Question Description
I am using Hexo 8.10.0 for hosting my blog, and what I am trying to do is:

- Create a customized page for displaying one specific category, marked as category "A".
- **Hide all the posts under category A in the home page.** This means I only want posts under category A to be displayed in the customized page other than home.
## Expected behavior 
I have made a customized page that I need, but what really troubles me is "Hide all the posts under category A in the home page." I have tried one approach, which is to modify `layout/index.njk` (P.S I am new to nunjucks):
```nunjucks
{%- set non_snippets = [] %}
{%- for post in page.posts.toArray() %}
  {%- set flag = true %}
  {%- for cat in post.categories.toArray() %}
    {%- if cat.name == 'learning' %}
      {%- set flag = false %}
    {%- endif %}
  {%- endfor %}
  {%- if flag %}
    {%- set non_snippets = (non_snippets.push(post), non_snippets) %}
  {%- endif %}
{%- endfor %}

{% block content %}
  {%- for post in non_snippets %}
    {{ partial('_macro/post.njk', {post: post, is_index: true}) }}
  {%- endfor %}
  {%- include '_partials/pagination.njk' -%}
{% endblock %}
```
The code above will disable all the posts categorized as "learning" from displaying in `home`, which is successful. Yet, **Pagination** failed to filter out those posts, resulting in:
![aaa](https://raw.githubusercontent.com/Enigmatisms/Enigmatisms/master/1.png)
This page has no content (all the posts in the page is categorized as "learning"), but is still paginated. I suspect that the posts are just not rendered. The posts not categorized as "learning" even won't fill one single page (10 posts per page).
### Question
So how can I hide the post under certain categories in "home page" and display them in some other customized pages? Is there any way more elegant?

**Comment by stevenjoezhang** [comment]
Replace `hexo-generator-index` with `hexo-generator-indexed`.

See https://github.com/next-theme/hexo-generator-indexed#隐藏特定分类中的文章-hide-articles-in-specified-categories

**Comment by Enigmatisms** [comment]
> Replace `hexo-generator-index` with `hexo-generator-indexed`.
> 
> See [https://github.com/next-theme/hexo-generator-indexed#隐藏特定分类中的文章-hide-articles-in-specified-categories](https://github.com/next-theme/hexo-generator-indexed#%E9%9A%90%E8%97%8F%E7%89%B9%E5%AE%9A%E5%88%86%E7%B1%BB%E4%B8%AD%E7%9A%84%E6%96%87%E7%AB%A0-hide-articles-in-specified-categories)

Thanks. Will try this in a minute.

**Comment by Enigmatisms** [comment]
hexo-generator-indexed solves the problem.
