### ISSUE TITLE
compatibility with adblock (jsdelivr.com)

### ISSUE THREAD

**Issue by liuwangdao** [theme-next/hexo-theme-next#1695]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
website elements normally loaded

## Actual behavior 
blank page

- Links to demo site with this issue: https://theme-next.js.org/

## Steps to reproduce the behavior 
1. adblock block site cdn.jsdelivr.net
2. site with next can not be displayed，e.g. https://theme-next.js.org/ or mysite

>>
next version：8.4.0（my site）
but it work well on loacalhost:400

**Comment by liuwangdao** [comment]
I revised ./_config.yml and  it is solved
```
vendors:
  # The CDN provider of NexT internal scripts.
  # Available values: local | jsdelivr | unpkg | cdnjs
  # Warning: If you are using the latest master branch of NexT, please set `internal: local`
  internal: local
  # The default CDN provider of third-party plugins.
  # Available values: local | jsdelivr | unpkg | cdnjs
  # Dependencies for `plugins: local`: https://github.com/next-theme/plugins
  # plugins: jsdelivr
  # plugins: loli
  plugins: local
```

<blockquote><img src="https://opengraph.githubassets.com/d697bb6e892442aeb90b2c2d981adbf62ec56790e6f9effe89340702770c3171/next-theme/plugins" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/next-theme/plugins">GitHub - next-theme/plugins: 🔮 Third-party front-end plugins for Hexo theme NexT.</a></strong></div><div>🔮 Third-party front-end plugins for Hexo theme NexT. - GitHub - next-theme/plugins: 🔮 Third-party front-end plugins for Hexo theme NexT.</div></blockquote>

**Comment by sli1989** [comment]
jsdelivr 国内访问 好像不那么顺畅

**Comment by SunJunge08** [comment]
> I revised ./_config.yml and it is solved
> 
> ```
> vendors:
>   # The CDN provider of NexT internal scripts.
>   # Available values: local | jsdelivr | unpkg | cdnjs
>   # Warning: If you are using the latest master branch of NexT, please set `internal: local`
>   internal: local
>   # The default CDN provider of third-party plugins.
>   # Available values: local | jsdelivr | unpkg | cdnjs
>   # Dependencies for `plugins: local`: https://github.com/next-theme/plugins
>   # plugins: jsdelivr
>   # plugins: loli
>   plugins: local
> ```
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0cbf6d61431d9b43368552bb312958b452221e8ab337c02ddb9fbec0f2d95b04/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f643639376262366538393234343261656239306232633264393831616462663632656335363739306536663965666665383933343037303237373063333137312f6e6578742d7468656d652f706c7567696e73"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[GitHub - next-theme/plugins: 🔮 Third-party front-end plugins for Hexo theme NexT.](https://github.com/next-theme/plugins)**🔮 Third-party front-end plugins for Hexo theme NexT. - GitHub - next-theme/plugins: 🔮 Third-party front-end plugins for Hexo theme NexT.

I tried to do by your method but it doesn't work...
