### ISSUE TITLE
docs/MATH.md doesn't tell user to install pandoc

### ISSUE THREAD

**Issue by botbotty** [theme-next/hexo-theme-next#1697]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Other Information 

docs/MATH.md says you need to install "hexo-renderer-pandoc" by npm, but doesn't mention that you also need to install "pandoc" (by apt in Ubuntu for example).

**Comment by sli1989** [comment]
welcome to new repo: https://theme-next.js.org/

<blockquote><div><img src="/images/favicon-16x16-next.png" height="14"> NexT</div><div><strong><a href="https://theme-next.js.org/index.html">NexT</a></strong></div></blockquote>
