### ISSUE TITLE
gitment fails in edge&ie&mobile

### ISSUE THREAD

**Issue by sli1989** [theme-next/hexo-theme-next#17]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

display the comments and login box

### Actual behavior 

- chrome displayed the comments and login box
- edge failed to display login box. `Microsoft Edge 40.15063.0.0` `Microsoft EdgeHTML 15.15063`
- ie&mobile failed to display the comments and login box

the known issue in gitment is [#50](https://github.com/imsun/gitment/issues/50)

* Link to demo site with this issue: 

http://saili.science/2016/04/04/how-to-research/

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
![image](https://user-images.githubusercontent.com/16944225/34640261-5a6d0baa-f300-11e7-92ed-7a7c47840a52.png)
What version of Edge/IE fail?

**Comment by sli1989** [comment]
just let u know, i will check it again..
thank u

**Comment by sli1989** [comment]
in muse, it works well in mobile.
in Pisces, there is a  override between gitment and footer.
maybe, you can close the issue.

**Comment by ivan-nginx** [comment]
> in Pisces, there is a override between gitment and footer.

What kind of ovveride is this? If there are any errors, need to fix they. But i can't to fix what i not see, i must to reproduce this bug before. If u give me reproduce steps, i'll try to fix it.

**Comment by sli1989** [comment]
Just forget it, 
maybe it's my own problem, i have switch the theme to muse.
i will let u know the details when I run into the problem again.

**Comment by ivan-nginx** [comment]
@sli1989 ok.

Also, u can test in different browsers any site [here](https://www.browserstack.com).

**Comment by stevenjoezhang** [comment]
Gitment removed in #939
