### ISSUE TITLE
Your Blogs Here!

### ISSUE THREAD

**Issue by StudentWeis** [theme-next/hexo-theme-next#1700]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Other Information 

传承之前的一个 [Issue](https://github.com/iissnan/hexo-theme-next/issues/119)！希望大家把自己的博客地址留在这里，彼此了解和分享！我先来！

https://www.studentwei.xyz/

Pass on previous [Issue](https://github.com/iissnan/hexo-theme-next/issues/119)! Hope everyone to leave their own blog address here, understand each other and share! I come first!

https://www.studentwei.xyz/

**Comment by zerobio** [comment]
初来乍到，请多关照！
感谢 Next 各位开发大佬！！！
https://zerobio.github.io/

<blockquote><div><img src="/images/favicon-16x16.png" height="14"> 生信小白</div><div><strong><a href="https://zerobio.github.io/index.html">生信小白</a></strong></div><div>爱随意却不失精致 乐自由而不失自律</div></blockquote>
