### ISSUE TITLE
Pisces主题，修改段间距方法

### ISSUE THREAD

**Issue by Eminem-x** [theme-next/hexo-theme-next#1703]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## 解决方法 
Pisces主题下，段间距太大了，在网上找了很多，包括旧仓库的 issue 都没有合适的解决方案，
后来通过这篇博客：https://blog.csdn.net/weixin_44253490/article/details/107786023，
在站点路径 `public\css\main.css` 文件中找到 `p {margin: 0 0 20px 0;}`，但是修改会不发生变化，
查看 `main.css` 会发现恢复成最开始的参数，具体原因似乎是静态文件覆盖，
但是可以在主题路径 `themes\next\source\css\main.styl` 添加 `p {margin: 0 0 10px 0;}`，进行修改即可。

**Comment by Code-Newborn** [comment]
![image](https://github.com/theme-next/hexo-theme-next/assets/47051839/d23c3a13-d882-4ef9-8525-e0baad3a51c7)
每行间距不一致，看着很难受
