### ISSUE TITLE
数学公式问题

### ISSUE THREAD

**Issue by bugcat9** [theme-next/hexo-theme-next#1714]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***
我编写的公式在博客上渲染的显示的乱七八糟的，但是在本地使用Typora打开源文件查看又没有问题，不知道是bug还是我公式编写有问题😂
在博客上
![image-20220730204835753](https://cdn.jsdelivr.net/gh/zhou-ning/blog-image-bed@main/others/image-20220730204835753.png)
在本地
![image-20220730204906551](https://cdn.jsdelivr.net/gh/zhou-ning/blog-image-bed@main/others/image-20220730204906551.png)
我配置了`mathjax: true`，有的公式渲染是成功的，只是有的乱起八糟的
我公式的写法如下
```
其中$\alpha_t=f_{\alpha}(x_t)$为学习到的重要性分数，将生成的视频特征进一步送入到分类器以获得预测结果$\tilde{y}=f_{cls}(\bar{x})$。经过模型训练后。使用$f_\alpha(\cdot)$和$f_{cls}(\cdot)$来推断测试视频的片段级别激活序列CAS。
```
## Other Information 
可以直接访问[blog](https://zhou-ning.github.io/2022/07/22/%E8%AE%BA%E6%96%87%E5%AD%A6%E4%B9%A0/Fine-grained%20Temporal%20Contrastive%20Learning%20for%20Weakly-supervised%20Temporal%20Action%20Localization/)进行查看

**Comment by SunJunge08** [comment]
我把你这段代码
```
其中$\alpha_t=f_{\alpha}(x_t)$为学习到的重要性分数，将生成的视频特征进一步送入到分类器以获得预测结果$\tilde{y}=f_{cls}(\bar{x})$。经过模型训练后。使用$f_\alpha(\cdot)$和$f_{cls}(\cdot)$来推断测试视频的片段级别激活序列CAS。
```
放到了我的 Blog 文章中，效果是这样的：

![image](https://user-images.githubusercontent.com/70008772/183227710-66fef1dd-a4fe-41c1-b642-bc9e674a71f4.png)

并没有什么问题。

判断是你的 `MathJax` 版本有问题，把 CDN 地址改为 `//cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js` 就可以了

**Comment by bugcat9** [comment]
> 



> 我把你这段代码
> 
> ```
> 其中$\alpha_t=f_{\alpha}(x_t)$为学习到的重要性分数，将生成的视频特征进一步送入到分类器以获得预测结果$\tilde{y}=f_{cls}(\bar{x})$。经过模型训练后。使用$f_\alpha(\cdot)$和$f_{cls}(\cdot)$来推断测试视频的片段级别激活序列CAS。
> ```
> 
> 放到了我的 Blog 文章中，效果是这样的：
> 
> ![image](https://user-images.githubusercontent.com/70008772/183227710-66fef1dd-a4fe-41c1-b642-bc9e674a71f4.png)
> 
> 并没有什么问题。
> 
> 判断是你的 `MathJax` 版本有问题，把 CDN 地址改为 `//cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js` 就可以了

谢谢老哥的解答，想问一下啊在那里改`MathJax`的版本号呢。就是`//cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js`这个应该在那里进行更改呢😂

**Comment by SunJunge08** [comment]
> > 
> 
> > 我把你这段代码
> > ```
> > 其中$\alpha_t=f_{\alpha}(x_t)$为学习到的重要性分数，将生成的视频特征进一步送入到分类器以获得预测结果$\tilde{y}=f_{cls}(\bar{x})$。经过模型训练后。使用$f_\alpha(\cdot)$和$f_{cls}(\cdot)$来推断测试视频的片段级别激活序列CAS。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 放到了我的 Blog 文章中，效果是这样的：
> > ![image](https://user-images.githubusercontent.com/70008772/183227710-66fef1dd-a4fe-41c1-b642-bc9e674a71f4.png)
> > 并没有什么问题。
> > 判断是你的 `MathJax` 版本有问题，把 CDN 地址改为 `//cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js` 就可以了
> 
> 谢谢老哥的解答，想问一下啊在那里改`MathJax`的版本号呢。就是`//cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js`这个应该在那里进行更改呢😂

打开 `\themes\next\_config.yml` 这个文件，用 `Ctrl+F` 搜索 `MathJax` ，翻到最后一个，把下图中用绿色框选出来的部分改为 `//cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js` 即可。

![image](https://cdn.u1.huluxia.com/g4/M03/70/43/rBAAdmLvKbaAaEI0AAP17T5pqxc741.png)

**Comment by bugcat9** [comment]
> > > 
> > 
> > 
> > > 我把你这段代码
> > > ```
> > > 其中$\alpha_t=f_{\alpha}(x_t)$为学习到的重要性分数，将生成的视频特征进一步送入到分类器以获得预测结果$\tilde{y}=f_{cls}(\bar{x})$。经过模型训练后。使用$f_\alpha(\cdot)$和$f_{cls}(\cdot)$来推断测试视频的片段级别激活序列CAS。
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 放到了我的 Blog 文章中，效果是这样的：
> > > ![image](https://user-images.githubusercontent.com/70008772/183227710-66fef1dd-a4fe-41c1-b642-bc9e674a71f4.png)
> > > 并没有什么问题。
> > > 判断是你的 `MathJax` 版本有问题，把 CDN 地址改为 `//cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js` 就可以了
> > 
> > 
> > 谢谢老哥的解答，想问一下啊在那里改`MathJax`的版本号呢。就是`//cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js`这个应该在那里进行更改呢😂
> 
> 打开 `\themes\next\_config.yml` 这个文件，用 `Ctrl+F` 搜索 `MathJax` ，翻到最后一个，把下图中用绿色框选出来的部分改为 `//cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js` 即可。
> 
> ![image](https://camo.githubusercontent.com/2140d2159e2de1f03641bf3ddad4b7277798ec0cec6f1ba5d36eba737d94b503/68747470733a2f2f63646e2e75312e68756c757869612e636f6d2f67342f4d30332f37302f34332f72424141646d4c764b6261416145493041415031375435707178633734312e706e67)

谢谢老哥的解答，但是我这边还是这样😂，不知道为啥

**Comment by CroMarmot** [comment]
我这边也是正常的, 不过我遇到过不少类似情况, 可能是 `_`,`*` 被解析的时候识别成了 markdown 的倾斜语法, 一般来说可能可以通过 加一些空格解决, 你可以试试 `$\alpha_ t=f_ {\alpha}(x_ t)$`

这个应该和theme本身关系不大, 应该是markdown+mathjax解析的问题,其它theme也会遇到

**Comment by bugcat9** [comment]
> 我这边也是正常的, 不过我遇到过不少类似情况, 可能是 `_`,`*` 被解析的时候识别成了 markdown 的倾斜语法, 一般来说可能可以通过 加一些空格解决, 你可以试试 `$\alpha_ t=f_ {\alpha}(x_ t)$`
> 
> 这个应该和theme本身关系不大, 应该是markdown+mathjax解析的问题,其它theme也会遇到

诶，还真是这样，不过我加空格_还是解析成了倾斜，目前似乎没有找到很优雅的解决方法。但还是谢谢老哥的解答，让我知道了原因😁

**Comment by CroMarmot** [comment]
可能不只需要出问题的`_` 加空格, 前面没出问题的`_`可能也需要后面加空格, 

目前也没有优雅的办法, 有的时候比如多行公式`\\` 还需要写`\\\\`, 我就一般就多敲几个, 感觉还是markdown工具支持不太行吧

不知道你用的是哪个版本,看[新版本文档](https://theme-next.js.org/docs/third-party-services/math-equations.html) 是可以用katex, 也可以用mathjax , 我目前用的还是mathjax, 没有试过katex

文档里说 可能需要替换的

```diff
-$\epsilon_0$
+$\epsilon\_0$
-\begin{eqnarray*}
+\begin{eqnarray\*}
-\\
+\\\\
```

你可以试试加个`\` 转义呢?

**Comment by bugcat9** [comment]
> 可能不只需要出问题的`_` 加空格, 前面没出问题的`_`可能也需要后面加空格,
> 
> 目前也没有优雅的办法, 有的时候比如多行公式`\\` 还需要写`\\\\`, 我就一般就多敲几个, 感觉还是markdown工具支持不太行吧
> 
> 不知道你用的是哪个版本,看[新版本文档](https://theme-next.js.org/docs/third-party-services/math-equations.html) 是可以用katex, 也可以用mathjax , 我目前用的还是mathjax, 没有试过katex
> 
> 文档里说 可能需要替换的
> 
> ```diff
> -$\epsilon_0$
> +$\epsilon\_0$
> -\begin{eqnarray*}
> +\begin{eqnarray\*}
> -\\
> +\\\\
> ```
> 
> 你可以试试加个`\` 转义呢?

新版本文档中推荐使用pandoc，然后我装了一下这个包，但是最后hexo g报错了😥，最近都没啥时间折腾这个了，先把这个加入待定当中，谢谢老哥了。
