### ISSUE TITLE
Next官网主题模板

### ISSUE THREAD

**Issue by Bonjour-Lemonde** [theme-next/hexo-theme-next#1715]
https://theme-next.iissnan.com/使用的主题是免费模板吗？非常喜欢，请指导下来源！感谢！！！

**Comment by stevenjoezhang** [comment]
见 https://github.com/iissnan/theme-next-docs

<blockquote><img src="https://opengraph.githubassets.com/94f8b9c6166e04cfdccff9334d97910c5cce39949fbc597c34eb2b5d11bf1a87/iissnan/theme-next-docs" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/iissnan/theme-next-docs">GitHub - iissnan/theme-next-docs: Documentations for NexT theme</a></strong></div><div>Documentations for NexT theme. Contribute to iissnan/theme-next-docs development by creating an account on GitHub.</div></blockquote>
