### ISSUE TITLE
Conflict between algolia and svg

### ISSUE THREAD

**Issue by pengzhendong** [theme-next/hexo-theme-next#172]
I agree and want to create new issue
 Yes, I was on Hexo Docs page, especially on Templates, Variables, Helpers and Troubleshooting.
 Yes, I was on NexT Documentation Site.
 And yes, I already searched for current issues and this is not help to me.
Expected behavior
When algolia search is enable, I want to use add this share plugin.

Actual behavior
But the svg file can not show. (Same issue for github_banner)
![image](https://user-images.githubusercontent.com/10704539/37444833-e8242522-284e-11e8-8417-d691dfcee1b4.png)

Steps to reproduce the behavior
N/A
N/A
N/A
Link to demo site with this issue: N/A
Link(s) to source code or any usefull link(s): N/A
Hexo Information
hexo: 3.6.0
hexo-cli: 1.1.0
os: Darwin 17.4.0 darwin x64
http_parser: 2.7.0
node: 9.8.0
v8: 6.2.414.46-node.21
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2n
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c
NexT Information
NexT Version:

[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
NexT Scheme:

[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini

**Comment by sli1989** [comment]
Related in [PR](https://github.com/theme-next/hexo-theme-next/pull/119/files#diff-a8164b1286413219a3653b987a7ebcba), need further confirm.

**Comment by sli1989** [comment]
Fixed in [PR](https://github.com/theme-next/hexo-theme-next/pull/173), pull the latest branch after merged. Further question can be raised here.

**Comment by ivan-nginx** [comment]
> Maybe blocky element is related as well.

Maybe... :smirk:

**Comment by ivan-nginx** [comment]
@pengzhendong close it if solved. Thank's!
