### ISSUE TITLE
Add support to disable disqus on specific pages

### ISSUE THREAD

**Issue by codevenkat** [theme-next/hexo-theme-next#178]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

This theme's documentation can not be found anywhere. I don't want disqus on a page, but NexT loads it anyway. Is there something I can do in the front matter to stop this? I tried the old `comments: false` but it does not work anymore. Help needed.

**Comment by sli1989** [comment]
how about 'theme.disqus.enable=false'

**Comment by sli1989** [comment]
@codevenkat any questions? if solved, close the issue.

**Comment by codevenkat** [comment]
Fpr some reason I had to reinstall theme-next for it to work with that. It still shows a blank space where the comments were, but it is not where anymore. Thanks.
