### ISSUE TITLE
after deploy, page is blank and files 404 under lib

### ISSUE THREAD

**Issue by gegenhasi** [theme-next/hexo-theme-next#179]
### Expected behavior 
Local preview is as normal as deploying to github pages

### Actual behavior 
There is no problem with the local preview, but when deploying to git using the hexo d, it is a blank screen.  Files 404 under lib.
![image](https://user-images.githubusercontent.com/37357243/37551816-188a3978-29e3-11e8-92be-91b24526e321.png)

### Node.js and NPM Information

```
node v8.4.0
npm v5.3.0
```

### Package dependencies Information

```

```

#### Hexo version
v6.0.6
#### Hexo Configuration
```

```

### NexT Information

**NexT Version:**

- [x ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

#### NexT Configuration:

```yml

```

**Comment by sli1989** [comment]
It's repo is not supported 5.1.x theme. NexT 5 not supported by me anymore, u know it. So, if u have reproduce steps on this 6.x version, u can create new issue and just like that explain your situation. 

If you want to update from v5.1.x to v6.0.x, read [here](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md).

**Comment by gegenhasi** [comment]
@sli1989  i upgrade my version to  6.0.6 but not solved, can i just modify this issue instead create new issue ???

**Comment by sli1989** [comment]
the way u like. it's all ok.

**Comment by ivan-nginx** [comment]
@gegenhasi please, no need to add ALL configuration if it is standart config. Only changed options need to define in PR, i think.

**Comment by sli1989** [comment]
Check the related [issue](https://github.com/theme-next/hexo-theme-next/issues/37).

**Comment by ivan-nginx** [comment]
@sli1989 yeah, in this issue strange bug what wasn't sovled in 1 case. And ssems it's similar situation.
Anyway, try check #23, #64 or #121.

**Comment by gegenhasi** [comment]
@sli1989  yes,seems like #37. but i don't understand why the files under lib would lost. i try to modify   .gitignore files ,but don't work.

**Comment by sli1989** [comment]
The detail steps to reproduce or the source codes are needed.
Anyway, U can delete all folder and create a new one to rebuilt the hexo-next.

**Comment by ivan-nginx** [comment]
In addition to this and #37 issue i found [this](https://stackoverflow.com/questions/48376742/js-css-file-disappeared-after-hexo-d-next-theme-6-0) question it StackOverflow (i think @MARGI3 posted this).

**Comment by wkq278276130** [comment]
1.  checkout blog/_config.yml    config appId or applicationID
2. checkout have .js   if not  ` git clone https://github.com/theme-next/theme-next-algolia-instant-search  ` to ` next/source/lib/algolia-instant-search `
