### ISSUE TITLE
set scheme in hexopath/source/_data/next.yml is no useful

### ISSUE THREAD

**Issue by locbytes** [theme-next/hexo-theme-next#183]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

The Scheme is Pisces.

### Actual behavior 

The Scheme is Muse.

### Steps to reproduce the behavior 
1. Set `scheme: Pisces` in `hexopath/source/_data/next.yml`
2. Execute `$ hexo clean && hexo generate && hexo server`
3. View the page in Chrome.

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v9.7.1
5.7.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.6.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

#### Hexo version

```
hexo: 3.6.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 9.7.1
v8: 6.2.414.46-node.20
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2n
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c
```

#### Hexo Configuration

```yml
theme: next-6
```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [X] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
none has changed in _config.yml
```

### Other Information 
```yml
theme_config:
  #scheme: Muse
  scheme: Pisces
```

**Comment by ivan-nginx** [comment]
PLease, read [DATA-FILES](https://github.com/theme-next/hexo-theme-next/blob/master/docs/DATA-FILES.md) guide.

**Comment by ivan-nginx** [comment]
@locbytes 5.1.X version with old repo has no support from this year anymore. For now latest version is 6.0.6. See [latest relases here](https://github.com/theme-next/hexo-theme-next/releases).

**Comment by locbytes** [comment]
I have found the reason, I must set the `theme_config:` in hexo _config.yml, if I set it in `hexo/source/_data/next.yml`, it will be no useful.
I think it will help someone has the same problem with me.

**Comment by ivan-nginx** [comment]
In accordiance with [DATA-FILES](https://github.com/theme-next/hexo-theme-next/blob/master/docs/DATA-FILES.md) guide and **[NexT-Way section](https://github.com/theme-next/hexo-theme-next/blob/master/docs/DATA-FILES.md#option-2-next-way)**, no need to set `theme_config` parameter.

**Comment by locbytes** [comment]
Thanks for your patient answers and help!
