### ISSUE TITLE
New theme Gemini is not friendly for ipad

### ISSUE THREAD

**Issue by necan** [theme-next/hexo-theme-next#184]
when use iPad on landscape, theme Gemini cannot fill the whole screen

![](https://i.loli.net/2018/03/18/5aae0672b14a8.png)

but the theme Pisces can
![](https://i.loli.net/2018/03/18/5aae07bc87877.png)

please fix it.

**Comment by sli1989** [comment]
PR #111 add support to manual configure the sidebar width of the Gemini Scheme.

**Comment by Raincal** [comment]
The default $main-desktop width is 75%, you can configure the max_content_width in 
https://github.com/theme-next/hexo-theme-next/blob/1975fd0c95e85abad045c7f1dd2dd67e0e2c09a1/_config.yml#L329
and then change the  $main-desktop like this
https://github.com/Raincal/hexo-theme-next/commit/3ccbd29b000effba0fda18f7fc229245ceba8efd

**Comment by ivan-nginx** [comment]
@necan @sli1989 @Raincal → Fixed and improved in #339 pull. Will be released in NexT 6.4.0.
