### ISSUE TITLE
suggest to modify the mathjax code [need to change CDN to cdn.mathjax.org]

### ISSUE THREAD

**Issue by sli1989** [theme-next/hexo-theme-next#19]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

display inline formula using `hexo-renderer-pandoc` with the mathjax support in the theme's `_config.yml`.

### Actual behavior 

1. using `hexo-renderer-marked` , and  `mathjax:   enable: true` in the theme's `_config.yml`: 
**fail** to display all formula;
1. `mathjax:   enable: true` in the theme's `_config.yml`, and `npm uninstall hexo-renderer-marked --save` and **Remove** `the if(config.template) args.push("--template=" + config.template);` in `hexo\node_modules\hexo-renderer-pandoc\index.js` using `npm install hexo-renderer-pandoc --save` ([the known issue](https://github.com/theme-next/hexo-theme-next/issues/10)): 
**fail** to display all formula;
1.  `mathjax:   enable: true` in the theme's `_config.yml`, and `npm uninstall hexo-renderer-marked --save` and **Remove** `the if(config.template) args.push("--template=" + config.template);` in `index.js` using `npm install hexo-renderer-pandoc --save` , and try to **modify** mathjax in `/themes/next/source/js/custom.js`,  and **add** `<script type="text/javascript" src="/js/custom.js"></script>` in front of `/body` in `/layout/_layout.swig`:
display inline formula successfully.

the modify in `/themes/next/source/js/custom.js` is here, 
**but i don't known how to merge the code in [layout/_third-party/mathjax.swig](https://github.com/theme-next/hexo-theme-next/blob/e12bb0b27e16072eb82baa4c7dda1c41c8de7264/layout/_third-party/mathjax.swig), just a suggestion**

```
//MathJax
window.MathJax = {
    AuthorInit: function () {
      MathJax.Hub.Register.StartupHook("Begin",function () {
        MathJax.Hub.Queue(function() {
      var all = MathJax.Hub.getAllJax(), i;
      for (i=0; i < all.length; i += 1) {
        all[i].SourceElement().parentNode.className += ' has-jax';
      }
    });
      });
    }
  };

window.MathJax = {
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true,
      skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
    }
  };


//  <script type="text/javascript" src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
// jQuery
$.getScript('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML', function()
{
    // script is now loaded and executed.
    // put your dependent JS here.
});
```

* Link(s) to source code 

```
TESTING inline formula： $R{m \times n} = U{m \times m} S{m \times n} V{n \times n}’$，$d_{1}=\frac{\ln(S_{t}/K)  +(r+\sigma^{2}/2)(T-t)}{\sigma\sqrt{T-t}}$。This is an example for $x_mu$ and $y_mu$. This is an example for $x_{mu}$ and $y_{mu}$.
This is an example for $x\_mu$ and $y\_mu$.
```

```
$$
\begin{eqnarray}
\nabla\cdot\vec{E} &=& \frac{\rho}{\epsilon_0} \\
\nabla\cdot\vec{B} &=& 0 \\
\nabla\times\vec{E} &=& -\frac{\partial B}{\partial t} \\
\nabla\times\vec{B} &=& \mu_0\left(\vec{J}+\epsilon_0\frac{\partial E}{\partial t} \right)
\end{eqnarray}
$$
```

```
$$T(n) = \Theta(n) + \sum{i=0}^{n-1}{O({n}{i}^2)}$$
$$T(n) = \Theta(n) + \sum_{i=0}^{n-1}{O({n}_{i}^2)}$$
$$T(n) = \Theta(n) + \sum\_{i=0}^{n-1}{O({n}\_{i}^2)}$$
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[x] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
As i see u sugges 3rd variant to solve this problem, right?
And u write:

> but i don't known how to merge the code in layout/_third-party/mathjax.swig, just a suggestion

So, the simplest way to modify any part of main repo code is:
1. Do fork of main repo to your remote (and local) repo.
2. U do any changes in your forked repo, this changes can be made in Github web-interface directly.
3. After all changes, u create pull request from your remote changesd repo to main repo.

Try it.

**Comment by ivan-nginx** [comment]
So, can u step by step write how and where you do changes? And i'll try to do this.

**Comment by sli1989** [comment]
i will do my best...I'm just a layman in JS.

**Comment by ivan-nginx** [comment]
Ok, can u give the path to `next/source/js/custom.js` file?

**Comment by sli1989** [comment]
@ivan-nginx 

1. `mathjax:   enable: true` in the theme's `_config.yml`, 
1. `npm uninstall hexo-renderer-marked --save`
1. `npm install hexo-renderer-pandoc --save` 
1. **Remove** `the if(config.template) args.push("--template=" + config.template);` in `hexo\node_modules\hexo-renderer-pandoc\index.js` , 
1. **add** mathjax in `/themes/next/source/js/custom.js`:

```
//MathJax
window.MathJax = {
    AuthorInit: function () {
      MathJax.Hub.Register.StartupHook("Begin",function () {
        MathJax.Hub.Queue(function() {
      var all = MathJax.Hub.getAllJax(), i;
      for (i=0; i < all.length; i += 1) {
        all[i].SourceElement().parentNode.className += ' has-jax';
      }
    });
      });
    }
  };

window.MathJax = {
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true,
      skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
    }
  };


//  <script type="text/javascript" src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
// jQuery
$.getScript('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML', function()
{
    // script is now loaded and executed.
    // put your dependent JS here.
});
```

1.  **add** `<script type="text/javascript" src="/js/custom.js"></script>` in front of `/body` in `/layout/_layout.swig`:

**Comment by ivan-nginx** [comment]
Ok, i see now. I just not understand what is `index.js` and `custom.js`. Awaiting for new branch.

**Comment by sli1989** [comment]
i still have no clue and have given up trying it...
haha

**Comment by ivan-nginx** [comment]
Please, try to change in NexT config:
```diff
# MathJax Support
mathjax:
  enable: false
  per_page: false
- cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
+ cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
```
Still need modify `mathjax.swig`?

**Comment by sli1989** [comment]
it works, thank u.

```
# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
```

**Comment by ivan-nginx** [comment]
@sli1989 really? Works in **2 variant** suggested by u, right?

**Comment by sli1989** [comment]
yes, testing in NexT.Muse v6.0.0, there is no need to modify the `next/source/js/custom.js`

**Comment by ivan-nginx** [comment]
So, this issue is solved?

**Comment by sli1989** [comment]
yes, it's done. thank u.

**Comment by ivan-nginx** [comment]
Links on MathJax CDN in config was updated: (be3528fd50596e9c67ac1e3ee57f54cc12f06f49)
```yml
# MathJax Support
mathjax:
  enable: false
  per_page: false
  # For newMathJax CDN (cdnjs.cloudflare.com) with fallback to oldMathJax (cdn.mathjax.org).
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # For direct link to MathJax.js with CloudFlare CDN (cdnjs.cloudflare.com).
  #cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML
  # For automatic detect latest varsion link to MathJax.js and get from CloudFlare.
  #cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
```

**Comment by sli1989** [comment]
😲, suggest to use `cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML` as default, 

[The MathJax CDN hosted at cdn.mathjax.org will be shutting down](https://www.mathjax.org/cdn-shutting-down/) on April 30, 2017.

**Comment by ivan-nginx** [comment]
I suggest:
1. Add `//cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js` as written in docs above.
2. Add local copy of MathJax as 3rd-party `lib` extension. For that need to add separated repo.

**Comment by sli1989** [comment]
it's not working with `//cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js`.

**Comment by ivan-nginx** [comment]
Ok. Well, need to add local libs with separated repos. I'll do it later, after 6.0.1 release, i think.
