### ISSUE TITLE
Failed to load the popup window of local search.

### ISSUE THREAD

**Issue by sundongxu** [theme-next/hexo-theme-next#190]
@iissnan 
Hello, my problem is about the Local Search function on the version 5.x of Next. After I finished all the configuration to the _config.yml in the next repo according to here: https://theme-next.iissnan.com/third-party-services.html#search-system,  and of course enabled the local search function, too, it still failed to load the popup search window just as the underlying image showed, keeping loading....... please help me to solve this problem.
Thanks.

![1](https://user-images.githubusercontent.com/13673539/37585986-f40863ea-2b95-11e8-9b51-19946801ae41.png)

**Comment by sli1989** [comment]
the edge explorer?

**Comment by sundongxu** [comment]
@sli1989 chrome... It did work well before, but recently...just go crashed...

**Comment by sli1989** [comment]
maybe slow network in china..

**Comment by ivan-nginx** [comment]
> maybe slow network in china..

Slow network can't be in v5 but not in v6. MB AdBlock or something, need to see live demo at least.

@sundongxu and pf course reccomended to update from 5 to 6 to bypass all possible bugs and get new features. Docs in [CN](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) and [EN](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) also aviable.

**Comment by sundongxu** [comment]
@ivan-nginx I read the docs you offered about updating and was going to try to update v5 to v6, but there were some customizations that I didn't remember clearly... I don't want any customization for my site to be missing... Any tool recommendation for comparing between the new repo and the old one?

Thanks a lot~

**Comment by ivan-nginx** [comment]
«Beyond Compare» to compare files in localhost.

**Comment by sundongxu** [comment]
it doesn't work well even after I have already updated the Next to v6...Who can help me debug this annoying bug???
![selection_002](https://user-images.githubusercontent.com/13673539/37593641-a6219922-2bad-11e8-990c-0eee58ef46af.png)

**Comment by ivan-nginx** [comment]
This config not from v6. Here is current config:

https://github.com/theme-next/hexo-theme-next/blob/f2a939f76805255d6ae1fd0163bc75d95c7fcd23/_config.yml#L677-L687

**Comment by sundongxu** [comment]
@iissnan @ivan-nginx 
When I click the search button in the top menu, the window keeps loading...and never show up...
![selection_003](https://user-images.githubusercontent.com/13673539/37593741-fd82f6ac-2bad-11e8-98f1-c2eb4c1d519e.png)
![selection_004](https://user-images.githubusercontent.com/13673539/37593746-0719053a-2bae-11e8-8359-c17dd1327650.png)

**Comment by ivan-nginx** [comment]
Give your reproduce steps and all possible links (repo, live demo, etc.)

**Comment by sundongxu** [comment]
@ivan-nginx what material am i supposed to provide to reproduce the bug???Aren't those pictures enough???

**Comment by sundongxu** [comment]
@ivan-nginx 
My site: dongdongdong.me.

**Comment by ivan-nginx** [comment]
> what material am i supposed to provide to reproduce the bug???Aren't those pictures enough???

All your steps during upgrading from 5 to 6.

> My site: dongdongdong.me.

I see. And i see what this is 5.1.3 version.

**Comment by sundongxu** [comment]
@ivan-nginx 
Yes, my site is still using v5.1.3 but I did update and run locally while still got failed.

**Comment by ivan-nginx** [comment]
1. https://github.com/theme-next/hexo-theme-next/issues/190#issuecomment-374185157
2. https://github.com/theme-next/hexo-theme-next/issues/190#issuecomment-374185392
3. https://github.com/theme-next/hexo-theme-next/issues/190#issuecomment-374189809

**Comment by sundongxu** [comment]
@ivan-nginx 
They can't be the reasons why it failed...I think.

**Comment by ivan-nginx** [comment]
Ok, let's go with another variant: can u try to install new latest version 6 release with search, search is works?

It must work, because in other peoples search works fine.

1. Let's look on stargazers,
2. Then look on last man — https://github.com/21sta,
3. then look at he's repo — 21sta.github.io — go to he's site and as we can see current NexT version is 6.0.6 (latetst) and local search works fine.

**Comment by sundongxu** [comment]
Still following these steps???
![selection_005](https://user-images.githubusercontent.com/13673539/37595165-b6f13c3a-2bb2-11e8-992d-b98611190ace.png)

**Comment by ivan-nginx** [comment]
> Ok, let's go with another variant: **can u try to install new latest version 6 release with search, search is works**?

How to install NexT v6 see main [Installation section in readme](https://github.com/theme-next/hexo-theme-next#installation).

**Comment by sundongxu** [comment]
@ivan-nginx 
Hey! I just can't believe! You know what... I uninstall the hexo-generator-searchdb module using cmd below:
$ npm uninstall hexo-generator-searchdb --save

And the search window works!!!
Then I quickly switch to the v5, it still works! 
Oh yeah...
MB it's because I installed hexo-generator-searchdb while I already got the hexo-generator-search... There may exist some confliction between these two module.

**Comment by sundongxu** [comment]
Thank you for being so nice~

**Comment by Raincal** [comment]
@ivan-nginx 
hexo-generator-searchdb was forked from hexo-generator-search
This is a bug in early version of the hexo-generator-search and it has been fixed recently
https://github.com/PaicHyperionDev/hexo-generator-search/issues/30#issuecomment-366582937

**Comment by ivan-nginx** [comment]
@Raincal so, u suggest to update `hexo-generator-searchdb`?

**Comment by Raincal** [comment]
@ivan-nginx Yes

**Comment by ivan-nginx** [comment]
@flashlab can u support this?

**Comment by stevenjoezhang** [comment]
One year has passed, is this bug still there?

**Comment by ivan-nginx** [comment]
Need to try reproduce this. I think bug still exists, but I can't catch him.
