### ISSUE TITLE
Katex css wrong version number

### ISSUE THREAD

**Issue by maboloshi** [theme-next/hexo-theme-next#191]
katex解析器的版本号必须与`katex css`的版本号一致，否则 最终的显示结果会不理想。
在持续构建平台上 可能不能提前获悉katex解析器的版本号，需要手动修正`katex css`的版本号

是否可以根据解析式所用katex解析器的版本 自动设置`_config.yml`中`katex css`的版本号

**Comment by ivan-nginx** [comment]
請用英文寫。

**Comment by AlynxZhou** [comment]
@ivan-nginx Katex parser's version number should be the same as the version number of `katex css` or it won't show as expected.

When using a CI, you may be unable to get the version of katex parser in advance, and you need to edit the version of `katex css` manually.

Can we set the version of `katex css` in `_config.yml` automatically according to ketex parser version used by the parsing formula?

---------

I don't know katex but I think it's impossible...

**Comment by LEAFERx** [comment]
@maboloshi 
Don't understand ur issue.
Set the version u use in config and use it in every post so no need for CI to change version.
I am not familiar with katex too.

**Comment by ivan-nginx** [comment]
Maybe @wafer-li can help with katex.

**Comment by wafer-li** [comment]
@ivan-nginx 
Sorry, I am preparing for the national entrance examination for postgraduate in China.
That's really important for me. 

Maybe you could look for other people to deal with it, or wait until **2018's Xmas** , when the examination is finished.

**Comment by maboloshi** [comment]
What I mean is to automatically get the package `katex` version number  (node_modules/katex/Package.json, version) instead of the version of `katex css`.

`katex css` can use the following method
`cdn.jsdelivr.net/npm/katex/dist/katex.min.css?v=0.9.0`

**Comment by stevenjoezhang** [comment]
建议通过设置Katex的CDN以选用特定的版本
