### ISSUE TITLE
The alignment of the menu is different from before in mist scheme

### ISSUE THREAD

**Issue by xanadus1** [theme-next/hexo-theme-next#193]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
Sorry. English is not my native language; Please excuse typing errors.
### Expected behavior 
**In the previous version, the menu's position is right-align.**
![-2](https://user-images.githubusercontent.com/35560692/37661494-ec2940a4-2c8f-11e8-8f88-c10b885b97ee.jpg)
### Actual behavior 
**In the 6.0.6 version, the menu's position is center-align.**
![-3](https://user-images.githubusercontent.com/35560692/37662628-6c25640c-2c92-11e8-8848-1ca71bc40154.jpg)

--

### Node.js and NPM Information

```
node v8.10.0
npm 5.6.0
```

#### Hexo version

```
hexo: 3.6.0
hexo-cli: 1.1.0
os: Windows_NT 6.3.9600 win32 x64
http_parser: 2.7.0
node: 8.10.0
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by ivan-nginx** [comment]
It's better to center?

**Comment by xanadus1** [comment]
No, I think right-align is better, but it is center-align in v6.0.6.

**Comment by ivan-nginx** [comment]
Why i think like this? Can u explore your vision?

**Comment by xanadus1** [comment]
Sorry, I misunderstood your last sentence. My English is poor. 
I just think something wrong, but it is not. I'm sorry.
And I think if the menu is center-aligned, in my personal opinion it could center for full page,
**like this picture**.
![23](https://user-images.githubusercontent.com/35560692/37670339-fd5840b4-2ca3-11e8-8f32-df82bc69a07e.jpg)
**not like this**,
![12](https://user-images.githubusercontent.com/35560692/37670378-16d93548-2ca4-11e8-9bb6-f54c6a6a2eff.jpg)
It's my personal opinion, I don't know whether it is better or not.

**Best Wishes For You!**

**Comment by stevenjoezhang** [comment]
Refactored in https://github.com/theme-next/hexo-theme-next/pull/702
