### ISSUE TITLE
Can I fold post on index?

### ISSUE THREAD

**Issue by cptbong** [theme-next/hexo-theme-next#196]
I wanna show just title on index page.

**Comment by sli1989** [comment]
For what, [archives page](http://test.saili.science/archives/)?

**Comment by cptbong** [comment]
Can I change home to archives page?

**Comment by sli1989** [comment]
https://github.com/theme-next/hexo-theme-next/blob/52d3c024e2e8cb3f1a538ed780187ec8d944f2ed/_config.yml#L109-L117

maybe change the `home: / || home`. U can also check [here](https://github.com/iissnan/hexo-theme-next/issues/341) to display all posts.

**Comment by cptbong** [comment]
Thank you
