### ISSUE TITLE
Inline code word-break bug?

### ISSUE THREAD

**Issue by lzyroot** [theme-next/hexo-theme-next#197]
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

文章中如果包含上面代码，会显示为下图这样

<img src="https://i.loli.net/2018/03/23/5ab3f32f95c94.png" alt="QQ20180323-021659@2x.png" title="QQ20180323-021659@2x.png" />

**Comment by ivan-nginx** [comment]
請用英文寫。

**Comment by lzyroot** [comment]
If the ruby ​​-e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" code appears in the post

The situation in the picture will appear

<img src="https://i.loli.net/2018/03/23/5ab3f32f95c94.png" alt="QQ20180323-021659@2x.png" title="QQ20180323-021659@2x.png" />

**Comment by ivan-nginx** [comment]
Live demo or *.MD sourse?

**Comment by lzyroot** [comment]
Sent to your email, please check

**Comment by ivan-nginx** [comment]
![image](https://user-images.githubusercontent.com/16944225/37792732-a7cdd8fe-2e1d-11e8-9f87-e846b3eb47e2.png)

**Comment by lzyroot** [comment]
Why is it displayed abnormally in my place?

**Comment by lzyroot** [comment]
Problems with the markdown editor？I use MacDown write

**Comment by ivan-nginx** [comment]
Another question: why it's display normally in my place? :smile: 

Need to create issue with given templates: to define all versions info, reproduce steps, etc. IDK why it's abnormal for u, and yes, it can be in markdown editor.

**Comment by lzyroot** [comment]
OK, I want to try to solve it myself. thank you

**Comment by stevenjoezhang** [comment]
@lzyroot Set `highlight.enable` to `true` in Hexo `_config.yml`

**Comment by stevenjoezhang** [comment]
Please avoid writing too much content in inline code block.
