### ISSUE TITLE
AlgoliaSearchError:   Record  is too big. 

### ISSUE THREAD

**Issue by Chiuhum** [theme-next/hexo-theme-next#199]
```
...\node_modules\hexo-algolia\lib\command.js:85
      throw err;
      ^
AlgoliaSearchError: Record at the position 0 objectID=66b48a62afbaed772ba74ecd57c3e4db77c8d882 is too big size=21329 bytes. Contact us if you need an extended quota
    at success (D:\onedrive\blog\node_modules\algoliasearch\src\AlgoliaSearchCore.js:361:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by sli1989** [comment]
[Known Issues using AlgoliaSearch](https://github.com/theme-next/hexo-theme-next/blob/master/docs/ALGOLIA-SEARCH.md#known-issues)
There seems another way, but i can't figure it out.

**Comment by Chiuhum** [comment]
@sli1989  Well, I know what the problem is. None of them worked, since Algolia removed the content indexing feature for free account.  And here seems to be a solution, but I can't work it out.
[Record is too big错误](https://solf.me/migrate-to-hexo/#Record-is-too-big%E9%94%99%E8%AF%AF)

**Comment by sli1989** [comment]
The method in above link is out of date and unclear, maybe used in lower version. I also tried and failed.
But there are some people using it smoothly...

**Comment by Chiuhum** [comment]
Right, that method gave us a thinking that may be we can find a way to shorter the index.
