### ISSUE TITLE
How to remove black line above header? [you can add/rewrite any styles you want in custom.styl]

### ISSUE THREAD

**Issue by zq-97** [theme-next/hexo-theme-next#20]
电脑还好，但对于Android Chrome，如图，在浏览器地址栏和页面中间的黑线特别违和，请问如何取消之?或者改变颜色让它和标题栏融为一体也好。

![](https://user-images.githubusercontent.com/17429111/34696992-3bea3f9a-f4d1-11e7-9620-78f5c155d5cb.png)

**Comment by ivan-nginx** [comment]
In `source/css/_custom/custom.styl`:
```css
// Custom styles.

.headband { display: none; }
```
P.S. U can add here any customs styles u want, without touch original NexT styles.

***

If issue solved, close it please.

**Comment by zq-97** [comment]
thank you very much, it works perfectly
