### ISSUE TITLE
Want to a new feature.

### ISSUE THREAD

**Issue by xiekeyi98** [theme-next/hexo-theme-next#200]
I want to have a good feature , which is can **fold the code** . ( If user click the button , all the code will be show , reversely , it will not show too many lines.

I looked at the latest features and don't seem to have the support.

And I found someone implement the feature by modify the `themes/next/source/js/src/post-details.js`
( links: http://www.bubuko.com/infodetail-2466336.html **sorry for Chinese** ) 

It sounds a great feature , isn't?

**Comment by ivan-nginx** [comment]
Fold — it's like spoiler? Somewhere i can see example with code folding?

**Comment by sli1989** [comment]
[GitHub collapse in comment](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-collapse-in-comment)

![](https://cloud.githubusercontent.com/assets/136959/16365968/71ebeeac-3bd4-11e6-970f-b7616347e440.gif)

**Comment by ivan-nginx** [comment]
So? Here is plugin [hexo-sliding-spoiler](https://github.com/fletchto99/hexo-sliding-spoiler).
BTW, [same function](https://almostover.ru/2016-01/hexo-theme-next-test/#third-unique-name-1) can be implemented by `tab` tag.

**Comment by xiekeyi98** [comment]
I'm sorry to bother you.

With the help of everyone, the problem has been solved perfectly.

**Comment by xiekeyi98** [comment]
@ivan-nginx  I tested the plugin ..
Ah, Have a good way to make the code highlight?

**Comment by ivan-nginx** [comment]
What u want, i don't understand.

**Comment by sli1989** [comment]
@xiekeyi98 the use of highlight with codeblock can check [this](http://test.saili.science/posts/codeblock-test/).

**Comment by xiekeyi98** [comment]
@sli1989  you mean I should use the codeblock to make the code highlight , and use the other plugins or functions to fold the code like spoiler ?

**Comment by xiekeyi98** [comment]
Simply to say , I want to fold the code like spoiler , and can highlight the code easiliy .( I want to choose the language like markdown . Now some implementation can not choose the language.

**Comment by sli1989** [comment]
they are difference function and not contradictory...
the spoiler plugin doesn't render your code block, something you want to fold, include code block.

**Comment by xiekeyi98** [comment]
@sli1989  Thanks a lot .
I will try to do it .
And hope this features can be protogenesis.

------
And have to say that I am so sorry for my poor English.

**Comment by yannxia** [comment]
@ivan-nginx  i think `spoiler` maybe not a good way, it's best way that  we can add `_config.yml` `codeblock` add a item is 'fold: [true/false]', what do you think?

**Comment by ivan-nginx** [comment]
It's will be something like autospoiler? You want to fold **all** your code blocks by default, if option `fold` will be `true`?

Can u try to use `tabs` tag? It looks something like that:

![image](https://user-images.githubusercontent.com/16944225/42173964-669973c8-7e29-11e8-8276-84008b4cd6dd.png)

***

I just still don't understand what u exactly want. I think your code blocks very big to height and user must a lot of scroll your post, and information became not nice-looking. So, for good give your info from your blog you must economize vertical scroll of current page on maximum and use colorized instruments to design your post to better reading.

**Comment by yannxia** [comment]
@ivan-nginx  you're right, i think it's  good for me,thanks

**Comment by stevenjoezhang** [comment]
@xiekeyi98 @ivan-nginx @sli1989 Use html `<details>` tag https://www.w3schools.com/tags/tag_details.asp
