### ISSUE TITLE
The interface of github.io show different from the local server

### ISSUE THREAD

**Issue by imhuay** [theme-next/hexo-theme-next#201]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The interface of github.io should be same as the local server.

### Actual behavior 
The local I have change scheme to Gemini, and it works correctly.
But when I push it to the github, it still show the Muse style.
You can see NexT.Gemini **v6.0.6**, but it shows Muse style

### Steps to reproduce the behavior 
1. init the hexo and next
2. hexo g & hexo s
3. hexo g & hexo d

* Link to demo site with this issue: https://imhuay.github.io/
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by sli1989** [comment]
Check carefully with [DATA-FILES](https://github.com/theme-next/hexo-theme-next/blob/master/docs/DATA-FILES.md) guide.

**Comment by imhuay** [comment]
Thank U. I move the config to the _data, and it shows correctly.
