### ISSUE TITLE
Submit a Muse theme demo

### ISSUE THREAD

**Issue by webees** [theme-next/hexo-theme-next#206]
There are many minor adjustments and I hope to inspire the optimization of the muse theme.
 
Some of the plug-in adjustments will be submitted to issues, and now I enjoy "next" first

Demo: [webees.net](https://webees.net)

**Comment by ivan-nginx** [comment]
Nice look! I think u can add this settings as new `scheme` and called as something new name. For now there is 4 schemes:

https://github.com/theme-next/hexo-theme-next/blob/ca2554bcfe766a01def2cb723c52a020d94a2060/_config.yml#L135-L139

**Comment by webees** [comment]
Yep, I optimize some code first.

**Comment by webees** [comment]
It is better to separate the configuration files of different schemes

**Comment by ivan-nginx** [comment]
It was question or statement? If second, u can suggest pull request for this.
