### ISSUE TITLE
I have set permalink to be invalid

### ISSUE THREAD

**Issue by wxlost** [theme-next/hexo-theme-next#207]
Hello.
I used this theme for the first time.
I have set permalink to be invalid

![image](https://user-images.githubusercontent.com/19698455/38162378-ae4d8e12-3512-11e8-8b45-08900a06101b.png)

**Comment by wxlost** [comment]
试着使用 permalink: post/:title.html 也不行..访问是
http://IP/2018/01/01/post/:title.html.html

**Comment by sli1989** [comment]
can't get your point...follow the issue template.
Your site's `_config.yml` is needed.

**Comment by wxlost** [comment]
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 迷失的笔记    # 博客名
subtitle: 让我抓到你我就把你嘿嘿嘿   # 副标题
description: 迷失的备忘录  # 站点描述
author: 迷失小白菜  # 作者名
language: zh-CN # 语言设置
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.wxlost.com # 博客所要绑定的域名，没有则不填
root: /
permalink: :year/:month/:day/:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:  # Hexo自带代码高亮插件
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# BlueLake 主题压缩css开关
stylus:
  compress: true

**Comment by songouyang** [comment]
change `permalink` in site's `_config.yml` . For example `permalink: posts/:abbrlink/`, and set abbrlink in `posts` header for example `abbrlink: 43250 `. Finally your post link will be `http://yourip/posts/43250/`. You can refer to my [blog source](https://github.com/songouyang/blog/blob/master/_config.yml#L17-L18) and [post](https://raw.githubusercontent.com/songouyang/blog/master/source/_posts/%E5%91%BD%E4%BB%A4%E8%A1%8C%E7%99%BB%E9%99%86%E6%A0%A1%E5%9B%AD%E7%BD%91.md).

**Comment by wxlost** [comment]
@songouyang 你好.我是想不设置permalink的文章访问是默认格式,.设置了permalink的个别文章则是 域名/permalink.html的格式.,.你这个一改就是全部,,,

**Comment by stevenjoezhang** [comment]
Please read the docs: https://hexo.io/docs/front-matter
