### ISSUE TITLE
【HELP】Why does the [toc] tag appear?

### ISSUE THREAD

**Issue by webees** [theme-next/hexo-theme-next#215]
# display
![_20180405031743](https://user-images.githubusercontent.com/5155291/38329315-1162f558-3880-11e8-8c07-e81bc0292325.png)
![_20180405031831](https://user-images.githubusercontent.com/5155291/38329404-45e7e6b2-3880-11e8-8bde-57bcf7578839.png)

# Source code
![_20180405031814](https://user-images.githubusercontent.com/5155291/38329316-11b3044e-3880-11e8-8729-b7ee82a9a779.png)

# Preview URL
https://webees.net/1522750298.html

# other
It may not be related to the template. So did not provide more information.

**Comment by sli1989** [comment]
Github connot render toc...must be manual or use plugins.

**Comment by ivan-nginx** [comment]
@webees why u added TOC? No need, TOC must added automatically. For example, u add headers:

```md
# Header 1

Some text...

## Header 2

Some another text text...
```

And TOC will added automatically for this headers.

**Comment by webees** [comment]
thank.
