### ISSUE TITLE
"hexo-leancloud-counter-security" plugin: should add some instructions into the guide document. 

### ISSUE THREAD

**Issue by AlanKeene** [theme-next/hexo-theme-next#217]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I install the 'hexo-leancloud-counter-security', and when I run 'hexo d' to deploy, I will get the deploy 'leancloud_counter_security_sync' failure.

I finally find the answer in [https://github.com/theme-next/hexo-leancloud-counter-security](https://github.com/theme-next/hexo-leancloud-counter-security) that:
```
You should build the Leancloud background first to make the counter active.
After that, install this plugin and config it to make the counter safe.
```
That's because before install the `hexo-leancloud-counter-security` plugin, should make the `Counter` active.

But I don't see the instruction in the [https://github.com/theme-next/hexo-theme-next/blob/3dabc1651bbfa9376815e2e561ffb9c42049a3ad/docs/LEANCLOUD-COUNTER-SECURITY.md](https://github.com/theme-next/hexo-theme-next/blob/3dabc1651bbfa9376815e2e561ffb9c42049a3ad/docs/LEANCLOUD-COUNTER-SECURITY.md) (in EN) and  [https://github.com/theme-next/hexo-theme-next/blob/3dabc1651bbfa9376815e2e561ffb9c42049a3ad/docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md](https://github.com/theme-next/hexo-theme-next/blob/3dabc1651bbfa9376815e2e561ffb9c42049a3ad/docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md) (in CN) when I follow the guide documents to install the `hexo-leancloud-counter-security` plugin.
  
### Actual behavior 

so, please add the instructions:
```
You should build the Leancloud background first to make the counter active.
After that, install this plugin and config it to make the counter safe.
```
into the guide documents of:
[https://github.com/theme-next/hexo-theme-next/blob/3dabc1651bbfa9376815e2e561ffb9c42049a3ad/docs/LEANCLOUD-COUNTER-SECURITY.md](https://github.com/theme-next/hexo-theme-next/blob/3dabc1651bbfa9376815e2e561ffb9c42049a3ad/docs/LEANCLOUD-COUNTER-SECURITY.md) (in EN)
[https://github.com/theme-next/hexo-theme-next/blob/3dabc1651bbfa9376815e2e561ffb9c42049a3ad/docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md](https://github.com/theme-next/hexo-theme-next/blob/3dabc1651bbfa9376815e2e561ffb9c42049a3ad/docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md) (in CN) to avoid the user got failure when install the `hexo-leancloud-counter-security` plugin.

And @LEAFERx, please update the instructions into your guide post in [https://leaferx.online/2018/03/16/lc-security-en/](https://leaferx.online/2018/03/16/lc-security-en/) in English, and the [https://leaferx.online/2018/02/11/lc-security/](https://leaferx.online/2018/02/11/lc-security/) in Chinese also.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by sli1989** [comment]
The section before [Deploy web engine to avoid your data being changed illegally](https://github.com/theme-next/hexo-theme-next/blob/3dabc1651bbfa9376815e2e561ffb9c42049a3ad/docs/LEANCLOUD-COUNTER-SECURITY.md#deploy-web-engine-to-avoid-your-data-being-changed-illegally) is the instruction to add `Counter` in `Leancloud`.

**Comment by sli1989** [comment]
@AlanKeene any questions? If solved, close the issue.
