### ISSUE TITLE
The menu item has always been activated even other item selected

### ISSUE THREAD

**Issue by YangAnLin** [theme-next/hexo-theme-next#218]
when i come into homepage, the menu `about` is being activated.
![image](https://user-images.githubusercontent.com/30170561/38417915-cc552dde-39cc-11e8-9de9-e85d1db06099.png)

The live demo: [YangAnLin.github.io](http://yanganlin.com/)

But preview in `localhost:4000`, it works fine.

when i come into homepage
![image](https://user-images.githubusercontent.com/30170561/38417930-e2f82640-39cc-11e8-89fd-3aca27573d8d.png)

**Comment by lloyd-delacroix** [comment]
I'm able to reproduce the same problem on 6.1.0, though for me its on the "categories" link in the navbar. It seems like the list item in public/index.html is being created with the class menu-item-active rather than it being applied dynamically.

<li class="menu-item menu-item-categories menu-item-active">

**Comment by YangAnLin** [comment]
my site yesterday all the time active categories,but today active about, I just't understand ,I user hexo d,run local server ,blog normal operate ,but run github, it's happend this problem

this is bug？

**Comment by ivan-nginx** [comment]
@YangAnLin @lloyd-delacroix i think this is bug produced by this commit: 6f787af30855c34a8f1c1d06124baf57c7459371

As for temp solution try to revert this commit. It's strange what with `hexo d` this bug not appear and only appear with `hexo g` command.

**Comment by YangAnLin** [comment]
think for your help, I finally solve
i user  commit: `6f787af`,not sovle,but i rockback commit:`50d85ea`,sovlue

**Comment by ivan-nginx** [comment]
Fixed in #221 pull.
