### ISSUE TITLE
Change the style of  About Page

### ISSUE THREAD

**Issue by ComplicatedPhenomenon** [theme-next/hexo-theme-next#219]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
 
### Expected behavior 

Since I add a picture in the main body , [link](https://complicatedphenomenon.github.io/about/) . Then I can't clearly see the words. After change the About page style, I hope it can be like the page of categories. [link](https://complicatedphenomenon.github.io/categories/index.html)
### Actual behavior 
It didn't work

### Steps to reproduce the behavior 
Add below  to `themes/next/source/css/_custom/custom.styl`
```
.about-page {
    margin: -80px 0px 60px 0px;
    box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.5);
    background-color: rgb(255, 255, 255);
    padding: 106px 36px 36px 36px;
}
@media (max-width: 767px) {
    .about-page {
        margin: -73px 0px 50px 0px;
        padding: 96px 15px 20px 15px;
    }
}
h2.about-title {
    border-left: none !important;
    margin-left: 0px !important;
    padding-left: 0px !important;
    text-align: center;
    background-image: linear-gradient(90deg, #a166ab 0%, #a166ab 40%, #ef4e7b 45%, #f37055 50%, #ef4e7b 55%, #a166ab 60%, #a166ab 100%);
    background-size: cover;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    user-select: none;
}
```

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): [Blog Backup](https://github.com/ComplicatedPhenomenon/BuildABlogSite)

### Node.js and NPM Information

```
v6.11.4
3.5.2

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.5.0"
  },
  "dependencies": {
    "hexo": "^3.5.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-fs": "^0.2.2",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-migrator-wordpress": "^0.1.2",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.2",
    "hexo-tag-cloud": "^2.0.9",
    "hexo-wordcount": "^3.0.2"
  }
}

```

#### Hexo version

```
hexo: 3.5.0
hexo-cli: 1.0.4
os: Linux 4.13.0-38-generic linux x64
http_parser: 2.7.0
node: 6.11.4
v8: 5.1.281.108
uv: 1.9.1
zlib: 1.2.11
ares: 1.13.0
icu: 57.1
modules: 48
openssl: 1.0.2g

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by sli1989** [comment]
How about like this to add background in all pages.

```
body {
    background:url(https://...jpg);
    background-repeat: no-repeat;
    background-attachment:fixed;
    background-position:50% 50%;
}
```

and use this to change the opacity

```
.main-inner { 
    background: #fff;
	opacity: 0.8;
}
```

**Comment by ComplicatedPhenomenon** [comment]
@sli1989 It will affect the layout of every  page beside `About` page. Not a good idea, I would like to define every pages separately.

**Comment by stevenjoezhang** [comment]
Is the problem solved now?

**Comment by ComplicatedPhenomenon** [comment]
> Is the problem solved now?

Thanks for reminding, It got solved.

**Comment by sli1989** [comment]
Can u share your solutions? 😄

**Comment by ComplicatedPhenomenon** [comment]
> Can u share your solutions? 😄

Sorry, strictly speaking, I avoid that problem, I give up the initial implementation. So I can offer no useful information. That what I mean it got solved. 😅
