### ISSUE TITLE
fatal: Pathspec is in submodule Failed to add submodule

### ISSUE THREAD

**Issue by willin** [theme-next/hexo-theme-next#220]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

travis-ci needs to add theme/plugins as submodules.

### Actual behavior 

```bash
~ git submodule add -f https://github.com/theme-next/hexo-theme-next themes/next
Cloning into '~/site/themes/next'...
remote: Counting objects: 2932, done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 2932 (delta 39), reused 70 (delta 37), pack-reused 2840
Receiving objects: 100% (2932/2932), 1.12 MiB | 436.00 KiB/s, done.
Resolving deltas: 100% (1823/1823), done.
 ~ git submodule add -f https://github.com/theme-next/theme-next-pace themes/next/source/lib/pace
Cloning into '~/site/themes/next/source/lib/pace'...
remote: Counting objects: 21, done.
remote: Total 21 (delta 0), reused 0 (delta 0), pack-reused 21
Unpacking objects: 100% (21/21), done.
fatal: Pathspec 'themes/next/source/lib/pace' is in submodule 'themes/next'
Failed to add submodule 'themes/next/source/lib/pace'
```

### Node.js and NPM Information

```
v9.8.0
5.8.0
```

### Package dependencies Information

```
{
  "name": "blog-willin-wang",
  "version": "3.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.0"
  },
  "scripts": {
    "start": "./deploy-ghpages.sh"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^0.3.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json": "github:52cik/hexo-generator-json",
    "hexo-generator-search": "^2.1.1",
    "hexo-generator-searchdb": "^1.0.7",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.3.2",
    "hexo-wordcount": "^3.0.2"
  }
}
```

#### Hexo version

```
hexo: 3.7.0
hexo-cli: 1.1.0
os: Darwin 17.5.0 darwin x64
http_parser: 2.7.0
node: 9.8.0
v8: 6.2.414.46-node.21
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2n
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c
```

#### Hexo Configuration

```yml
# normal
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml
# none
```

### Other Information 

https://github.com/theme-next/theme-next-pace

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/56820076-pathspec?utm_campaign=plugin&utm_content=tracker%2F83013353&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F83013353&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by sli1989** [comment]
Did you remove the submodule before? Maybe caused by unclear remove action.

```
$ rm ./gitmodules
$ rm -rf themes/next
$ vim config # delete submodule information
$ rm -rf .git/modules/themes/next
$ git rm --cached themes/next
```

**Comment by willin** [comment]
run this first:

```bash
git submodule update --init --recursive
```

then add submodules.

**Comment by Richard-Cao** [comment]
still wrong...
