### ISSUE TITLE
suggestion: add copy to clipboard feature to the code blocks

### ISSUE THREAD

**Issue by jdhao** [theme-next/hexo-theme-next#222]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

It would be great if you can add the feature 'copy to clipboard' for the code block in the generated html post, something like what is discussed [here](https://github.com/BoostIO/Boostnote/issues/582). Right now, we have to manually select all the content in the code block and copy it, which is kind of clumsy. 

Thanks for reading 😄

**Comment by ivan-nginx** [comment]
Request for this feature already [added in NexT 7.0 Roadmap](https://github.com/theme-next/hexo-theme-next/issues/67).
