### ISSUE TITLE
Logo Font not Loaded Correctly

### ISSUE THREAD

**Issue by allenfrostline** [theme-next/hexo-theme-next#237]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

This is what's shown after `hexo d -g`.

<img width="537" alt="screen shot 2018-04-16 at 11 49 53 am" src="https://user-images.githubusercontent.com/24261329/38802338-79a6166e-416c-11e8-81d6-a30c407728fb.png">

### Actual behavior 

This is what's shown after `hexo s -g`.

<img width="495" alt="screen shot 2018-04-16 at 11 49 58 am" src="https://user-images.githubusercontent.com/24261329/38802350-80532b3c-416c-11e8-9e5e-18e10eb1ea2a.png">

### Steps to reproduce the behavior 
1. Update npm and hexo.
2. Use the most recent master branch of Next.
3. Use configuration of fonts as below (comments skipped), `hexo clean` and then `hexo s -g`/`hexo d -g`:

```{css}
font:
  enable: true
  host: //fonts.googleapis.com
  global:
    external: true
    family: Montserrat
    size:
  headings:
    external: true
    family: Palatino
    size:
  posts:
    external: true
    family:
  logo:
    external: true
    family: Amatic SC
    size:
  codes:
    external: true
    family: Inconsolata
    size: 14
```

* Link to demo site with this issue: [allenfrotline.com](http://www.allenfrostline.com)
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v9.11.1
5.8.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.7.1",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Darwin 17.5.0 darwin x64
http_parser: 2.8.0
node: 9.11.1
v8: 6.2.414.46-node.23
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 3
openssl: 1.0.2o
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
```

#### Other Information

Not sure if it's a bug or something related to Google fonts' api. If it's the latter and it's too unstable to work as expected, then I suppose using local fonts or other font apis would be a necessity for NexT. (BTW, I'm not located in China.)

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/hexo-theme-next/pull/1007
