### ISSUE TITLE
how prevent text expand ['text-align: initial' in custom.styl]

### ISSUE THREAD

**Issue by zq-97** [theme-next/hexo-theme-next#24]
![image](https://user-images.githubusercontent.com/17429111/34838193-8505405c-f6fd-11e7-8b0a-7cb616b5cff1.png)
In the picture, a line of Chinese characters are arranged with more space between each other because it is followed with a URL, my question is how to prevent this it.

**Comment by ivan-nginx** [comment]
![image](https://user-images.githubusercontent.com/16944225/34838424-12c1b7ac-f70f-11e7-9d02-e870239859ba.png)
