### ISSUE TITLE
I hope to have comment function， i use livere, but nothing appears

### ISSUE THREAD

**Issue by blacklisten** [theme-next/hexo-theme-next#241]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I hope to have comment function， i use livere, 
### Actual behavior 
![image](https://user-images.githubusercontent.com/26319882/38923590-87cf5d6e-432d-11e8-8ae8-e428a71c96c0.png)
but nothing appears

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
this is my blog http://blacklisten.cn
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

![image](https://user-images.githubusercontent.com/26319882/38923818-fe295212-432d-11e8-8df4-1c09893f5bc3.png)

### Package dependencies Information

![image](https://user-images.githubusercontent.com/26319882/38923772-e6b7ac8c-432d-11e8-920a-d95690206d62.png)

#### Hexo version

![image](https://user-images.githubusercontent.com/26319882/38923830-079ba034-432e-11e8-8ed8-ca6b7041c921.png)

#### Hexo Configuration

![image](https://user-images.githubusercontent.com/26319882/38923514-51f1a8b4-432d-11e8-909f-0f0077715ed1.png)
![image](https://user-images.githubusercontent.com/26319882/38923561-71490298-432d-11e8-811f-306bacca26c9.png)
![image](https://user-images.githubusercontent.com/26319882/38923569-785628d6-432d-11e8-9da4-ca29e7f0f690.png)

 Actual behavior
![image](https://user-images.githubusercontent.com/26319882/38923590-87cf5d6e-432d-11e8-8ae8-e428a71c96c0.png)

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [X] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by sli1989** [comment]
Need agent perhaps in china.

**Comment by maple3142** [comment]
![](https://i.imgur.com/RdfpiCO.png)
It works for me, perhaps it is blocked in China gfw.

**Comment by blacklisten** [comment]
@maple3142 oh  it is bad。  Is there any way to deal with it?

**Comment by maple3142** [comment]
@blacklisten Use other service except disqus?

**Comment by blacklisten** [comment]
@maple3142 Can't visit several other disqus in China。It seems that I need to get a vpn。But this is always inconvenient，It's terrible。 thanks，I try other ways， github issues seems to be possible

**Comment by blacklisten** [comment]
@maple3142 i use disqus and valine , but  nothing appears 。 Is it wrong with my usage?
![image](https://user-images.githubusercontent.com/26319882/38928563-cf974c16-433b-11e8-834c-341129ee95cd.png)
![image](https://user-images.githubusercontent.com/26319882/38928588-dffa0918-433b-11e8-8f3c-2d6ffc340959.png)
![image](https://user-images.githubusercontent.com/26319882/38928727-9acc4878-433c-11e8-8f01-dca00f5de92a.png)
![image](https://user-images.githubusercontent.com/26319882/38928774-d98422f2-433c-11e8-964b-18c075cac0ea.png)

why? Who can tell me？

**Comment by sli1989** [comment]
set `disqus.enable= false` and `valine.enable= true`

**Comment by blacklisten** [comment]
@sli1989 thanks  i try

**Comment by sli1989** [comment]
Only one comment system can be used. disqus and livere_uid (sometime) are blocked in china.

**Comment by blacklisten** [comment]
https://notes.wanghao.work/  
But this did not， Is it because of the issue of the version? @sli1989 
This used livere

**Comment by sli1989** [comment]
Maybe U didn't close the disqus.

**Comment by blacklisten** [comment]
what? I closed the valine and opened the livere， Then it's ok。 it is magical.  @sli1989

**Comment by blacklisten** [comment]
@sli1989 Most likely that is the reason  thanks very much

**Comment by blacklisten** [comment]
you are right, livere are blocked in china. It is dead again @sli1989 
Maybe I should use valine
