### ISSUE TITLE
文章阅读次数问题

### ISSUE THREAD

**Issue by noodles1995** [theme-next/hexo-theme-next#246]
我加了文章阅读次数之后，发现一个文章地下出现了两个阅读次数，有一个是光显示“阅读次数：”；然后再出来一个阅读次数就是正常的了；请问你们发现这个问题了吗？是什么导致的

**Comment by LEAFERx** [comment]
Please write in English and follow the issue template.
Give us more detailed information please, like hexo version, NexT version, screenshots, etc.

**Comment by noodles1995** [comment]
My Hexo version is 3.7.1 and Next is 6.2.0.
I added the number of articles to read. But It appears twice. one right one wrong


![1](https://user-images.githubusercontent.com/21075238/38999584-bd49f45c-4424-11e8-8e39-5f6660c46692.png)

**Comment by noodles1995** [comment]
@LEAFERx  thanks

**Comment by LEAFERx** [comment]
It seems like you enabled two different counter: leancloud and busuanzi.
The leancloud counter is malfunctioning maybe because you didn't set it up correctly.

**Comment by LEAFERx** [comment]
see instructions here to set up leancloud counter: https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
or you can just use busuanzi counter.
close this issue if your problem is solved.

**Comment by noodles1995** [comment]
@LEAFERx  thanks
