### ISSUE TITLE
The article reads the record question

### ISSUE THREAD

**Issue by noodles1995** [theme-next/hexo-theme-next#247]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I wang to add Reading quantity record for article 

### Actual behavior 
I operate according to the document.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```
3.7.1
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X ] Latest Release version
- [] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X ] Gemini

#### NexT Configuration:

```yml

```

### Other
![1](https://user-images.githubusercontent.com/21075238/39000477-bb4e4692-4426-11e8-8457-31286834b387.png)

**Comment by LEAFERx** [comment]
Why you create another issue? #246 doesn't solve your problem?
