### ISSUE TITLE
Not load mathjax per page 

### ISSUE THREAD

**Issue by icecory** [theme-next/hexo-theme-next#257]
https://github.com/theme-next/hexo-theme-next/blob/1e8670bed2b4c382e8a0bc5fa8f02fe5044995ed/layout/_third-party/math/index.swig#L13
i think this line should be
 {% if  theme.math.per_page or (is_index_has_math or page.mathjax) %}

**Comment by ivan-nginx** [comment]
U suggest not load MJ per peg by default?

https://github.com/theme-next/hexo-theme-next/blob/1e8670bed2b4c382e8a0bc5fa8f02fe5044995ed/_config.yml#L423-L430

**Comment by sli1989** [comment]
We had discussed [before](https://github.com/theme-next/hexo-theme-next/pull/66#issuecomment-359358370). 
And I prefer to change too.
He seems busy on exam this year.

**Comment by sli1989** [comment]
I think it can be done just reverting some logic, but may result in breaking change (can't be compatible).

**Comment by ivan-nginx** [comment]
It's will be breaking change if we change here anything. So, to prevent confuse users rename this option on more comfortable value will be best.

**Comment by bitwater1997** [comment]
sorry, my next version is a little old, not have this comment , 
   # Default(true) will load mathjax/katex script on demand 
   # That is it only render those page who has 'mathjax: true' in Front Matter. 
   # If you set it to false, it will load mathjax/katex srcipt EVERY PAGE. 
so i think per_page is meaning load every page , so i set this false,
my mathjax cdn is too slow ,mathjax.js also too large( sometimes loading 7-8s ) , making loading totally  slow.

**Comment by oracleyue** [comment]
a bug for me:

If I set `per_page` to `true`, the `hexo-math` (using MathJAX) fails to show equations (it shows the latex source.)

**Comment by greedyboy** [comment]
I think rename `per_page` is usefull, such as `per_page_manual_control`,`per_page_on_deand`

**Comment by oracleyue** [comment]
@StoneMa Ah, I get the meaning of per_page, thanks! To avoid the legacy users, alternatively, you may clarify it in the comments. For example, “when per page is set to true, you need to use mathjax:true in each md to enable mathjax.” Something like this. FYI.

**Comment by oracleyue** [comment]
It already had such comments. Excuse me. I will just upgrade my next.

**Comment by xu-song** [comment]
Maybe we can set default value as `false`, to make sure it works by default.

```yml
per_page: false
```

**Comment by panqiincs** [comment]
Just my opinion, the post file should be independent from the theme, if not, once the theme changes, the post file should be modified too. 

So, is there a mechanism that can detect equations in the post? Can it be implemented in NexT not Hexo?

**Comment by stevenjoezhang** [comment]
So, is there any good way to judge whether there is a math formula in the page? `per_page` is really a a misleading option, and `math: true` in front matter is not cool

**Comment by ivan-nginx** [comment]
Need to ask someone who often work math. @sli1989?

**Comment by sli1989** [comment]
yeah, I talked about this last year, and I prefer to change the logic too.
Doing this introduces the breaking change, so this section remain the status quo without necessarily command.

**Comment by stevenjoezhang** [comment]
Two different solutions:
- Server side rendering: https://github.com/stevenjoezhang/hexo-filter-mathjax
- Automatically detect math formulae in the page, use regex to match `$` `$$` `\(` etc.

**Comment by stevenjoezhang** [comment]
My opinion is to keep it as is. Regular expressions are not always accurate (depending on the renderer).
`hexo-filter-mathjax` plugin added to awesome-next list.
