### ISSUE TITLE
Why my mathjax can not display correctly ? 

### ISSUE THREAD

**Issue by xiekeyi98** [theme-next/hexo-theme-next#261]
Hi , sorry to bother everyone .

I have something wrong in my blog , and can not search any help . Therefore , I have to ask someone for help and a lot thanks to you .

In my blog , I wrote some formulas.
And one is work correctly , another is not .

Uncorrectly : 
In editor: 
![image](https://user-images.githubusercontent.com/7782671/39300219-93254128-497d-11e8-9790-8be804295013.png)
In blog: 
![image](https://user-images.githubusercontent.com/7782671/39300271-b82d72ec-497d-11e8-9394-484dd9874ab6.png)

Correctly :
In editor : 
![image](https://user-images.githubusercontent.com/7782671/39300290-c2c95afe-497d-11e8-9433-fa80cb73163e.png)

In blog : 
![image](https://user-images.githubusercontent.com/7782671/39300294-c5afe49a-497d-11e8-92e7-c2232643aa17.png)

Anyone can help me ?

I am very appreciate  for you help .

**Comment by sli1989** [comment]
which hexo render tool do u use ?

**Comment by ivan-nginx** [comment]
Could you please provide the following information?

* Node.js and NPM version ($`node -v && npm -v`)?
* Hexo version ($`hexo -v`)?
* Your site package dependencies ($`cat package.json`)?

**Comment by xiekeyi98** [comment]
1. 
![image](https://user-images.githubusercontent.com/7782671/39306863-dd499748-4993-11e8-9a54-bc90644eb293.png)
2.
![image](https://user-images.githubusercontent.com/7782671/39306865-e175614e-4993-11e8-89b7-3e59b69c424d.png)
3.
![image](https://user-images.githubusercontent.com/7782671/39306877-f0ebe1a2-4993-11e8-8c3d-8b4006da4a52.png)

@ivan-nginx  @sli1989 
A lot thanks to you .
At first , I doubt that I use wrong Latex grammar.

**Comment by xiekeyi98** [comment]
![image](https://user-images.githubusercontent.com/7782671/39309775-6383569e-499b-11e8-9ad7-fde476c646fe.png)
![image](https://user-images.githubusercontent.com/7782671/39309780-653c7a6a-499b-11e8-8d76-1ee45f9431b5.png)

I found if I use the "\" to   transferred meaning , then everything are ok .
( Swap them positions is can't work well ).

If I have to transfer meanning , why another  which not transferred meaning  is work well ?

**Comment by jdhao** [comment]
@xiekeyi98 , apparently it has something to do with your renderer. See [here](https://jdhao.github.io/2017/10/06/hexo-markdown-latex-equation/) for an explanation.  A solution might be:
1. Uninstall `hexo-renderer-marked`
2. install [`hexo-renderer-pandoc`](https://github.com/wzpan/hexo-renderer-pandoc)

**Comment by xiekeyi98** [comment]
@jdhao
Cool! 
You have solved my problem perfectly! Thank you very much .
