### ISSUE TITLE
The feature of symbols_count_time doesn't work for me ?

### ISSUE THREAD

**Issue by wenkanglin** [theme-next/hexo-theme-next#268]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

https://github.com/theme-next/hexo-theme-next/issues/86#issuecomment-360057421

### Actual behavior 

nothing has shown at blog footer

### Steps to reproduce the behavior 
1. install `hexo-symbols-count-time`
2. add config of `symbols_count_time` at my blog root's `_config.yml`

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
E:\Workspaces\wenkanglin.github.io>node -v
v8.11.1

E:\Workspaces\wenkanglin.github.io>npm -v
5.6.0

E:\Workspaces\wenkanglin.github.io>
```

### Package dependencies Information

```json
"hexo": {
    "version": "3.7.1"
  },
"dependencies": {
    "hexo": "^3.2.0",
    "hexo-algolia": "^1.2.5",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.3.1",
    "hexo-symbols-count-time": "^0.4.2"
  }
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.14393 win32 x64
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

```yml
# ...
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: true
  awl: 4
  wpm: 275
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by ivan-nginx** [comment]
> nothing has shown at blog footer

Please, read it carefully and try to reproduce: https://github.com/theme-next/hexo-symbols-count-time#installation

**Comment by wenkanglin** [comment]
What's mean? I has followed the installation of `hexo-symbols-count-time` and carefully config it at root `_config.yml`. Is there anything missing for me?

**Comment by sli1989** [comment]
Need to set theme `_config.yml` too.

**Comment by wenkanglin** [comment]
I'm sure. In root `config.yml`, it has enabled these fields

**Comment by sli1989** [comment]
So complete the section `Steps to reproduce the behavior`, and maybe provide the links of  your live demo and config file.

**Comment by wenkanglin** [comment]
### Reproduce

* `hexo init `hexo-site`
* `yarn add hexo-symbols-count-time`
* add `symbols_count_time` config to root `_config.yml` like below
* `hexo serve`, open `localhost:4000`

```yml
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
```

you can look my config at https://github.com/wenkanglin/wenkanglin.github.io/blob/blog/_config.yml, this is my hexo blog config

**Comment by sli1989** [comment]
https://github.com/wenkanglin/wenkanglin.github.io/blob/a6026b3362adcb360f57850be2bbc69b2030c275/_config.yml#L98-L103

In root `_config.yml`, it should be

```
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
```

So, did you modify them?

**Comment by wenkanglin** [comment]
Get it. This is my fault and thx @ivan-nginx @sli1989
