### ISSUE TITLE
[KaTeX] Support for copying tex?

### ISSUE THREAD

**Issue by nanpi** [theme-next/hexo-theme-next#269]
This feature is very important for copying formula in html,  but this extension  [copy-tex](https://github.com/Khan/KaTeX/tree/master/contrib/copy-tex) isn't part of KaTeX proper, related js scripts should be separately included in the page. Any plan to support [copy-tex](https://github.com/Khan/KaTeX/tree/master/contrib/copy-tex) in KaTeX (by default)?

**Comment by stevenjoezhang** [comment]
Added support for copy-tex in #543
