### ISSUE TITLE
Optimize the loading of comment counter

### ISSUE THREAD

**Issue by icecory** [theme-next/hexo-theme-next#271]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

on my blog ,comment limit loading rate of sit, that maybe also for many users.
although some comment plug-in not block the main thread on page showing, it still load and a loading icon show on chrome status bar. others plug-in even block the page showing.
i used gitment,youyan,changyan,LiveRe , now i used valine,
1. comment counter default loading on homepage.
i think there should be a option to control the comment counter plug-in in homepage also postpage.
if i set show 5 post in homepage , there will be 10 http requests, and cdn won't work on it;
![screenshot from 2018-05-04 12-24-57](https://user-images.githubusercontent.com/23610405/39613060-35fc67ae-4f97-11e8-8f88-41aa142ed8f6.png)

2. some js file url should write in _config.yml such as
https://github.com/theme-next/hexo-theme-next/blob/d4475e5d99f3fe04ed450e52600d3ab1ae0425bb/layout/_third-party/comments/valine.swig#L1-L3
https://github.com/theme-next/hexo-theme-next/blob/d4475e5d99f3fe04ed450e52600d3ab1ae0425bb/layout/_third-party/analytics/lean-analytics.swig#L3-L5
cdn1.lncld.net is really slow

**Comment by stevenjoezhang** [comment]
For the second question, maybe we can use jsdelivr CDN:
//cdn.jsdelivr.net/npm/leancloud-storage@3.11.0/dist/av-min.js
