### ISSUE TITLE
How to configure the theme with a CI tool using HEXO's dataFiles configuration, such as next. Yml?

### ISSUE THREAD

**Issue by keees** [theme-next/hexo-theme-next#273]
### I agree and want to create new issue 

- [ X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

auto update
### Actual behavior 

Manually edit each time, then upgrade.
### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [X ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by keees** [comment]
https://github.com/iissnan/hexo-theme-next/issues/328

**Comment by ivan-nginx** [comment]
You need to read Data Files guide on [EN](https://github.com/theme-next/hexo-theme-next/blob/master/docs/DATA-FILES.md) or [CN](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/DATA-FILES.md) languages.

**Comment by sli1989** [comment]
U mean travis CI or gitlab CI?

**Comment by fattypiggy** [comment]
@sli1989 I want to create another repo for src files, and myname.github.io for the generated files, so I need a CI such as Travis. And now I have a problem that CI works well, but the generated files are EMPTY, what should I do to solve that? I found that next theme is not in the themes/ folder.
