### ISSUE TITLE
In NexT _config.yml:  copycode: true.Can you set up a prompt for the success of the copy?

### ISSUE THREAD

**Issue by aixiu** [theme-next/hexo-theme-next#276]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml

```

### Other Information 
Replace the copy with a copy
![copy](https://user-images.githubusercontent.com/8064012/39673954-8b275f2c-5177-11e8-9754-0a9ebfb33bbb.png)

**Comment by maple3142** [comment]
1. Hover on code block and show **Copy** button.
2. Click copy, and change button text to **Copied!**
3. Mouse leave the code block and the button disappear.
4. Same as **Step 1**

Is this you wants?

**Comment by maple3142** [comment]
But add this need a breaking change.
Because current config:
```yaml
codeblock:
  copy_button: true
```
To add this need to add `codeblock.copy_button.enable` and `codeblock.copy_button.success_message`

**Comment by maple3142** [comment]
pull #282 
Demo: https://blog.maple3142.net/2018/05/05/how-to-download-youtube-video/

**Comment by aixiu** [comment]
@maple3142 good jb.
