### ISSUE TITLE
打赏设置能否再智能点

### ISSUE THREAD

**Issue by znmlr** [theme-next/hexo-theme-next#278]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
> 仅仅是建议，而不是bug

目前打赏设置仅仅是一个开关，而实际情况比较复杂，很多作者既会发布原创文章，也会转载别人的文章，建议提供4个设置：  
- 完全关闭
- 开放，但是所有文章默认关闭，需要在文章顶部手动设置reward: true来开启
- 开放，所有文章默认开启，如果有需要则在文章顶部手动设置reward: false来关闭  

后面两种设置，分别是对应原创比例少的作者和原创比例多的作者
### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/issues/280, fixed in https://github.com/theme-next/hexo-theme-next/pull/465
