### ISSUE TITLE
Please let the reward be more intelligent

### ISSUE THREAD

**Issue by znmlr** [theme-next/hexo-theme-next#280]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
> This is just a suggestion, not a bug.  

At present, the reward setting is just a switch, and the actual situation is more complex. Many authors will publish original articles and others' articles. It is recommended to provide 3 settings:

- Completely shut down
- Open, but all articles are closed by default. ``reward: true`` is manually set up at the top of the article to open it.
- Open, all articles are opened by default. ``reward: false`` is manually set up at the top of the article to close it.

The latter two settings are those with fewer original ratios and more original authors.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by ivan-nginx** [comment]
Fixed in #465.
