### ISSUE TITLE
Unhandled rejection TypeError: path.substring is not a function

### ISSUE THREAD

**Issue by FannyChung** [theme-next/hexo-theme-next#290]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).页面404了
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
hexo s打不开页面
```
Unhandled rejection TypeError: path.substring is not a function
    at Object.urlForHelper (。。。\hexo\node_modules\hexo\lib\plugins\helper\url_for.js:7:31)
    at wrapper (。。。\hexo\node_modules\lodash\lodash.js:4949:19)
```
用landscape原生主题没问题。
### Node.js and NPM Information

```
v8.11.1
5.6.0
```
### 重现步骤
hexo init，clone next主题，把原来保存的source文件夹拷贝过来，设置hexo的config文件的主题，hexo s。

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-server": "^0.2.0"
  }
}
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

没有修改过

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [X] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

没有修改过

**Comment by sli1989** [comment]
maybe caused by the unusual update. How about **delete** the local folds and new init?

**Comment by sli1989** [comment]
Can provide the living link of your source folder?

**Comment by wt1098078873** [comment]
@FannyChung I meet same error. Are you use `next.yml`? I find many value's field has bean changed between `V5+` and `V6`. For example: `since`,`favicon`. You can compare your files careful and find the difference.

**Comment by FannyChung** [comment]
@wt1098078873 Thank you! But I use a new hexo fold, just copy my source fold(including my .md and pictures) , I didn't change `yml` file.

**Comment by FannyChung** [comment]
@sli1989  here's my source folder. https://1drv.ms/f/s!AmqC5vM1N-zd-QQDTFMgDqBJGc1T

**Comment by sli1989** [comment]
DId u use next.yml in v5 without download the v6 files?
I saw u mixed the configuration. How about [use v6](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.3.0) separately and set the next.yml comparing the [next v6 yml](https://github.com/theme-next/hexo-theme-next/blob/master/_config.yml) with your custom setting before?

**Comment by stevenjoezhang** [comment]
I believe this issue is caused by a malformed `_config.yml`.
