### ISSUE TITLE
使用tomorrow-theme高亮代码,highlight-selection不起作用

### ISSUE THREAD

**Issue by chenfengfeng** [theme-next/hexo-theme-next#299]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
能够使用highlight-selection的颜色

### Actual behavior 
全局都是next的选择颜色

### Steps to reproduce the behavior 
安装next主题,版本最新
highlight_theme: normal

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by CnWenquan** [comment]
me to

**Comment by CnWenquan** [comment]
me too

**Comment by ivan-nginx** [comment]
Could you please provide the following information?

* Node.js and NPM version ($`node -v && npm -v`)?
* Hexo version ($`hexo -v`)?
* Your site package dependencies ($`cat package.json`)?

***

Screens? Live demo?

**Comment by stevenjoezhang** [comment]
Seems `$highlight-selection` in `source/css/_common/components/highlight/theme.styl` is ignored.

**Comment by stevenjoezhang** [comment]
实现起来有点麻烦。选择区域可以使用highlight-selection的颜色，但是文字会失去原来的高亮颜色。

**Comment by stevenjoezhang** [comment]
Fixed in #965
