### ISSUE TITLE
Questions about documents

### ISSUE THREAD

**Issue by hl262** [theme-next/hexo-theme-next#301]
Do maintainers provide a full document for reference on 6.xbecause some configurations and 5.x have changed

**Comment by sli1989** [comment]
yes, sorry for the inconvenient.
The main website is under construction with our best, and will be online as soon as possible.
You can take a look for [temp doc](https://github.com/theme-next/hexo-theme-next/tree/master/docs).

**Comment by hl262** [comment]
OK, and thank you for continuing to maintain this project. It's not necessary to waste too much time on setting the theme.^_^

**Comment by ivan-nginx** [comment]
Site already done. So, issue is solved.
