### ISSUE TITLE
How to get the theme under the Windows system？

### ISSUE THREAD

**Issue by championheng** [theme-next/hexo-theme-next#304]
**I tried to use the following commands under the Windows system:**
```
curl -s https://api.github.com/repos/theme-next/hexo-theme-next/releases/latest | grep tarball_url | cut -d '"' -f 4 | wget -i - -O- | tar -zx -C themes/next --strip-components=1
```

**I tried several ways：**
1. The command is used under CMD, and curl is installed. However, commands such as grep and cut can not be well solved.
2. Failure to use Windows PowerShell.
3. Failure to use Cygwin.

I hope to receive your reply. Thank you.

**Comment by maple3142** [comment]
Try using git?

**Comment by championheng** [comment]
Using git is a only way ？Is there any other way？I want to download the version of stable.Thank you~

**Comment by Raincal** [comment]
```bash
git clone https://github.com/theme-next/hexo-theme-next.git
git checkout v6.3.0
```
