### ISSUE TITLE
The phonetic symbols are abnormal on different mobile phones. 

### ISSUE THREAD

**Issue by ithou** [theme-next/hexo-theme-next#305]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
English phonetic symbols appear normal on different phones.

### Actual behavior 
English phonetic symbols are displayed abnormally on different mobile phones.

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

### Other Information 
**`OPPO`**  Normal
**`Windows`**  Normal
**`Most of Android`**  Abnormal
**`IOS`**  Unknown

**Some screenshots**

1. 音标显示异常( **`一加手机`** )
![异常](http://p8x82yt4t.bkt.clouddn.com/1.jpg)

2. 正常显示
![正常](http://p8x82yt4t.bkt.clouddn.com/2.jpg)

**Comment by geekrainy** [comment]
设备内置字体不完整

**Comment by ithou** [comment]
@geekrainy 不是这个原因。因为我浏览其他网页的音标却能正常显示。

**Comment by maple3142** [comment]
Could you test it on different browser?
system,chrome,firefox....

**Comment by stevenjoezhang** [comment]
这是你自己的使用问题，与NexT主题无关。
