### ISSUE TITLE
Adblock block sp0.baidu.com

### ISSUE THREAD

**Issue by wt1098078873** [theme-next/hexo-theme-next#306]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

没有网络请求被`block`

### Actual behavior 

当使用`Adblock`时，网站会有一个域名为`sp0.baidu.com`的请求被`block`

### Steps to reproduce the behavior 
1. 安装chrome拓展程序`Adblock`
2. 打开开发者工具
3. 发现网络请求有一个接口`https://sp0.baidu.com/9_Q4simg2RQJ8t7jm9iCKT-xh_/s.gif?l=https://iwyatt.cc/ 0`被block。关闭`Adblock`无失败接口。

* Link to demo site with this issue: [Blog](https://iwyatt.cc/)
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.2.1
5.6.0

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Darwin 17.5.0 darwin x64
http_parser: 2.8.0
node: 10.2.1
v8: 6.6.346.32-node.8
uv: 1.20.3
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.29.0
napi: 3
openssl: 1.1.0h
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [X] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

### Other Information 
Demo in [Live Preview](https://github.com/theme-next/hexo-theme-next#live-preview) has some problem.

**Comment by sli1989** [comment]
why not add the site to white list.
Maybe it's third party service site.

**Comment by wt1098078873** [comment]
white list is a way. but i think it's a problem.😂 Actually, It don't affect use.

**Comment by sli1989** [comment]
it's irritant to the next.

**Comment by maple3142** [comment]
I think it is impossible to block a site with javascript.

**Comment by maple3142** [comment]
You can prevent that request from being sent by set `baidu_push: false` in `_config.yml`.

**Comment by stevenjoezhang** [comment]
这和NexT半毛钱关系都没有😂建议你去找百度或者Adblock解决问题
