### ISSUE TITLE
Chrome can not display bold or strong

### ISSUE THREAD

**Issue by shijiebei2009** [theme-next/hexo-theme-next#310]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
In liebao it correctly, but in chrome, it can't display bold or strong word. Just look like below. I don'w know why? Is it my chrome problem? My chrome version is 版本 67.0.3396.62（正式版本） （64 位）os is win7 64bit

### Actual behavior 
![qq 20180531233638](https://user-images.githubusercontent.com/4994697/40792404-713c9b04-652c-11e8-8881-9ff009ca8227.png)

You can try the link in chrome online, http://codepub.cn/2018/05/31/read-stanford-university-start-up-class/
### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
$ node -v
v7.10.1

WX@WX-PC ~
$ npm -v
4.2.0
```

### Package dependencies Information

```

```

#### Hexo version

```
hexo-cli: 1.0.3
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 7.10.1
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [X ] Old version v6.0.0

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by maple3142** [comment]
What's your chrome font setting?

**Comment by shijiebei2009** [comment]
@maple3142 
I have not setting, it is the default setting.
![qq 20180601072913](https://user-images.githubusercontent.com/4994697/40813504-d1c44382-656d-11e8-94b6-13c84c39b396.png)

**Comment by shijiebei2009** [comment]
I find this in stackoverflow https://stackoverflow.com/questions/22522186/chrome-cant-estimate-bold-font-weight
https://stackoverflow.com/questions/16105292/strong-tag-not-showing-up-in-chrome-but-does-show-up-in-all-other-browsers
is it chrome's bug??

**Comment by maple3142** [comment]
In my opinion, it has something to do with `han.min.css`.
I blocked that css with ublock, than `<strong>` in correctly bold with `font-weight: 700;`.

**Comment by shijiebei2009** [comment]
so, what should I do that enable chrome display correctly?

**Comment by maple3142** [comment]
@shijiebei2009 I think that you could disable `han`.
Maybe it is a chromium bug.
I tested it with different css, and it works everywhere except this.

**Comment by shijiebei2009** [comment]
So, how should I disable .han, can you give the detail steps?

**Comment by maple3142** [comment]
In theme's `_config.yml`, set `han: true` to `han: false`.

**Comment by shijiebei2009** [comment]
I wonder to know, what is `han` using for? and if I set `han:false`, what effect does it have?

**Comment by maple3142** [comment]
https://css.hanzi.co/

**Comment by sli1989** [comment]
Hey, is it solved?

**Comment by stevenjoezhang** [comment]
`Han` has been removed in #912

See also: #911
