### ISSUE TITLE
menu icons display abnormal ?

### ISSUE THREAD

**Issue by leeyongda** [theme-next/hexo-theme-next#311]
![20180606191122](https://user-images.githubusercontent.com/11832476/41034965-d270eb06-69bd-11e8-9683-846845c203f4.png)

**Comment by maple3142** [comment]
Demo site?
And did you hover on it?

**Comment by leeyongda** [comment]
I know 
// settings next.yml
menu:
  home: / || home
  archives: /archives/ || archive
  categories: /categories/ || th
  tags: /tags/ || tags
