### ISSUE TITLE
Emoji are not colored

### ISSUE THREAD

**Issue by gapplef** [theme-next/hexo-theme-next#312]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
Color emoji is supported in my system.
When I insert emoji in my blog, the `.md` file look like this: 
![screenshot from 2018-06-07 09-43-47](https://user-images.githubusercontent.com/5604665/41073871-d7589f7c-6a37-11e8-8f8b-536ba0ebceaa.png)

I would expect the emoji also colored in the final web page.
And It did as expected when use other hexo theme like `tranquilpeak`. 
But when use `NexT`, only few emoji are colored.
So, I think there's something wrong with `NexT`.

### Expected behavior 
![screenshot from 2018-06-07 09-44-02](https://user-images.githubusercontent.com/5604665/41073842-bff32cb2-6a37-11e8-89ff-00fcb68c8de5.png)

### Actual behavior 
![screenshot from 2018-06-07 09-45-33](https://user-images.githubusercontent.com/5604665/41073847-c2fd8268-6a37-11e8-8567-175d428ec7db.png)

**Comment by maple3142** [comment]
Emoji depends on what font you use, but different platform has different emoji font by default.
If you wants same emoji everywhere, you should add a font which includes emoji inside.

**Comment by gapplef** [comment]
So, If I want to use `Noto Color Emoji` font for the emoji , what should I do?

**Comment by reuixiy** [comment]
因为你 emoji 用的是 Unicode，这样导致 emoji 的显示和中文字体一样，显示效果取决于设备上的字体库，而不同设备上有不同的默认字体，故显示效果不一致。两种方案：

1. 显示为图片。利用 [hexo-filter-github-emojis](https://github.com/crimx/hexo-filter-github-emojis) 再加上[我的方法](https://reuixiy.github.io/technology/computer/computer-aided-art/2017/06/09/hexo-next-optimization.html#如何使用-emoji)或[这种方法](https://novnan.github.io/Hexo/emojis-for-hexo-next/)即可实现。特点：可以使用 GitHub 的书写方式，即`:joy:`会显示为:joy:，并且插件支持将这种代码转换为 Unicode，与下面这种方案有关。
2. 网页上直接加载 NotoColorEmoji 这个字体，然后修改相关 CSS 文件，实现显示。问题：字体太大，[源文件](https://github.com/googlei18n/noto-emoji/blob/master/fonts/NotoColorEmoji.ttf)足足 7 Mb 多，不太现实，而且 font-spider 啥的目前好像也不支持压缩这种格式的字体。

**Comment by stevenjoezhang** [comment]
Try this:
https://www.google.com/get/noto/#emoji-zsye-color
