### ISSUE TITLE
Music iframe do not follow the given width.

### ISSUE THREAD

**Issue by gapplef** [theme-next/hexo-theme-next#316]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
I use the follow code to insert music iframe, and set width=330 height=450.
```html
<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=450
src="//music.163.com/outchain/player?type=0&id=739576121&auto=1&height=430"></iframe>
```
### Expected behavior 
This is the result with theme `tranquilpeak`, the width of music iframe is as expected.
![screenshot from 2018-06-09 20-10-51](https://user-images.githubusercontent.com/5604665/41191403-7ae7dc4e-6c21-11e8-8c26-b1b8ce2cef74.png)

### Actual behavior 
When use  theme `next`, the music iframe seems fit to the content width, and is much wider than the requirement.
![screenshot from 2018-06-09 20-11-36](https://user-images.githubusercontent.com/5604665/41191405-7b2a44f8-6c21-11e8-8f7e-5b16a8254eb2.png)

**Comment by sli1989** [comment]
It can be controlled by the music iframe code.

```
<iframe frameborder="0" width="100%" height="100" src="http://v.qq.com/iframe/player.html?vid=m0178qd1etl&tiny=0&auto=0" allowfullscreen></iframe>
```

**Comment by gapplef** [comment]
I think you misunderstand my problem.
I set the width of iframe to 330px, but the result is that it take the full width, which is not what I expected.
And this only happened for `next` theme, not others like `tranquilpeak`.
Also this only happend for music iframe, not videos.

**Comment by maple3142** [comment]
Maybe you need quote in html attributes.
```html
<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width="330" height="450"
src="//music.163.com/outchain/player?type=0&id=739576121&auto=1&height=430"></iframe>
```

**Comment by gapplef** [comment]
@maple3142 Actually, that's the default iframe code of NetEase Music, and after add quote, the result is still unchange.
Also I want to emphasise again that  this only happened for `next` theme, not others like `tranquilpeak` in my test. That's why I think it's a bug of `next.

**Comment by ivan-nginx** [comment]
@gapplef othe NexT schemes like Muse still have same bug?

**Comment by gapplef** [comment]
@ivan-nginx yes, all have the same problem.

**Comment by stevenjoezhang** [comment]
In `source/js/src/utils.js`, remove
```
$iframe.width('100%').height('100%')
  .css({
    position: 'absolute',
  });
```
can solve the problem.
It seems to be a feature rather than a bug.

**Comment by ivan-nginx** [comment]
Maybe we can add option for 100% width or not here.
Let's add feature request on this issue.

**Comment by stevenjoezhang** [comment]
@gapplef iframe of origin `music.163.com` will no longer be resized automatically now.

**Comment by gapplef** [comment]
@stevenjoezhang thanks a lot.
