### ISSUE TITLE
Suggestion: Why not use npm to manage and record theme-next plugins?

### ISSUE THREAD

**Issue by YunYouJun** [theme-next/hexo-theme-next#318]
# Suggestion

I find theme-next has some plugins(like [theme-next-pace](https://github.com/theme-next/theme-next-pace)).

If I want to install this module, I have to use `git clone` to clone it in my folder.
Why not use npm to record these plugins? And then we can install it together just by `npm install`.

If there are any special reasons, can I know it?

### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

**Comment by zhangyunhai210** [comment]
Npm is a bad choice,especially for users,not developers.

**Comment by YunYouJun** [comment]
@ivan-nginx Thanks for your explanation. Looking forward to the realization of this function.

**Comment by ivan-nginx** [comment]
Added in [NexT 7.0 Roadmap](https://github.com/theme-next/hexo-theme-next/issues/67) as `Console reminder if new version released [autoupdate option] (#318)`.

**Comment by stevenjoezhang** [comment]
See: https://github.com/theme-next/awesome-next
