### ISSUE TITLE
Cannot GET /categories/ ,   Cannot GET /tags/

### ISSUE THREAD

**Issue by yongjunwen** [theme-next/hexo-theme-next#325]
cannot find the two catalogues   ------>     Cannot  GET /categories/   ,   Cannot GET /tags/

menu:
  home: / || home
  # about: /about/ || user
  tags: /tags/ || tag
  categories: /categories/ || th
  archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

**Comment by sli1989** [comment]
hi, follow this [guideline](https://github.com/iissnan/hexo-theme-next/wiki/%E5%88%9B%E5%BB%BA%E5%88%86%E7%B1%BB%E9%A1%B5%E9%9D%A2).

**Comment by a3349384** [comment]
I have the same problem.When get /categories or /tags,the webbrowser shows the "403 Forbidden" error.

**Comment by maple3142** [comment]
@a3349384 Have you created tags and categories pages?

**Comment by sli1989** [comment]
Hey, is it solved?

**Comment by a3349384** [comment]
@maple3142 Thanks
