### ISSUE TITLE
Multiple Tags and Categories?

### ISSUE THREAD

**Issue by jiapei100** [theme-next/hexo-theme-next#327]
NexT theme is fantastic... However, for every single blog, 

* can it be classified into multiple categories?
* it should be able to have multiple tags?

Any suggestions?

Cheers
Pei

**Comment by henryhoo** [comment]
1. You can have nested categories

2. You can have multiple tags

for example, in a post's xxxxx.md, you can have 
```
---
title: xxxxx
date: 2018-06-08 07:24:13
tags:
- tag1
- tag2
categories:
- cat1
- cat1.1
---
```

**Comment by jdhao** [comment]
See [here](https://hexo.io/docs/front-matter.html#Categories_&_Tags) for more information about multiple tags and categories.

**Comment by sli1989** [comment]
Any questions? If not, please close the issue.
