### ISSUE TITLE
HyperComments is charging now, How can I export the comments data?

### ISSUE THREAD

**Issue by Vincentqyw** [theme-next/hexo-theme-next#329]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 

HyperComments  cannot work.
![](http://oofx6tpf6.bkt.clouddn.com/18-6-19/28301188.jpg)

Actually I cannot read the following Russian in this [page](https://www.hypercomments.com/pricing) when I logged in as Admin:

![](http://oofx6tpf6.bkt.clouddn.com/18-6-19/16713992.jpg)

How can I **export** the comments data from HyperComments.

**Comment by ivan-nginx** [comment]
I'm trying to translate this message:

Dear HC users!
Is we send with e-mail's to all our users from 14.05.2018, we must close uor support with free plan.

From 15.06.2018 your plan «Lite» is disable for now.
For resume to use HC choose any paid plain below.
If you don't not have time for export your comments, you can do it with this **instructions**.

**Comment by Vincentqyw** [comment]
ok, I don't use it now.

**Comment by ivan-nginx** [comment]
Removed HyperComments in #342. From NexT v6.4.0 HyperComments system will not supported anymore.

***

P.S. Really sorry. I was like this comment system... :disappointed:

**Comment by achuanya** [comment]
111
