### ISSUE TITLE
Drop swig dependency

### ISSUE THREAD

**Issue by charsi** [theme-next/hexo-theme-next#33]
Hexo is switching to nunjucks from swig as it seems to be unmaintained now. There is some discussion on backward compatibility and one of their concerns is ensuring this theme keeps working as expected. 

So perhaps a future release of this theme can make the switch too and make things easier for everyone?  https://github.com/hexojs/hexo/pull/2903

**Comment by ivan-nginx** [comment]
Don't worry about this. I already connected with @NoahDragon about swig changed and he told me what NexT will work regardless of Hexo. So, only not maintained engine (swig) may have a problem (but he did not) and i, if will so hard, can switch from swig on something about mustache. Don't worry about this and i don't want to inside this Hexo discussion: there are their own decision, my part of work only is NexT.

**Comment by Blealtan** [comment]
Upvote for dropping this deprecated dependency (as said by npm) . Hope we can put this on the "future" timeline.

**Comment by ivan-nginx** [comment]
Already replaced `swig` by `swig-templates` in [this pull](https://github.com/hexojs/hexo/pull/2949) and released in [Hexo v3.5.0](https://github.com/hexojs/hexo/releases/tag/3.5.0).

So, no need to worry about dropped `swig` anymore.

**Comment by stevenjoezhang** [comment]
See also https://github.com/theme-next/hexo-theme-next/issues/1214
