### ISSUE TITLE
 >   引用无效

### ISSUE THREAD

**Issue by Zzz468005600** [theme-next/hexo-theme-next#330]
使用markdown语法中的   >   没有任何效果，去hexo那边看了下，反馈信息是主题的问题。

**Comment by sli1989** [comment]
following ENTER, ensure normal indentation.

can u show your source md content?

**Comment by Zzz468005600** [comment]
以前是好的，有一次我删除了hexo根目录下的.deploy_git，然后重新hexo d -g，之后无意中发现这个问题的。

source md content：
![source md content](http://pa8r6emo8.bkt.clouddn.com/other/bug1.png)
show：
![show](http://pa8r6emo8.bkt.clouddn.com/other/bug2.png)

**Comment by sli1989** [comment]
Can't be reproduced. Need u next version number and detailed step to reproduce.

![_20180716204940](https://user-images.githubusercontent.com/8521181/42759521-cf22a278-8939-11e8-9fa2-ca15bd45d45c.png)

**Comment by stevenjoezhang** [comment]
It has nothing to do with theme NexT. Please check your markdown renderer.
