### ISSUE TITLE
not work on post excerpt

### ISSUE THREAD

**Issue by icecory** [theme-next/hexo-theme-next#333]
- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

i find mathjax not work on post excerpt in homepage, and i try to use chrome ext [Math Anywhere](https://chrome.google.com/webstore/detail/math-anywhere/gebhifiddmaaeecbaiemfpejghjdjmhc) its also not work
so these code perhaps should be deleted
https://github.com/theme-next/hexo-theme-next/blob/08efdabadd21f567a9ad4864e4d451bd6f3eae93/layout/_third-party/math/index.swig#L5-L11

when \``` in post excerpt it will be replaced with `12345678910111213141516171819202122232425262728293031323334` a large string 
like
\```
int a;
\```
it will be replaced like `12345678910111213141516171819202122232425262728293031323334int a;12345678910111213141516171819202122232425262728293031323334`

**Comment by ivan-nginx** [comment]
Try to use with **post excerpt in homepage** code block or any other tag before. I think in post excerpt only simple words working for now.

**Comment by stevenjoezhang** [comment]
Could you provide more details? For me, mathjax works fine on the homepage.
