### ISSUE TITLE
Tag C#

### ISSUE THREAD

**Issue by iweixubin** [theme-next/hexo-theme-next#336]
title: Hello world
tags: C#

the link http://127.0.0.1:4000/tags/C/
#  is missing...

**Comment by ivan-nginx** [comment]
Please, try to reproduce this behavior with any default Hexo theme ([light](https://github.com/hexojs/hexo-theme-light) / [landscape](https://github.com/hexojs/hexo-theme-landscape)).
If behavior will same, it's not NexT theme bug; close this issue and create same issue in [Hexo](https://github.com/hexojs) repositories: [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) or [hexo root engine](https://github.com/hexojs/hexo) will at most best choises.

**Comment by maple3142** [comment]
Url cannot contain `#`.
Besides, we couldn't visit a website hosted on your machine.(127.0.0.1)
