### ISSUE TITLE
index_with_subtitle：连接号不够优雅

### ISSUE THREAD

**Issue by tingstory** [theme-next/hexo-theme-next#337]
### Expected behavior 

``` SEO Settings
# If true, will add site-subtitle to index page, added in main hexo config.
# subtitle: Subtitle
index_with_subtitle: true
```

开始使用 - NexT 使用文档（中间这个是连接号的宽度同拉丁小写字母「n」）

### Actual behavior 

开始使用 — NexT 使用文档（中间这个是连接号的宽度同拉丁小写字母「m」）

### NexT Information

**NexT Version:**
- 6.3.0

**NexT Scheme:**
- Mist

#### NexT Configuration:
```yml
# If true, will add site-subtitle to index page, added in main hexo config.
# subtitle: Subtitle
index_with_subtitle: true
```

### Troubleshooting

在「next」 > 「layout」 > 「index.swig」中，把 `mdash` 改为 `ndash`：

```
{% block title %}{{ title }}{% if theme.index_with_subtitle and subtitle %} &ndash; {{ subtitle }}{% endif %}{% endblock %}
```

**Comment by ivan-nginx** [comment]
Fixed in #341.
