### ISSUE TITLE
打开文章页，直接定位到文章末尾 when I open the article, it is located to the bottom（add another question）

### ISSUE THREAD

**Issue by mingxing47** [theme-next/hexo-theme-next#338]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
例如个人页面：https://www.simonming.com/2018/06/26/Netty-%E8%8F%9C%E9%B8%9F%E6%80%A5%E8%A1%8C%E5%86%9B%EF%BC%88%E4%B8%80%EF%BC%89/#more
预期是，打开时跳到页面头部

the url above, when I open the url, it is located to the bottom.
I want it locate to the top.

### Actual behavior 
实际是跳到了页面尾部

我刚刚又测试了一遍，在Chrome浏览器和微信访问时，会定位到底部。但是用 Edge 浏览器又会定位到顶部。
我也不知道 是什么原因
locate to the bottom

I‘v tested it, it appears in Chrome,but it won't appear in Edge.
I don't know why.
### Steps to reproduce the behavior 
1. hexo 配置：https://github.com/mingxing47/blog-source/blob/master/_config.yml
2. next 配置（实际使用时会改为 _config.yml，且增加评论系统相关key）：https://github.com/mingxing47/blog-next-source/blob/master/_config.yml.bak

1. hexo _config.yml: https://github.com/mingxing47/blog-source/blob/master/_config.yml
2. next _config.yml: https://github.com/mingxing47/blog-next-source/blob/master/_config.yml.bak

* Link to demo site with this issue:  YES
* Link(s) to source code or any usefull link(s): YES

### Node.js and NPM Information

```
$ node -v && npm -v
v8.11.3
6.1.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 8.11.3
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

```yml
前文中已经有
it is posted above.
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
前文已经贴出地址
it is posted above.
```

**Comment by sli1989** [comment]
it's about the read more tag. when you click `read more` in the main page, it will direct to the content after `<!--more-->` in your md file.
in your live dome, because of the less of your content, it seems to direct to bottom, but not actually.

**Comment by mingxing47** [comment]
@sli1989 I‘v sloved it as you say. Thank you~

**Comment by mingxing47** [comment]
@sli1989 您好，现在还有一个问题，就是我使用了 v6 之后，点击打赏，图片不会弹出来。
之前点击打赏图片是会浮动出来的，请问这个是否可配置？

**Comment by sli1989** [comment]
live demo?
check 
https://github.com/theme-next/hexo-theme-next/blob/07d83efa0fc88f5351da4a9d14b60af3ad54d3fe/_config.yml#L305-L309

**Comment by mingxing47** [comment]
@sli1989 
my _config.yml is here:
![image](https://user-images.githubusercontent.com/11155853/42087498-f2f6b46a-7bc8-11e8-88a7-40e1a4accb6a.png)
my live demo: https://www.simonming.com/2018/06/26/Netty-%E8%8F%9C%E9%B8%9F%E6%80%A5%E8%A1%8C%E5%86%9B%EF%BC%88%E4%B8%80%EF%BC%89/

when I click the QR code photo，it won't pop up.
![image](https://user-images.githubusercontent.com/11155853/42087591-38406192-7bc9-11e8-8903-3c71945b5cd2.png)

**Comment by sli1989** [comment]
@mingxing47 Can u try to install [fancybox](https://github.com/theme-next/theme-next-fancybox) (same as in 5.1.x version) or [fancybox3](https://github.com/theme-next/theme-next-fancybox3) (new style)?

**Comment by stevenjoezhang** [comment]
@mingxing47 It's a feature that the reward photo won't pop up. You can edit `source/js/src/utils.js` and remove `.not(':hidden')` in line 10 manually.
```
$('.content img')
      .not(':hidden')
```
