### ISSUE TITLE
Support mermaid? Suggesting Enhancements

### ISSUE THREAD

**Issue by xiaohaoliang** [theme-next/hexo-theme-next#347]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
[mermaid](https://mermaidjs.github.io/) is a simple markdown-like script language for generating charts from text via javascript.

flowchart, sequence diagram, gantt diagram~  

Is there a plan to support mermaid?

**Comment by maple3142** [comment]
It is not related to hexo theme, it should be done by hexo's markdown plugins.
https://github.com/threeq/hexo-tag-mermaid

**Comment by ivan-nginx** [comment]
@maple3142 but it can be maked as internal tag plugin or external repo.
@xiaohaoliang and if https://github.com/threeq/hexo-tag-mermaid works fine, why need to create another similar plugin?

**Comment by xiaohaoliang** [comment]
Tks, and I agree~ @maple3142 @ivan-nginx 

I try to use [hexo-tag-mermaid](https://github.com/threeq/hexo-tag-mermaid) .  
Two question: 
- I do not know how to configure it.
- The grammar of `hexo-tag-mermaid` is not fit me.

The grammar of `hexo-tag-mermaid`

```
{% mermaid flow 流程图 2 %}
    B["fa:fa-twitter for peace"]
    B-->C[fa:fa-ban forbidden]
    B-->D(fa:fa-spinner);
    B-->E(A fa:fa-camera-retro perhaps?);
{% endmermaid %}
```
I  expect like ：

>\```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
\```

I am newbee~

**Comment by icecory** [comment]
is `https://github.com/webappdevelp/hexo-filter-mermaid-diagrams` supported in hexo next?

**Comment by ivan-nginx** [comment]
@stevenjoezhang if issue solved, need to add label solved.

**Comment by stevenjoezhang** [comment]
Ah.. it's closed automatically, I forgot to add the tag..
