### ISSUE TITLE
Image cannot be enlarged preview in version 6.0.x.

### ISSUE THREAD

**Issue by cong** [theme-next/hexo-theme-next#352]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Image can be enlarged preview in version 5.1.x

### Actual behavior 
Image cannot be enlarged preview in version 6.0.x.

#### Hexo version

```
hexo: 3.3.8
hexo-cli: 1.0.3
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 6.11.3
v8: 5.1.281.107
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

**Comment by pengfeigao** [comment]
I had the same problem

**Comment by ivan-nginx** [comment]
Can you guys try to install [fancybox](https://github.com/theme-next/theme-next-fancybox) (same as in 5.1.x version) or [fancybox3](https://github.com/theme-next/theme-next-fancybox3) (new style)?

**Comment by jiyiren** [comment]
I had the same problem, 

**Theme**: NexT.Mist  v6.3.0

**URL** : [http://jiyiren.github.io/2017/10/06/picture-group/](http://jiyiren.github.io/2017/10/06/picture-group/)

**hexo version** :

```bash
hexo: 3.3.9
hexo-cli: 1.0.3
os: Darwin 17.6.0 darwin x64
http_parser: 2.7.0
node: 8.2.1
v8: 5.8.283.41
uv: 1.13.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

**Comment by cong** [comment]
@ivan-nginx That's really hepl, Thx!
