### ISSUE TITLE
underlined category under title ends in an extra blank

### ISSUE THREAD

**Issue by mgourd** [theme-next/hexo-theme-next#36]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
no underlined blank after category name,like this:
NameOfACategory 
--------------------------(no extra blank)

### Actual behavior 
NameOfACategory 
---------------------------(an extra blank)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: mgourd.github.com
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v8.9.1
5.5.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.4.4"
  },
  "dependencies": {
    "hexo": "^3.4.4",
    "hexo-deployer-ftpsync": "^0.1.1",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^2.1.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-markdown-it-plus": "^1.0.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.2.0",
    "markdown-it-toc-and-anchor": "^4.1.2"
  }
}
```

#### Hexo version

```
hexo: 3.4.4
hexo-cli: 1.0.4
os: Linux 4.13.0-25-generic linux x64
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

#### NexT Configuration:

```yml

```

### Other Information 
Chrome 63.0.3239.132 64bit
Ubuntu 17.10 64bit
![2018-01-15 15-44-48](https://user-images.githubusercontent.com/29856997/34931731-2f72dad0-fa0b-11e7-993b-489bf87baa32.png)
![2018-01-15 15-44-48](https://user-images.githubusercontent.com/29856997/34932380-942bf7ac-fa0d-11e7-911e-64b3ca7e3b0a.png)

**Comment by ivan-nginx** [comment]
Fixed in 08d35be1c92b4596e6a3c672dcb0c0fb32088a31
