### ISSUE TITLE
代码高亮,normal时没有效果,识别不出代码

### ISSUE THREAD

**Issue by yangyuanming** [theme-next/hexo-theme-next#363]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
highlight_theme: normal，高亮显示代码块，样式为normal

### Actual behavior 
无法识别代码,没有样式,没有copy按钮。其他代码样式正常显示

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
node -v
v9.10.1

npm -v
5.6.0

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.0"
  },
  "dependencies": {
    "gitment": "0.0.3",
    "hexo": "^3.2.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-admin": "^2.3.0",
    "hexo-all-minifier": "^0.5.2",
    "hexo-asset-image": "git+https://github.com/CodeFalling/hexo-asset-image.git",
    "hexo-deployer-git": "^0.3.1",
    "hexo-deployer-heroku": "^0.1.2",
    "hexo-deployer-openshift": "^0.1.2",
    "hexo-fs": "^0.2.3",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-search": "^2.2.5",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.0.2",
    "hexo-helper-post-top": "0.0.1",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-inject": "^1.0.0",
    "hexo-pagination": "^0.1.0",
    "hexo-related-popular-posts": "^3.0.1",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-less": "^0.2.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-search": "^1.0.4",
    "hexo-server": "^0.2.2",
    "hexo-symbols-count-time": "^0.4.2",
    "live2d-widget-model-shizuku": "^1.0.5",
    "live2d-widget-model-tororo": "^1.0.5",
    "live2d-widget-model-wanko": "^1.0.5",
    "live2d-widget-model-z16": "^1.0.5",
    "npm": "^5.10.0"
  }
}
```

#### Hexo version

```
hexo: 3.7.0
hexo-cli: 1.1.0
os: Darwin 16.4.0 darwin x64
http_parser: 2.8.0
node: 9.10.1
v8: 6.2.414.46-node.23
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2o
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

#### NexT Configuration:

```yml
# Code Highlight theme
# Available values: normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

```

**Comment by sli1989** [comment]
Have you added this setting?

https://github.com/theme-next/hexo-theme-next/blob/2d3e4d7c065f2faa680aac13c24ce14b44e3134b/_config.yml#L295-L303

`highlight_theme` seems a bug needing to be confirmed.

**Comment by yangyuanming** [comment]
@sli1989 the problem  has been solved,thanks,i am good at speaking English,so i decide to speak Chinese.hexo主配置文件配置错了,hightlight的enable设置成了false,改成true就ok了
前:
highlight:
  enable: false
后:
highlight:
  enable: true
