### ISSUE TITLE
3rd-party Question-Answer services for CN / 第三方中文问答服务建议

### ISSUE THREAD

**Issue by sli1989** [theme-next/hexo-theme-next#366]
When the new official website is online (ASAP), we want to reduce the number of issues with simple questions for future. In this way, all the issues are bugs or features requests related.

So users can create questions with `theme-next` tag in 3rd-party Question-Answer services, like [StackOverflow](https://stackoverflow.com/), [Mail.ru](https://mail.ru/). But for Chinese, can u dudes suggest some good services besides  [segmentfault](https://segmentfault.com), [v2ex](https://www.v2ex.com), and [ZHIHU](https://www.zhihu.com)? Thanks.

---

当新的官方网站上线时（我们正在努力完善），我们希望减少简单 issues 的数量。这样，所有的 issues 都是与之相关的bug或特性请求。

用户可以在第三方问答服务中创建问题，比如[StackOverflow](https://stackoverflow.com/)和[Mail.ru](https://mail.ru/)。但对于汉语来说，除了[segmentfault](https://segmentfault.com)，[v2ex](https://www.v2ex.com)和[ZHIHU](https://www.zhihu.com)之外，还有其他这样的常用第三方问答社区吗？希望大家能够提供一些参考。

**Comment by LEAFERx** [comment]
CNode？

**Comment by ivan-nginx** [comment]
Site is ready, BTW.

**Comment by stevenjoezhang** [comment]
https://ask.csdn.net/ ?
