### ISSUE TITLE
如何设置背景动画固定不动？

### ISSUE THREAD

**Issue by Jacknolfskin** [theme-next/hexo-theme-next#367]
如题，如何设置波浪背景动画不随鼠标移动而移动，使其固定

**Comment by ChungZH** [comment]
问题有点奇怪。。。不会动的还是动画？

**Comment by Jacknolfskin** [comment]
不随鼠标移动而移动，不是动画不动

**Comment by sli1989** [comment]
@Jacknolfskin take [this](https://github.com/hustcc/canvas-nest.js/issues/24#issuecomment-406686776) for temp solution.
It's 3rd party plugins, so need further soft setting for next.

**Comment by stevenjoezhang** [comment]
在`three-waves.min.js`中注释或删除掉`document.addEventListener("mousemove",u,!1)`即可

**Comment by Jacknolfskin** [comment]
> 在`three-waves.min.js`中注释或删除掉`document.addEventListener("mousemove",u,!1)`即可

完美解决，非常感谢！

**Comment by stevenjoezhang** [comment]
> > 在`three-waves.min.js`中注释或删除掉`document.addEventListener("mousemove",u,!1)`即可
> 
> 完美解决，非常感谢！

不客气😊
