### ISSUE TITLE
Can you add the encrypt for NexT? 

### ISSUE THREAD

**Issue by htharoldht** [theme-next/hexo-theme-next#373]
I want to encrypt the content as well as the toc, like [hexo-blog-encrpy](https://github.com/MikeCoder/hexo-blog-encrypt). 

But that plugins can't support NexT perfectlly---I have already given some Issues on that page in Chinese. 

I hope you can Integrate the functionality of that plugin, in order to better fit the NexT theme. 

Last but not least, thank you for your read! And I'd very appreciate if you can resolve the issues.

**Comment by stevenjoezhang** [comment]
The latest version of hexo-blog-encrpy works fine with NexT. You can have a try.
![2018-12-17 7 38 29](https://user-images.githubusercontent.com/16272760/50084897-73267a80-0233-11e9-866e-f4adc7ea9f28.png)

**Comment by ivan-nginx** [comment]
@stevenjoezhang need to add adaptation under this plugin or not?

**Comment by stevenjoezhang** [comment]
@ivan-nginx This plugin works well with NexT after upgrading to the newest version, maybe no need for additional adaptation

**Comment by ivan-nginx** [comment]
Encrypted TOC?

**Comment by stevenjoezhang** [comment]
Oh, yes, it can be intergrated to NexT: https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.md#encrypt-toc

**Comment by ivan-nginx** [comment]
So, can u implement this feature?

**Comment by stevenjoezhang** [comment]
No problem, I'll try.

**Comment by stevenjoezhang** [comment]
Through further investigation, I think Hexo blog's encryption is still very imperfect. It involves a lot of plug-ins, not just a single theme.
