### ISSUE TITLE
请问怎么出来多个标签，多个连接？

### ISSUE THREAD

**Issue by shuimaizi** [theme-next/hexo-theme-next#378]
请问每篇文章里面，# 笔记 # 编程 # 学习 # 计算机程序的构造和解释 # SICP， 这个是怎么写出来啊。
我用MacDown, tags: 花园； 园艺

请问要怎么写啊，为什么不能出来多个连接啊， 怎么搞都是一个标签，一个连接

**Comment by shuimaizi** [comment]
还有就是在那个tags这个标签汇总页面， 怎么能搞出来所有标签啊。

**Comment by LEAFERx** [comment]
```yml
tags:
  - 笔记
  - 编程
  - 学习
  - 计算机程序的构造和解释
  - SICP
```

**Comment by shuimaizi** [comment]
多谢！ 搞定！
