### ISSUE TITLE
如何判断当前域名并由此决定是否显示评论？

### ISSUE THREAD

**Issue by YangDuck** [theme-next/hexo-theme-next#397]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).（无法访问）
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
比如我有两个域名`abc.top`和`abc.cn`，两个域名绑定到同一个仓库并部署，请问要怎样才能实现通过`abc.cn`访问时不显示评论和搜索（个人网站备案不允许提供交互式功能）并显示备案号，通过`abc.top`访问时不显示备案号并显示评论和搜索？

### Actual behavior 
无

### Steps to reproduce the behavior 
无

### Node.js and NPM Information

```
v10.7.0
6.1.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "gitment": "0.0.3",
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-pdf": "^1.1.1",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.4.4"
  }
}
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.7.0
v8: 6.7.288.49-node.15
uv: 1.22.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [x] Old version v6.3.0

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml

```

**Comment by LEAFERx** [comment]
Read the theme source code and insert  your own js. Try window.location

**Comment by YangDuck** [comment]
@LEAFERx Where should I insert the js, and what code should I insert?  I tried inserting `{% if window.location.hostname === 'example.top' %}` into line 1 of `themes\next\layout\_partials\comments.swig`, but there was no comments on the `example.top`.

我应该写什么代码，把它们放在哪里才行？我尝试过把`{% if window.location.hostname === 'example.top' %}`插入到`themes\next\layout\_partials\comments.swig`的第一行，但是当我通过`example.top`访问时并没有评论出现。

And then I inserted the code into `comments.swig`, but it didn't work.
之后我有尝试把下面的代码插入到刚才文件中，也不起作用。
```
{% elseif theme.valine.enable and theme.valine.appid and theme.valine.appkey %}
<script type="text/javascript">
host = window.location.host
    if (host == "example.top")
    {
    document.write("<div class="comments" id="comments"></div>");
    } 
    else if (host == "localhost")
    {
    document.write("<div><p>test</p><div>");
    }
    else if (host == "example.cn")
    {
    document.write("<div><p>There is nothing.</p><div>");
    }        
</script>
{% endif %}
```

**Comment by LEAFERx** [comment]
Try `layout\_third-party\comments\valine.swig`

**Comment by YangDuck** [comment]
@LEAFERx It works, Thanks! Here is my code in `themes\next\layout\_third-party\comments\valine.swig`
成功了，谢谢你。下面是我修改的代码。
```
  <script type="text/javascript">
    host = window.location.host
    if (host == "yangduck.cn")
      {
      }
    else
      {
      var GUEST = ['nick','mail','link'];
      var guest = '{{ theme.valine.guest_info }}';
      guest = guest.split(',').filter(function (item) {
        return GUEST.indexOf(item)>-1;
      });
      new Valine({
          el: '#comments' ,
          verify: {{ theme.valine.verify }},
          notify: {{ theme.valine.notify }},
          appId: '{{ theme.valine.appid }}',
          appKey: '{{ theme.valine.appkey }}',
          placeholder: '{{ theme.valine.placeholder }}',
          avatar:'{{ theme.valine.avatar }}',
          meta:guest,
          pageSize:'{{ theme.valine.pageSize }}' || 10,
          visitor: {{ theme.valine.visitor }}
      });
      } 
  </script>
```
But there is still a small problem, although there are not comments on `example.cn`, there is an empty box. It's not a big deal.
但这里仍然有一个问题，虽然在`example.cn`上没有评论显示出来了，但会留下一个空白的框。不过问题不大。
Thanks again.

**Comment by YangDuck** [comment]
![](https://t1.aixinxi.net/o_1clqbdufke6m1rqu5jv1k3lkvma.png-j.jpg)

**Comment by sli1989** [comment]
Maybe u can try to add if condition in this file.

https://github.com/theme-next/hexo-theme-next/blob/62f69afb14b1393a3bea4895b0242b1d01b75030/layout/_layout.swig#L107
