### ISSUE TITLE
自定义界面怎么禁止facybox渲染？

### ISSUE THREAD

**Issue by jerryc127** [theme-next/hexo-theme-next#399]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

点击跳到对应的网址

### Actual behavior 
点击跳出facybox界面 显示 The requested content cannot be loaded.  Please try again later.

![image](https://user-images.githubusercontent.com/16351105/44728500-437e2600-ab0f-11e8-9821-d765fa2dbbb2.png)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

### Other Information 

自定义了一个页面
hexo g 后
发现a 标签多了rel="external nofollow noopener noreferrer"
点击跳到facybox界面而不是跳到对应的网址
‘怎么禁止facybox渲染？

自定义界面部分截图
![image](https://user-images.githubusercontent.com/16351105/44728565-6d374d00-ab0f-11e8-9c08-172af248bfd1.png)

渲染后 多了
![image](https://user-images.githubusercontent.com/16351105/44728693-ab347100-ab0f-11e8-8c3b-30eb6c37510f.png)

**Comment by maple3142** [comment]
Maybe it is duplicate. #394

**Comment by ivan-nginx** [comment]
Fixed in #468.
