### ISSUE TITLE
How to add the count number to menu?

### ISSUE THREAD

**Issue by xieduo7** [theme-next/hexo-theme-next#401]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
How to add the number to the sidebar like this?
![sidebar](http://p76pxmjnt.bkt.clouddn.com/Snipaste_2018-08-30_13-01-24.png)

#### Hexo version

```
hexo: 3.7.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [X] Old version v6.0.0

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

**Comment by sli1989** [comment]
Option for count of Posts / Categories / Tags with badges in menu is based on [v6.0.1](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.0.1).
You need to git pull the version or higher and set the `menu_settings`

https://github.com/theme-next/hexo-theme-next/blob/44da676ae109df42a0200909573691a9cff641ae/_config.yml#L130-L132

**Comment by xieduo7** [comment]
@sli1989 Thank you for your answer!
