### ISSUE TITLE
需要帮助

### ISSUE THREAD

**Issue by JslinSir** [theme-next/hexo-theme-next#402]
按照流程生成分类，但是还是报错

code:
![image](https://user-images.githubusercontent.com/30678791/44896855-35592100-ad2c-11e8-9873-76e3c0edecb3.png)
![image](https://user-images.githubusercontent.com/30678791/44896874-430ea680-ad2c-11e8-9c3f-c54a08a0c4b0.png)
![image](https://user-images.githubusercontent.com/30678791/44896913-65a0bf80-ad2c-11e8-9fe0-d2f1f73a1264.png)

**Comment by sli1989** [comment]
what's the meaning of  `/RN/`?

use `title: Categories` in English. and then change the language your want in `_config.yml`.

**Comment by JslinSir** [comment]
@sli1989  it mens 
![image](https://user-images.githubusercontent.com/30678791/44897488-72261780-ad2e-11e8-87c0-10ca581e3de0.png)

**Comment by sli1989** [comment]
So use `title: Categories` in English? is this works?

**Comment by JslinSir** [comment]
![image](https://user-images.githubusercontent.com/30678791/44899409-4ad24900-ad34-11e8-95d4-74c2a96f2850.png)
Cannot GET /blog/categories/RN%E9%9B%86%E6%88%90SDK%E7%9B%B8%E5%85%B3/

I really do not know how to do, according to the document this situation  @sli1989

**Comment by JslinSir** [comment]
i  user gitee hosting is this reason？ 

gitee need index.html   I copy index.html under publish every time  dou you have any idea?

**Comment by sli1989** [comment]
If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/' in site `_config.yml`.

**Comment by JslinSir** [comment]
yes  i  do this already
![image](https://user-images.githubusercontent.com/30678791/44900143-66d6ea00-ad36-11e8-9f13-8b57b9140282.png)
 @sli1989

**Comment by sli1989** [comment]
Maybe need u online demo... U can deploy with bug for debug.

**Comment by ivan-nginx** [comment]
`url` without `blog` maybe?

**Comment by JslinSir** [comment]
i try  but Still the same


@ivan-nginx @sli1989

**Comment by JslinSir** [comment]
The console： GET https://jslinlink.gitee.io/blog/tags/RN/ 404 (Not Found)

**Comment by sli1989** [comment]
Con't deploy with bugs? Need see your blog online.

**Comment by JslinSir** [comment]
blog address： https://jslinlink.gitee.io/blog/   @sli1989

**Comment by sli1989** [comment]
> gitee need index.html I copy index.html under public every time dou you have any idea?

Don't need to do this. just add anything your like in index.html as index page.
like:
```
<html>
  <head><title>Welcome</title></head>
  <body>
    <h2>hello world</h2>
  </body>
</html>
```
- It's the bug that [the tags folds](https://gitee.com/jslinLink/blog/tree/master/tags) are not produced. It should be like [this](https://github.com/sli1989/testing/tree/gh-pages/tags) 
- U used 5.1.4? can try to use v6+ to reproduce this bug?

**Comment by ChungZH** [comment]
你的网站现在打不开了。。。

**Comment by JslinSir** [comment]
Give up on fixing the problem  @ChungZH   try  agin

**Comment by JslinSir** [comment]
i change  new version still the same

**Comment by ChungZH** [comment]
OK

**Comment by ChungZH** [comment]
你的tags页面也是这个问题。

**Comment by JslinSir** [comment]
怎么解决呢？@ChungZH  什么原因导致的呢

**Comment by Wechatoff** [comment]
我的是6.4.0。你把`_config.yml`里面menu设置中的/`Categories/`变成`Categories/`试一下。`_config.yml`里面提示了：如果在二级目录，要把前面的斜杠去掉，原文如下：

> # When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).

**Comment by Wechatoff** [comment]
Mine is 6.4.0。Please edit `_config.yml `, change `/Categories/` to `Categories/`
It says that "When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives)." at  `_config.yml ` file. you need to read it carefully.

**Comment by JslinSir** [comment]
@Wechatoff  我试着你说的那样 还是不行
![image](https://user-images.githubusercontent.com/30678791/44917436-e4b4e880-ad6a-11e8-9c9c-029cabf12e10.png)
```
menu:
  home: / || home
  about: about/ || user
  tags: tags/ || tags
  categories: categories/ || th
  archives: archives/ || archive
```
我的next版本是  "version": "6.4.0",

**Comment by JslinSir** [comment]
@Wechatoff  我试了改下，还是不行 放弃修复了。。。。

**Comment by ChungZH** [comment]
不用子目录试试？
直接 https://jslinlink.gitee.io 这样试试。

**Comment by Open343** [comment]
@JslinSir  請教你一個問題，博客中「我挥舞着键盘和本子，发誓要把世界写个明明白白！」這句話是怎麼設置上去的？非常感謝！

**Comment by JslinSir** [comment]
@Open343   _config.yml文件中的
![image](https://user-images.githubusercontent.com/30678791/45026607-65c4f600-b071-11e8-8fa0-a7ba98cfee6e.png)

**Comment by Open343** [comment]
@JslinSir 好的！謝謝。

**Comment by sli1989** [comment]
Gitee's blog must be placed in the subdirectory? There are other blogs built normally using . Is it a problem in building steps?

**Comment by Sun-xyu** [comment]
没有source下新建page页面
可手动执行hexo new page tags

**Comment by stevenjoezhang** [comment]
玄学问题啊，如果是`/blog/categories/RN/index.html`没有生成，可能是Hexo的bug

**Comment by JiangTJ** [comment]
复现了问题，通过去掉"hexo-generator-category"依赖
![image](https://user-images.githubusercontent.com/15902347/48173081-4f6f3b00-e33d-11e8-9c89-28745bb47952.png)
您可以试一下添加依赖，查看问题是否修复
```
//npm
npm install --save hexo-generator-category
//or yarn
yarn add hexo-generator-category
```

**Comment by ivan-nginx** [comment]
Please, try to reproduce this behavior with any default Hexo theme ([light](https://github.com/hexojs/hexo-theme-light) / [landscape](https://github.com/hexojs/hexo-theme-landscape)).
If behavior will same, it's not NexT theme bug; close this issue and create same issue in [Hexo](https://github.com/hexojs) repositories: [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) or [hexo root engine](https://github.com/hexojs/hexo) will at most best choises.
