### ISSUE TITLE
hexo deploy fail to change scheme

### ISSUE THREAD

**Issue by accelsao** [theme-next/hexo-theme-next#421]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
hexo deploy上去 scheme可以換Gemini

### Actual behavior 
結果還是保持 Muse
但是hexo serve local顯示是成功的

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml

```

**Comment by sli1989** [comment]
can your show live demo site with Gemini deployment ?

**Comment by accelsao** [comment]
```
v8.11.4
5.6.0
```
```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 8.11.4
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

```
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-search": "^2.3.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}
```

**Comment by JiangTJ** [comment]
@accelsao 
It's your blog source:<https://github.com/accelsao/blog-save-next>?
I exce `hexo g`, but the generated `css/main.css` is not match your site css(<https://github.com/accelsao/accelsao.github.io/blob/master/css/main.css>)
It maybe a bug in `hexo-deployer-git`.
May need try some cmd to fix? 
```
//try clean before deploy
hexo clean
hexo deploy

//if not work, try use git push --force
//it will cause your deploy repo lose all previous commits!!!!
//need backups!!!!
hexo clean
hexo g
cd ./public
git init
git add .
git commit -m “force-deploy”
git push –force –quiet –set-upstream <your-blog-deploy-repo> master
```

**Comment by accelsao** [comment]
@JiangTJ 感謝你的幫忙和回答 我用 'hexo clean'  and 'hexo d' 就成功了
hexo clean 的 info 有 deleted database 和 public folder 可能是這裡出bug了

**Comment by sli1989** [comment]
oh, u didn't use `hexo clean`? It is needed for every deployment.
