### ISSUE TITLE
The index page not dispaly visiting counts by using busuanzi?

### ISSUE THREAD

**Issue by shuaijunlan** [theme-next/hexo-theme-next#428]
![screenshot from 2018-09-28 09-23-46](https://user-images.githubusercontent.com/13015473/46182886-bd692100-c300-11e8-8056-b56479c02172.png)
Website addressing: [https://shuaijunlan.github.io/](https://shuaijunlan.github.io/)

**Comment by sli1989** [comment]
Yeah, when using busuanzi, the view count would not be displayed in the index page.

https://github.com/theme-next/hexo-theme-next/blob/9ec34d34a24fd83e289248c17e40966b33ac6e87/layout/_macro/post.swig#L224-L232

**Comment by shuaijunlan** [comment]
@sli1989 Will the bug be fixed in the next release version of hexo-theme-next ?

**Comment by sli1989** [comment]
yeah, it's a easy implement.

**Comment by shuaijunlan** [comment]
Ok , thanks.

**Comment by shuaijunlan** [comment]
@sli1989 According to your suggestion, I just delete `not is_index and`,  but the `view count` only displays in the first entry in every index page.
![screenshot from 2018-09-28 17-10-48](https://user-images.githubusercontent.com/13015473/46199386-8404d580-c341-11e8-8241-2995c59355e6.png)

**Comment by shuaijunlan** [comment]
@maple3142 So, how to fix the bug?

**Comment by ChungZH** [comment]
#436

**Comment by shuaijunlan** [comment]
@ChungZH At the home page of [**https://chungzh.cn/**](https://chungzh.cn/ ) , it also doesn't display the visiting counts.

**Comment by ChungZH** [comment]
你刷新几次试试

**Comment by sli1989** [comment]
> 注意：不蒜子为保持极简，暂不支持在站点文章摘要列表中（如首页）逐个显示每篇文章的阅读次数，如果您非常需要这一功能，可以留言。根据需要程度再考虑开发相应的功能。

> Note: If you don't want to keep it very simple, you can't display the number of readings of each article one by one in the summary list of the site (such as the home page). If you need this feature very much, you can leave a message. Consider developing the corresponding features as needed.

Seems this function is not supported by the official.

**Comment by shuaijunlan** [comment]
If the function is supported, it will be better, I think.

**Comment by stevenjoezhang** [comment]
@shuaijunlan Seems the maintainer of busuanzi doesn't have a plan to add this feature in a short time.
You can use leancloud counter instead.
