### ISSUE TITLE
Sorry, or #429 follow your code changes, or there is no change

### ISSUE THREAD

**Issue by pzb568** [theme-next/hexo-theme-next#430]
@
![untitled](https://user-images.githubusercontent.com/38772754/46254310-f62e0500-c47c-11e8-9c5e-3824e6fb5711.png)
![untitled0](https://user-images.githubusercontent.com/38772754/46254311-f6c69b80-c47c-11e8-887f-9eac1e5c83e8.png)
![untitled6](https://user-images.githubusercontent.com/38772754/46254312-f6c69b80-c47c-11e8-8257-079071419a8a.png)
![untitled552](https://user-images.githubusercontent.com/38772754/46254313-f75f3200-c47c-11e8-922f-032bdac3853e.png)
![untitled2220](https://user-images.githubusercontent.com/38772754/46254314-f75f3200-c47c-11e8-9b63-f1d2996e4d13.png)

### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by ivan-nginx** [comment]
Yes, this PR – fix, ёпта.
