### ISSUE TITLE
后面能否增加对Hugo的支持？

### ISSUE THREAD

**Issue by lemonhu** [theme-next/hexo-theme-next#435]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by LEAFERx** [comment]
AFAIK, there is no plan for hugo now.
Contribute is always welcomed btw.

**Comment by AlynxZhou** [comment]
Actually this is a Hexo theme, it's ridiculous for asking a Hexo theme to support Hugo instead of porting it to Hugo. If I am right there's already a third party hugo-theme-next, you can try that, or porting another one, but it's not ok for a Hexo theme to support another generator.

你让一个 Hexo 主题去添加对另一个生成器的支持本身就是不合理的，你应该考虑把这个主题移植到 Hugo 上，而不是让它同时支持两个生成器，因为他们之间可能有很多细节差距，要在每一处都做判断实在是不太现实。

**Comment by ivan-nginx** [comment]
Because tags and other helpers in Hexo & NexT – JS libraries. This scripts for now important and NexT can't work property without they.

But idea nice, mb later, in next year i think about port it. Just not enought time to Hugo & Jekyll maintenance for NexT.

**Comment by cocobear** [comment]
> Because tags and other helpers in Hexo & NexT – JS libraries. This scripts for now important and NexT can't work property without they.
> 
> But idea nice, mb later, in next year i think about port it. Just not enought time to Hugo & Jekyll maintenance for NexT.

Hope NexT port for Hugo will coming the next year!

**Comment by stevenjoezhang** [comment]
@lemonhu @cocobear We have no plans to migrate to Hugo. Hexo does have a lot of shortcomings, but migration requires a lot of work & time for coding.

Here is a forked version: https://github.com/xtfly/hugo-theme-next

**Comment by stevenjoezhang** [comment]
See also https://github.com/next-theme/hexo-theme-next/issues/146
