### ISSUE TITLE
Vue代码块无法高亮显示

### ISSUE THREAD

**Issue by hooray** [theme-next/hexo-theme-next#440]
有办法解决么？还是需要由 hexo 去解决？

**Comment by stevenjoezhang** [comment]
确实需要由 hexo ，或者说 hexo 的依赖 highlight.js 去解决

https://github.com/highlightjs/highlight.js/pull/1929

**Comment by stevenjoezhang** [comment]
可以安装这个插件： https://github.com/highlightjs/highlightjs-vue/
然后修改hexo-util中highlight相关的代码。
