### ISSUE TITLE
代码块问题

### ISSUE THREAD

**Issue by zeroccDeNA** [theme-next/hexo-theme-next#444]
代码块如下：
<img width="1223" alt="2018-10-17 11 28 20" src="https://user-images.githubusercontent.com/30892505/47097903-e6783400-d264-11e8-8bfd-b3c46bfdd4e8.png">

next 主题上却成如下了：

<img width="456" alt="code" src="https://user-images.githubusercontent.com/30892505/47097213-8634c280-d263-11e8-8be1-1b44ac1bc625.png">

**Comment by xu-song** [comment]
你试试多加个 `c`

```
```c
//  CCPerson 类
...
```

**Comment by zeroccDeNA** [comment]
> 你试试多加个 `c`
> 
> ```
> ```c
> //  CCPerson 类
> ...
> ```
没有用 难受

**Comment by sli1989** [comment]
@zeroccDeNA I can't reproduce it..

```
// CCPerson 类
struct CCPerson {
  struct test1 test2
  int _number;
}
```

![image](https://user-images.githubusercontent.com/8521181/47650831-66cf5b00-dbbc-11e8-8be9-f80a088287d4.png)

**Comment by stevenjoezhang** [comment]
It might be caused by markdown renderer
