### ISSUE TITLE
what is the purpose of  post.sticky ?

### ISSUE THREAD

**Issue by xu-song** [theme-next/hexo-theme-next#447]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### what's the purpuse of post.sticky

According to the [source code](https://github.com/theme-next/hexo-theme-next/search?q=sticky&unscoped_q=sticky), `post.sticky` seems no use, except adding `<i class="fa fa-thumb-tack"></i>` before title.

![screen shot 2018-10-21 at 12 38 06 pm](https://user-images.githubusercontent.com/13825126/47263357-9b934080-d532-11e8-8f98-e60a49a8e4b6.png)

### How to use

https://github.com/theme-next/hexo-theme-next/blob/62f69afb14b1393a3bea4895b0242b1d01b75030/layout/_macro/post.swig#L42-L47

- Is `post.sticky` an int or string or boolean?

**Comment by sli1989** [comment]
The sticky feature had been removed. [#705](https://github.com/iissnan/hexo-theme-next/issues/705)
Maybe it's a feature request.
U can also try to use [hexo-generator-topindex](https://github.com/amlove2/hexo-generator-topindex)

**Comment by stevenjoezhang** [comment]
Use this plugin: https://github.com/othorizon/hexo-generator-index-sticky

**Comment by youngjuning** [comment]
Thanks bro

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/hexo-generator-index/pull/51
