### ISSUE TITLE
Next主题站内搜索功能不能使用

### ISSUE THREAD

**Issue by RobertDawn** [theme-next/hexo-theme-next#450]
**NexT Scheme:**
- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

> ### 因为自己的一次hexo g失误报错后，`hexo clean && hexo g` 后站内本地搜索不能使用了，**主要出现情况**：为搜索界面正常，但是输入搜索框，内容区一片空白，不能使用，看过网上很多解决方法还是不行，望大佬们帮忙解决。

**Comment by xu-song** [comment]
test

**Comment by sli1989** [comment]
Need detailed and every steps to reproduce your problem.

**Comment by sli1989** [comment]
Need detailed and every steps to reproduce your problem.

**Comment by sli1989** [comment]
Need detailed and every steps to reproduce your problem.

**Comment by stevenjoezhang** [comment]
@RobertDawn 你用的哪个搜索插件？渲染后的根目录下是否有`search.xml`？

**Comment by stevenjoezhang** [comment]
执行`npm list`，检查`hexo-generator-search`插件是否正常，是否在`_config.yml`中配置了search的相关选项

**Comment by hfsyun** [comment]
@stevenjoezhang  感谢， 问题已解决，可能报错时把搜索插件损坏，我重新下载覆盖就好了，当然也有可能是他大姨夫来了，总有那么几天

**Comment by sli1989** [comment]
@hfsyun the same person with @RobertDawn
