### ISSUE TITLE
Formula not compiled with version 6.0+

### ISSUE THREAD

**Issue by nocater** [theme-next/hexo-theme-next#457]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I want to show latex in my blog.

### Actual behavior 
same steps like [math.md](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/MATH.md)   

### Steps to reproduce the behavior 
wrong with `npm un hexo-renderer-marked --save`: 
``` bash
npm ERR! code EINVAL
npm ERR! EINVAL: invalid argument, read

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chenshuai\AppData\Roaming\npm-cache\_logs\2018-10-26T10_15_06_132Z-debug.log
```
the tail of log file `debug.log`:
``` 
541 verbose stack Error: EINVAL: invalid argument, read
541 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\rm.js:245:7
541 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\node_modules\iferr\index.js:13:50
541 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
541 verbose stack     at FSReqWrap.oncomplete (fs.js:153:5)
542 verbose cwd D:\Documents\Blog\nocater.github.io
543 verbose Windows_NT 10.0.17763
544 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "uninstall" "hexo-renderer-marked" "--save"
545 verbose node v8.12.0
546 verbose npm  v6.4.1
547 error code EINVAL
548 error EINVAL: invalid argument, read
549 verbose exit [ 1, true ]
```

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v8.12.0
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-algolia": "^1.2.5",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.4",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}

```

#### Hexo version

```
INFO  [hexo-math] Using engine 'mathjax'
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17763 win32 x64
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
math:
  enable: true
```

### Other Information 
I also try to install `hexo-renderer-kramed`, and change the item to ' engine: katex', the equation is also source code.
I switch `NexT` to version 5, only edit `next\_config.yml`：
```
mathjax:
  enable: true
```
it works well , not need other operations.

**Comment by nocater** [comment]
could anyone help?

**Comment by sli1989** [comment]
The problem shows when `npm un hexo-renderer-marked --save`?
Try to deleted all folds to re-initialization?

**Comment by nocater** [comment]
I re-install Node.js and re-initialization,
the result of `npm un hexo-renderer-marked --save`
```
npm ERR! code EINVAL
npm ERR! EINVAL: invalid argument, read

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chenshuai\AppData\Roaming\npm-cache\_logs\2018-11-05T07_48_57_181Z-debug.log
```

the tail of `debug.log` is that:
```
544 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "un" "hexo-renderer-marked" "--save"
545 verbose node v8.12.0
546 verbose npm  v6.4.1
547 error code EINVAL
548 error EINVAL: invalid argument, read
549 verbose exit [ 1, true ]
```

[2018-11-05T07_48_57_181Z-debug.log](https://github.com/theme-next/hexo-theme-next/files/2547350/2018-11-05T07_48_57_181Z-debug.log)

**Comment by sli1989** [comment]
waiting for others' help. 😭

**Comment by ivan-nginx** [comment]
```
npm i hexo-renderer-kramed --save
```
