### ISSUE TITLE
文章标题是H2标签,如何改成H1标签

### ISSUE THREAD

**Issue by mayongze** [theme-next/hexo-theme-next#458]
![image](https://user-images.githubusercontent.com/22066360/47644357-e3583e80-dba8-11e8-95cf-ec71bba2edd0.png)
文章的标题是h2标签,想让标题使用h1的标签

**Comment by sli1989** [comment]
what's the point of this modification? enlarge font size?

**Comment by mayongze** [comment]
对，标题有点小,看着不太舒服:joy:,我看其他人的next都是h1标签

**Comment by sli1989** [comment]
https://github.com/theme-next/hexo-theme-next/blob/770f34d869929191bf0e6d7d5864807ffe1c07d2/_config.yml#L109-L110

what's u setting for this?

**Comment by mayongze** [comment]
Thanks you. 我之前设置的是true,现在改成false后变成了h1标签，但是效果感觉还不是太好，我又改了https://github.com/theme-next/hexo-theme-next/blob/770f34d869929191bf0e6d7d5864807ffe1c07d2/source/css/_variables/base.styl#L243
为 **$font-weight-bolder** ，这是改之后的效果
![image](https://user-images.githubusercontent.com/22066360/47655318-b7988100-dbc7-11e8-8b1c-d1b90f1b42bc.png)

如果我还想单独设置主标题的字体大小有啥实现的办法没

**Comment by sli1989** [comment]
可以看这个 https://github.com/theme-next/hexo-theme-next/issues/455#issuecomment-433305773
