### ISSUE TITLE
Startup welcome page like Android 我想到一个绝妙的idea

### ISSUE THREAD

**Issue by wuxinvip** [theme-next/hexo-theme-next#467]
我想到一个绝妙的idea

项目加载可不可以加一个像android一样的启动欢迎页

**Comment by sli1989** [comment]
a index page of site can be personalized and provides this feature.
The animation process seems redundant.

**Comment by ivan-nginx** [comment]
@wuxinvip 請用英文寫。

**Comment by yinyang996** [comment]
ok i got it and thanks

**Comment by stevenjoezhang** [comment]
首页可以换成自定义页面：

https://github.com/theme-next/hexo-theme-next/issues/581

如果是要每个页面的加载动画，可以使用前端JS实现
