### ISSUE TITLE
click read more in chrome, but download the web

### ISSUE THREAD

**Issue by skobekuang** [theme-next/hexo-theme-next#471]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Clicking read more(阅读全文), we will get the whole post.

### Actual behavior 
but when we try it in chrome, the explorer will download the hype-link. 

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "hexo-wordcount": "^2.0.1"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml

```

**Comment by maple3142** [comment]
Which web server you are using?
It may relate to `Content-Type` sent by server.

**Comment by skobekuang** [comment]
> Which web server you are using?
> It may relate to `Content-Type` sent by server.

I build my homepage(https://skobekuang.github.io/) by github page

**Comment by skobekuang** [comment]
> Caused by a missing `/`
> 
> ```
> <a class="btn" href="/uncategorized/hello-world#more" rel="contents">
>               阅读全文 »
>             </a>
> ```
> It should be `/uncategorized/hello-world/#more`
> Interesting.
the hype-link by generated by next hexo-next automatically

**Comment by skobekuang** [comment]
I find the content-type of url(https://skobekuang.github.io/uncategorized/hello-world#more) is aplication/octet-stream, why causes this situation

**Comment by stevenjoezhang** [comment]
In `layout/_macro/post.swig`, `url_for(post.path)` method returns a wrong URL without `/`. Need to figure out why.

**Comment by ivan-nginx** [comment]
Please, try reproduce this bug with clean Hexo & NexT installation. With default renderer.

**Comment by ivan-nginx** [comment]
Yep, must be with end `/`.

**Comment by stevenjoezhang** [comment]
Is the problem solved now?

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/2650

**Comment by stevenjoezhang** [comment]
I'll take your silence as a sign the problem is solved!
