### ISSUE TITLE
Refused to apply style from 'http://localhost:4000/css/main.css?v=6.5.0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by ssjcoding** [theme-next/hexo-theme-next#479]
Refused to apply style from 'http://localhost:4000/css/main.css?v=6.5.0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by stevenjoezhang** [comment]
It's caused by hexo-server. If the problem still exist, please ask https://github.com/hexojs/hexo-server for help
