### ISSUE TITLE
the footer is overrided by the valine comment in mobile

### ISSUE THREAD

**Issue by sli1989** [theme-next/hexo-theme-next#48]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 

![qq 20180118222621](https://user-images.githubusercontent.com/8521181/35102712-a4f6f71a-fc9e-11e7-9489-739bd73dadfb.png)

Is it possible to be add gap between comment and the footer? 

* Link to demo site with this issue: http://saili.science/2016/10/17/windows-use/

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by tsanie** [comment]
Well, your footer height is too large.
In the default, `$footer-height` is 50px and the `$gap-between-main-and-footer` is 100px, the footer height will be up to 150px.

But in your page the footer height, in the desktop layout, is 180px, and in the mobile layout, the height is 208px.

**Now you can just change the `$footer-height` in the file `next/source/css/_variables/base.styl`.**

PS: Maybe there need an option in the theme config file, which allows the users define their own footer-height (like `footer.min_height`)? @ivan-nginx whats your opinion?

**Comment by sli1989** [comment]
yes, thank u. i did add content in the footer page...

**Comment by ivan-nginx** [comment]
I think need to:

1. Check other comment systems (disqus, etc.). If there are works fine, write to [Valine repo about bug](https://github.com/xCss/Valine/issues).
2. If on other comment systems see the same, then need to see scheme templates. Need to try:
    2.1. Reset all custom footer styles.
    2.2. Test on other schemes (Gemini must have auto footer adjustments, 3 other shemes not).

It's a not critical bug, but need to be fixed.

**Comment by tsanie** [comment]
Got it. 👍 

But I think his problem is not the comments issues, it's the issue that his footer is too high and covering the main block.

When you fill too many things into the footer, it will cause the issues (except the Gemini scheme).

---

**Steps to reproduce:**

1. Reset all the settings.
2. Uncomment the `footer.custom_text` in the `theme/_config.yml`, and fill texts with several `<br/>` or some wide words.
3. Enable a scheme except Gemini.
4. Start the server and take a look.

![image](https://user-images.githubusercontent.com/980449/35129690-a55c02aa-fcf7-11e7-980d-5b23b444e82f.png)

**Comment by sli1989** [comment]
1. test different scheme
- in the Mist, there is a clear cut between the comment and footer, the `powered by the valine` is missing, that might otherwise be obscured. the gap between the comment and footer in my custom page is also clear.
![](https://ws1.sinaimg.cn/large/006V2m65ly1fnlrwcktalj30b60cd3z2.jpg)
![](https://ws1.sinaimg.cn/large/006V2m65ly1fnlrwhf3nxj30aw0cfaat.jpg)

- in the Pisces, there has still overlapping phenomenon in post and my custom page

![](https://ws1.sinaimg.cn/large/006V2m65ly1fnlryer03tj30b60cfmxs.jpg)
![](https://ws1.sinaimg.cn/large/006V2m65ly1fnlryi5uu3j30b30cdwfb.jpg)

- in the Gemini, it's fine for its auto footer adjustments.

![](https://ws1.sinaimg.cn/large/006V2m65ly1fnlrzc5uowj30b00cat99.jpg)
![](https://ws1.sinaimg.cn/large/006V2m65ly1fnlrzetxibj30bc0cm3z6.jpg)

- test the comment system, there is also have overlapping phenomenon in post and my custom page.

![](https://ws1.sinaimg.cn/large/006V2m65ly1fnls04j4rvj30b10ceaah.jpg)
![](https://ws1.sinaimg.cn/large/006V2m65ly1fnls06m9wyj30b40c8zl1.jpg)

---

Now i just change the `$footer-height` to `100px` in the file `next/source/css/_variables/base.styl`, it works.

![](https://ws1.sinaimg.cn/large/006V2m65ly1fnls148t0rj30b90caq3m.jpg)
![](https://ws1.sinaimg.cn/large/006V2m65ly1fnls16vzv1j30b50ccq3i.jpg)

**Comment by ivan-nginx** [comment]
Ok, i think need to add something like auto-heght on footer, like on Gemini.

**Comment by ivan-nginx** [comment]
```yml
custom_text: Hosted by <a target="_blank" rel="external nofollow" href="https://pages.github.com">GitHub Pages</a><br>Hosted by <a target="_blank" rel="external nofollow" href="https://pages.github.com">GitHub Pages</a><br>Hosted by <a target="_blank" rel="external nofollow" href="https://pages.github.com">GitHub Pages</a>
```
![image](https://user-images.githubusercontent.com/16944225/35259351-621e9f58-0016-11e8-9e1a-95ba33066320.png)

**Comment by ivan-nginx** [comment]
@sli1989 problem still exists?

**Comment by sli1989** [comment]
For me, I know the solutions.
For Next, like u said: `Ok, i think need to add something like auto-height on footer, like on Gemini.`
