### ISSUE TITLE
Can I fork this repo and use in my blog with git submodule?

### ISSUE THREAD

**Issue by magic3584** [theme-next/hexo-theme-next#483]
First of all sorry to open this issue because of my poor knowledge about license.

I noticed that the license is APGL after version 6.0 which is MIT before.

I used this theme like this:

1. `git clone` in my blog
2. remove the .git under **next folder** 
3. change some config file in the **next folder**
4. git back up with my blog
5. back up **next folder** somewhere else like dropbox

The above makes that if I changed to a new computer, after I checked out my blog, I have to paste back up from dropbox manually.

Now next is 6.0 and I wanna try it, and I wanna try if it can be done with git submodule (sorry for I haven't used git submodule before), but I'm wonder that if can I fork this repo and use it as git submodule.

Yours help will be appreciate, thanks ~

**Comment by sli1989** [comment]
ok, maybe can u follow this:

1. fork the Next repo, and init submodule

```
cd hexo_blog
git rm -r --cached themes/next/
git submodule add git@github.com:username/hexo-theme-next.git themes/next/
# set up remote upsteam to update
cd themes/next
git remote add upsteam https://github.com/theme-next/hexo-theme-next
```

2. then do your custom, and git push to your `username/hexo-theme-next`

```
cd thems/next
git checkout master
# do your custom
git add
git commit -m "Get something done"
git push origin master
```

3. in your new computer, 

```
git init
git clone git@gitlab.com:username/username.gitlab.io.git
cd username.gitlab.io
# for the first time to get submodule
git submodule init
git submodule update
```

**Comment by magic3584** [comment]
Thanks for your reply, but I have a little questions:
1. If I wanna sync my-next-repo with Next I can do like this [https://help.github.com/articles/syncing-a-fork/](url) under themes/next
2. After I make my custom next config I do git pull/push with my-next-repo under themes/next
3. After I change to a new computer after checked out my-blog and I find the the themes/next is not updated(supposed I just modify my-next-repo on web) I can just do `git pull` under themes/next, then the next is following like step 2 I just said.

Are they all right what I considered or I have some wrong thoughts please point out them, thanks~

**Comment by ivan-nginx** [comment]
@magic3584 yes, you can fork and make any changes you want, only 1 condition in this license here:

You must specify theme info link by this option:

```yml
footer:
  theme:
    enable: true
```

But you can ignore this condition if you: collaborator / contributor or author specified in the 'docs/AUTHORS.md' file under this repo.
