### ISSUE TITLE
请增加基于github或者gitalk的评论系统

### ISSUE THREAD

**Issue by svandex** [theme-next/hexo-theme-next#484]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
增加基于github或者gitalk的评论系统，网络上也有很多的范例。似乎增加这个功能不是很困难，我没有js和html基础，自己不会改这个主题。我贴出两篇网络文章。

1.如何用gitalk制作评论系统：https://callmesoul.cn/shi-yong-gitalk-dai-ti-qi-ta-di-san-fang-ping-lun-cha-jian/
2.如何用github制作评论系统：https://segmentfault.com/a/1190000011100934

### Actual behavior 
disqus系统容易因为外网不稳定导致很难访问，当然对于在国外的使用这个主题的用户来说没有这个问题。国内的很多这种评论系统经济效益都不好，存在停止运营风险。

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [X] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
已经有PR了https://github.com/theme-next/hexo-theme-next/pull/464
应该很快会加上

**Comment by stevenjoezhang** [comment]
已经加好啦
https://github.com/theme-next/hexo-theme-next/pull/464

**Comment by svandex** [comment]
我和@ysun 一样都是无法初始化gitalk，github_id和admin_user都是填的我自己svandex，rep是svandex.github.io。另外，在设置oauth apps时填的url 和callback url填的svandex.github.io和我的博客地址，都不行。

**Comment by svandex** [comment]
@stevenjoezhang 求助。
