### ISSUE TITLE
Search box is under post card

### ISSUE THREAD

**Issue by Bitrhythm** [theme-next/hexo-theme-next#490]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The search box should be the topmost element.

### Actual behavior 
The search box is covered by post cards.

### Steps to reproduce the behavior 
1. Open the blog https://bitrhythm.github.io/en/
2. Click the search navigation link
3. Now you can see what happened

* Link to demo site with this issue: https://bitrhythm.github.io/en/
* Link(s) to source code or any usefull link(s): https://github.com/Bitrhythm/Blogs

### Node.js and NPM Information

```
node -v -> v10.14.1
npm -v -> 6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.4.4"
  }
}
```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [x] Latest Release version
- [x] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml

```

### Other Information 
![x](https://user-images.githubusercontent.com/23711687/49338050-1aae8500-f658-11e8-8805-1322ad8189a1.PNG)

**Comment by stevenjoezhang** [comment]
Remove
```
.header-inner {
    opacity: 0.9;
}
```
in your `themes/next/source/css/_custom/custom.styl` will solve the problem

**Comment by Bitrhythm** [comment]
@stevenjoezhang Thanks a lot!
