### ISSUE TITLE
Add support for social buttons — Likely

### ISSUE THREAD

**Issue by online** [theme-next/hexo-theme-next#491]
Hi to all!

Developers, please, add support for [Likely](https://ilyabirman.net/projects/likely/). These social buttons will appeal to many users. Thanks!

**Comment by sli1989** [comment]
you can try this

https://github.com/theme-next/hexo-theme-next/blob/5d677f45709457dcf6c6473eba2eee7ff7966f66/_config.yml#L655-L662

**Comment by stevenjoezhang** [comment]
AddThis is another good choice. You can have a try.

**Comment by online** [comment]
@stevenjoezhang, thanks, I tried, I didn't like it.

**Comment by 1v9** [comment]
@online #678, is this ok?

**Comment by online** [comment]
@1v9, yes, thank you. Just what I needed.
