### ISSUE TITLE
请教一下，这个页面内容都是正常的，但是没有渲染出来，why?

### ISSUE THREAD

**Issue by shijiebei2009** [theme-next/hexo-theme-next#494]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
**直接打开如下网址，即可重现**
1. http://codepub.cn/2015/04/10/Java's-volatile-boolean-AutomaticBoolean-analysis/

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
WX@WX-PC MINGW64 /d/hexo (master)
$ node -v
v7.10.1

WX@WX-PC MINGW64 /d/hexo (master)
$ npm -v
4.2.0
```

### Package dependencies Information

```
$ cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.5"
  },
  "dependencies": {
    "es5-ext": "^0.10.35",
    "exec-buffer": "^0.1.1",
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.0",
    "hexo-filter-optimize": "^0.1.3",
    "hexo-fs": "^1.0.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.2.0",
    "hexo-util": "^0.6.1",
    "highlight": "^0.2.4",
    "highlight.js": "^9.13.1"
  },
  "devDependencies": {
    "hexo-generator-baidu-sitemap": "^0.1.2"
  }
}
```

#### Hexo version

```
$ hexo -v
hexo: 3.3.5
hexo-cli: 1.0.3
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 7.10.1
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
1230行，disqus_config中的一个引号没有被转义，导致语法错误。停用JavaScript的情况下可以正常显示。

**Comment by shijiebei2009** [comment]
@stevenjoezhang Java's-volatile 那是因为这个名字的原因喽？必须要改名吗？

**Comment by stevenjoezhang** [comment]
@shijiebei2009 目前比较方便的解决方案是把`'`换成全角的`’`。这确实是个bug，出现在`layout/_third-party/comments/disqus.swig`中，似乎还不太好解决...

**Comment by stevenjoezhang** [comment]
@Raincal 是否需要一个字符串转义的方案？毕竟未来出现一个带有`"`的标题又会出现问题。

**Comment by Raincal** [comment]
@stevenjoezhang 双引号的话，需要转义
那就改成这样
```js
this.page.url = encodeURI(`{{ page.permalink }}`);
this.page.identifier = encodeURI(`{{ page.path }}`);
```

**Comment by Raincal** [comment]
@stevenjoezhang 双引号的话，需要转义
那就改成这样
```js
this.page.url = encodeURI(`{{ page.permalink }}`);
this.page.identifier = encodeURI(`{{ page.path }}`);
```

**Comment by ivan-nginx** [comment]
![image](https://user-images.githubusercontent.com/16944225/49869657-50e6c400-fe11-11e8-9259-5662a26f1129.png)

1. Error appear because in permalink symbol «'» exists. But page succesfully loaded, only disqus not load.
2. As we see – sidebar undefined. And this is strange. I see this string in bundle and compare with original – they same. So, i think @shijiebei2009 do modify something in this post, because other posts working fine. Also, i can't find [this post](http://codepub.cn/2015/04/10/Java's-volatile-boolean-AutomaticBoolean-analysis/) with bug, but can find [that post](http://codepub.cn/2015/04/10/java-volatile-boolean-atomic-boolean-analysis/). Maybe both this posts conflict or something lika that?

Anyway, post source can help to resolve this bug, @shijiebei2009

**Comment by ivan-nginx** [comment]
Also, bug with Disqus fixed in #504.

Before:
![image](https://user-images.githubusercontent.com/16944225/49870370-72e14600-fe13-11e8-8704-0a0201e55256.png)

After:
![image](https://user-images.githubusercontent.com/16944225/49870412-8f7d7e00-fe13-11e8-9065-391f1ad49971.png)

**Comment by maple3142** [comment]
Convert them to json will work, because a valid json will be a valid javascript:
```js
this.page.url = {{ page.permalink|json }};
this.page.identifier = {{ page.path|json }};
```

**Comment by maple3142** [comment]
Encoding url might lead to unwanted result, because identifier may work like id for Disqus.
Changing them might cause current comment on Disqus lost. (I am not sure)

**Comment by ivan-nginx** [comment]
Hmm... Maybe you right. So, i make your method then?

**Comment by Raincal** [comment]
@maple3142 Please see this post.
https://blog.fooleap.org/disqus-url-encode.html

**Comment by ivan-nginx** [comment]
@Raincal i understand only `encodeURI` from this post. :smile:

**Comment by stevenjoezhang** [comment]
See also https://github.com/theme-next/hexo-leancloud-counter-security/issues/15
