### ISSUE TITLE
FontAwesome icon issue | FontAwesome 图标问题

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#505]
The icon library of the latest version of theme NexT has been migrated to FontAwesome 5. This change is not backward compatible, which means that the previous configuration for FontAwesome 4.7.0 will fail and the icons will not be displayed. If you have encountered related issues, please remove the customized icon and CDN link in the configuration file according to this Pull Request: #1438 .

最新版本的 NexT 主题迁移到了 FontAwesome 5。此改动不向下兼容，这意味着此前对于FontAwesome 4.7.0 版本的配置会失效，且导致图标无法显示。如果你遇到了图标问题，请根据此 Pull Request #1438 的更改，移除配置文件中自定义的图标和 CDN 链接，并重新进行配置。

---

Today i decided to update FontAwesome from v4 to v5 in accordance with #94 and #474 
issues. Well, this was not hard and at least 2/3 icons was successfully shown. But! Trouble is happened (i know what Free and Pro versions – it's not simple way): free icons was very **smoothly** and some icons was not in their places (a little topped, a little bottomed)...
Firstly i think what i not set some options or something like that. I try many parameters – without luck. And what are you guys thinking? I'm going on FA site and saw randomed PRO icon; lets see on [Book](https://fontawesome.com/icons/archive?style=solid)) or on [Bullhorn](https://fontawesome.com/icons/bullhorn?style=solid) icon. See and click on from Free to PRO version. 
See this *hit? They specially make Free version more cloudy and PRO version more legibly. I compare NexT online site FA v4 to localhost with FA v5 – FA v4 looks like icons in PRO version.

So, as FA can't upgrade anymore, i suggest to switch on Material Design Icons (Google).

Let's compare icons number:
- FA v4.7.0 – `675` icons.
- MDI latest version – `2,346` icons (if i right understand). Of cource, mb icons repeated like FA (transparent / not), but anyway if `2,346 / 3 = 782`.

Let's compare pack weight:
- FA v4.7.0 – `429 kb`.
- MDI latest version – `5,3 mb`.

What do you thinking, guys? I can soon switch from FA to MDI and up on test domain to see how they looks. If icons will better, we can totally switch on MDI (they, by the way, periodically add icons to main pack):

```
19 New Icons.
Latest commit 22874e5  4 days ago
```

Other Information

**Comment by maple3142** [comment]
Perhaps [iconmoon](https://icomoon.io/) will be a good solution, it support lots of iconpacks including FA4 and MDI, and it enable you to select icons you need.
Otherwise, I don't think 5.3mb is suitable for web at all.

**Comment by ivan-nginx** [comment]
@maple3142 [this](https://icomoon.io/#icons-icomoon)?

**Comment by maple3142** [comment]
The website I provided (icomoon) can also offer both FA & MDI, and you just need to select what icon you need then pack it as a new icon font.
With this, it can significantly reduce the size of icon font and provide multiple icon fonts.

**Comment by ivan-nginx** [comment]
Oooh! I see. Icomoon App at the right top corner. Ok, i'll try it.

**Comment by ivan-nginx** [comment]
Well, @maple3142, FA + MDI splitted ≈ 1.6 mb.

**Comment by maple3142** [comment]
The reason of using these icon pack is is smaller icon pack size, so you wouldn't want to use it if you simply select all icons.
As for `woff2`, only premium version can generate it, and there is some free alternatives such as [fontello](http://fontello.com/)(I currently use it in my site.).

**Comment by JiangTJ** [comment]
@maple3142 If only select next using icon, how to change icon. Regenerate iconmoon pack? This may be a bit of trouble.

**Comment by ivan-nginx** [comment]
@JiangTJ @maple3142 i already find solution: 3rd-party icons (except FA) will be used as external modules, like Fancybox. Feature will be ASAP.

**Comment by stevenjoezhang** [comment]
Should notice that:
> Outline Style Icons - Similarly, all icons that had an outlined style (and usually ended with -o) now have a prefix of far and have had their -o suffix removed.

See: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
And the default font-size in v5 seems bigger than v4

**Comment by stevenjoezhang** [comment]
And I found that fontawesome v5 conflict with han...

**Comment by stevenjoezhang** [comment]
@ivan-nginx I found this in `source/css/_common/components/third-party/han.styl`:
```
i.fa { font-family: FontAwesome !important; }
```
Because han.css will override all the `font-family` settings, it's necessary to use `!important` to declare the font-family of font-awesome icons.
The font name is changed in v5, so this conflict is easy to resolve:
```
i.fa, i.far, i.fas {
    font-family: "Font Awesome 5 Free" !important;
}
```

**Comment by ivan-nginx** [comment]
Ok, let's make this issue into Low Priority. For now we need to resolve #547 pull with cache generation (High Priority).

**Comment by jodumont** [comment]
if I may; [ForkAwesome](https://github.com/ForkAwesome/Fork-Awesome/) propose a good alternative of Font-Awesome 5
Have extra icons and keep the old way of calling these icon such as : `<i class="fa fa-camera-retro"></i>`

**Comment by 1v9** [comment]
@jodumont I've tested and it's prety good.

**Comment by ivan-nginx** [comment]
@1v9 can u generate 2 live demos for compare both versions?

**Comment by stevenjoezhang** [comment]
Maybe it's time to update these internal libraries: jQuery, velocity and font-awesome
we can't get rid of them in a short time

**Comment by 1v9** [comment]
@ivan-nginx 

* [FontAwesome](https://demo.1v9.im/)

* [ForkAwesome](https://1v9.im/)

You can check html source code to find ForkAwesome and FontAwesome, two type of fonts but arguably they are same. I‘m  not sure if it is necessary to update  internal library or add a alternative option.

**Comment by 1v9** [comment]
See: https://github.com/1v9/hexo-theme-next/commit/85517ebd48c3a84bad5f5e4cb965695c27fd1822

**Comment by stevenjoezhang** [comment]
@1v9 Just update the internal library, no need to add options in `_config.yml`. Giving users too much freedom will lead to confusion

**Comment by 1v9** [comment]
@stevenjoezhang I don't want PR, as I said, forkawesome is 'equal' to fontawesome 😂

**Comment by maple3142** [comment]
Are there any benefits of replace FontAwesome with ForkAwesome?

**Comment by 1v9** [comment]
@maple3142 Anyway, I didn't find it. 🤷‍♂️

**Comment by Pilgrimss** [comment]
I am confused with social icons in the sidebar, the prefix of Facebook, Github icons are 'fab fa-fw', while the envelope icon with the prefix 'fa fa-fw'. 
However, in layout/_macro/sidebar.swig:
```
{% if theme.social_icons.enable %}
                   {% set sidebarIcon = '<i class="fa fa-fw fa-' + link.split('||')[1] | trim | default('globe') + '"></i>' %}
 {% endif %}
 {{ next_url(sidebarURL, sidebarIcon + sidebarText, {title: name + ' &rarr; ' + sidebarURL}) }}
```
If I change the 'fa fa-fw fa' to 'fab fa-fw fa', brand icons are shown, but envelope icon not. So how should we modify it to make brand icons and common icons displayed at the same time.

**Comment by Aqua-Dream** [comment]
Any progress? Does closing this issue mean there is no plan to update yet?

**Comment by stevenjoezhang** [comment]
This is a backlog issue, and I believe we will come up with a workable solution in the future

**Comment by stevenjoezhang** [comment]
@theme-next/next One possible solution is to load the icons that the user needs to use, which can avoid performance issues caused by loading all Font Awesome icons.

https://fontawesome.com/how-to-use/with-the-api/setup/importing-icons
https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself
https://icomoon.io/app/#/select

**Comment by jiangtj** [comment]
reopen... planning to upgrade v5?

**Comment by stevenjoezhang** [comment]
The best way is to find a tool that can generate and package fonts locally. This way users can always use the icons they want and avoid loading the entire font awesome icon library (it's too big even for CDNs).

**Comment by jiangtj** [comment]
> The best way is to find a tool that can generate and package fonts locally.

This is possible, but requires npm

e.g. https://github.com/hexojs/hexo-fontawesome, we can use this plugin to convert to svg.

Although hexo plans to support npm installation themes, this will make users have to install the theme through npm or do some extra steps to install dependencies in order to use the theme they have cloned.

**Comment by stevenjoezhang** [comment]
hexo-fontawesome cannot handle dynamically loaded icons. We may need to develop a plugin based on this module: https://www.npmjs.com/package/webfont

**Comment by stevenjoezhang** [comment]
@jiangtj Plugin created: https://github.com/next-theme/hexo-next-fontawesome-subset

<blockquote><img src="https://opengraph.githubassets.com/e0577aece07e54477d95831e746877c9814e5160f7983fb6b5960624b4e5ed72/next-theme/hexo-next-fontawesome-subset" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/next-theme/hexo-next-fontawesome-subset">GitHub - next-theme/hexo-next-fontawesome-subset: Generate site-specific Font Awesome webfont subsets for Hexo NexT</a></strong></div><div>Generate site-specific Font Awesome webfont subsets for Hexo NexT - next-theme/hexo-next-fontawesome-subset</div></blockquote>
