### ISSUE TITLE
Suggestion to rename Han to han.

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#510]
In accordance with #508 issue i suggest remake Han **vendors** option to lowercase.
Lets see:

https://github.com/theme-next/hexo-theme-next/blob/8380b98f6337adb39ec8c97e5d9cd5bafd663f96/_config.yml#L495-L497

This looks fine, right? Ok, let's see vendors:

https://github.com/theme-next/hexo-theme-next/blob/8380b98f6337adb39ec8c97e5d9cd5bafd663f96/_config.yml#L1012-L1014

If someone use Han and can test it, welcome please. Thank's!

**Comment by Maples7** [comment]
I'll handle the rename work, but I am actually not a front-end guy so bugs in `Han` lib need to be fixed by someone else.

**Comment by ivan-nginx** [comment]
@Maples7 thank's and GJ! Solved with #512.
