### ISSUE TITLE
怎么git pull 不会把本地主题设置给覆盖了呢

### ISSUE THREAD

**Issue by pzb568** [theme-next/hexo-theme-next#513]
next 主题又更新了，git pull后把本地修改覆盖，怎么样又可以更新昨天又不覆盖本地设置呢

**Comment by JiangTJ** [comment]
可以使用data-files或者hexo的theme_config覆盖主题配置     
https://theme-next.org/docs/getting-started/data-files/

**Comment by stevenjoezhang** [comment]
commit your changes, then run `git pull`, your changes will be merged automatically
