### ISSUE TITLE
Consider to remove all «Please»

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#515]
As a title, it's already done for understanding.

Another side: must we use anytime words like «please», if problem can be solved without this word?

— Please, anybody help me!
— Of course, please, dude, here it is – your solution.
— (no response for long time)...

Dude just going-out, yep. What we will do?
We write «Please». Nothing more.

I suggest don't write «please» (as the extra word), but writing only for on business. For current questions / issues. And try to remove all parasite words what you have. I will.

***

Holiday Greetings, see ya!

**Comment by sli1989** [comment]
😃
