### ISSUE TITLE
Can footnotes be integrated into Next | 引用链接效果做成像论文那样

### ISSUE THREAD

**Issue by svandex** [theme-next/hexo-theme-next#517]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
很多论文都是引用链接在右上角，然后链接放在文章最后集中显示。或者类似wikipedia那种效果，右上角有个数字标志[1]，然后文章底部是所有链接。

### Actual behavior 
目前的链接方式都是下划线，这个效果可以保留。然后增加有个论文效果的链接方式。

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [X] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
如果只是需要把正文中的链接提取出来，列在文末，用jQuery很好实现。可能需要自己写一下样式表，比如书名、作者的字体等等。
其实也可以直接在Markdown中加链接？

**Comment by sli1989** [comment]
So you mean footnotes? like [this](http://saili.science/2016/10/17/markdown-user-guide/#%E8%84%9A%E6%B3%A8) using pandoc or other plugins.

**Comment by svandex** [comment]
@stevenjoezhang  markdown默认是有链接语法的，我的意思是next主题能够把显示效果做出来就好了。我不会jQuery搞不出来，所以拜托各位开发者看有没有时间加个feature

**Comment by svandex** [comment]
@sli1989 footnotes like pages on Wikipedia, see this https://en.wikipedia.org/wiki/Node.js

**Comment by svandex** [comment]
@sli1989 你也是HUSTer啊，学长幸会。我2009级的。。。

**Comment by sli1989** [comment]
> @sli1989 footnotes like pages on Wikipedia, see this https://en.wikipedia.org/wiki/Node.js

It can be down 3rd party plugins. I don't know is it possible to integrated in Next yet.

> @sli1989 你也是HUSTer啊，学长幸会。我2009级的。。。

HI, huster. 😃

**Comment by songouyang** [comment]
<https://www.ouyangsong.com/posts/55291/> 你是说像这样的吧？
![image](https://user-images.githubusercontent.com/16632254/50389812-ca63a800-0769-11e9-8924-ff0e20eabc38.png)

我用的是 [hexo-renderer-markdown-it-plus](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus)。
<details>
<summary>我的 package.json</summary>

```json
{
  "name": "hexo-site",
  "version": "1.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "gulp": "^4.0.0",
    "gulp-concat": "^2.6.1",
    "gulp-csso": "^3.0.1",
    "gulp-dom": "^1.0.0",
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^5.0.1",
    "gulp-insert": "^0.5.0",
    "gulp-pretty-data": "^0.2.0",
    "gulp-uglify": "^3.0.1",
    "hexo": "^3.8.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-autonofollow": "^1.0.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-seo-friendly-sitemap": "0.0.22",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-markdown-it-plus": "^1.0.3",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.3.3"
  },
  "scripts": {
    "prebuild": "hexo clean",
    "build": "hexo g",
    "postbuild": "gulp"
  }
}
```

</details>

**Comment by svandex** [comment]
@songgouyang 效果是这样的。不过上角标的序号是要自己打吗？最后的链接列表也是？能否自动生成，比如我文章中间突然加了一个链接可以自动填写序列？

**Comment by songouyang** [comment]
@svandex 序号需要自己打，这样才能对上号呢。不能自动生成。你一开始说的，写论文的时候也是要自己对应序号吧？

**Comment by sli1989** [comment]
No, no.
No need manually to add number-list. You can just use index keywords, like [^link1].

**Comment by songouyang** [comment]
@sli1989 [markdown-it-footnote](https://www.npmjs.com/package/markdown-it-footnote) do you mean this? 
```markdown
Here is a footnote reference,[^1] and another.[^longnote]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.
```
output html

```html
<p>Here is a footnote reference,<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup> and another.<sup class="footnote-ref"><a href="#fn2" id="fnref2">[2]</a></sup></p>
<p>This paragraph won’t be part of the note, because it
isn’t indented.</p>
<hr class="footnotes-sep">
<section class="footnotes">
<ol class="footnotes-list">
<li id="fn1"  class="footnote-item"><p>Here is the footnote. <a href="#fnref1" class="footnote-backref">↩</a></p>
</li>
<li id="fn2"  class="footnote-item"><p>Here’s one with multiple blocks.</p>
<p>Subsequent paragraphs are indented to show that they
belong to the previous footnote. <a href="#fnref2" class="footnote-backref">↩</a></p>
</li>
</ol>
</section>
```

**Comment by stevenjoezhang** [comment]
![35143422-d524bf0c-fd44-11e7-841b-bb0907b583cb](https://user-images.githubusercontent.com/16272760/54065151-447ad780-4257-11e9-9696-e0eda2575463.png)
![35143435-e00c0f1a-fd44-11e7-8300-62e732b5fbda](https://user-images.githubusercontent.com/16272760/54065152-45ac0480-4257-11e9-9922-56f32e292363.png)


See: https://github.com/theme-next/hexo-theme-next/pull/56
