### ISSUE TITLE
Mistake as code block

### ISSUE THREAD

**Issue by Holmeyoung** [theme-next/hexo-theme-next#521]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
![1](https://user-images.githubusercontent.com/18281399/50269519-64c1a400-0469-11e9-9506-bcb5f5d4fd80.PNG)

### Actual behavior 
![2](https://user-images.githubusercontent.com/18281399/50269543-7c009180-0469-11e9-9595-f01186e947bf.PNG)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v11.4.0
6.5.0

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}#   
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.17.0-1.el7.elrepo.x86_64 linux x64
node: 11.4.0
v8: 7.0.276.38-node.13
uv: 1.24.0
zlib: 1.2.11
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 3
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.0j
icu: 63.1
unicode: 11.0
cldr: 34.0
tz: 2018e

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

### Other Information 
this is my code
![3](https://user-images.githubusercontent.com/18281399/50269643-dd286500-0469-11e9-8999-8ba0aecf1ef9.PNG)

**Comment by sli1989** [comment]
add an empty line after codeblock and before Lists ?

**Comment by sli1989** [comment]
@Holmeyoung give me your original markdown code to reproduce.

**Comment by Holmeyoung** [comment]
@sli1989 

```markdown

- 解决冲突
  
  运行 `git pull` 会出现冲突
  ```sh
  Automatic merge failed; fix conflicts and then commit the result.
  ```
  参照
  > [How to resolve merge conflicts in Git](https://stackoverflow.com/questions/161813/how-to-resolve-merge-conflicts-in-git)
  
  - 设置 `vimdiff` 作为默认的 merge 工具
    ```sh
    git config merge.tool vimdiff
    git config merge.conflictstyle diff3
    git config mergetool.prompt false
    ```

  - 运行 `mergetool`
    ```sh
    git mergetool
    ```

  - `gitdiff` 会通过如下形式展示
    ```sh
    +----------------------+
    |       |      |       |
    |LOCAL  |BASE  |REMOTE |
    |       |      |       |
    +----------------------+
    |        MERGED        |
    |                      |
    +----------------------+
    ```
    这四个视图分别是
    > **LOCAL**：本地当前分支的文件
    >
    > **BASE**：共同的祖先。在本地和远端修改之前文件的样子
    >
    > **REMOTE**：合并入当前分支的远端的文件
    >
    > **MERGED**：merge 的结果。这就是我们最终要在仓库保存的状态

    可以通过 `ctrl+w` 在这些视图之间跳转。可以通过 `ctrl+w+j` 直接到达 `MERGED` 视图

    更多关于 `vimdiff` 的说明可见
    > [Vim: Move window left/right?](https://stackoverflow.com/questions/4556184/vim-move-window-left-right)
    >
    > [How do I jump to the next/prev diff in GIT difftool?](https://stackoverflow.com/questions/27151456/how-do-i-jump-to-the-next-prev-diff-in-git-difftool)

  - 可以通过如下方式编辑 `MERGED` 视图
      
    如果想从 `REMOTE` 获取改动
    ```sh
    :diffg RE  
    ```
    
    如果想从 `BASE` 获取改动
    ```sh
    :diffg BA
    ```

    如果想从 `LOCAL` 获取改动
    ```sh
    :diffg LO  
    ```

  - 保存、退出、提交、清除
      
    - 保存并从 `vi` 视图中退出
      ```sh
      :wqa
      ```
  
    - 提交改动
      ```sh
      git commit -m "message"
      ```

    - 移除由 `vimdiff` （或其他的 `diff` 工具）产生的冗余文件。例如：`*.orig`
      ```sh
      git clean
      ```
      若提示
      ```sh
      fatal: clean.requireForce defaults to true and neither -n nor -f given; refusing to clean
      ```
      则执行
      ```sh
      git clean -n
      git clean -f
      ```
```
Thanks a lot. And, i think we can communicate in Chinese. 哈哈～

**Comment by ivan-nginx** [comment]
```
- 解决冲突
  
  运行 `git pull` 会出现冲突
<!-- NEED SPACE HERE -->
```sh
  Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by Holmeyoung** [comment]
> ```
> - 解决冲突
>   
>   运行 `git pull` 会出现冲突
> 
> ```sh
>   Automatic merge failed; fix conflicts and then commit the result.
> ```

@ivan-nginx , thank you, but i have tried and it still didn't work. 

this is my full text
```markdown
	---
	title: 升级博客
	tags:
	  - 折腾
	date: 2018-12-20 01:02:39
	---


	## 升级 npm
	- 正常升级
	  ```sh
	  npm i -g npm
	  ```

	- 指定版本
	  ```sh
	  npm i -g npm@5.0.0
	  ```

	## 升级 node
	- npm中有一个模块叫做 `n` ，专门用来管理 `node.js` 版本的
	  ```sh
	  npm install -g n
	  ```
	- 安装 node
	  ```sh 
	  n stable
	  ```
	
	- 设置环境变量
	  > n 默认安装路径是 `/usr/local`，若你的 node 不是在此路径下，n 切换版本就不能把bin、lib、include、share 复制该路径中，所以我们必须通过 `N_PREFIX` 变量来修改 n 的默认node安装路径

	  修改 `~/.bashrc`
	  ```sh
	  export N_PREFIX=/usr/local #node实际安装位置
	  export PATH=$N_PREFIX/bin:$PATH
	  ```
	  使环境变量生效
	  ```sh
	  source ~/.bashrc
	  ```
	## 升级 hexo
	- 全局更新
	  
	  运行
	  ```sh
	  npm update -g
	  ```

	- 升级 hexo
	  
	  在 `hexo根目录` 运行
	  ```sh
	  npm update
	  ```

	## 升级 next
	- 进入 `themes/next`
		
	  运行
	  ```sh
	  git pull
	  ```

	- 解决冲突
	  
	  运行 `git pull` 会出现冲突
	  
          ```sh
	  Automatic merge failed; fix conflicts and then commit the result.
	  ```
	  参照
	  > [How to resolve merge conflicts in Git](https://stackoverflow.com/questions/161813/how-to-resolve-merge-conflicts-in-git)
	  
	  - 设置 `vimdiff` 作为默认的 merge 工具
		```sh
		git config merge.tool vimdiff
		git config merge.conflictstyle diff3
		git config mergetool.prompt false
		```

	  - 运行 `mergetool`
		```sh
		git mergetool
		```

	  - `gitdiff` 会通过如下形式展示
		```sh
		+----------------------+
		|       |      |       |
		|LOCAL  |BASE  |REMOTE |
		|       |      |       |
		+----------------------+
		|        MERGED        |
		|                      |
		+----------------------+
		```
		这四个视图分别是
		> **LOCAL**：本地当前分支的文件
		>
		> **BASE**：共同的祖先。在本地和远端修改之前文件的样子
		>
		> **REMOTE**：合并入当前分支的远端的文件
		>
		> **MERGED**：merge 的结果。这就是我们最终要在仓库保存的状态

		可以通过 `ctrl+w` 在这些视图之间跳转。可以通过 `ctrl+w+j` 直接到达 `MERGED` 视图

		更多关于 `vimdiff` 的说明可见
		> [Vim: Move window left/right?](https://stackoverflow.com/questions/4556184/vim-move-window-left-right)
		>
		> [How do I jump to the next/prev diff in GIT difftool?](https://stackoverflow.com/questions/27151456/how-do-i-jump-to-the-next-prev-diff-in-git-difftool)

	  - 可以通过如下方式编辑 `MERGED` 视图
		  
		如果想从 `REMOTE` 获取改动
		```sh
		:diffg RE  
		```
		
		如果想从 `BASE` 获取改动
		```sh
		:diffg BA
		```

		如果想从 `LOCAL` 获取改动
		```sh
		:diffg LO  
		```

	  - 保存、退出、提交、清除
		  
		- 保存并从 `vi` 视图中退出
		  ```sh
		  :wqa
		  ```
	  
		- 提交改动
		  ```sh
		  git commit -m "message"
		  ```

		- 移除由 `vimdiff` （或其他的 `diff` 工具）产生的冗余文件。例如：`*.orig`
		  ```sh
		  git clean
		  ```
		  若提示
		  ```sh
		  fatal: clean.requireForce defaults to true and neither -n nor -f given; refusing to clean
		  ```
		  则执行
		  ```sh
		  git clean -n
		  git clean -f
		  ```
```

**Comment by stevenjoezhang** [comment]
This should work: https://galaxymimi.com/blogpage.md

**Comment by Holmeyoung** [comment]
@stevenjoezhang It works. Thanks a lot.
