### ISSUE TITLE
adding noopener noreferrer to the js script addthis

### ISSUE THREAD

**Issue by jodumont** [theme-next/hexo-theme-next#526]
### Expected behavior 
Find a way to add, at least, `rel="noopener"`, or even better, `rel="noopener noreferrer"` in

> [<script type = "text/javascript" src = "//s7.addthis.com/js/300/addthis_widget.js#pubid={{ theme.add_this_id }}" async = "async" ></script>](https://github.com/theme-next/hexo-theme-next/blob/master/layout/_partials/share/add-this.swig)

### Actual behavior 
`target="_blank" only`

### Steps to reproduce the behavior 
1. Active your `add_this_id:`  in your Next theme

2. Launch **Lighthouse** in `Chrome` (Ctrl+Shift+I)
![image](https://user-images.githubusercontent.com/5204724/50288840-62f6e100-0467-11e9-9510-c7f24f2ffaae.png)

3. Choose to Audit the **Best practices**, than `Run audits`
![image](https://user-images.githubusercontent.com/5204724/50288871-7bff9200-0467-11e9-8210-3b94500174c1.png)

4. You will receive a similar result
![image](https://user-images.githubusercontent.com/5204724/50289493-4d82b680-0469-11e9-98c2-8dd437f4fad7.png)

PS: I see the same kind of issue with other plugins like **needmoreshare2**

**Comment by maple3142** [comment]
Maybe you can use some post-processing tool like [this one](https://github.com/liuzc/hexo-autonofollow).
Otherwise, you can use some external tool to do so. (This is how I achieve this: https://github.com/maple3142/Blog/blob/fd5fc10e78b6b45f7540cfe47ed46d350925d420/gulpfile.js#L30).

**Comment by maple3142** [comment]
@jodimont Maybe you should report this problem to `addthis` itself, because the href is added by their script.
It has nothing to do with NexT.

**Comment by ivan-nginx** [comment]
@maple3142 right. This script (http://s7.addthis.com/js/300/addthis_widget.js) loaded from 3rd-party side, as we all can see.

**Comment by jodumont** [comment]
@maple3142 and @ivan-nginx this is explain why I wasn't able to find it :)
thanks for your help
PS: I sent them an email without further expectation :)
