### ISSUE TITLE
Add Emoji support

### ISSUE THREAD

**Issue by online** [theme-next/hexo-theme-next#560]
Hello to all!

I propose to add support for emoji. Sometimes there is not enough opportunity to use emoji.

Happy New Year to all 😉

**Comment by stevenjoezhang** [comment]
Happy New Year!

You can use `hexo-filter-github-emojis` plugin 😉

**Comment by online** [comment]
@stevenjoezhang, thanks for your reply. I have not tried this plugin, but if you recommend, I will try 😉

**Comment by stevenjoezhang** [comment]
@online Does `hexo-filter-github-emojis` working fine?

**Comment by online** [comment]
@stevenjoezhang, thanks for reminding me. I didn't try this solution yet. I'll try tonight.

**Comment by online** [comment]
@stevenjoezhang, I checked the plugin [hexo-filter-github-emojis](https://github.com/crimx/hexo-filter-github-emojis), but there are problems in his work.

![Emoji_2019-03-15_221746](https://user-images.githubusercontent.com/722881/54460055-19214c80-4771-11e9-9ceb-7a6363bc8ee7.png)

**Comment by stevenjoezhang** [comment]
@online Seems `hexo-filter-github-emojis` forgot to update the json file:
https://github.com/crimx/hexo-filter-github-emojis/blob/master/emojis.json
https://api.github.com/emojis
Maybe this emoji filter can be integrated into NexT

**Comment by stevenjoezhang** [comment]
@online I know how to make it work again:
```bash
npm install hexo-filter-github-emojis
node node_modules/hexo-filter-github-emojis/update-emojis.js
```
You can have a try

**Comment by online** [comment]
@stevenjoezhang, yes, thanks, after update works fine.

**Comment by stevenjoezhang** [comment]
@online I'll work on this: https://github.com/theme-next/hexo-filter-emoji
