### ISSUE TITLE
About Tinysou and Gitment

### ISSUE THREAD

**Issue by stevenjoezhang** [theme-next/hexo-theme-next#562]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

Seems Tinysou was deprecated in 2016, and it's never introduced in `_config.yml`, see: https://github.com/iissnan/hexo-theme-next/commit/3afb544f84a0b355d12d406f52063cc24c6bcfbd
Should we remove
`layout/_third-party/search/tinysou.swig`
`layout/_partials/search/tinysou.swig`

and modify
`layout/_third-party/search/index.swig`
`layout/_partials/search/index.swig`
`layout/_partials/header/menu.swig`

To remove it completely?

Besides, Gitment is outdated too: https://github.com/imsun/gitment/issues/170
https://github.com/imsun/gitment#why-does-gitment-send-a-request-to-gh-oauthimsunnet

**Comment by ivan-nginx** [comment]
IDK about Chinese services too much. It's on your decision, guys.
