### ISSUE TITLE
May hava compatibility problem when migrate blog from Windows to masOS Mojave

### ISSUE THREAD

**Issue by AlanKeene** [theme-next/hexo-theme-next#564]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
When migrate NexT blog from window to masOS Mojave(v10.14.2), it should work fine.

### Actual behavior 
When push the blog source file on windows to repository and then pull into my mac, and after `npm install`、`hexo g`、`hexo s`. Unfortunately,  I found the the all FontAwesome icons didn't show any more but every other things are fine. And it's all right on  my  windows device.

After two days try and test, I finally found that it miss generate some files in `hexo/public/lib` directory on my mac. When my run `hexo g`, it's only generate `jquery` 、`velocity` directory on my mac. But I can see other directories on my windows device, including `algolia-instant-search`、`canvas-nest`、`canvas-ribbon`、`fastclick`、`font-awesome`、`needsharebutton`、`pace`、`ua-parser-js`.

So as you can see, there didn't generate the `font-awesome` dir in `hexo/public/lib`, that's the reason I miss all the awesome icons to show out and miss the share button also. But it didn't just miss the `font-awesome` dir and also miss so many other directories. 

After these things below I had try and test at the present, I guess it may be has compatibility problem when migrate NexT v6.1.0 theme's blog from windows to mac. As follows are these what I had try:
  
  1. I guess it may be the node version problem, on my mac the node version is latest of v11.6.0, it certainly didn't compatible with node v11+, you will found that you can't download the `fsevents` because the `fsevents` didn't support the node v11+ yet. [fsevents #244](https://github.com/strongloop/fsevents/issues/244)

     But when I downgrade my node version(v8.10.0) as the windows device, and set the environment the same as the windows device. And then have a try, it's still the some wrong. So I guess it isn't the node's problem.

  2. Maybe the hexo version's problem? So I put the hexo version(v3.8.0) the same as my windows, and try, it still can't work. So it isn't the hexo version's problem.

  3. Maybe the hexo can't compatible with the macOS Mojave(v10.14.2)? So I new a hexo directory and `hexo init`、`hexo g`、`hexo s`, it go well, I can see the icons of the defualt theme of hexo. So it isn't the hexo's compatibility problem.

   4. I use `zsh` on mac right now. Maybe the `zsh` problem? So I change the `zsh` to `bash` and try, it' s still can't work.

Above of all, I guess it may be the NexT theme have compability problem with macOS Majave(v10.14.2). But I didn't find the solution about this yet. 

And search the issues and see that `remote js css files disappeared after hexo d or git push`#37, finally he say that downgrade the macOS version would solve his this problem. But I think these are two irrelevant  problems. Also, for some reasons I can't downgrade my macOS version to test if is the latest masOS version(v10.14.2) cause this problem. 

Any other can test it and hava some solution about this? Or some experiences about migrate NexT blog from windows to mac?

### Node.js and NPM Information

```
chenpeidadeMBP:hexo alankeene$ node -v
v8.10.0
chenpeidadeMBP:hexo alankeene$ npm -v
5.6.0
```

### Package dependencies Information

```
chenpeidadeMBP:hexo alankeene$ cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.6.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-algolia": "^1.2.4",
    "hexo-deployer-git": "^0.3.1",
    "hexo-filter-optimize": "^0.2.5",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-leancloud-counter-security": "^1.3.2",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-less": "^0.2.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.4.2"
  }
}
```

#### Hexo version

```
chenpeidadeMBP:hexo alankeene$ hexo -v
hexo: 3.6.0
hexo-cli: 1.1.0
os: Darwin 18.2.0 darwin x64
http_parser: 2.7.0
node: 8.10.0
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [x] Old version  
  - NexT v6.1.0

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

### Other Information 
Window OS: win10
masOS OS: masOS Mojave(v10.14.2)

**Comment by stevenjoezhang** [comment]
> When push the blog source file on windows to repository and then pull into my mac

So, you are using git, and that make sense ... all optional external libraries in `themes/next/source/lib` are Ignored by .gitignore, that's why they're missing.
> After two days try and test, I finally found that it miss generate some files in hexo/public/lib directory on my mac. When my run hexo g, it's only generate jquery 、velocity directory on my mac. But I can see other directories on my windows device, including algolia-instant-search、canvas-nest、canvas-ribbon、fastclick、font-awesome、needsharebutton、pace、ua-parser-js.

You can try to copy and paste the `themes/next/source/lib` folder manually, and generate the site again

**Comment by AlanKeene** [comment]
@stevenjoezhang All right, thanks, it solved this problem.

**Comment by tsiq-bolunz** [comment]
I came across the exact same issue. Glad to find the solution here. Thanks!
