### ISSUE TITLE
GitLocalize members inviting

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#57]
I today created account in [GitLocalize](https://gitlocalize.com) and add there [NexT repository](https://gitlocalize.com/repo/679).

For now supported filters are:

1. All languages in `languages` directory.
2. All languages in `docs` directory.

There is some troubles with `zh-tw`, `zh-hk` and `zh-hk-Hans` (I just not understand this difference), need to resolve this and refactor language names in NexT.

So, i can invite anyone who want to accept to translation team in [GitLocalize for NexT](https://gitlocalize.com/repo/679/roles).
Just let me know what you wish to join and i'll invite you.

**Comment by tsanie** [comment]
Good, I wish to join in.

---

The **s** in the word `Hans` stands for **Simplified**, and the **t** in the word `Hant` stands for **Traditional**.

`zh-hk` and `zh-tw` are both traditional characters, default to `zh-hk-Hant` and `zh-tw-Hant`, in the most situation they are the same thing, but sometimes there is difference, like

**inside**
* zh-Hans (used in Mainland China): 里面
* zh-HK (used in HongKong): 裏面
* zh-TW (used in Taiwan): 裡面

`zh-hk-Hans` maybe the same as `zh-Hans` which is simplified characters.

---

PS: I often use the **simplified characters** (zh-Hans), and I could read the traditional characters (zh-Hant) but cannot write them. 💭

**Comment by maple3142** [comment]
I think I can help `zh-tw`.

**Comment by maple3142** [comment]
I think I can help `zh-tw`.

**Comment by ivan-nginx** [comment]
![image](https://user-images.githubusercontent.com/16944225/35149611-db472176-fd27-11e7-990a-c6e901e2246c.png)
I just not understand, see on this: there are 0 percent translated because they names different from NexT names.

In NexT there are:
1. zh-Hans.yml
2. zh-hk.yml
3. zh-tw.yml

In GitLocalize are:
1. https://gitlocalize.com/repo/679/zh-HK-Hans
2. https://gitlocalize.com/repo/679/zh-HK
3. https://gitlocalize.com/repo/679/zh-TW

So, i think need to rename in NexT this languages, but it will be **hard breaking changes**.

**Comment by tsanie** [comment]
Oh, I understand. I have just added a language `zh-Hans` in the GitLocalize.

The simplified characters should be `zh-Hans`, the `zh-HK-Hans` is the simplified characters only used in HongKong (and I think it is maybe the alias of `zh-Hans`)

**Comment by ivan-nginx** [comment]
Yeah, i see it. Good. Need just delete `zh-HK-Hans`.
And what to do with other langs? Rename? It's just caps difference.

**Comment by maple3142** [comment]
I get a message `Content You need to upgrade the plan to translate`.
And I find its [pricing page](https://gitlocalize.com/pricing) said open source project is free.

**Comment by ivan-nginx** [comment]
Yeah, it must be free for at least 1 repo, i added only NexT repo. I'll contact to them, need to wait.

**Comment by tsanie** [comment]
@ivan-nginx I think so, just rename them. 😄

**Comment by ivan-nginx** [comment]
@maple3142 no need to start to translate https://gitlocalize.com/repo/679/zh-TW

For now there is 2 langs not detected, but already translated:
1. https://gitlocalize.com/repo/679/zh-TW
2. https://gitlocalize.com/repo/679/zh-HK

See this problem above.

**Comment by maple3142** [comment]
I think need to change `zh-tw.yml` to `zh-TW.yml`, and `zh-hk.yml` to `zh-HK.yml`

**Comment by ivan-nginx** [comment]
Yes, but i told about this above: it will be hard breaking changes for NexT users.

**Comment by tsanie** [comment]
I think it should be `zh-Hans`, but now I'm a bit confusing too... 😕

**Comment by ivan-nginx** [comment]
Ok, there are some troubles with GitLocalize:
![image](https://user-images.githubusercontent.com/16944225/35151766-a96aed14-fd30-11e7-9341-7d0258730c2d.png)
![image](https://user-images.githubusercontent.com/16944225/35151839-e70ffb1e-fd30-11e7-8851-d01850da674f.png)
![image](https://user-images.githubusercontent.com/16944225/35151790-bee32e04-fd30-11e7-880e-ef48bc4e57f8.png)
This is a little bit idiotism to pay 45$ per month for just preserve 3k strings for languages.
I think need to change localization service.

**Comment by maple3142** [comment]
Isn't open source project has 20000 string for free?
[https://gitlocalize.com/pricing](https://gitlocalize.com/pricing)

**Comment by ivan-nginx** [comment]
@maple3142 yes! I don't understand why in my account i see 1k limit. I register NexT as open source with public repo. Meybe need just wait for response from support, idk.

**Comment by ivan-nginx** [comment]
@tsanie @maple3142 @wafer-li so, `zh-Hans` or `zh-CN` to set dir in the `docs` by default?

**Comment by wafer-li** [comment]
`zh-CN` will be more accurate, I think.

But in real production, we don't care about such slight difference [above](https://github.com/theme-next/hexo-theme-next/issues/57#issuecomment-358957211).
Just use `zh-Hans` is fine, since there is no **character difference** between `zh-SG` and `zh-CN`.

**Comment by tsanie** [comment]
`zh-Hans` is better I think, since there is no need to make a difference between `docs` dir and `languages` dir, let it just be the same with the filename within `languages` dir.

**Comment by sotayamashita** [comment]
@ivan-nginx 

I am Sam from GitLocalize.Thank you for reaching out to us.
We can give you our free OSS plan if you can follow these conditions:

- The OSS projects should be non-profitable
- Up to 5 repositories
- Put a note that GitLocalize is used for a localization and its project link on README.md
- If you have a website for a project, put a GitLocalize logo on the site

Let me know if you have any questions.
If no problem with above, we can give the plan.

**Comment by ivan-nginx** [comment]
@sotayamashita i already give answer by e-mail and did not notice this message was directly in Github.

So, i'll repeat message from E-Mail:
1. Yes.
2. For now only 1 repo, main repo with this theme: https://github.com/theme-next/hexo-theme-next
3. Already added. See 1 badge in main readme — `languages`.
4. Site in maintenance mode for now. So, we can take this advantage later.

We have no problem with all this conditions and want OSS free plan.

**Comment by sotayamashita** [comment]
@ivan-nginx 

> 3\. Already added. See 1 badge in main readme — languages.

Sorry. I cannot find the project link. I would appreciate if you could share the link to README.

> 4\. Site in maintenance mode for now. So, we can take this advantage later.

Sure. I'm looking forward to it.

**Comment by ivan-nginx** [comment]
@sotayamashita 

> Sorry. I cannot find the project link. I would appreciate if you could share the link to README.

https://github.com/theme-next/hexo-theme-next/blob/master/README.md
![image](https://user-images.githubusercontent.com/16944225/35185252-40e95266-fe12-11e7-9452-16a7ce214a4b.png)
First orange badge, called languages. Link to https://gitlocalize.com/repo/679 with project.

**Comment by sotayamashita** [comment]
@ivan-nginx I have changed your plan to OSS. Happy localization!!

**Comment by ivan-nginx** [comment]
@sotayamashita alright, thank you!

**Comment by maple3142** [comment]
![image](https://i.imgur.com/Jrrloh1.png)
`Content seems not same as original content`, but that text is same as [zh-Hans/README.md](theme-next/hexo-theme-next/blob/master/docs/zh-Hans/README.md)

**Comment by tsanie** [comment]
@maple3142 you can try to add {a0}...{/a0} between the `Hexo`, I just meet the same error.

**Comment by ivan-nginx** [comment]
@sotayamashita there is some bugs detected in GL service:

1. [*.md path rules cannot be synced from source](https://github.com/gitlocalize/feedback/issues/42)
2. [Order of keys in translated YAML file is corrupted](https://github.com/gitlocalize/feedback/issues/25#issuecomment-359279952)

**Comment by sotayamashita** [comment]
@ivan-nginx I have changed branch `i18n` -> `master`. Please confirm that there are no problems

**Comment by ivan-nginx** [comment]
Yes, thank's! Branch is `master`.

**Comment by sotayamashita** [comment]
@ivan-nginx I will check the bugs you mentioned

**Comment by ivan-nginx** [comment]
@sotayamashita [another bug posted](https://github.com/gitlocalize/feedback/issues/43) (word wrap not worked).

**Comment by sotayamashita** [comment]
@ivan-nginx Thank you for giving us the feedback. We try to solve the problem **ASAP**

**Comment by ivan-nginx** [comment]
> btw, I have translated some sentences into Japanese

I saw, but i recreate repo (twice, for it's 3rd) because there was bugs with source language (at start i set it as `default.yml`, but later i changed it on `_en.yml` and config can't be loaded, 404 not found was).

**Comment by ivan-nginx** [comment]
@sotayamashita and there is [another bug](https://github.com/gitlocalize/feedback/issues/45).
