### ISSUE TITLE
how to use icon without Font awesome

### ISSUE THREAD

**Issue by DamonChow** [theme-next/hexo-theme-next#571]
I want to use some custom icon.
So, How to use.

**Comment by stevenjoezhang** [comment]
What kind of icon? Like icomoon?

**Comment by DamonChow** [comment]
Local icon.

**Comment by maple3142** [comment]
There is no icon by default, so you have to include at least one icon pack to use it.

**Comment by ivan-nginx** [comment]
Need to add icon classes to provide use custom icons. And make it separated, i think. As separated library.

**Comment by mengbilitycat** [comment]
@DamonChow 
https://catrise.cn/post/5/
比如这样吗？试试吧胸滴...

**Comment by stevenjoezhang** [comment]
See also https://blog.dlzhang.com/posts/89dad1c1/
