### ISSUE TITLE
[Mist] Footer is not at the bottom of the page

### ISSUE THREAD

**Issue by invkrh** [theme-next/hexo-theme-next#573]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
在使用Mist schema时，footer应该在页面最底下，即使footer上方还有很多空间

### Actual behavior 
在使用Mist schema时，当footer会紧挨着上方的内容，从而不在页面的最下方
使用5.X版本的 Next不会有此类问题，刚更新到6.X的master，存在这个问题

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```
v3.8.0
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

### Other Information 
![image](https://user-images.githubusercontent.com/5421623/50938284-d2189180-1477-11e9-8943-4e23a488f16b.png)

**Comment by stevenjoezhang** [comment]
6.7.0更改了footer的定位方式，对Muse,Pisces和Gemini都是正常的，但是忽略了页面高度较小时Mist底部栏的美观问题...确实是个Bug

**Comment by Klausdive** [comment]
I think you might find this https://dilan140.github.io/kXHib31TAv-k_QHhp_UfjOUFIhJv4VcCawgpGVGPViLFyIaiakgdUXmE0NLQcfkZLz9Yuse5GrMJwfaw/ helpful

<blockquote></blockquote>
