### ISSUE TITLE
Insecure Content Blocked from http://schema.org

### ISSUE THREAD

**Issue by anbuchelva** [theme-next/hexo-theme-next#575]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
There should not be scripts loaded from unsafe places it should look for `https://` instead of `http://`

### Actual behavior 
webpage is referring http://schema.org/ instead of https://schema.org/

### Steps to reproduce the behavior 
1. Open a site built with Hexo-Theme-Next in chrome.
2. Look at the address bar for errors as mentioned in the screenshot.

![screenshot 151](https://user-images.githubusercontent.com/5076760/50971622-74815500-150a-11e9-9b0f-8e218ff8cd95.png)

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
-  [x] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
That's weird. Actually there's no script loaded from http://schema.org/. Only `itemtype="http://schema.org/WebPage"`, which should work fine on most browsers.
You can check this: https://support.mozilla.org/questions/1179446

**Comment by anbuchelva** [comment]
The issue happens when I access the page from a specific network.  There's no such warning when I access it from my home.

**Comment by stevenjoezhang** [comment]
Can you locate the bug? Is it caused by some other 3rd-party scripts?
