### ISSUE TITLE
Link color in modern notes with `exturl` must be same as background color

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#578]
![image](https://user-images.githubusercontent.com/16944225/51019506-70d9e680-157b-11e9-926a-cc250f331edd.png)

**Comment by stevenjoezhang** [comment]
It looks fine, I think. Maybe it doesn't matter that the color of link is different from other text?

**Comment by ivan-nginx** [comment]
For simple or flat styles – fine. But not for modern styles, i think.
