### ISSUE TITLE
Display Author Info

### ISSUE THREAD

**Issue by anbuchelva** [theme-next/hexo-theme-next#584]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
**Feature Request**
If there are more than one author write posts in a blog, we mention the author name in the post meta.  The same should be displayed in some places such as meta.

### Actual behavior 
The author name is being displayed only in the creative commons copy right notice area only. If we set the creative common copyright notice as false for each post, there's no place it is available.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
See also: https://github.com/iissnan/hexo-theme-next/pull/1804

**Comment by jiangtj** [comment]
https://github.com/theme-next/hexo-next-coauthor  Does this meet your needs?

About the author, currently hexo only supports a single author, and needs to consider how to better implement this function.

**Comment by stevenjoezhang** [comment]
I'll take your silence as the sign that the problem has been solved. Feel free to open new issues here: https://github.com/theme-next/hexo-next-coauthor
