### ISSUE TITLE
IE11 compatibility issue with 6.7.0 Gemini.

### ISSUE THREAD

**Issue by uinika** [theme-next/hexo-theme-next#587]
### Expected behavior 

Browser compatibility bug for IE11.

### Actual behavior 

 Open the hexo-theme-next 6.7.0 website with IE11, unable to display content and layout dislocation.

### NexT Information

**NexT Version:**

- [ x ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ x ] Gemini

**Comment by uinika** [comment]
企业实际生产环境当中，前端通常都会要求兼容至IE11，国内Win7 + IE11的用户占据全部PC用户的一半以上，这个是现实国情。如果这个项目总是按照团队偏好尝试使用IE11的新特性，而不考虑最为基本的兼容性（保持布局基本可用，内容完整可见），我确实只能选择使用其它皮肤，毕竟我的博客并不是写来只拥有现代浏览器的用户阅读的。

**Comment by sli1989** [comment]
Thanks, We'll consider it with discretion.

**Comment by JiangTJ** [comment]
Maybe it is different between china and world.
- https://netmarketshare.com/?options=%7B"filter"%3A%7B%7D%2C"dateLabel"%3A"Custom"%2C"attributes"%3A"share"%2C"group"%3A"browser"%2C"sort"%3A%7B"share"%3A-1%7D%2C"id"%3A"browsersDesktop"%2C"dateInterval"%3A"Monthly"%2C"dateStart"%3A"2018-12"%2C"dateEnd"%3A"2018-12"%2C"segments"%3A"-1000"%7D
- https://tongji.baidu.com/data/browser
![image](https://user-images.githubusercontent.com/15902347/51231971-4e433580-19a0-11e9-897c-11fed65ef24f.png)
![image](https://user-images.githubusercontent.com/15902347/51231990-5b602480-19a0-11e9-994d-636e007cd51b.png)
But i don't care about ie compatible, all my friends using chrome.

**Comment by uinika** [comment]
Some goverment and enterprise still choose IE11, because IE Edge must install Win10 that usually force-autoupdate and upload private info to the MS cloud. obviously,  it's not safe !

**Comment by ivan-nginx** [comment]
So, can you try to switch to [v6 branch](https://github.com/theme-next/hexo-theme-next/tree/v6.x) and check IE11 compatability?

**Comment by uinika** [comment]
![iexplore_2ptheuhpjf](https://user-images.githubusercontent.com/3454764/51235281-117c3c00-19aa-11e9-87c5-17f459dbf14f.png)

> Nothing to see in IE11

**Comment by ivan-nginx** [comment]
So, can you try to switch to [v6 branch](https://github.com/theme-next/hexo-theme-next/tree/v6.x) and check IE11 compatability?

Just switch branch from `master` to `v6`:

```bash
cd themes/next
git checkout v6.x
```

And try to repeat same steps.

**Comment by uinika** [comment]
I always use below command update my project.
```
λ git submodule update --remote
```
So there is no way to specify the exact version. but it works good when i take the  `checkout v6.7.0`.
I think `git submodule` is more elegant than the `git checkout`, I  suggesstion that push statble release into the `master` branch and push development code into the `develop`, it  should be a best practice.

**Comment by ivan-nginx** [comment]
If you want stable release version, you read installation guide here: https://theme-next.org/docs/getting-started/installation/

**Comment by JiangTJ** [comment]
https://git-scm.com/book/zh/v2/Git-工具-子模块
You can go into submodule directory and check out branch
![image](https://user-images.githubusercontent.com/15902347/51292716-c5330980-1a46-11e9-91ab-f54ba69ab1ff.png)
I'm using submodule too, and work in custom branch

**Comment by JiangTJ** [comment]
See this issue https://github.com/theme-next/hexo-theme-next/issues/567
This branching model is also best practice.
And gitlab use the similar branching model.
https://docs.gitlab.com/ee/university/training/gitlab_flow.html#release-branch
I love this!

**Comment by uinika** [comment]
IE11 works fine when checkout 6.7.0 tag.

**Comment by ivan-nginx** [comment]
But not work with `master` branch?

**Comment by JiangTJ** [comment]
[Here is my blog about git-flow](https://www.dnocm.com/articles/almond/git-flow/)
Also referred to Vincent Driessen's branching model.
I don't like Vincent Driessen's branching model, duo to it maybe cause error when the operator is not careful

**Comment by uinika** [comment]
@ivan-nginx 
Yep,  there seems to be a problem with the `master` branch, U can see my screenshot above.

**Comment by JiangTJ** [comment]
@uinika `master` branch as `v7.x` deploy branch,  it no longer supports ie

**Comment by ivan-nginx** [comment]
@uinika fix will soon, wait a little.

**Comment by ivan-nginx** [comment]
@uinika check `master` branch now (update it).

**Comment by uinika** [comment]
![iexplore_5dfc7yicw0](https://user-images.githubusercontent.com/3454764/51310386-879fa200-1a81-11e9-90ea-0c374efc104a.png)

Thanks for your help.

**Comment by stevenjoezhang** [comment]
> 企业实际生产环境当中，前端通常都会要求兼容至IE11，国内Win7 + IE11的用户占据全部PC用户的一半以上，这个是现实国情。如果这个项目总是按照团队偏好尝试使用CSS3的各类新特性，而不考虑最为基本的兼容性（保持布局基本可用，内容完整可见），我确实只能选择使用其它皮肤，毕竟我的博客并不仅仅是写来给拥有新版浏览器的用户阅读的。

https://www.microsoft.com/en-us/microsoft-365/windows/end-of-ie-support
https://zh.wikipedia.org/wiki/Internet_Explorer_11

> THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
