### ISSUE TITLE
configed with Hexo data file format  (merged themes/next/_config.yml into hexoblog/_config.yml), but when using hexo g && hexo s, no main.css file was generated in hexoblog/public/css folder

### ISSUE THREAD

**Issue by Wegome** [theme-next/hexo-theme-next#59]
configed with Hexo data file format  (merged themes/next/_config.yml into hexoblog/_config.yml), but when using hexo g && hexo s, no main.css file was generated in hexoblog/public/css folder,

and hexo s dubug showed error below:
ERROR Asset render failed: css/main.css
Error: D:/AServers/hexobdg/themes/next/source/css/_common/components/highlight/h
ighlight.styl:79:30
   75|
   76|   .gutter pre {
   77|     padding-left: 10px
   78|     padding-right: 10px
   79|     color: $highlight-gutter.color
------------------------------------^
   80|     text-align: right
   81|     background-color: $highlight-gutter.bg-color
   82|   }
...

$highlight-gutter has no property .color
    at ".gutter pre " (D:/AServers/hexobdg/themes/next/source/css/_common/compon
ents/highlight/highlight.styl:75:4)
    at ".highlight " (D:/AServers/hexobdg/themes/next/source/css/_common/compone
nts/highlight/highlight.styl:39:2)

however using both hexoblog/source/data/NexT.yml to config and the legacy Hexo 2.x way to config, there generated main.css file in hexoblog/public/css folder.

could you please help?

**Comment by Wegome** [comment]
@wafer-li sorry. updated issue.

**Comment by ivan-nginx** [comment]
Try to download latest master branch, this bug seems was fixed. Will be merged into 6.0.2 release tomorrow.

**Comment by Wegome** [comment]
@ivan-nginx ok, thanks. i'll try tomorrow.

**Comment by shijiebei2009** [comment]
> configed with Hexo data file format (merged themes/next/_config.yml into hexoblog/_config.yml), but when using hexo g && hexo s, no main.css file was generated in hexoblog/public/css folder,
> 
> and hexo s dubug showed error below:
> ERROR Asset render failed: css/main.css
> Error: D:/AServers/hexobdg/themes/next/source/css/_common/components/highlight/h
> ighlight.styl:79:30
> 75|
> 76| .gutter pre {
> 77| padding-left: 10px
> 78| padding-right: 10px
> 79| color: $highlight-gutter.color
> ------------------------------------^
> 80| text-align: right
> 81| background-color: $highlight-gutter.bg-color
> 82| }
> ...
> 
> $highlight-gutter has no property .color
> at ".gutter pre " (D:/AServers/hexobdg/themes/next/source/css/_common/compon
> ents/highlight/highlight.styl:75:4)
> at ".highlight " (D:/AServers/hexobdg/themes/next/source/css/_common/compone
> nts/highlight/highlight.styl:39:2)
> 
> however using both hexoblog/source/data/NexT.yml to config and the legacy Hexo 2.x way to config, there generated main.css file in hexoblog/public/css folder.
> 
> could you please help?

我碰到一样的问题，请问你是怎么解决的?
ERROR Asset render failed: css/main.css
Error: D:/hexo/themes/next/source/css/_common/components/highlight/highlight.styl:84:30
   80|
   81|   .gutter pre {
   82|     padding-left: 10px
   83|     padding-right: 10px
   84|     color: $highlight-gutter.color
------------------------------------^
   85|     text-align: right
   86|     background-color: $highlight-gutter.bg-color
   87|   }

$highlight-gutter has no property .color
    at ".gutter pre " (D:/hexo/themes/next/source/css/_common/components/highlight/highlight.styl:80:4)
    at ".highlight " (D:/hexo/themes/next/source/css/_common/components/highlight/highlight.styl:38:2)

**Comment by stevenjoezhang** [comment]
The styl file is malformed. Need to reinstall NexT.
