### ISSUE TITLE
meta description is missing

### ISSUE THREAD

**Issue by jodumont** [theme-next/hexo-theme-next#591]
Hi;

### Issue

I was surprise by not being able to see meta description into my header after rendering my hexo blog with next theme.

![image](https://user-images.githubusercontent.com/5204724/51458921-17ca3980-1d57-11e9-96f2-a23bcc3b7f05.png)

So I took a look inside the layout/_partials/head and header I wasn't able to find any line referring to description.

### Expected

I would expect next-theme generate a meta description if this description: is present in my _config.yml or source/_data/next.yml

What about you ?
Why it is missing or what I'm missing ?

**Comment by stevenjoezhang** [comment]
Can you provide the URL of the page which doesn’t contain meta description?

**Comment by jodumont** [comment]
sorry I forgot this detail :)
but also I found the description meta
