### ISSUE TITLE
It is possible to have a homepage/landing page ?

### ISSUE THREAD

**Issue by jodumont** [theme-next/hexo-theme-next#592]
Hi;

I look around a little bit and I did'nt find any info about it, so here my question;

#### There a way to make a homepage/landingpage with hexo theme next ?

like independently of the post my visitor will arrive always on the same page when they hit the root of my website ?

**Comment by JiangTJ** [comment]
Yeah, see this https://github.com/hexojs/hexo-generator-index, you can set blog index path, and make another landingpage that you like in root path.

**Comment by jodumont** [comment]
@JiangTJ thank for your quick and sleek answer ;)
I was probably searching for something too close to next theme so I missed looking for a general solution in hexo :+1:
