### ISSUE TITLE
In index page, external links didn't get replaced with spanned links.

### ISSUE THREAD

**Issue by yizhoumo** [theme-next/hexo-theme-next#594]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
External links should get replaced with spanned links in all pages.

### Actual behavior 
In the post page, external links got replaced. In index page, however, external links (from posts with `<!-- more -->`) didn't get replaced.

### Steps to reproduce the behavior 
1. `hexo init`
2. (IMPORTANT) In `hello-world.md`, add `<!-- more -->` after a few external links.
3. Set `theme` to `next` in hexo config.
4. Set `exturl` option to `true` in theme config.
5. Check the index page.

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.15.0
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.9.125-linuxkit linux x64
http_parser: 2.8.0
node: 10.15.0
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

```yml
theme: next
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [X] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
exturl: true
```

### Other Information 
![image](https://user-images.githubusercontent.com/4203620/51991386-fa7b3500-24e5-11e9-8b85-0230eacaf96d.png)

**Comment by stevenjoezhang** [comment]
Exturl is generated by `after_post_render` filter, just after post.excerpt generated, as you can see in https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/after_post_render/index.js and https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/after_post_render/excerpt.js. That's why external links didn't get replaced with spanned links in index page. Adding an extra argument (priority) will solve this.

**Comment by stevenjoezhang** [comment]
Fixed in #599

**Comment by 1v9** [comment]
Is it really soved? I have same issue.
https://netlify.1v9.im/
https://github.com/1v9/hexo-on-netlify

**Comment by stevenjoezhang** [comment]
Yes, it is solved. For some reason, `after_post_render` filter was not triggered on your site. I'm busy these days, so you can debug by yourself. For example, you can download a pure version of NexT and check what went wrong step by step.

**Comment by stevenjoezhang** [comment]
@1v9 I know why. PLEASE, set `categories`, `date` and `tags` in Front-matter.
https://raw.githubusercontent.com/1v9/hexo-on-netlify/master/source/_posts/hello-world.md

**Comment by 1v9** [comment]
@stevenjoezhang https://raw.githubusercontent.com/1v9/hexo-on-netlify/master/source/_posts/test.md

**Comment by 1v9** [comment]
@stevenjoezhang Thanks. I tried a fresh init for hexo & NexT and exturl is back to index, it's strange.😫

**Comment by stevenjoezhang** [comment]
Fixed again in https://github.com/theme-next/hexo-theme-next/pull/1299
