### ISSUE TITLE
It is recommended to add unionpay support in reward.  / 建议添加云闪付收款码至Reward列表

### ISSUE THREAD

**Issue by wordlesswind** [theme-next/hexo-theme-next#596]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

### Other Information 

UnionPay freely distributes the paper version of the QR code sticker, and currently has more discount activities.
银联免费发放纸质版的收款二维码贴纸，并且目前折扣活动多。

**Comment by stevenjoezhang** [comment]
Reward is now hardcoded. Maybe we should add some options to allow users to add any contents they like

**Comment by stevenjoezhang** [comment]
Added in #695
