### ISSUE TITLE
Ordered list nested in unordered list became unordered

### ISSUE THREAD

**Issue by xxwywzy** [theme-next/hexo-theme-next#601]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
when nesting an ordered list in an unordered list, the order number should perform correctly

```
- aaa
  1. bbb
```

- aaa
    1. bbb

### Actual behavior 
the ordered list became unordered

```
- aaa
  1. bbb
```

- aaa
    - bbb

### Steps to reproduce the behavior 
just type the following：

```
- aaa
  1. bbb
```

### Node.js and NPM Information

```
v8.0.0
5.0.3
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.5.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-render-pug": "^2.0.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-pandoc": "^0.2.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.2"
  }
}
```

#### Hexo version

```
hexo: 3.5.0
hexo-cli: 1.0.4
os: Darwin 18.2.0 darwin x64
http_parser: 2.7.0
node: 8.0.0
v8: 5.8.283.41
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2k
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

**Comment by stevenjoezhang** [comment]
Seems it’s not generated by NexT, thus NexT can’t solve the problem. You can open an issue in hexo-renderer-pandoc.
