### ISSUE TITLE
A small Q. about Mathjax in next

### ISSUE THREAD

**Issue by Violetqwq** [theme-next/hexo-theme-next#605]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

As a enthusiast of mathjax, I use it very frequently when wrote my blogs. I tried to use mathjax in the headlines, and it worked well in the homepage, such as:

![image](https://user-images.githubusercontent.com/47584083/52684749-3d2b1b80-2f82-11e9-9a07-4804d028f7d8.png)

However, it doesn't work in some other pages, like `tags/archives`.

As u can see, it does not support mathjax. And…If it could, I hope I can also use the mathjax in this pages, like `tags`、`archives` and the child pages of them. 

Is there any simple solutions? I really really want to use MATHJAX in these kinds of pages.>_<

I feel very, very sorry to disturb u !

**Comment by stevenjoezhang** [comment]
You can set `per_page` to `false` under `mathjax` section in `_config.yml`

**Comment by Violetqwq** [comment]
@stevenjoezhang Wow, thank u a lot>_<.
I thought if I chose `true` ，it will do "per-page" before…
I feel so sorry to take up this page for such a simple Q.
Best wishes to u!
