### ISSUE TITLE
suggestion: can we use the latest fontawesome?from v4.7 to v5. i tried and failed...

### ISSUE THREAD

**Issue by myoumeng** [theme-next/hexo-theme-next#608]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior &Actual behavior 

can we use the latest "[fontawesome](https://fontawesome.com/start)"??
i only tried to add in `themes/next/layout/_partials/head.swig`
```
<!--自己加的fontawesome--> <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
``` 
after
```
<link rel="stylesheet" href="{{ font_awesome_uri }}"/>
```

then, it did update some fonts (shows in local).
however, some fonts shows strange. like "fa fa-external-link", it cannot show in the web.

so, i feel so sad, and remove what  i have changed. everything become normal. 

how can i turn this issue into suggestion??(i am so unfamiliar with git 😢).

我在本地预览，大部分图标是正常的，但是，这个链接的符号就显示不出来了，只显示了一个正方形，相当于我的每个链接后面都有一个正方形「笑抽」。
当然了，我删除我自己加的部分后，还是正常的，只是有的新图标又变回了原来的老图标，比如：“火”（fire）.新图标的fire要比旧的fire更加大、好看（所以好想更新啊，但是按照我这样的更新，那个链接的图标就不行了）

我建议大佬们更新一下（毕竟我不太熟悉代码，随意加一段代码还是有bug），==

（怎么把这个issue变成“建议”呢？？）

**Comment by stevenjoezhang** [comment]
`fa fa-external-link` was renamed to `fab fa-external-link` in fontawesome v5 ... you can have a try
And you can join the discussion about fontawesome here: https://github.com/theme-next/hexo-theme-next/issues/505
