### ISSUE TITLE
代码块css样式错误(Code block css style error)

### ISSUE THREAD

**Issue by drrrMikado** [theme-next/hexo-theme-next#609]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
![image](https://user-images.githubusercontent.com/11224565/52909768-b602de00-32c8-11e9-9dab-0943f388738b.png)

### Actual behavior 
![image](https://user-images.githubusercontent.com/11224565/52909766-aaafb280-32c8-11e9-93d1-84e3a82abda3.png)

### Steps to reproduce the behavior 
1.  `hexo new hexo-test` and use Next theme.
2.  And `hexo server`.

### Node.js and NPM Information

```
v11.8.0
6.7.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-server": "^0.3.1"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
node: 11.8.0
v8: 7.0.276.38-node.16
uv: 1.25.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 4
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.0j
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0

```

#### Hexo Configuration

```yml
# 我就修改了这个(I just modify that)
theme: next
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
# Did not edit this file
```

### Other Information 
我使用 `tags/v7.0.0` 是正常的，就是 `master` 是异常的。
I use `tags/v7.0.0` is normal, but `master` is abnormal.

**Comment by Tarocch1** [comment]
https://github.com/theme-next/hexo-theme-next/blob/7d7078c87fef1e5c3ac3ed138c4af45124be50d3/source/js/src/utils.js#L294-L296

这里把所有的table都包上了，应该做一下区分。

**Comment by stevenjoezhang** [comment]
是的，这里疏忽了，应改成`$('table').not('figure table')`
