### ISSUE TITLE
next v6.0+ Hypercomment 评论框背景色修改为透明

### ISSUE THREAD

**Issue by tankeryang** [theme-next/hexo-theme-next#61]
next更新后Hypercomment的评论框背景色设置成了白色，一时间适应不了。
本人用的scheme是Gemini
![_20180121051420](https://user-images.githubusercontent.com/14998687/35188063-f7da2016-fe69-11e7-91aa-919958ebf85e.png)

遂着手修改其为透明
进入 ../themes/next/source/css/_schemes/Gemini 目录下，编辑 index.styl
定位到 // Comments blocks.
将
`.comments {
  padding: $content-desktop-padding;
  margin: initial;
  margin-top: sboffset;
  background: white;
  box-shadow: $box-shadow;
  border-radius: $border-radius;
}`
修改为
`.comments {
  padding: $content-desktop-padding;
  margin: initial;
  margin-top: sboffset;
  //background: white;
  background-color: transparent;
  //box-shadow: $box-shadow;
  //border-radius: $border-radius;
}`

**Comment by ivan-nginx** [comment]
Need to update at least 5.1.3 version (or better on 6.x) to style like on Alynx blog. Your blog have 5.1.2 version and have this bug in Gemini scheme.

**Comment by tankeryang** [comment]
I'm sorry. What I mean is I don't want the comment background to be white, I just want it to be transparent like v5.1.x. So I make this issue to tell somebody who use v6.x + Gemini scheme and want to set the comment background to be transparent or another color.

**Comment by ivan-nginx** [comment]
Oh, i see. U can try to write in English next time, because google translate sometimes not accurate.
