### ISSUE TITLE
leancloud stop offering analysis service

### ISSUE THREAD

**Issue by Jun-Wang-2018** [theme-next/hexo-theme-next#615]
### I agree and want to create new issue 

- [x ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 
Leancloud doesn't work. And I found a notice in my leancloud account. It says that Leancloud has already stopped offering analysis service for new users. And they will stop analysis service for regular users on 2019-02-27. It looks like this:
<img width="972" alt="2019-02-21 10 02 09" src="https://user-images.githubusercontent.com/34991818/53175310-a7992700-3626-11e9-8d2f-e45fcdc6d7fe.png">

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by Jun-Wang-2018** [comment]
Fortunately, "firestore", the other embedded tool to show the number of visitors to each article, still works.

**Comment by sli1989** [comment]
what a pity. The function works fine for me, and I haven't received this message yet.

**Comment by LEAFERx** [comment]
No need to worry. We are not using this analysis function. Actually, we are using cloud storage and its REST API to collect numbers of visitors. They are not the same.
