### ISSUE TITLE
Suggestion: add instant.page & mediumZoom

### ISSUE THREAD

**Issue by maple3142** [theme-next/hexo-theme-next#627]
How about add https://instant.page/ and [mediumZoom](https://github.com/francoischalifour/medium-zoom) into NexT?
Perhaps in external plugin form like what fancybox and others have done...

https://instant.page/ can improve website performance on modern browsers by preloading content, and it doesn't affect old browser.

[mediumZoom](https://github.com/francoischalifour/medium-zoom) is a script to provide medium-like image viewer, but it somewhat like fancybox but smaller.

Both of them are currently applied to my [website](https://blog.maple3142.net/), so what do you think about them?
It is okay to integrate them with NexT?

**Comment by 1v9** [comment]
instant,page & mediumZoom VS quicklink & fancyBox ?

**Comment by maple3142** [comment]
quicklink has bigger size and more features, and it proload pages more aggressively.
Both of them use the same api underhood.

mediumZoom and fancybox are image viewer, but they have totally different UI.
IMHO, fancybox has more features but somewhat bloated. That is why I useediumZoom instead.

**Comment by ivan-nginx** [comment]
Well, that's 3rd-party services, right? Mb it's make sense to add alternate variants for allow user to choose.

**Comment by stevenjoezhang** [comment]
Which one is better?
https://github.com/terrymun/Fluidbox
https://github.com/francoischalifour/medium-zoom

**Comment by jiangtj** [comment]
I prefer medium-zoom or fancybox, because their website is more beautiful.
