### ISSUE TITLE
unable to disable sidebar with Gemini

### ISSUE THREAD

**Issue by jodumont** [theme-next/hexo-theme-next#630]
I saw [#3421](https://github.com/hexojs/hexo/issues/3421) and @ivan-nginx kindly respond to my question [here](https://github.com/theme-next/hexo-theme-next/issues/67#issuecomment-466613399)
but I still going through the issue

### Expected
Having a single column page with **Gemini Scheme** when my header have : sidebar: false

```
---
layout: page
title: Title of this Page
sidebar: false
---

```

### Current result

I still have a 2column page even I declare `sidebar: false` in the header of my page

-----

1. Do Gemini Scheme support sidebar: false ?
2. What I'm missing ?

**Comment by stevenjoezhang** [comment]
Nope, `sidebar` option in front matter is not supported

**Comment by ivan-nginx** [comment]
#93

**Comment by jodumont** [comment]
Non of these works ;(

```
---
layout: page
title: Title of this Page
sidebar: false
---
```
```
---
layout: post
title: Title of this Post
sidebar: false
---
```
```
---
title: Title of this Post
sidebar: false
---
```

_It's might simply not my day_

**Comment by ivan-nginx** [comment]
Oh, actually this option not for show or hide sidebar. It's for Muse/Mist shemes to produce automatically slide-in/slide-out sidebar when post will opened. Detailed description here: https://github.com/theme-next/hexo-theme-next/pull/93#issuecomment-361080206
It's for this setting:
https://github.com/theme-next/hexo-theme-next/blob/61286029705d0d78d6db1762bc28d565d6e2d974/_config.yml#L247-L252

But i think we can add just show/hide sidebar on Pisces/Gemini shemes with same option.

***

I only don't understand why u want not to show sidebar on specified page?

**Comment by jodumont** [comment]
oh, to make kind of landing page
since the concept of landing page is to minimize the distraction and to bring the user to make a specific action, the sidebar act as a distraction

**Comment by stevenjoezhang** [comment]
@jodumont Add this to your markdown file:
```
<style>.sidebar-inner { display: none !important; }</style>
```
