### ISSUE TITLE
Category page shows error（/categories/index.html is different from /categories）

### ISSUE THREAD

**Issue by lzh0108** [theme-next/hexo-theme-next#633]
Such as the title

/categories/index.html is different from /categories

/categories/index.html page
![image](https://user-images.githubusercontent.com/30595408/53493512-757c3f00-3ad6-11e9-8a89-3e1c3f79bf18.png)

/categories page
![image](https://user-images.githubusercontent.com/30595408/53493557-8af16900-3ad6-11e9-8051-9917d7114870.png)

May I ask what is the reason（If you can, please tell me the answer in Chinese）

如题，我的 /categories/index.html 页面和 /categories 页面显示的不一样（如上图所示），请问是什么原因？

**Comment by stevenjoezhang** [comment]
这个应该已经被修复了，你可以下载升级到6.x或者7.x版本试试（你现在用的是v5.1.4）

**Comment by lzh0108** [comment]
> 这个应该已经被修复了，你可以下载升级到6.x或者7.x版本试试（你现在用的是v5.1.4）

好的，我试试

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/hexo-theme-next/pull/634
