### ISSUE TITLE
找不到font-awesome.min.css 等lib下的文件

### ISSUE THREAD

**Issue by littp** [theme-next/hexo-theme-next#636]
本地模拟启动的时候，完全没问题，部署到github就会出现这样的问题

![image](https://user-images.githubusercontent.com/15848626/53554583-0e649600-3b7b-11e9-83fb-8100d83207b6.png)

### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.2.0 darwin x64
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
你看下执行`hexo g`之后，`public`目录下是否存在`lib`文件夹

**Comment by littp** [comment]
> 你看下执行`hexo g`之后，`public`目录下是否存在`lib`文件夹

@stevenjoezhang 试过了 hexo g，public目录下已经有了lib，然后使用 hexo d 部署之后，线上的还是显示一样的错误。

**Comment by sli1989** [comment]
same bug with #37?

**Comment by littp** [comment]
> same bug with #37?

看起来是的，但是37 也没有解决啊

**Comment by littp** [comment]
> 你看下执行`hexo g`之后，`public`目录下是否存在`lib`文件夹



> same bug with #37?

已经解决了

macOS 之前的git忽略文件包含lib，删掉就好

>  vi ~/.gitignore_global 

>  #lib 

![image](https://user-images.githubusercontent.com/15848626/53622528-0e28d100-3c35-11e9-82bc-6c66b321e6de.png)

**Comment by stevenjoezhang** [comment]
谢谢指出，这个应该加到文档里面，提醒其他用户

Thank you for pointing out the problem. This should be added to the documentation to remind other Mac users of potential `.gitignore_global` problems.

**Comment by stevenjoezhang** [comment]
See also: https://github.com/theme-next/hexo-theme-next/issues/37
