### ISSUE TITLE
How to avoid out-of-div inline mathjax

### ISSUE THREAD

**Issue by zq1997** [theme-next/hexo-theme-next#645]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Sometime inline mathjax code is just too long, and it will be displayed out of the main div, especially on mobile devices. 
How can I add a scroll-container outside the mathjax inline code to prevent it from out-of-div? Or is it possible to make it auto breakline (break only when it is needed)?

### Actual behavior 
![screenshot_2019-03-03-21-11-37-662_com android ch](https://user-images.githubusercontent.com/17429111/53695831-775a4100-3dfb-11e9-86b5-dddfa4ff4d6f.png)

### Steps to reproduce the behavior 
Wirte `$a very long inline mathjax code$` and open the page on mobile phone, you can reproduce it.
like `$f_{k+1}=x+(k+1)=(x+k)+1=S(x+k)=Comp_1^1[S,f_k]\in{\mathcal{BF}}$`

### Node.js and NPM Information
v11.10.1
6.8.0

### Package dependencies Information
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}

#### Hexo version
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.15.0-45-generic linux x64
node: 11.10.1
v8: 7.0.276.38-node.17
uv: 1.26.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 4
llhttp: 1.1.1
http_parser: 2.8.0
openssl: 1.1.1a
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [X] All schemes(maybe)
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini(I use it)

Issue Checklist

**Comment by stevenjoezhang** [comment]
You can edit `_layout/_third-party/math/mathjax.swig`, and add `linebreaks` property manually. See: http://docs.mathjax.org/en/latest/options/output-processors/HTML-CSS.html?highlight=linebreaks

Or you can simply use displayed math instead of inline math to solve this

**Comment by sli1989** [comment]
The pr #488 had added the overflow option, but it doesn't work?

**Comment by zq-97** [comment]
@stevenjoezhang 
Nice solution and I sovled it by the following modification.
``` diff
diff --git a/layout/_third-party/math/mathjax.swig b/layout/_third-party/math/mathjax.swig
index df9b5b9..d8f0b59 100644
--- a/layout/_third-party/math/mathjax.swig
+++ b/layout/_third-party/math/mathjax.swig
@@ -4,6 +4,11 @@
   {% endif %}
 
   MathJax.Hub.Config({
+    "HTML-CSS": {
+      linebreaks: {
+        automatic: true
+      }
+    },
     tex2jax: {
       inlineMath: [ ['$', '$'], ['\\(', '\\)'] ],
       processEscapes: true,
```

**Comment by zq-97** [comment]
@sli1989 
It seems that PR works for `$$block mathjax code$$` but not `$inline mathjax code$`.
Actually, I find block code works as you show in that PR, the problem is just lies in inline code.
@sli1989 @ivan-nginx  Is it possible to add inline mathjax automatic linebreak as theme option in newer version?

**Comment by sli1989** [comment]
yeah, absolutely. waiting for optimization.

**Comment by zq-97** [comment]
I would like to show the new picture after set *automatic linebreak* option,
![screenshot_2019-03-04-14-19-47-584_com android ch](https://user-images.githubusercontent.com/17429111/53714349-fc3f6c00-3e88-11e9-8a68-ff62f84d4d1b.png)
It works perfectly except for the word align problem, as I edited in the picture, the word `成` will be better to align the bottom of mathjax code.
A liitle defect, but anaway, it works.

**Comment by sli1989** [comment]
anyway. the break of inline math is not recommended when your write your blog.

so u can use enter to use `$$` instead.

**Comment by ivan-nginx** [comment]
@sli1989 is this fine?

![image](https://user-images.githubusercontent.com/16944225/54068494-961e6480-424d-11e9-8d9a-8bd16b2a4e17.png)

**Comment by sli1989** [comment]
The demo link maybe not generated by the fixed pr.
This problem is about the inline math, but the pr above just fixed the math out of the line. @ivan-nginx

**Comment by ivan-nginx** [comment]
So, can u regenerate same with fixed PR? To be sure all work fine.

**Comment by sli1989** [comment]
Yeah, u can [this](https://test.saili.science/posts/math-test/) now.
The math out of the line works fine.

**Comment by zq-97** [comment]
@sli1989 @ivan-nginx 
[that](https://github.com/sli1989) still has problem if you swith `math settings -> math rendere` other than `HTML+CSS`.
![Screenshot_2019-03-09-19-24-37-380_com android ch2](https://user-images.githubusercontent.com/17429111/54070946-803a8f00-42a1-11e9-9366-e4a95d6bb5bf.png)

I worked for it fews day ago and found the solution, I also wrote [a blog](https://i-m.dev/posts/pnuetp.html) about it, but the blog is just in Chinese, so it may help you @sli1989.
The solution is not very elegant and I'm too lazy to describe its detail in English, that's I did not make a PR for it.

**Comment by zq-97** [comment]
Here is my solution for it.
```diff
diff --git a/layout/_third-party/math/mathjax.swig b/layout/_third-party/math/mathjax.swig
index df9b5b9..a21e093 100644
--- a/layout/_third-party/math/mathjax.swig
+++ b/layout/_third-party/math/mathjax.swig
@@ -33,15 +33,19 @@
   MathJax.Hub.Queue(function() {
     var all = MathJax.Hub.getAllJax(), i;
       for (i = 0; i < all.length; i += 1) {
-        all[i].SourceElement().parentNode.className += ' has-jax';
+        document.getElementById(all[i].inputID + '-Frame').parentNode.classList.add('has-jax');
       }
   });
 </script>
 <script src="{{ theme.math.mathjax.cdn }}"></script>
 
 <style>
-.MathJax_Display {
-  overflow-x: scroll;
+.has-jax {
+  overflow-x: auto;
   overflow-y: hidden;
 }
+
+li {
+  list-style-position: inside !important;
+}
 </style>
```
[the blog](https://i-m.dev/posts/pnuetp.html) explains for these change

**Comment by 1v9** [comment]
@zq-97 Maybe a PR? I'm not familiar with mathjax, you can contact others.

**Comment by stevenjoezhang** [comment]
Need to consider this issue: https://github.com/theme-next/hexo-theme-next/issues/658

**Comment by zq-97** [comment]
@stevenjoezhang use `auto` instead of `scroll` solves that problem.
My solution also fix it and I'm trying to make a PR @1v9 now.

**Comment by stevenjoezhang** [comment]
But some brosers (like macOS safari) won't scroll with CSS `overflow-x: auto;`

**Comment by zq-97** [comment]
![VirtualBox_MacOS_09_03_2019_20_18_35](https://user-images.githubusercontent.com/17429111/54071528-8b44ed80-42a8-11e9-8b69-f99fb4626bf7.png)
I make a test for safri but `overflow-x: auto;` works?

**Comment by 1v9** [comment]
@zq-97 @stevenjoezhang https://caniuse.com/#search=overflow-x

**Comment by stevenjoezhang** [comment]
@AlynxZhou @1v9 Thanks. Maybe I mistakenly remembered some results of the Mathjax overflow test I did in 2018. I will confirm again

**Comment by stevenjoezhang** [comment]
We are considering migrating to Mathjax3, but we have not found a way to handle inline math overflow because Mathjax3 is completely rewritten.

https://github.com/mathjax/MathJax/issues/2319 https://github.com/theme-next/hexo-theme-next/pull/1314
