### ISSUE TITLE
About the loading of some third-party libraries

### ISSUE THREAD

**Issue by stevenjoezhang** [theme-next/hexo-theme-next#655]
I'm not sure if it's because of some historical reasons, but the loading of several third-party libraries is really confusing.

## Issue 1: About mermaid and mathjax
Should we create new repo `theme-next-mermaid` or `theme-next-mathjax`? Should we move the `cdn` settings of mathjax to `vendors` section in `_config.yml`? Besides, many third-party libraries haven't been updated for a long time, e.g. the Internal version of jQuery remains 2.1.3

## Issue 2: About the loading of pdf and mathjax
The `per_page` option is not complete of all possible situations. Is it possible to use a script to detect if there's any math formulae or pdf contens in the page, then load `mathjax.js` or `pdfObject.js` with ajax?
Besides, I would like to make `pdf` a new tag. The docs of https://github.com/theme-next/hexo-theme-next/pull/466 haven't been added yet.

## Issue 3: `_third_party`?
In `layout/_layout.swig`:
https://github.com/theme-next/hexo-theme-next/blob/1a1bb451c19679ce8b9a60493cb4c4cbda6e4024/layout/_layout.swig#L118-L119
In `layout/_thire-party/scroll-cookie.swig`:
https://github.com/theme-next/hexo-theme-next/blob/1a1bb451c19679ce8b9a60493cb4c4cbda6e4024/layout/_third-party/scroll-cookie.swig#L1-L4
In `source/js/src/scroll-cookie.js`:
https://github.com/theme-next/hexo-theme-next/blob/1a1bb451c19679ce8b9a60493cb4c4cbda6e4024/source/js/src/scroll-cookie.js#L1-L25
So, why not just copy `scroll-cookie.js` to `scroll-cookie.swig`? This can reduce the times of http requests at the same time.

**Comment by maple3142** [comment]
I think it would be better to externalize all the optional libs, including their dependencies and code.
My proposal:
Create a `third-party` or `plugins` directory, and move some optional libs' implementation and dependencies to another repo.
When user want to use one, just clone (or git submodule) it into the folder and enable it through `_config.yml`.
The only thing remaining in the main repo is a `include` to the swig file in the plugin folder.

**Comment by 1v9** [comment]
* `theme.vendors.mathjax` is ok

* `per_page` is not good enough so I removed for quicklink, I think a uniform script can solve these problems.

* keep js like js, keep swig like swig?

**Comment by stevenjoezhang** [comment]
@maple3142 Agree, git-submodule is a good idea.
The `_config.yml` is over 1000 lines now... it's almost impossible for new users to understand what they should configure without reading all the docs.
@1v9 It can be implemented like this:
`{% mermaid %} ... {% endmermaid %}` -> `<pre class="mermaid"></pre>`
```
if ($("body").find(".mermaid")) {
     $.getScript("mermain.js", () => { ... });
}
```

**Comment by 1v9** [comment]
Maybe checkout a new branch such as dev, do the huge job over there, if it's good enough then we can merge to master, also many docs need to update.

**Comment by JiangTJ** [comment]
> When user want to use one, just clone (or git submodule) it into the folder and enable it through `_config.yml`.

I think if possible, once cloning is enabled automatically. And they have their own configuration files that we can custom. Or overwrite it in the main configuration file. 
But it seems unrealistic in hexo.

**Comment by stevenjoezhang** [comment]
Related issues: #318, #413 and #564

**Comment by stevenjoezhang** [comment]
@ivan-nginx How do you think? Many `theme-next-*` repos are out of date. Need someone to maintain them, or we just change the way to manage these third-party packages.
![2019-03-06 11 51 27](https://user-images.githubusercontent.com/16272760/53894626-644da800-406b-11e9-9ee4-b276cc812517.png)

**Comment by ivan-nginx** [comment]
@stevenjoezhang Oh, it's a little bit hard, I agree. But we need for provide end-user to choose what he want tu use: CDN or local files. Because in own server-use cases local files can joined into 1 request via HTTP2 protocol and site will load faster.

**Comment by ivan-nginx** [comment]
Ok, let's I show my vision on it.

### About mermaid and mathjax

> Should we create new repo `theme-next-mermaid` or `theme-next-mathjax`?

Yes, we should.

> Should we move the `cdn` settings of mathjax to `vendors` section in `_config.yml`?

Yes, we should.

> Besides, many third-party libraries haven't been updated for a long time, e.g. the Internal version of jQuery remains 2.1.3

I think in the distant future we can cutted out jQuery totally.

### About the loading of pdf and mathjax

> The `per_page` option is not complete of all possible situations. Is it possible to use a script to detect if there's any math formulae or pdf contens in the page, then load `mathjax.js` or `pdfObject.js` with ajax?
Besides, I would like to make `pdf` a new tag. The docs of https://github.com/theme-next/hexo-theme-next/pull/466 haven't been added yet.

I think u already get the solution for this.

### _third_party?

> So, why not just copy `scroll-cookie.js` to `scroll-cookie.swig`? This can reduce the times of http requests at the same time.

Yes, wiser will be to do that. In previous your PR I just talking about: no need to join Features & Bugfixes & Optimizations at once because if we will want to revert PR, PR will be reverted with all changes.. If it's Feature – create PR with Feature only; if Optimization – with Optimization. I know what sometimes when you modify code, you just modify other and other and other things, because you see something like bug and your hands want to «autofix» it. I reccomended to learn and use `stash` & `pop` in Git for that; it's something like backup current changes: when you didn't finish some feature and in same time find a bug, you can just `stash` current feature changes, when fix bug with further commit / PR and after that – `pop` your previous stash (feature changes).

**Comment by stevenjoezhang** [comment]
Superseded by https://github.com/next-theme/plugins
