### ISSUE TITLE
Maintenance conditions

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#670]
For now, as we can all see, [MIMI](https://github.com/stevenjoezhang) is the topest contributor. So, if I will be out-off, Mimi will be admin of my place. He think what I think. And I also glad for that. So, guys, resume to growing NexT for all of us. It's a little bit hard, but it's little bit easy.

Alex, Maple, liolok and other contrubutors, I don't forgot about u. Don't forget your dream. It's will rollback with the time.

**Comment by stevenjoezhang** [comment]
Thanks for your trust. NexT is the first large project I participated in, and I am very happy to see it continue to develop and improve. Thanks to every contributor and maintainer for making the open source community better ❤️

**Comment by sli1989** [comment]
😄 +1 👏 
PS 我是摸鱼的
