### ISSUE TITLE
Disqus makes velocity dead

### ISSUE THREAD

**Issue by Songkeys** [theme-next/hexo-theme-next#673]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The disqus works fine with velocity.

### Actual behavior 
Both cannot work together.
The console said `Uncaught TypeError: $(...).velocity is not a function` if disqus is enabled.

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
disqus:
  enable: true
  shortname: #yourname
  count: true
  lazyload: false
```

### Other Information 

I found that the problem is with disqus comment count for each post on index page.

When I disabled `disqus.count`, it works fine.

And when I try to disable velocity instead, the Sidebar won't appear in Gemini. Console:
```
Uncaught TypeError: sidebarInner.affix is not a function
    at initAffix (pisces.js?v=7.0.1:28)
    at HTMLDocument.<anonymous> (pisces.js?v=7.0.1:55)
    at j (jquery.js:3094)
    at Object.fireWith [as resolveWith] (jquery.js:3206)
    at Function.ready (jquery.js:3412)
    at HTMLDocument.I (jquery.js:3428)
```

**Comment by Songkeys** [comment]
Update:

I'm not sure but this commit might need checking: <https://github.com/theme-next/hexo-theme-next/commit/0926ec4c73cb72d537daec945fa0ccc56933b706>. Cuz it's the only latest commit related to the comment count display on index page...?

**Comment by stevenjoezhang** [comment]
Not sure... maybe disqus changed their script?

**Comment by Songkeys** [comment]
@stevenjoezhang 

That's reasonable... Cuz this problem occurred only since today. And I didn't do anything on my site actually.

**Comment by JiangTJ** [comment]
> When I disabled `disqus.count`, it works fine.

Disabled too, as temporary solution, QwQ
Thank U

**Comment by sealedace** [comment]
This problem does occur since today. Two days ago it was running fine at least.
And I enabled disqus too ...😂

**Comment by sparkydogX** [comment]
I encounter the same problem today. 
It works fine when disable disqus. 
Maybe disqus update their script 😒

**Comment by 31415926535x** [comment]
I encounter this problem yesterday, too. I thought I may make some mistakes when I updated my blog, lost one day to try to solve it, then I see this issue. Now it works again, thx. 😂

**Comment by stevenjoezhang** [comment]
More information: https://disqus.com/home/discussion/channel-discussdisqus/installation_disqus_suddenly_includes_its_own_jquery_version/

**Comment by stevenjoezhang** [comment]
Issue seems to be resolved now. You can confirm it.
