### ISSUE TITLE
Algolia Search needs application Key

### ISSUE THREAD

**Issue by wafer-li** [theme-next/hexo-theme-next#68]
To be simple:

Let's see here:
https://github.com/theme-next/hexo-theme-next/blob/e12bb0b27e16072eb82baa4c7dda1c41c8de7264/source/js/src/algolia-search.js#L6-L8

It needs an application key and etc.

So, where does it come from? Here:

https://github.com/theme-next/hexo-theme-next/blob/1cb4d086bd31c061764ceadddc82a729e4dc3fd5/layout/_partials/head/head.swig#L124-L130

It should be an application key field in the config.

https://github.com/theme-next/hexo-theme-next/blob/7e71b4ba4c66a49c477065704210a71e9357e6e8/_config.yml#L641-L648

Without it, it will complain about the Algolia Setting is invalid.

In fact, in the NexT 5.1.x, there is a [doc](http://theme-next.iissnan.com/third-party-services.html#algolia-search) describe the application keys:

![image](https://user-images.githubusercontent.com/12459199/35233814-855e709e-ffe2-11e7-8ff2-c69747ac8c21.png)

**Comment by sli1989** [comment]
i am going to take a  PR in [theme-next-algolia-instant-search](https://github.com/theme-next/theme-next-algolia-instant-search) to add the configurations, and wondering how to index the content with the latest hexo-Algolia.
