### ISSUE TITLE
Tabs tag overflow bug

### ISSUE THREAD

**Issue by online** [theme-next/hexo-theme-next#691]
Hi to all.

To reproduce the bug you need to open the page "[Getting Started](https://theme-next.org/docs/getting-started/)" on mobile device. Here is my screenshot:

![IMG_20190315_212828](https://user-images.githubusercontent.com/722881/54457160-5c77bd00-4769-11e9-83a1-7f3ca8c0c0d6.jpg)

**Comment by 1v9** [comment]
Related to screen width? I'm not sure.

**Comment by stevenjoezhang** [comment]
Reproduced on my iPhone ...
![IMG_1177](https://user-images.githubusercontent.com/16272760/54470360-70f79c00-47e1-11e9-84f2-7620c2c38277.PNG)
But it looks fine in Chrome's simulator... don't know why
![屏幕快照 2019-03-16 上午11 48 10](https://user-images.githubusercontent.com/16272760/54470361-7523b980-47e1-11e9-8a76-2d42a1ffdfc5.png)

**Comment by 1v9** [comment]
@stevenjoezhang reproduced in simulator responsive mode, drag screen...

**Comment by stevenjoezhang** [comment]
Ah... need to update this file: https://github.com/theme-next/hexo-theme-next/blob/master/source/css/_common/components/tags/tabs.styl
to make tabs more responsive

**Comment by ivan-nginx** [comment]
https://github.com/theme-next/hexo-theme-next/blob/20abf291fb24c92ed18f3393ea7b79ae53fdf7af/source/css/_common/components/tags/tabs.styl#L13-L17

**Flex:**
![image](https://user-images.githubusercontent.com/16944225/54471633-5eb73700-47bc-11e9-95ef-dd9fb932f373.png)

**Block:**
![image](https://user-images.githubusercontent.com/16944225/54471638-6e368000-47bc-11e9-928a-0c17dcd68f69.png)

And other borders & marigns in this file...

**Comment by stevenjoezhang** [comment]
How about tabs like this:
![下载](https://user-images.githubusercontent.com/16272760/54476537-9adcad00-4839-11e9-9689-065dc738c8da.jpeg)
Using `float: left`

**Comment by JiangTJ** [comment]
![image](https://user-images.githubusercontent.com/15902347/54476647-c0b68180-483a-11e9-920a-f9de9a01f90b.png)
Or vertical? 😹 
Referenced：https://getbootstrap.com/docs/4.3/components/navs/#vertical
Example： https://www.dnocm.com/more/tools/
Code：https://raw.githubusercontent.com/JiangTJ/blog/master/source/more/tools/index.md

**Comment by ivan-nginx** [comment]
> How about tabs like this:
> ![下载](https://user-images.githubusercontent.com/16272760/54476537-9adcad00-4839-11e9-9689-065dc738c8da.jpeg)
> Using `float: left`

Seems good too. Need just to fix this bug.

**Comment by stevenjoezhang** [comment]
See also https://github.com/next-theme/hexo-theme-next/commit/eb4388f8b432f7e13b7db035555a5c5f2e3c4744
