### ISSUE TITLE
One more bug in mobile layout on theme-next.org

### ISSUE THREAD

**Issue by online** [theme-next/hexo-theme-next#696]
Hello.

I discovered such problem:

![IMG_20190316_114726](https://user-images.githubusercontent.com/722881/54473510-748b2300-47e1-11e9-9c1f-8d2defd47d4a.jpg)

**Comment by stevenjoezhang** [comment]
Maybe a side effcet of https://github.com/theme-next/hexo-theme-next/pull/669

**Comment by stevenjoezhang** [comment]
It's a bug when `mobile_layout_economy` enabled

**Comment by ivan-nginx** [comment]
Emm, not exactly. When `mobile_layout_economy` enabled just marign-right styles for some pixels need to add. But without mobile option we can see bug with brackets too:
![image](https://user-images.githubusercontent.com/16944225/54474374-2e838e80-47e4-11e9-8b55-0557d3ea030d.png)

**Comment by stevenjoezhang** [comment]
@ivan-nginx Maybe it's not bug with brackets, but `exturl`. `word-wrap` doesn't work correctly because `exturl` creates an extra `<span>` element
