### ISSUE TITLE
Roadmap vs. Project Cards

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#698]
I was see some [disputes about Roadmap](https://github.com/theme-next/hexo-theme-next/issues/586#issuecomment-469947620).
So, we need to decide what we will use.

1. Keep going to resume Roadmap. But what we will do with Projects then? Remove?
2. Smoothly end checkboxes in Roadmap, close it and new Issues tagged under Projects.

Why we need to have both Roadmap and Projects cards? It makes no sense and this bring more work.

***

Ok, let's think about it from point of view practicality:

* Roadmap in one place, and this is good.
  But Cards will be in one place too after setting Project on issue. **[draw]**
* When adding in Roadmap we need to set «Roadmap» label on issue, open Roadmap Issue, find where we can checkbox and how he will called, and, paste link to issue near that checkbox.
  And when we add to card, we will define Project on issue faster and then just define to that issue priority in Projects tabs (if needed). **[W2]**
* Every time Roadmap issue growing more and more. More checkboxes, more comments. Revisions are hard for viewing and impossible to editing (only delete is possible). BTW, when I edit Roadmap issue I always use browser search by issue number to find what I need...
  Cards editing more simply. They can be archived or deleted. They easier for visual perception, they colorized and we see all tags on all issues directly from Cards. And we can open issues directly inside Projects tab by clicking on any Card. **[W2]**
* And finally, when we close issue with Feature Request or Bug Fix, we need to go in Roadmap, find that issue for editing it again, checking box for this issue and adding corresponding Pull in which this issue was Solved.
  Cards will closed automatically. If issue was closed (auto-closing by Pull), card will auto-obtain Solved status too. **[W2]**
  ![image](https://user-images.githubusercontent.com/16944225/54474776-6fca6d00-47e9-11e9-9386-70dda001671d.png)

***

So, dudes, need to think about it and vote for better variant. With smooth closing of Roadmap issue. They don't was automatically several years ago, that's why I was create Roadmap. But for now we have another situation and can save our time easily.

## Voting

http://www.easypolls.net/poll.html?p=5c8ce46be4b070a0255c16f5

**Comment by stevenjoezhang** [comment]
Suggestion: Stop using roadmap after all item checked in https://github.com/theme-next/hexo-theme-next/issues/67

**Comment by ivan-nginx** [comment]
> Suggestion: Stop using roadmap after all item checked in #67

Exactly! If votes will be for Cards, from this moment all new [issues with Requested Features](https://github.com/theme-next/hexo-theme-next/projects/3) or [issues with Bug Reports](https://github.com/theme-next/hexo-theme-next/projects/2) we will add into the [Project Cards](https://github.com/theme-next/hexo-theme-next/projects), fine?
