### ISSUE TITLE
Interactive International Chat

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#699]
At last days I have some troubles with communication to some of other collaborators. For example, I never see @stevenjoezhang and @1v9 and some other dudes in one of the supported by NexT chat.

For now I communicate with them via GitHub Reviews and / or Comments. And this no good. I can to explain same things in any interactive Chat for 10-20 minutes without flooding in GitHub.

I also understand what in China providers block some clients like Telegram and I suggest to find any universal chat or platform, which no one provider will not (or will can't) block, never.

For now I communicate with 3 clients:

* [Telegram](https://t.me/theme_next) → always there, but CN providers block it, as hear. Is it true or not?
* [Gitter](https://gitter.im/theme-next) → almost always there too, because we install bridge with bot for auto-resending messages: Telegram ←→ Gitter (remember, Alex? :smiley: )
* [Riot](https://riot.im/app/#/room/#NexT:matrix.org) → Same as with Gitter: bridge connected to Gitter / Telegram. BTW, because Riot use Matrix for messages, hes can't be blocked by any provider.

So, if anyone will be write in one of this chat, another side will see messages in any another chat. But! It only for group chats, not for private messages.

Any suggestions, mans? How we will to communicate?

**Comment by 1v9** [comment]
Telegram has been blocked in China through blocking SMS verification and network.
Gitter and Riot is ok.

**Comment by JiangTJ** [comment]
Telegram is the best chat software I've ever seen. The only downside is that it has been blocked in China.
