### ISSUE TITLE
Split config on pieces under categories

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#703]
First question: is it good or not?

From one side we can see all settings in one file and use search with CTRL + F.
From another side config is too big and sometimes we need just set true for one option, but file will changed entirely (for developers) or we search option but forget her name (for users), and this situation often repeats even if you know NexT a long time...
But what will be with new users? They will be probably shocked.

So, we need to cut NexT config or not? I already have 1 idea how to try to implement this feature.

[![](https://api.gh-polls.com/poll/01D7BJ86H43WX8C47VXX42V186/yes)](https://api.gh-polls.com/poll/01D7BJ86H43WX8C47VXX42V186/yes/vote)
[![](https://api.gh-polls.com/poll/01D7BJ86H43WX8C47VXX42V186/no)](https://api.gh-polls.com/poll/01D7BJ86H43WX8C47VXX42V186/no/vote)

**Comment by stevenjoezhang** [comment]
I agree, it's really necessary because `_config.yml` is nearly 1200 lines now. New users will be confused about how to get start.

**Comment by liolok** [comment]
We'll need to discuss how to split to get to a balance between "config line number in each file" and "file number". The category is important.

**Comment by ivan-nginx** [comment]
Under categories, of course. Like in website.

**Comment by stevenjoezhang** [comment]
Or we just move the `vendors` part (advanced settings) away? And remove some comment settings (discussion in https://github.com/theme-next/hexo-theme-next/issues/788). `_config.yml` will be much clearer.

**Comment by stevenjoezhang** [comment]
After about a year, the configuration file has been reduced to ~1000 lines.
