### ISSUE TITLE
Prevent the header from disappearing when scrolling down with Pisces / Gemini

### ISSUE THREAD

**Issue by echebbi** [theme-next/hexo-theme-next#708]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

I'd like to fix the positions of both the header and the sidebar so that the reader can see both of them while reading.

### Actual behavior 

The header gradually disappears at the top of the window as the reader scrolls down.

### Steps to reproduce the behavior 
1. Create a blog with Pisces or Gemini
2. Scroll down

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.15.0
6.4.1
6.4.1
```

### Package dependencies Information
N/A

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.15.0
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

N/A

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [x] Gemini

#### NexT Configuration:

N/A

### Other Information 

I'm ready to modify theme's code if necessary but I didn't managed to implement a solution without breaking the responsiveness.

**Comment by stevenjoezhang** [comment]
What's your expected behavior if the sum of the height of the header and the sidebar is greater than the height of the page?

**Comment by KazeJiyu** [comment]
In such a situation the actual behavior suits me.

**Comment by KazeJiyu** [comment]
Could anyone explain to me how I could achieve this, or should I wait for a contributor to implement the feature?

**Comment by stevenjoezhang** [comment]
@echebbi Solution here:

Replace

https://github.com/theme-next/hexo-theme-next/blob/156ba15fbaae35d3f68e6f8ec35273139ed9b85d/source/js/schemes/pisces.js#L22-L35
With

```
$('.header-inner, .sidebar').css('position', 'fixed');
```
