### ISSUE TITLE
Render failed in mobile using script

### ISSUE THREAD

**Issue by sli1989** [theme-next/hexo-theme-next#71]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

Render success in web & mobile circumstance.

### Actual behavior 

Render success in web but failed in mobile circumstance using `<script type="text/javascript" src="http://www.xiami.com/widget/player-single?uid=0&sid=1775449134&mode=js"></script>` in `.md` file.

And the post content in mobile with muse scheme are not `text-align=justify`.

![2018-01-23_122019](https://user-images.githubusercontent.com/8521181/35258176-b17d9686-0038-11e8-9703-538deaeb757f.png)

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
This is 3rd-party not NexT script, i can't help u.
