### ISSUE TITLE
«DeprecationWarning: Buffer()» in node v10.x

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#712]
![image](https://user-images.githubusercontent.com/16944225/54603932-d9df4e00-4a45-11e9-918d-73571b1a2b16.png)

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/pull/599/files
Not solved?

**Comment by ivan-nginx** [comment]
OMG, my fault. I was on v6.x branch. In v7.x (master branch) already solved.

**Comment by stevenjoezhang** [comment]
Maybe we should fix this in v6x branch, using `Buffer.from` instead of `Buffer`?

**Comment by ivan-nginx** [comment]
Because in #599 pull label v6.x exists, I'll merge this pull before releasing. Don't worry about it.
