### ISSUE TITLE
Disable TOC for any post

### ISSUE THREAD

**Issue by Aqua-Dream** [theme-next/hexo-theme-next#715]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
In the front-matter of any post, we can set `toc=false`, so that there would be no TOC for this post, even if there are `<h1>, <h2>, ...` labels in this post. I need this because I'm writing my own 404 page which contains title labels (h1 and h2). It could be strange if I do not disable TOC for this page. You may argue that I can set "sidebar=false", but the user can still click the button to show the TOC of this page.

![404](http://cdn.aqua.hk.cn/404.png)

### Actual behavior 
No choice.

* Link to demo site with this feature: N/A
* Link(s) to source code or any usefull link(s): N/A

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by stevenjoezhang** [comment]
How about using `font-size` settings instead of using `<h1>` `<h2>`

**Comment by stevenjoezhang** [comment]
Or add this script to the page:
```
$(".post-toc-wrap, .sidebar-nav").hide();
$(".site-overview-wrap").addClass("sidebar-panel-active");
```

**Comment by Aqua-Dream** [comment]
@stevenjoezhang Thanks for your suggestion. Actually I've disabled TOC by modifying "themes/next/layout/_macro/sidebar.swig" and wrote `set display_toc =... and page.type != "404"`, which can solve my problem. 

I opened this issue because I was considering there may be other people who want to disable TOC, possibly because of the same reason or not.

**Comment by stevenjoezhang** [comment]
@Aqua-Dream Thank you, I will add it to the docs to let more people know
