### ISSUE TITLE
Please consider to support PayPal donate button for reward.

### ISSUE THREAD

**Issue by Liam0205** [theme-next/hexo-theme-next#717]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

One could easily configure the donate button of PayPal.

![image](https://user-images.githubusercontent.com/3348485/54737035-f7005200-4be8-11e9-8622-8862463a1a1b.png)

### Actual behavior 

One will have to hack the code of reward layout.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this feature: https://liam.page/2019/03/19/compile-and-install-Python-3-7-2-on-CentOS-7/
* Link(s) to source code or any usefull link(s): https://github.com/Liam0205/hexo-theme-next/blob/liam/layout/_partials/post/reward.swig#L22-L36

**NexT Scheme:**

- [X] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by JiangTJ** [comment]
https://github.com/theme-next/hexo-theme-next/pull/695 Maybe it's done.

**Comment by Liam0205** [comment]
@JiangTJ No. 'cuz PayPal doesn't provide a QRcode for cash transfer (for donating), but a button, which is not supported by that PR.

**Comment by JiangTJ** [comment]
😰 好吧~没用过paypal,不清楚

**Comment by stevenjoezhang** [comment]
https://www.paypal-community.com/t5/About-Payments/how-to-QR-code-scan-to-make-a-payment-through-PayPal/td-p/1319724

**Comment by Liam0205** [comment]
> https://www.paypal-community.com/t5/About-Payments/how-to-QR-code-scan-to-make-a-payment-through-PayPal/td-p/1319724

Just in your URL, see the reply:

> There's no built in PayPal account features for creating QR Codes so you have to go outside the box.

**Comment by stevenjoezhang** [comment]
> Find an online free barcode generator, scan your PayPal.ME URL and generate the QR Code.   You can then use an app on your smart phone that reads QR Codes.

**Comment by Liam0205** [comment]
> > Find an online free barcode generator, scan your PayPal.ME URL and generate the QR Code.   You can then use an app on your smart phone that reads QR Codes.

That's not a workaround for me.

Scan that kind of QRcode open the link of PayPal.ME, but not PayPal app itself. User will have to do a series of action to complete the donate process. What's more, business account is required, which is a strict drawback.

**Comment by stevenjoezhang** [comment]
Seems that you have already implemented this feature. How do you like to open a PR?

**Comment by Liam0205** [comment]
> Seems that you have already implemented this feature. How do you like to open a PR?

Well, yes.

However, that's just an ugly workaround. As you might have noticed from the Telegram group, I'm not good at HTML/CSS bundles. If possible, re-implement it in a right or more elegant way would be a better choice.

**Comment by Liam0205** [comment]
> But it will make `_config.yml` longer... maybe we should deal with this: #703 first

Okay, I could fully understand. The team of course has its roadmap, and since I have my own workaround, it's not a urgent feature request --- at least for me, myself.

**Comment by ivan-nginx** [comment]
> But it will make `_config.yml` longer... maybe we should deal with this: #703 first

No, no config longer! Just longer docs & link from config to docs. :100:

**Comment by stevenjoezhang** [comment]
Yes, we can move the docs to the theme-next.org site first...

**Comment by ivan-nginx** [comment]
I think he want to add only PP button to separated donation or something like this. It's can be added to `custom.swig` in sidebar, for example.

**Comment by Liam0205** [comment]
I'm not sure why PayPal doesn't support QRCode donation, and it seems that PayPal is the only one who doesn't support that, in main stream E-Cash applications. Hence, in my point of view, adding an exception is acceptable. Here, exception means [here](https://github.com/Liam0205/hexo-theme-next/blob/liam/layout/_partials/post/reward.swig#L9-L10) and [here](https://github.com/Liam0205/hexo-theme-next/blob/liam/layout/_partials/post/reward.swig#L24-L37).

**Comment by Liam0205** [comment]
> I think he want to add only PP button to separated donation or something like this. It's can be added to `custom.swig` in sidebar, for example.

Yes, adding to `custom.swig` is an option, but not for me. Making donation entrance together, at the bottom of posts, seems better.

**Comment by stevenjoezhang** [comment]
Paypal is different from some services that distinguish users only by their ids - it provides QR Code and a high level of customization now.

https://www.paypal.com/donate/buttons

Integrating the Paypal button into NexT makes it difficult for users to customize. We recommend that users copy the code themselves into `custom.swig`.

😢
