### ISSUE TITLE
How to close creative_commons in a specific article？怎么在特定文章里关闭版权声明

### ISSUE THREAD

**Issue by wyx1818** [theme-next/hexo-theme-next#720]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
在某些转载的文章里关闭版权信息，可以像下面一样在文章里单独设置来关闭么

```
---yml
title: title-name
date: 2018-11-05
...
copyright: true/false
---
```

### Actual behavior 
在_config.yml中设置后所有文章都附带了版权信息

``` yml
 license: by-nc-sa
  sidebar: false
  post: true
  language:
```

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
Try this:
```md
<style>.post-copyright{display:none}</style>
```

**Comment by wyx1818** [comment]
> Try this:
> 
> ```lisp
> <style>.post-copyright{display:none}</style>
> ```

Thank you for your prompt reply. I succeeded.
