### ISSUE TITLE
Extra new line on footnote

### ISSUE THREAD

**Issue by Aqua-Dream** [theme-next/hexo-theme-next#721]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I'm using hexo-renderer-markdown-it-plus to support footnote. My source file is
``` md
---
title: test
date: 2019-03-21 00:31:06
tags:
---

Footnote test[^1].

[^1]: https://tieba.baidu.com/p/3551069391
```
So I expect the footnote should be
```
1. https://tieba.baidu.com/p/3551069391
```

### Actual behavior 
However, it is actually
```
1.
https://tieba.baidu.com/p/3551069391
```
As the following picture shows. Or you can also go to "https://aqua.hk.cn/Algorithm/plixxc/" to see the generated html. I find the problem is that the style of tag `<p>` is actually `display: block;`. After changing it to `display: contents`, there is no problem.

![image](https://user-images.githubusercontent.com/17526818/54798606-78f98500-4c94-11e9-87d9-aaeed2da3565.png)

### Steps to reproduce the behavior 

* Link to demo site with this bug: https://aqua.hk.cn/Algorithm/plixxc/

### Package dependencies Information

```
dependencies": {
    "hexo": "^3.8.0",
    "hexo-all-minifier": "^0.5.3",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-markdown-it-plus": "^1.0.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.4.4"
  }
```

#### Hexo version

```
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.15.1
v8: 6.8.275.32-node.12
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by stevenjoezhang** [comment]
Add this to `custom.styl`:
```css
ol.footnotes-list li p {
    display: contents;
}
```

**Comment by Aqua-Dream** [comment]
Thanks!

**Comment by Aqua-Dream** [comment]
@stevenjoezhang The problem is caused by this pull (https://github.com/theme-next/hexo-theme-next/pull/669) by setting the global style of `li` as "list-style-position: inside". Besides, this setting makes all the indents of `li` look too long. Please have a check!

**Comment by stevenjoezhang** [comment]
@Aqua-Dream I know, and I have checked... Do you have any good idea to solve this: https://stackoverflow.com/questions/21769248/list-with-nested-overflow-x-hidden-hides-list-counter-point-why-is-this-a-b , without setting `list-style-position: inside`?

**Comment by Aqua-Dream** [comment]
My Chrome works well in this case:
![image](https://user-images.githubusercontent.com/17526818/54874304-5cd81e00-4e23-11e9-9078-43d09489b558.png)

**Comment by stevenjoezhang** [comment]
In some cases there will be problems, such as the mathjax formula inside `<li>` element...

**Comment by Aqua-Dream** [comment]
Is it the default behavior of Mathjax or else...? It seems that my demo (katex) also works well:

``` md
---
title: test
date: 2019-03-24 11:09:59
tags:
mathjax: true
---
 - blablablablablablablablablabla 
 - blablablablablablablabla $f_{k+1}=x+(k+1)=(x+k)+1=S(x+k)=Comp_1^1[S,f_k]\in{\mathcal{BF}}=f_{k+1}=x+(k+1)=(x+k)+1=S(x+k)=Comp_1^1[S,f_k]\in{\mathcal{BF}}$
```

![image](https://user-images.githubusercontent.com/17526818/54874412-bc372d80-4e25-11e9-8455-9aa88ceb6b03.png)

**Comment by stevenjoezhang** [comment]
Seems only mathjax will broke the list style:
![屏幕快照 2019-03-24 上午11 26 36](https://user-images.githubusercontent.com/16272760/54874521-f99cba80-4e27-11e9-8c46-890f594dc900.png)
![屏幕快照 2019-03-24 上午11 26 43](https://user-images.githubusercontent.com/16272760/54874522-fa355100-4e27-11e9-9d64-eb6423c97e10.png)

Need to modify `source/css/_common/components/third-party/third-party.styl`

**Comment by Aqua-Dream** [comment]
Since each `li` tag corresponds to a `ul` or `ol` tag, my suggestion is to set overflow on `ul` and `ol` instead of `li`. BTW, in the block math mode of Katex, the equation can also overflow if it is too long. Maybe you need to consider how to add `has-jax` in Katex.

Personally, I will vote for keeping the default behavior (without setting overflow or anything) to avoid bugs, considering that the user themselves should avoid writing equations that are too long, even in Latex.

**Comment by stevenjoezhang** [comment]
@Aqua-Dream Thanks. We changed the style back in #752. These warnings will be added to the docs:
- avoid writing equations that are too long
- avoid writing equations in the list
