### ISSUE TITLE
Support reading view functionality of edge broswer

### ISSUE THREAD

**Issue by cmpute** [theme-next/hexo-theme-next#737]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

If implemented correctly, I think the reading button on the right side of the address bar of edge will be lighted. And one can enter reading view and concentrate on the content in this mode.

![image](https://user-images.githubusercontent.com/9154441/55013346-52eb2200-4fbf-11e9-865e-155047da6dcf.png)

### Actual behavior 

Currently all pages in my blog don't support reading view. You will find the reading button in gray status.

### Steps to reproduce the behavior 

1. Open any supported page (e.g. the link below)
2. Click the reading button in the edge browser
3. You've entered the reading mode

![image](https://user-images.githubusercontent.com/9154441/55013503-9d6c9e80-4fbf-11e9-8451-9a26c851dfc8.png)

* Link to demo site with this feature: [This page has reading view support. You can find the reading button lighteed](https://www.windowscentral.com/how-enable-and-customize-reading-view-edge-windows-10)

* Link(s) to source code or any usefull link(s): [Documentation of reading view dev guide](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/browser-features/reading-view)

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by 1v9** [comment]
Not sure the upcoming new chromium-based EDGE browser will still retain reading view or not, so we may have to wait?🤷‍♂️

**Comment by stevenjoezhang** [comment]
macOS & iOS safari have similar feature (reading view functionality), but I have no idea how it works...

**Comment by stevenjoezhang** [comment]
About Safari: https://mathiasbynens.be/notes/safari-reader

**Comment by cmpute** [comment]
> Not sure the upcoming new chromium-based EDGE browser will still retain reading view or not, so we may have to wait?🤷‍♂️

I guess the old version of edge will remain preinstalled in windows

**Comment by stevenjoezhang** [comment]
https://docs.microsoft.com/zh-cn/microsoft-edge/dev-guide/browser-features/reading-view

**Comment by stevenjoezhang** [comment]
https://docs.microsoft.com/zh-cn/microsoft-edge/dev-guide/browser-features/reading-view

https://www.theverge.com/2019/11/4/20942038/microsoft-edge-chromium-release-date-new-logo-features

**Comment by stevenjoezhang** [comment]
I downloaded the new chromium edge and enabled the reading view based on this post: https://www.howtoedge.com/enable-reader-view-on-chromium-edge-browser/
Then, I opened http://hexo-theme-next.netlify.com/ and found that the reading view worked like a charm. I believe that Microsoft has adjusted the algorithm of the reading view, so we will not continue to consider adapting to the old edge browser.

**Comment by cmpute** [comment]
> I downloaded the new chromium edge and enabled the reading view based on this post: https://www.howtoedge.com/enable-reader-view-on-chromium-edge-browser/
> Then, I opened http://hexo-theme-next.netlify.com/ and found that the reading view worked like a charm. I believe that Microsoft has adjusted the algorithm of the reading view, so we will not continue to consider adapting to the old edge browser.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/ef5c694d83c9f8f7dbb9226e40017e89a0d64ffc/68747470733a2f2f73656375726573657276657263646e2e6e65742f3136302e3135332e3133382e3137372f6c6a6a2e3338372e6d7966747075706c6f61642e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031392f30342f656e61626c652d7265616465722d766965772d6f6e2d4368726f6d69756d2d456467652d42726f777365722e706e673f74696d653d31353739303830313236"><img alt="" height="14" src="https://camo.githubusercontent.com/6c3f59fbb622526ecb6cd834ccad36d84854ba6f/68747470733a2f2f73656375726573657276657263646e2e6e65742f3136302e3135332e3133382e3137372f6c6a6a2e3338372e6d7966747075706c6f61642e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031392f31322f63726f707065642d686f77746f656467655f6c6f676f332d313932783139322e706e67"> Howtoedge**[How to enable reader view on Chromium Edge Browser - Howtoedge](https://www.howtoedge.com/enable-reader-view-on-chromium-edge-browser/)**Here, we explain simple workaround to enable reader view on Chromium Edge Browser i.e. go to edge://flags then Reading view flag & select Enabled option.
> 
> > <img alt="" height="14" src="/images/favicon-16x16-next.png"> NexT**[NexT](https://theme-next.org/index.html)**

Which version of chromium edge you are using? I enabled reading view but still cannot enable the reading view on hexo-theme-next.netlify.com
My version is Version 81.0.394.0 Canary

**Comment by cmpute** [comment]
Can you try this page in my blog? https://zyxin.xyz/blog/2019-03/StochasticSystemNotes/

**Comment by stevenjoezhang** [comment]
The link you provided cannot enable Reading View. This is not difficult to understand, because there are a large number of unrendered mathjax on the page.

![批注 2020-01-16 120104](https://user-images.githubusercontent.com/16272760/72492482-53a7ba00-3858-11ea-88e1-03a522279413.png)

The other pages are perfectly fine.

![批注 2020-01-16 120105](https://user-images.githubusercontent.com/16272760/72492486-59050480-3858-11ea-8613-feef0852dd06.png)

I used three different versions and they all worked fine: 79.0.309.65 (官方内部版本), 80.0.361.32 (官方内部版本) beta and 81.0.394.0 (官方内部版本) canary. They are downloaded from Microsoft's official website:

https://www.microsoft.com/en-us/edge
https://www.microsoftedgeinsider.com/zh-cn/download
