### ISSUE TITLE
Custom 404 Page Docs doesn't work

### ISSUE THREAD

**Issue by codenoobforreal** [theme-next/hexo-theme-next#746]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
404 page is available

### Actual behavior 
I just follow the docs which title is "Custom 404 Page" in https://theme-next.org/docs/theme-settings/custom-pages but it doesn't work, I got an error showed in the page "can't get /404".:open_mouth:

### Steps to reproduce the behavior 
I check and repeat the steps several times but it still got the same error, luckily, i think of the "Custom Page Support" part in docs and move the "404" folder into source folder in my "hexo" root directory it works, the 404 page is available in my dev environment.
it could be some version problem of hexo or next documentation updating issue I think.
Sorry for my poor English.:yum:

### Node.js and NPM Information

node v10.13.0
npm 6.4.1

#### Hexo version

hexo 3.8.0
hexo-cli 1.1.0

### NexT Information
**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

#### NexT Configuration:

```yml
menu:
  home: / || home
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  commonweal: /404/ || heartbeat
```

#### Docs Update
it might be correct:exclamation:
```shell
cd your-hexo-site/source
mkdir 404
touch 404/index.md
```

**Comment by stevenjoezhang** [comment]
Sorry, there are some issues in the documentation that are misleading...

**Comment by codenoobforreal** [comment]
never mind!:satisfied:
If my suggestion had confirmed correctly by ur member just fix it and update the docs.Except for this little misleading text.Next is still a useful and powerful theme, I just enjoy it!
btw, you can close this issue if you want.:relaxed:
