### ISSUE TITLE
About Conventional Commits

### ISSUE THREAD

**Issue by 1v9** [theme-next/hexo-theme-next#753]
Some guideline like [Conventional Commits](https://www.conventionalcommits.org/) and our [commit-messages-rules](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#commit-messages-rules) seems no different.

~~I changed my PR title as @ivan-nginx said.~~

~~My confusion is which one is correct or acceptable?~~

~~For example:~~

~~- docs: update something~~
~~- Updated something~~

**Comment by ivan-nginx** [comment]
Ok, it's good question and let's take a look this in terms of common sense.

## Conventional Commits Titles

If commit messages will follow Conventional Commits style, when:
    ![image](https://user-images.githubusercontent.com/16944225/55234318-32270480-522b-11e9-9124-dbcbd7cec49c.png)
So, it will provide **explicit commit history** and ability for **automated tools**.

## Human-readable Titles

With this titles, we always keep grammar and provide direct copying into future [Release Notes](https://github.com/theme-next/hexo-theme-next/releases) to the tags. Moreover, I recently install [Release Drafter Bot](https://github.com/organizations/theme-next/settings/installations/782713) (but not configured him yet) which will make drafts from PR's automatically, so, we can't refer on possibility for renaming PR's for releases. And this will be our **automated tool**.

## Difference examples

**Human-readable titles** (good examples)
https://github.com/theme-next/hexo-theme-next/releases/tag/v7.0.0
https://github.com/theme-next/hexo-theme-next/releases/tag/v6.4.0
In this releases notes example we already see **Features**, **Improvements** or **Bug Fixes** titles. So, no need (but may sometimes) to write every time something like: ~~Fixed~~ something / ~~Added~~ something.

**Human-readable titles** (bad examples)
https://github.com/theme-next/hexo-theme-next/releases/tag/v7.0.1
https://github.com/theme-next/hexo-theme-next/releases/tag/v6.7.0
As I wrote above, in this PR's titles exists many **Fix** / **Fixed**, **Add** / **Added** which cause bad quality of reading for peoples. But it's not so scary and quite tolerable.

**Conventional Commits Titles** (bad examples; good can't be exists)

### Features

feat: added something
feat: from now something2
feat: something3
feat: added something4
feat: support something5
feat: added something6

### Improvements

imp: changed something
imp: from now something2
imp: something3
imp: changed something4
imp: improved something5
imp: changed something6

### Bug Fixes

fix: fixed something
fix: from now something2
fix: something3
fix: fixed something4
fix: delete something5
fix: fixed something6

Are peoples will be glad during read release notes like this?

***

So, I suggest to use **Human-readable titles** and change [commit-messages-rules](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#commit-messages-rules) in accordance with it.

***

Questions? Suggestions? Comments?

**Comment by ivan-nginx** [comment]
It will be good to use something like [this perfect example](https://support.gitkraken.com/release-notes/current/) for releases notes.

**Comment by 1v9** [comment]
So we need these apps?

- [Release Drafter](https://probot.github.io/apps/release-drafter/)
- [Semantic Pull Requests](https://probot.github.io/apps/semantic-pull-requests/)

**Comment by ivan-nginx** [comment]
Release Drafter I will configure anyway, no need to touch it.

About Semantic Pull Requests we talking here. Any constructive arguments for one or another variant needed. I saw about it above.

**Comment by 1v9** [comment]
I got it, we need `update commit-messages-rules`
