### ISSUE TITLE
Create Awesome list

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#758]
Like in [awesome-hexo](https://github.com/hexojs/awesome-hexo).

**Comment by stevenjoezhang** [comment]
We can add more recommended Hexo plugins:
- `hexo-renderer-markdown-it-plus`: support markdown footnote
- `hexo-generator-indexed`: support `post.sticky` and `hide single post`

**Comment by ivan-nginx** [comment]
1. Site use [`hexo-renderer-kramed`](https://github.com/theme-next/theme-next.org/blob/de6d92cd985ed07e90ee57a06da8b253f7f5df8f/hexo-theme-next-autodeploy.sh#L95-L96) engine for right MathJax rendering (and some other things, like tags insite notes tags only this rendering worked fine). Actually, I want to create own NexT renderer (with all possible tools supporting).
2. Yep. It looks fine.
3. Yeah, in our repo I was see u created this plugin.
