### ISSUE TITLE
Need update `commit-messages-rules`

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#762]
I got it, we need update `commit-messages-rules`

_Originally posted by @1v9 in https://github.com/theme-next/hexo-theme-next/issues/753#issuecomment-478191982_

**Comment by 1v9** [comment]
Remove `type` in `commit-messages-rules` and use PR `Labels` to meet `$TITLE` ([Change-Template Variables](https://github.com/toolmantim/release-drafter/blob/master/README.md#change-template-variables) ), am I right?

**Comment by ivan-nginx** [comment]
You are probably right, but... I just understand what **commit message** – it's not the same as **PR Title**.
For Draft Bot we need only Pr Titles and Labels for Categories. But commits can be named independently from titles.

**Comment by stevenjoezhang** [comment]
Any new developments?
