### ISSUE TITLE
Update screenshot in Hexo themes

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#770]
![image](https://user-images.githubusercontent.com/16944225/55285396-b0022180-538b-11e9-8bee-a9f559a648e6.png)

**Comment by stevenjoezhang** [comment]
Agree. How to contact Hexo to update it?

https://hexo.io/themes/

**Comment by ivan-nginx** [comment]
> Agree. How to contact Hexo to update it?

Just clone their repo and make pull with new screen.



> How about using this one:

Of course need to change too. And for now 4 schemes.

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/site/blob/master/source/themes/screenshots/NexT.png

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/site/pull/995
