### ISSUE TITLE
github follow 位置错误，back2top 没有出现在侧边栏

### ISSUE THREAD

**Issue by silloy** [theme-next/hexo-theme-next#799]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
1. github follow 出现在右上角
2. sidebar能正常显示百分比和箭头

### Actual behavior 
1. github corn 出现在左上角
![image](https://user-images.githubusercontent.com/12909107/55395265-ca96ef00-5573-11e9-96d1-5fdf6586f32b.png)
2. 进度条没有出现在sidebar，已设置：
back2top:
  enable: true
  sidebar: true
  scrollpercent: true
![image](https://user-images.githubusercontent.com/12909107/55395465-31b4a380-5574-11e9-9b2d-538cebd5e4a4.png)

### Steps to reproduce the behavior 
1. 本地 hexo server 正常显示，但push到远程出现问题
2. 系统：
    mac os 10.14
    chrome 73.0
3. 网站：https://silloy.me/

**Comment by stevenjoezhang** [comment]
这两个组件的CSS最近都更新过，检查一下是不是缓存的问题。清空浏览器缓存试一下。

**Comment by silloy** [comment]
清楚缓存之后，github corner 可以了，但是b2t出现样式不一致的问题，如何排查
![image](https://user-images.githubusercontent.com/12909107/55396221-f4e9ac00-5575-11e9-862d-46e1cd6cbde0.png)

**Comment by stevenjoezhang** [comment]
你试试`hexo clean`后执行`hexo g`和`hexo d`，看看能否解决？

**Comment by silloy** [comment]
没有，请问可能是什么原因导致的？浏览器都是一个

**Comment by stevenjoezhang** [comment]
玄学问题，看起来与侧边栏back2top有关的样式没有加载（即`/css/main.css`中缺失了一些内容）
你可以设置
```yaml
back2top:
  enable: true
  sidebar: false
  scrollpercent: true
```
渲染一次，然后再改回
```yaml
back2top:
  enable: true
  sidebar: true
  scrollpercent: true
```

**Comment by silloy** [comment]
神奇，改了两次好了， :droplet:
