### ISSUE TITLE
Several improvements in main menu on all schemes.

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#8]
<h1 align="center">Commit: 2412fbc6f0df6d558edcd11021b0faf8ddfce465</h1>

## Part 1. Main menu improvements

1. Add option for count of Posts / Categories / Tags with badges in menu. All 3 schemes.
2. Add `menu-item-active` styles to menu in Muse and Mist schemes. In Pisces and Gemini active menu was worked fine + was small dot.

### Muse
![image](https://user-images.githubusercontent.com/16944225/34536152-5b9cf7ec-f0d5-11e7-92a3-995064636f44.png)
![image](https://user-images.githubusercontent.com/16944225/34536145-5432e494-f0d5-11e7-8d46-bd4757972be9.png)

### Mist
![image](https://user-images.githubusercontent.com/16944225/34536160-60fb3492-f0d5-11e7-9c74-570165195652.png)
![image](https://user-images.githubusercontent.com/16944225/34536168-655f401e-f0d5-11e7-995d-a328dcb64f23.png)

### Pisces
![image](https://user-images.githubusercontent.com/16944225/34536279-b4193728-f0d5-11e7-85e0-d3aa6c6bf823.png)
![image](https://user-images.githubusercontent.com/16944225/34536285-b7ebd0c2-f0d5-11e7-9667-fcd135b19741.png)

### Gemini  
![image](https://user-images.githubusercontent.com/16944225/34536368-ee04be6c-f0d5-11e7-9d43-8b109c81bb78.png)

![image](https://user-images.githubusercontent.com/16944225/34536300-c3408378-f0d5-11e7-9f19-8ff45969234b.png)

### How to use?
In Next `_config.yml`:
```yml
menu_settings:
  badges: true
```

### How it looks?
![image](https://user-images.githubusercontent.com/16944225/34536639-d14ff060-f0d6-11e7-8653-682e729a221e.png)

### How to use?
In Next `_config.yml`:
```yml
# Posts / Categories / Tags in sidebar.
site_state: false
```

### Where?
In Next `_config.yml`:
```diff
-# Enable/Disable menu icons. 
-menu_icons: 
-  enable: true

+# Enable/Disable menu icons / item badges. 
+menu_settings: 
+  icons: true 
```

**Comment by Blealtan** [comment]
Maybe we should forbid direct pushes to master; I'd rather fire a PR from another branch named like `feature-blabla`. Also a PR forces other maintainers to know and talk about new changes, which is one of the most important things in collaboration.

Would you mind turn on the "protect master branch" and adapt this pattern of feature adding? I don't think an issue for an already-added feature is a good idea.

**Comment by ivan-nginx** [comment]
Yeah, good idea! I just frgot about possibility to work with our branches. At least at braking changes need to do separated branches, right.
