### ISSUE TITLE
Suggestions for organizing /docs directory

### ISSUE THREAD

**Issue by stevenjoezhang** [theme-next/hexo-theme-next#804]
```bash
├── AGPL3.md
├── ALGOLIA-SEARCH.md
├── AUTHORS.md
├── DATA-FILES.md
├── INSTALLATION.md
├── LEANCLOUD-COUNTER-SECURITY.md
├── LICENSE.txt
├── MATH.md
├── UPDATE-FROM-5.1.X.md
├── ru
│   ├── DATA-FILES.md
│   ├── INSTALLATION.md
│   ├── README.md
│   └── UPDATE-FROM-5.1.X.md
└── zh-CN
    ├── ALGOLIA-SEARCH.md
    ├── CODE_OF_CONDUCT.md
    ├── CONTRIBUTING.md
    ├── DATA-FILES.md
    ├── INSTALLATION.md
    ├── LEANCLOUD-COUNTER-SECURITY.md
    ├── MATH.md
    ├── README.md
    └── UPDATE-FROM-5.1.X.md
```

In `docs/`:
- [ ] Merge `AGPL3.md`, `LICENSE.txt` and `../LICENSE.md`, move to `../.github`
- [ ] Move `ALGOLIA-SEARCH.md`, `DATA-FILES.md`, `INSTALLATION.md`, `LEANCLOUD-COUNTER-SECURITY.md`, `MATH.md` and `UPDATE-FROM-5.1.X.md` to theme-next.org site
- [ ] Move `AUTHORS.md` to `../.github`, and merge `Contributors` part in `../README.md` to it

In `docs/ru`:
- [ ] Move `DATA-FILES.md`, `INSTALLATION.md` and `UPDATE-FROM-5.1.X.md` to theme-next.org site
- [ ] Move `README.md` to `../.github`

In `docs/zh-CN`:
- [ ] Move `ALGOLIA-SEARCH.md`, `DATA-FILES.md`, `INSTALLATION.md`, `LEANCLOUD-COUNTER-SECURITY.md`, `MATH.md` and `UPDATE-FROM-5.1.X.md` to theme-next.org site
- [ ] Move `README.md` to `../.github`
- [ ] Translate `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md`

**Comment by 1v9** [comment]
Merging LICENSE is a huge job, need discussion.

**Comment by ivan-nginx** [comment]
It seems all fine except License merging.

**Comment by stevenjoezhang** [comment]
Emm, but I found these in issues, not in Org discussions:
#798, #788, #771

**Comment by ivan-nginx** [comment]
1. Because Polls worked only in Issues.
2. Because Polls worked only in Issues.
3. And Because Polls worked only in Issues.

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/issues/67 and https://github.com/theme-next/hexo-theme-next/issues/690

**Comment by ivan-nginx** [comment]
Roadmap for all peoples.
About docs – was created long time ago. But need to move it, yes.

**Comment by ivan-nginx** [comment]
@stevenjoezhang moved to [here](https://github.com/orgs/theme-next/teams/next/discussions/13).
