### ISSUE TITLE
sitemap站点地图菜单404

### ISSUE THREAD

**Issue by yidasanqian** [theme-next/hexo-theme-next#811]
```
menu:
  sitemap: /sitemap.xml || sitemap
```
执行hexo clean && hexo g && hexo s

点击站点地图提示Cannot GET /sitemap.xml

**Comment by stevenjoezhang** [comment]
你装了hexo-generator-sitemap插件吗

**Comment by yidasanqian** [comment]
> 你装了hexo-generator-sitemap插件吗

装好插件可以使用了，谢谢回复

**Comment by stevenjoezhang** [comment]
可能文档有一些误导，我们会改进，谢谢指出
