### ISSUE TITLE
Unable to slide sidebar on mobile browser

### ISSUE THREAD

**Issue by sli1989** [theme-next/hexo-theme-next#812]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 

Since it's long content in [my sidebar](http://saili.science/comments/), but the sidebar can't slide up and down on the Android？ But the computer test terminal can.

![image](https://user-images.githubusercontent.com/8521181/55606521-afaebf80-57ab-11e9-93d6-29cb3dc64cb2.png)
![image](https://user-images.githubusercontent.com/8521181/55606525-b3424680-57ab-11e9-8900-2380b4a85a06.png)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
I think it's possible that mobile browsers behave differently than desktop browsers for better performance... This makes the sidebar slide look strange

**Comment by stevenjoezhang** [comment]
It's caused by this line

https://github.com/theme-next/hexo-theme-next/blob/726ce63d8478039ee4f549bedea74fd55d1a112d/source/js/schemes/muse.js#L39

which is added in this Pull Request

https://github.com/iissnan/hexo-theme-next/pull/1757
