### ISSUE TITLE
怎么设置评论组件valine只在文章页显示

### ISSUE THREAD

**Issue by yidasanqian** [theme-next/hexo-theme-next#813]
rt

**Comment by 1v9** [comment]
你是要关闭页面的评论？

**Comment by stevenjoezhang** [comment]
加个telegram群吧，issue讨论效率不高

**Comment by yidasanqian** [comment]
> 你是要关闭页面的评论？

不是，配置了valine评论插件，但是在文章、标签、存档、关于等菜单页下都有这个评论插件了，我想只在文章页下显示评论插件，即只有文章页下才有留言功能。

这个怎么设置指定页面不启用评论插件啊？

**Comment by stevenjoezhang** [comment]
front matter 中设置 comments: false

**Comment by yidasanqian** [comment]
> front matter 中设置 comments: false

有用，谢谢解答

**Comment by Jeffchal** [comment]
> > front matter中设置评论：false
> 
> 有用，谢谢解答

哥们，你  front matter 在哪找到的啊 ，我没找到😂

**Comment by 1v9** [comment]
@Jeffchal hexo 不是主题配置文件，在 hexo 新建的文章（md 文件）中上部的几行就是了。
