### ISSUE TITLE
How to modify <table> property as I wish? the default setting always covers my setting

### ISSUE THREAD

**Issue by Harrypotterrrr** [theme-next/hexo-theme-next#821]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
### Preface

If there are files or issues relative to my problem, please tell me. Thanks

In summary, my problem is how to cover the default css style and use my own setting.

### Expected behavior 
I hope to use HTML table to achieve the result showed as below, and the border of table is "0"
![image](https://user-images.githubusercontent.com/28552583/55685056-b5abc880-5984-11e9-953b-c1bcc17d6425.png)

This is my code of this table 
```html
<table border="0" width="500px" cellspacing="0" cellpadding="10">
	<tbody align="left" valign="left">
		<tr height="20px">
			<td width="50px" rowspan="4" valign="top">Feb 2019 ~ Mar 2019</td>
			<td>Team Member of SmartTab project</td>
		</tr>
		<tr>
			<td>Google AI ML Winter Camp</td>
		</tr>
		<tr>
			<td>Google headquarters, Beijing, China</td>
		</tr>
		<tr>
			<td>
				<ul>
					<li>To automatically analyze the structure of a relatively long article: it takes in the raw article
						and
						split it into reasonable sections.</li>
					<li>To use BERT as an encoder to encode paragraphs.</li>
					<li>To tag each paragraph according to its position within the section it belongs to and the
						relation
						between it with the neighbor above.</li>
			</td>
	</tbody>
</table>
```

### Actual behavior 

However it always shows this, where there are also a large blank block above my table and the border is visible.

![image](https://user-images.githubusercontent.com/28552583/55685133-497d9480-5985-11e9-9bce-c9306c4f4cdd.png)

Sincerely appreciate your help!

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.18.0-10-generic linux x64
node: 11.13.0
v8: 7.0.276.38-node.18
uv: 1.27.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 4
llhttp: 1.1.1
http_parser: 2.8.0
openssl: 1.1.1b
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0
```

#### Hexo Configuration

For my issue, there's no need for this file

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

#### NexT Configuration:

There's no need for this detail, for I never modified the css file of NexT

**Comment by Raincal** [comment]
1. Add your html into `{% raw %} {% endraw %}`.
2. The `border` attribute has been deprecated. You should use custom css to control this.
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/table

**Comment by Harrypotterrrr** [comment]
> 1. Add your html into `{% raw %} {% endraw %}`.
> 2. The `border` attribute has been deprecated. You should use custom css to control this.
>    https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/table
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1b1f8fee1a22bafda3fcd61c7a04f7d80c97b29b/68747470733a2f2f646576656c6f7065722e6d6f7a696c6c612e6f72672f7374617469632f696d672f6f70656e67726170682d6c6f676f2e3732333832653630356365332e706e67">MDN Web 文档**[HTML的 table 元素表示表格数据 — 即通过二维数据表表示的信息。](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/table)**

Thanks a ton! I have confused to this problem for a long time.
As a freshman of front-end, I have a question about this magic command..
I googled `{% raw %} {% endraw %}` and found that it is the command of **jekyll**, so I wonder if the hexo-NexT is based on jekyll? In other words, how can I use these commands in other files?

**Comment by Raincal** [comment]
> I googled {% raw %} {% endraw %} and found that it is the command of jekyll, so I wonder if the hexo-NexT is based on jekyll? In other words, how can I use these commands in other files?
Or is there any other document I can refer to?

You should use them in markdown files. Here are some useful docs. 
https://hexo.io/docs/tag-plugins
https://theme-next.org/docs/tag-plugins/

PS: I added two other ways to solve the blank block problem.

> And another problem turns out that HTML can be inserted into {% raw %} {% endraw %} , but there is often indent problem of CSS code in internal way

Sorry, I can't understand your problem.

**Comment by Harrypotterrrr** [comment]
Sorry for my late response and my vague expression. Just take a simple example,
As I write the code below in markdown, the `css` fails to render.
```markdown
{% raw %}
    <style type="text/css">
        table {
            border-collapse: collapse;
            font-size: 0.8rem;
        }
    </style>
{% endraw %}
```
While I eliminate the indent, note that there is no indent before the `<style>`, it works, so I wonder the reason for this.

```markdown
{% raw %}
<style type="text/css">
    table {
        border-collapse: collapse;
        font-size: 0.8rem;
    }
</style>
{% endraw %}
```

**Comment by Raincal** [comment]
I can't reproduce it, both ways work fine here and it's best to add a class name to table in order not to affect the style of other tables.

**Comment by Harrypotterrrr** [comment]
okay, since I have find a way to deal with this problem, it doesn't matter!
Appreciate your patience and help! 😊
