### ISSUE TITLE
Content Empty

### ISSUE THREAD

**Issue by HuHuwithcode** [theme-next/hexo-theme-next#822]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
After hexo s, can see the whole website

### Actual behavior 
After hexo s, the whole website were empty and disappear.
All page context empty. but still keep the sidebar button loge.

### Steps to reproduce the behavior 
1. use hexo clean
2. use hexo clean
3. use hexo clean, and wanna crying

* Link to demo site with this issue: https://huhuwithcode.github.io/
* Link(s) to source code or any usefull link(s): 

### Node.js and NPM Information

```v11.13.0

```6.9.0

### Package dependencies Information
<!-- Paste output from `cat package.json` (粘贴 `cat package.json` 输出的信息) -->
```{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}

```

#### Hexo version

```hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.5.0 darwin x64
node: 11.13.0
v8: 7.0.276.38-node.18
uv: 1.27.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 4
llhttp: 1.1.1
http_parser: 2.8.0
openssl: 1.1.1b
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0

```

#### Hexo Configuration

```yml

```
# Hexo Configuration
## Source: https://github.com/hexojs/hexo/

# Site
title: HUHU CODESIGN X LAB
subtitle: Stay Inspired
description: I am a web developer, UX/UI designer and lifelong learner interested in everything. Now I focus on Human-Computer Interaction.
keywords: Interaction Design,HCI,UX/UI Design,Journal
author: Siying Hu
language:
timezone: Australia/Brisbane

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Themes: https://hexo.io/themes/
theme: hexo-theme-next
plugins: hexo-generate-feed

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:HuHuwithcode/HuHuwithcode.github.io.git
  branch: master

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```rss: /atom.xml

```footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2019

```icon:
    # Icon name in fontawesome, see: https://fontawesome.com/v4.7.0/icons/
    # `heart` is recommended with animation in red (#ff0000).
    name: fa-smile-o
    # If you want to animate the icon, set it to true.
    animated: ture
    # Change the color of icon, using Hex Code.
    color: "#808080"

```powered:
    # Hexo link (Powered by Hexo).
    enable: false
    # Version info of Hexo after Hexo link (vX.X.X).
    version: false

  theme:
    # Theme & scheme info link (Theme - NexT.scheme).
    enable: false
    # Version info of NexT after scheme info (vX.X.X).
    version: false

```menu:
  Home: / || home
  About: /about/ || user
  Categories: /categories/ || th
  Archives: /archives/ || archive
  Tags: /tags/ || tags
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

```social:
  GitHub: https://github.com/HuHuwithcode || github

```# Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
  offset: 12
  # Enable sidebar on narrow view (only for Muse | Mist).
  onmobile: ture
  # Click any blank part of the page to close sidebar (only for Muse | Mist).
  dimmer: ture

```# Canvas-nest
# Dependencies: https://github.com/theme-next/theme-next-canvas-nest
canvas_nest:
  enable: ture

### Other Information <!-- Like Browser, System, Screenshots -->
Browser: chrom
System: macOS Mojave

[Uploading huhuwithcodesign.github.io.zip…]()

**Comment by JiangTJ** [comment]
Make sure `theme.back2top.sidebar` is `true`, not `ture`
