### ISSUE TITLE
怎么改全局配色

### ISSUE THREAD

**Issue by yidasanqian** [theme-next/hexo-theme-next#823]
比如我想把黑色改成浅蓝色，要怎么改配置？

**Comment by stevenjoezhang** [comment]
编辑`source/css/_variables/custom.styl`，对着`source/css/_variables/base.styl`照猫画虎地改就行了。

**Comment by yidasanqian** [comment]
没有更方便的配色方案了吗

**Comment by zq-97** [comment]
似乎应该没有了

**Comment by zq-97** [comment]
@stevenjoezhang 昨天我改配色的时候发现`custom.styl`优先级似乎并不是最高，比如在里面设置了`$orange`的颜色，并不能完全覆盖`base.styl`的效果，只有在后者中修改才能全局覆盖。这算是bug吗？

**Comment by JiangTJ** [comment]
![image](https://user-images.githubusercontent.com/15902347/55712245-f8bb7980-5a20-11e9-9640-a807709bf8f9.png)

See https://github.com/theme-next/hexo-theme-next/blob/master/source/css/main.styl
