### ISSUE TITLE
Swiftype Search doesn't work 

### ISSUE THREAD

**Issue by xiaohao890809** [theme-next/hexo-theme-next#831]
# Swiftype Search API Key
swiftype_key: ****

I have configed the swiftype_key, but when I click the search button in my homepage, nothing happens. Does the swiftype change the rule?

**Comment by stevenjoezhang** [comment]
Any URLs?

**Comment by stevenjoezhang** [comment]
https://juejin.im/post/5bbdc8d8e51d450e5e0cb269
