### ISSUE TITLE
Could you ignore letter cases when deciding tag display order?

### ISSUE THREAD

**Issue by panqiincs** [theme-next/hexo-theme-next#836]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

Tag display order in the `/tags` page is not determined by the case of tags' prefix letters, when sorting them, regard upper case letters as lower case letters. My reason is, we determine cases by convention, not because those tags start with a upper case letter are more important. All tags start with a upper case letter stand together in the front, it's not pretty.

标签页中标签的显示顺序与标签首字母的大小写无关，给它们排序时，大写字母当作小写字母来看待。我的理由是，我们根据习惯决定标签的大小写，并不是因为大写开头的标签更重要。所有大写字母开头的标签都排在前面，看起来并不和谐。

### Actual behavior 

In the `/tags` page, tags begins with a upper case letter always stand together in the beginning.

标签页中，以大写字母开头的标签总是扎堆排在最前面。

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this feature: N/A
* Link(s) to source code or any usefull link(s): N/A

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

**Comment by stevenjoezhang** [comment]
No, we can't. It's not generated by NexT. Ask Hexo for help:
https://github.com/hexojs/hexo-generator-tag/issues
https://github.com/hexojs/hexo/issues

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/3875
