### ISSUE TITLE
修改custom.styl..添加本地字体至next/source/fonts  无法生效

### ISSUE THREAD

**Issue by neoiso** [theme-next/hexo-theme-next#838]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. 将ttf移动至/fontsthemes/next/source
2. 修改next/source/_variables/custom.styl
3. 无法生效

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
能否提供一下链接，谢谢。

**Comment by neoiso** [comment]
NexT 从 5.0.1 版本开始提供一个 字体定制特性， 请先查看此特性是否能满足你的需求。以下的修改将覆盖 字体定制 的特性。 编辑主题下的 source/css/_variables/custom.styl 文件，新增两个变量：

**Comment by neoiso** [comment]
原地址 https://theme-next.iissnan.com/faqs.html
我不确定hexo是否支持本地字体

**Comment by stevenjoezhang** [comment]
我可能表达有误……能否提供出错的网站链接？理论上自定义字体是可以加载的。

**Comment by neoiso** [comment]
/ 标题，修改成你期望的字体族
$font-family-headings = Georgia, sans

// 修改成你期望的字体族
$font-family-base = "Microsoft YaHei", Verdana, sans-serif

// 代码字体
$code-font-family = "Input Mono", "PT Mono", Consolas, Monaco, Menlo, monospace

// 正文字体的大小
$font-size-base = 16px

// 代码字体的大小
$code-font-size = 13px

**Comment by neoiso** [comment]
代码字体的大小修改 有效。
就是字体不生效。
是我哪里做错了？

**Comment by neoiso** [comment]
https://neoiso.github.io

**Comment by neoiso** [comment]
> 我可能表达有误……能否提供出错的网站链接？理论上自定义字体是可以加载的。

https://github.com/neoiso/neoiso.github.io

<blockquote><img src="https://avatars3.githubusercontent.com/u/48611517?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/neoiso/neoiso.github.io">neoiso/neoiso.github.io</a></strong></div><div>Contribute to neoiso/neoiso.github.io development by creating an account on GitHub.</div></blockquote>

**Comment by neoiso** [comment]
是我自己下载的字体文件放在了主题文件下的font文件里。然後修改custom文件添加上字体名称无法生效
