### ISSUE TITLE
Bootstrap callout Bug

### ISSUE THREAD

**Issue by NashMiao** [theme-next/hexo-theme-next#839]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

The `markdown` contents between Bootstrap Callout can be rendered to `HTML` contents .

### Actual behavior 

![image](https://user-images.githubusercontent.com/18191964/56258171-3a26e580-6101-11e9-89a3-59aa49a02278.png)

### Steps to reproduce the behavior 

1. hexo new "example"
2. write content in `example.md`

```markdown
{% note default %} default {% endnote %}

I want to use `md` in here.

{% note primary %} primary {% endnote %}

I want to use `md` in here.

{% note success %} success {% endnote %}

I want to use `md` in here.

{% note info %} info {% endnote %}

I want to use `md` in here.

{% note warning %} warning {% endnote %}

I want to use `md` in here.

{% note danger %} danger {% endnote %}
```

3. run `hexo s` to see result.

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
$node -v
v8.11.3
$npm -v
5.6.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.4.4"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 8.11.3
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

**Comment by ivan-nginx** [comment]
```md
{% note default %}
default
{% endnote %}

I want to use `md` in here.

{% note primary %}
primary
{% endnote %}
```

https://theme-next.org/docs/tag-plugins/note#Known-Issues

**Comment by NashMiao** [comment]
@ivan-nginx thanks for your help. Maybe we should add a link in [this ](https://theme-next.iissnan.com/tag-plugins.html) page.
