### ISSUE TITLE
Automatically adding html, body tag on manifest, serviceworker files

### ISSUE THREAD

**Issue by gracefullight** [theme-next/hexo-theme-next#840]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
localhost:4000/manifest.json
```
{
    "name": "Blog",
     ...
}
```

### Actual behavior 
localhost:4000/manfiest.json
```
<html><body>{ "name": "Blog" ... }</body></html>
```

### Steps to reproduce the behavior 
1. enable exturl: true (on /themes/next/_config.yml)
2. create manifest.json (on /source/manifest.json)
3. set favicon.android_manfiest /manifest.json (on /themes/next/_config.yml)

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): 
https://github.com/cheeriojs/cheerio/issues/1031#issuecomment-368307598

### Node.js and NPM Information

```
v11.13.0
6.7.0
```

### Package dependencies Information

```
{
  "name": "blog",
  "version": "1.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "scripts": {
    "clean": "hexo clean && rimraf public/"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-all-minifier": "^0.5.3",
    "hexo-autonofollow": "^1.0.1",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-amp": "^3.0.19",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^4.1.3",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-seo-friendly-sitemap": "0.0.25",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-markdown-it-plus": "^1.0.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-renderer-swig": "^1.1.0",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.4.4",
    "hexo-tag-leaflet": "^1.0.4",
    "workbox-cli": "^3.6.3"
  },
  "devDependencies": {
    "rimraf": "^2.6.3"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.5.0 darwin x64
node: 11.13.0
v8: 7.0.276.38-node.18
uv: 1.27.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 4
llhttp: 1.1.1
http_parser: 2.8.0
openssl: 1.1.1b
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml

```

**Comment by JiangTJ** [comment]
You should config hexo `_config.yml` as following:
```yml
skip_render:
  - manfiest.json
```

**Comment by gracefullight** [comment]
@JiangTJ Skip rendering other files? (like serviceworker..) How about adding xmlMode option?

**Comment by JiangTJ** [comment]
xmlMode？What's it? :joy:

**Comment by gracefullight** [comment]
@JiangTJ I think this bug caused by [cheerio](https://github.com/cheeriojs/cheerio/issues/1031)

**Comment by JiangTJ** [comment]
So? If disable exturl, it work well?

**Comment by gracefullight** [comment]
@JiangTJ Yes, works fine.

**Comment by JiangTJ** [comment]
Orz, may need modify exturl filter...
Like this https://github.com/hexojs/hexo-filter-lqip/blob/a31d8d732e60bc3da92c77dc26b5296bfdf9655b/lqip/index.js#L32-L47
Set `hexo.route`

**Comment by stevenjoezhang** [comment]
I can’t reproduce this bug... exturl uses after_post_render filter, which should only work on html files, not json.

**Comment by JiangTJ** [comment]
@stevenjoezhang Yes, it seems not wrapper with `<html><body>`. But it rendered files that is not `.html` suffix.

![image](https://user-images.githubusercontent.com/15902347/56857551-7b40b480-69a1-11e9-8e1c-c7be2abd2fee.png)
![image](https://user-images.githubusercontent.com/15902347/56857553-81cf2c00-69a1-11e9-9fef-0d2cdd3d29d3.png)

@gracefullight Can you test it with added this. And I don't know why your json file wrappered with `<html><body>`?
![image](https://user-images.githubusercontent.com/15902347/56857606-4da83b00-69a2-11e9-8854-da9e36c30690.png)

**Comment by gracefullight** [comment]
@stevenjoezhang  yes, `after_post_render` is a hook for post only, but it's weird json files in that time.
(https://github.com/hexojs/hexo/blob/2ed17cd105768df379dad8bbbe4df30964fe8f2d/lib/hexo/post.js#L285)

I try to reproduce in this time, but it fails. 😨 
If it happens again next time, I'll write more details.

Thanks for your time. @JiangTJ

**Comment by stevenjoezhang** [comment]
The loading of cheerio has been optimized in #1042. You can help to confirm whether the problem has been solved

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/pull/3315
