### ISSUE TITLE
动态背景没有生效

### ISSUE THREAD

**Issue by ghost** [theme-next/hexo-theme-next#841]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
canvas ribbon 和sphere试过了都可以正常运行就这个nest没有效果。。。。
动态背景的canvas nest。我按照教程下载了canvas到lib。
并成功修改了主题配配置文件。参考的以下链接
https://github.com/theme-next/theme-next-canvas-nest/blob/master/README.md#step-1--go-to-next-dir

### Actual behavior 
没有生效
文件地址
ccvvv.github.io

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
清除一下缓存。在你的博客页面中没有看到与canvas nest相关的内容。

**Comment by ccvvv** [comment]
> 清除一下缓存。在你的博客页面中没有看到与canvas nest相关的内容。

主题配置文件的994行。刚刚一直在本地实验没上传。刚刚传好了。谢谢！
