### ISSUE TITLE
The title of About page is incomplete

### ISSUE THREAD

**Issue by panqiincs** [theme-next/hexo-theme-next#842]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

The title of About page showed in the browser tab should be like`About | Website name`.

### Actual behavior 

The title of About page showed in the browser tab is ` | Website name`.

### Steps to reproduce the behavior 
1. Create a new page called About: `hexo new page about`.
2. Modify the menu settings of `_config.yml` to enable About page. 
3. Deploy

* Link to demo site with this bug: my blog(in Chinese): https://panqiincs.me
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 5.0.7-1-default linux x64
http_parser: 2.8.0
node: 8.15.1
v8: 6.2.414.75
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 57
nghttp2: 1.36.0
napi: 3
openssl: 1.1.0h-fips
icu: 64.1
unicode: 12.0
cldr: 35.0
tz: 2018i
```

#### Hexo Configuration

```yml
menu:
  home: / || home
  archives: /archives/ || archive
  categories: /categories/ || th
  tags: /tags/ || tags
  series: /series/ || list
  about: /about/ || user
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by panqiincs** [comment]
It seems that, there's no title name configuration code for About page, Category, Tag pages are OK.

**Comment by stevenjoezhang** [comment]
Please provide `/about/index.md`

**Comment by panqiincs** [comment]
@stevenjoezhang Yes, you are right, problem solved. Forgive for such a problem...Please close the issue.
