### ISSUE TITLE
IE11 leancloud不显示阅读次数

### ISSUE THREAD

**Issue by cnrting** [theme-next/hexo-theme-next#843]
v6.0.0，chrome和Firefox都没问题，应该是兼容问题
控制台error消息:
SCRIPT1010: 缺少标识符
index.htm (2323,24)

      Counter('get', '/classes/Counter', { where: JSON.stringify({ url: { '$in': entries } }) })
        .done(function({results}) {  //这一行出错
          var COUNT_CONTAINER_REF = '.leancloud-visitors-count';

          if (results.length === 0) {
            $visitors.find(COUNT_CONTAINER_REF).text(0);
            return;
          }

          for (var i = 0; i < results.length; i++) {
            var item = results[i];
            var url = item.url;
            var time = item.time;
            var element = document.getElementById(url);

            $(element).find(COUNT_CONTAINER_REF).text(time);
          }
          for (var i = 0; i < entries.length; i++) {
            var url = entries[i];
            var element = document.getElementById(url);
            var countSpan = $(element).find(COUNT_CONTAINER_REF);
            if (countSpan.text() == '') {
              countSpan.text(0);
            }
          }
        })
        .fail(function ({ responseJSON }) {
          console.log(`LeanCloud Counter Error: ${responseJSON.code} ${responseJSON.error}`);
        });
    }
给出的参考:
https://docs.microsoft.com/zh-cn/previous-versions/k4eee20x(v=vs.94)

**Comment by stevenjoezhang** [comment]
是的，因为IE并不支持ES5和ES6的新特性。请使用其它浏览器。
