### ISSUE TITLE
Sidebar goes out of viewport after scroll down in custom page

### ISSUE THREAD

**Issue by zq-97** [theme-next/hexo-theme-next#846]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
After scolling down in some page, the side bar should fix on the side top.
![image](https://user-images.githubusercontent.com/17429111/56466051-c9a00180-643d-11e9-8165-3fa50590b3df.png)
I thought it is because `.sidebar-inner.affix` works.

### Actual behavior 
But for my custom page, the sidebar goes outside the viewport after scrolldown.
![image](https://user-images.githubusercontent.com/17429111/56466081-374c2d80-643e-11e9-92c3-b7a4a803d2b6.png)

### Steps to reproduce the behavior 
Please go to [my custom page](https://i-m.dev/tools/gsearch/) and search anything, when results appeared, scroll down the page, you'll see the sidebar will goes out.

* Link to demo site with this issue: <https://i-m.dev/tools/gsearch/>

### Node.js and NPM Information

```
v10.15.3
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-directory-category": "^1.0.7",
    "hexo-filter-mermaid-diagrams": "^1.0.5",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-heading-index": "^1.0.1",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

**Comment by ivan-nginx** [comment]
What's the search service?

**Comment by zq-97** [comment]
I wrote a Google search crawler in python as backend, it collects the google searched page html content and send it back, then add the results into a container `div` .

Actually, I found out the root cause seems to be dynamic height, try to render the following html and you can also reproduce it.

```html
<style>
#mydiv {
	width: 10em;
	height: 10em;
	background: green;
}
</style>

<div id='mydiv' onclick="this.style.height='100em'"></div>
````

**Comment by stevenjoezhang** [comment]
> Actually, I found out the root cause seems to be dynamic height, try to render the following html and you can also reproduce it.

@zq-97 I used your html code, but could not reproduce the problem...
Are you using any other custom CSS? Could you check if they are the cause of the problem?

**Comment by zq-97** [comment]
Indeed I have some custom css but it's all about color and font, nothing to do with layout.
A very confusing problem.

**Comment by stevenjoezhang** [comment]
Sidebar position is controlled by https://github.com/theme-next/hexo-theme-next/blob/master/source/js/affix.js
Need to read the source code to determine the possible cause of the problem

**Comment by stevenjoezhang** [comment]
@zq-97 
![屏幕快照 2019-07-20 上午12 21 25](https://user-images.githubusercontent.com/16272760/61550127-4b76e980-aa84-11e9-8519-1d5864757c12.png)

**Comment by zq-97** [comment]
The backends failed to work, so please don't take that page for reproduce.
I can still reproduce this issue by the following code
```html
<style>
#mydiv {
	width: 10em;
	height: 10em;
	background: green;
}
</style>

<div id='mydiv' onclick="this.style.height='100em'"></div>
```

**Comment by stevenjoezhang** [comment]
Weird...

![2019-07-20 20-55-33 2019-07-20 20_56_35](https://user-images.githubusercontent.com/16272760/61578951-c990ca00-ab30-11e9-903d-74b75a4aab95.gif)

**Comment by zq-97** [comment]
![demo](https://user-images.githubusercontent.com/17429111/61588435-0068ed80-abce-11e9-8cf2-1f283a369cbe.gif)
Not for me

**Comment by stevenjoezhang** [comment]
Still can't reproduce... even on your site

![2019-07-26 14-52-13 2019-07-26 14_53_06](https://user-images.githubusercontent.com/16272760/61932043-f7ed2a00-afb4-11e9-99a6-2abfede077ab.gif)

**Comment by zq-97** [comment]
@stevenjoezhang I've updated to v7.30 but not work,
I have made a test page [https://i-m.dev/test.html](https://i-m.dev/test.html), could you reproduce it in this page.
note: I'm using Linux and reproduce it both on chrome and firefox

**Comment by stevenjoezhang** [comment]
@zq-97 I believe I have found the right answer. Could you please help to confirm whether this PR (https://github.com/theme-next/hexo-theme-next/pull/1039) has fixed the problem.

**Comment by zq-97** [comment]
I just noticed that #1039 is not merged till now, after a manual fix and the problem solved!

**Comment by stevenjoezhang** [comment]
I'm glad the problem is solved.. I'll merge #1039 after further confirmation

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/hexo-theme-next/commit/b9968b6be0a8b20be80adad185ee94d713672e52
