### ISSUE TITLE
Feature Request: Calendar View

### ISSUE THREAD

**Issue by gapplef** [theme-next/hexo-theme-next#848]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
A calendar view can be useful when post is to many, especially for cases like diary or microblog.

### Expected behavior 
![Screenshot](https://user-images.githubusercontent.com/5604665/56478319-08d35e80-64e1-11e9-9e5e-b7f60ea2fbf3.png) ![calendar_compact_layout_1](https://user-images.githubusercontent.com/5604665/56480419-91a3c780-64ec-11e9-86b3-e3c6c0ba7f15.png)
- A calendar view similar to above.
- Marks shown for days that have post.
- Shown in the side bar or top of archive page.
- Click on the years, months, or days that have mark on, go to the corresponding archive page.
- Maybe also give an way to quick jump between years and months that have posts, skip these do not have posts.

A similar plugin for theme `Landscape-F` can be see [here](https://github.com/howiefh/hexo-generator-calendar). One problem of this plugin is once click on the calendar, the whole page will be refreshed, and the calendar back to current day, not the day/month/year that you clicked.

**Comment by gapplef** [comment]
or maybe a month and year only calendar like this:
![Screenshot-1](https://user-images.githubusercontent.com/5604665/56480092-358c7380-64eb-11e9-99d0-65700972f223.png)

**Comment by bevarb** [comment]
begain

**Comment by icecory** [comment]
Not long ago, I have already implemented it (also from Landscape-F)

- https://icecory.com/
- https://github.com/icecory/theme-next-calendar

I just adapte it, and i'm not good at js.

**Comment by ivan-nginx** [comment]
We all not good in that, but we try and make things for better.
U can try to move repo here, to the next org for redistribute to other members.

**Comment by gapplef** [comment]
@icecory Great! Thanks for your work.
But some thing is wrong here:
1. There are two posts on 4-04, but no mark is shown in the calendar.
2. I can see more than one post on many days, like 4-04, 4-07, 4-12, 4-18.... Click on the day, it will jump to the first post of that day, not the archive page of that day.
I don't think this is the right way, it will imply people only one post on that day.
3. Also the same problem as original plugin for `Landscape-F`: once click on the calendar, the whole page will be refreshed, and the calendar back to current day, not the day/month/year that you clicked.

@ivan-nginx It would be great if `NexT` could support this feature natively. I don't want to modify` NexT` source code.

As for problem 2, I check the archive page of `NexT`, and find it go down to month, not day. So there is no archive page for given day. I think we may use month and year only calendar as I said before, or we need create  archive page for every day.

**Comment by stevenjoezhang** [comment]
And another feature-request about creating archive page in monthly (#856)

**Comment by jiangtj** [comment]
You can install this plugin: https://github.com/theme-next/theme-next-calendar
