### ISSUE TITLE
加载过程中，整个页面会出现无样式的情况。加载完问题会消失，我在下面的描述中有图片。

### ISSUE THREAD

**Issue by wangccsd** [theme-next/hexo-theme-next#850]
请点击此处查看   www.ntssl.cn      查看
![image](https://user-images.githubusercontent.com/45278305/56626602-ee31ee80-6674-11e9-8c4d-0408e713965b.png)

**Comment by wangccsd** [comment]
问题已解决，是Bookmark 的问题，F12检查后发现没有成功加载，在_config把Bookmark 改成false后修复该问题。

**Comment by stevenjoezhang** [comment]
Bookmark 的有关问题应该已经在最新版本中修复了。
