### ISSUE TITLE
How to use different configs for different languages?

### ISSUE THREAD

**Issue by njzjz** [theme-next/hexo-theme-next#852]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

How to use different configs for different languages? I want to link the sidebars to different pages for different languages.

**Comment by ivan-nginx** [comment]
Feature is not documented yet because in beta testing, but u can try to followed by this feature: https://github.com/theme-next/theme-next.org/blob/source/source/_data/languages.yml

**Comment by jiangtj** [comment]
@ivan-nginx That doesn't seem to be what he's talking about.
Like the example below, the address of the menu bar jumps to a different address.
en
```yaml
menu:
  home: / || home
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
```
zh
```yaml
menu:
  主页: /zh/ || home
  标签: /zh/tags/ || tags
  类别: /zh/categories/ || th
  归档: /zh/archives/ || archive
```

**Comment by stevenjoezhang** [comment]
And blogs can be generated in different directories in different languages

**Comment by stevenjoezhang** [comment]
After investigation, I think this should be a feature of Hexo. Please ask Hexo for help.
See also
https://hexo.io/zh-cn/docs/internationalization
https://github.com/hexojs/hexo/issues/1696

What theme NexT can do is adding a multi-language switch button
https://github.com/theme-next/hexo-theme-next/issues/1070
