### ISSUE TITLE
`exturl` render code section mistakenly

### ISSUE THREAD

**Issue by NashMiao** [theme-next/hexo-theme-next#854]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

![image](https://user-images.githubusercontent.com/18191964/56789471-86c29d00-6834-11e9-960b-edd3ea2b4524.png)

### Actual behavior 

![image](https://user-images.githubusercontent.com/18191964/56789396-5549d180-6834-11e9-90ba-ac630c17af4f.png)

### Steps to reproduce the behavior 
1. enable  exturl in theme config.

```
# Automatically add external URL with BASE64 encrypt & decrypt.
exturl: true
```

2. create a new test page.

```
hex new test-page
```

3. add test content.

```
{% tabs git-proxy, 1 %}
<!-- tab 无鉴权的代理服务器 -->

{% code %}
git config --global https.proxy 'https://127.0.0.1:37269'
git config --global http.proxy 'https://127.0.0.1:37269'

git config --global http.proxy 'socks5://127.0.0.1:37633'
git config --global https.proxy 'socks5://127.0.0.1:37633'
{% endcode %}

<!-- endtab -->
<!-- tab 有鉴权的代理服务器 -->

{% code %}
git config --global https.proxy https://username:password@127.0.0.1:37269
{% endcode %}

<!-- endtab -->
{% endtabs %}
```

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
$node -v
v8.11.3
$npm -v
5.6.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.4.4"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 8.11.3
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

### Other Information

**Comment by stevenjoezhang** [comment]
Actually it's a bug (or feature) of `{% code %}` tag of Hexo. You can turn `exturl` off, and you'll find out that the urls inside `{% code %}` are still interpreted as hyperlinks

**Comment by NashMiao** [comment]
@stevenjoezhang Thanks. I turned `exturl` off, and found they re still interpreted as hyperlinks.

![image](https://user-images.githubusercontent.com/18191964/57088681-6499b500-6d35-11e9-8a88-e183487eacf7.png)

Currently, the markdown not fully supported in `{% tabs , %}`. So, I have to use `{% code %}`...

**Comment by stevenjoezhang** [comment]
See also: https://github.com/theme-next/hexo-theme-next/issues/654
