### ISSUE TITLE
图片块解析错误！

### ISSUE THREAD

**Issue by siaimes** [theme-next/hexo-theme-next#857]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
示例代码
```
\`\`\`
1
\`\`\`
![2](3.jpg)
```
### Expected behavior 
```
1
```
[3.jpg]

### Actual behavior 
```
1
```
[3.jpg]
2

### Steps to reproduce the behavior 
Paste the code on any post to reproduce it!

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
$ node -v && npm -v
v8.12.0
6.4.1
```

### Package dependencies Information

```
$ cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "braces": "^3.0.1",
    "eslint": "^5.16.0",
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-fs": "^1.0.2",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^2.2.5",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-recommended-posts": "^1.0.3",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-pandoc": "^0.2.5",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.2"
  }
}
```

#### Hexo version

```
$ hexo -v
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17763 win32 x64
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

```yml
Theoretically independent of Hexo configuration
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

#### NexT Configuration:

```yml
I only modified sensitive information!
```

### Other Information

**Comment by stevenjoezhang** [comment]
看上去不是NexT的bug

**Comment by siaimes** [comment]
@stevenjoezhang 我只是提出问题，内部什么情况就不知道啦，你们可以分析一下！

**Comment by siaimes** [comment]
@ivan-nginx It’s English now.

**Comment by stevenjoezhang** [comment]
@siaimes 能否换Hexo的默认主题，测试一下这个bug是否存在？

**Comment by siaimes** [comment]
@stevenjoezhang 试了一下，全新的Hexo文件夹也会存在这个问题，那我去Hexo反馈一下这个bug吧，谢谢啦！

**Comment by stevenjoezhang** [comment]
或者您试试把`hexo-renderer-pandoc`换成别的：
```
npm remove hexo-renderer-pandoc --save
npm install hexo-renderer-marked --save
```

**Comment by siaimes** [comment]
@stevenjoezhang 全新的下载的hexo文件夹也受到我安装的包的影响吗？

**Comment by stevenjoezhang** [comment]
嗷，那就是Hexo的锅了……

**Comment by weyusi** [comment]
[2] caption is added by the theme through this line,
https://github.com/theme-next/hexo-theme-next/blob/aa20bb0ebee64ca462a31431834e0bbb5af34c8b/source/js/utils.js#L32

**Comment by stevenjoezhang** [comment]
这个只在`fancybox: true`时启用

**Comment by weyusi** [comment]
> 这个只在`fancybox: true`时启用

Indeed,
https://github.com/theme-next/hexo-theme-next/blob/51bf6a010d45deb4ecaa29a2b94133287aa477b4/source/js/next-boot.js#L29

@siaimes 
can you attach your theme's `_config.yml`? is fancybox enabled?
I tried `![2](3.jpg)` while fancybox is disabled and I don't see [2] when (3.jpg) is a valid link.

**Comment by weyusi** [comment]
> @siaimes 能否换Hexo的默认主题，测试一下这个bug是否依然存在？



> @stevenjoezhang 试了一下，全新的Hexo文件夹也会存在这个问题，那我去Hexo反馈一下这个bug吧，谢谢啦！

do you mean [hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape)?
Note hexo-theme-landscape will add [2] caption even when fancybox is _disabled_.
If you remove [this line](https://github.com/hexojs/hexo-theme-landscape/blob/5d82fd51c7dc2c7fc886413bae313fe0cef50b57/source/js/script.js#L95) in hexo-theme-landscape, the [2] caption will not be displayed (if 3.jpg exists). So, it's related to theme, not hexo itself.

**Comment by siaimes** [comment]
> > @siaimes 能否换Hexo的默认主题，测试一下这个bug是否依然存在？
> 
> > @stevenjoezhang 试了一下，全新的Hexo文件夹也会存在这个问题，那我去Hexo反馈一下这个bug吧，谢谢啦！
> 
> do you mean [hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape)?
> Note hexo-theme-landscape will add [2] caption even when fancybox is _disabled_.
> If you remove [this line](https://github.com/hexojs/hexo-theme-landscape/blob/5d82fd51c7dc2c7fc886413bae313fe0cef50b57/source/js/script.js#L95) in hexo-theme-landscape, the [2] caption will not be displayed (if 3.jpg exists). So, it's related to theme, not hexo itself.

In short, theme-next said that it is a problem with hexo. Hexo said that it is a problem caused by the theme. Anyway, I just raised a potential problem, and the rest is left to you. I can only try to avoid such usage.

**Comment by stevenjoezhang** [comment]
If the issue is caused by fancybox, it should be independent of the code block...
Need to do more test

**Comment by weyusi** [comment]
> Anyway, I just raised a potential problem, and the rest is left to you. I can only try to avoid such usage.

I'm trying to troubleshoot the issue with you. The thing is I can't reproduce the bug, so I need more information from you. I requested more information from my [previous comment](https://github.com/theme-next/hexo-theme-next/issues/857#issuecomment-510740529),

So, can you please attach your theme's _config.yml?

If you can attach your post's md file (through pastebin.com), or even better, upload the whole blog to github (including the theme), it would help me tremendously to debug the issue.

I also suggested a workaround for you in my [previous comment](https://github.com/theme-next/hexo-theme-next/issues/857#issuecomment-510742763), by removing [this line](https://github.com/hexojs/hexo-theme-landscape/blob/5d82fd51c7dc2c7fc886413bae313fe0cef50b57/source/js/script.js#L95) from hexo-theme-landscape, and check whether the issue still persists.

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/61215203-b0f17000-a73c-11e9-965d-24de368bab64.png)
No markdown renderer. Try run this in bash.
```bash
npm install --save hexo-renderer-marked
```

**Comment by siaimes** [comment]
> ![image](https://user-images.githubusercontent.com/15902347/61215203-b0f17000-a73c-11e9-965d-24de368bab64.png)
> No markdown renderer. Try run this in bash.
> 
> ```shell
> npm install --save hexo-renderer-marked
> ```

Thank you for your reply, but it doesn't seem to work.

**Comment by siaimes** [comment]
> > Anyway, I just raised a potential problem, and the rest is left to you. I can only try to avoid such usage.
> 
> I'm trying to troubleshoot the issue with you. The thing is I can't reproduce the bug, so I need more information from you. I requested more information in my [previous comment](https://github.com/theme-next/hexo-theme-next/issues/857#issuecomment-510740529),
> 
> So, can you please attach your theme's _config.yml?
> 
> If you can attach your post's md file (through pastebin.com), or even better, upload the whole blog to github (including the theme), it would help me tremendously to debug the issue.
> 
> I also suggested a workaround for you in my [previous](https://github.com/theme-next/hexo-theme-next/issues/857#issuecomment-510742763) [comments](https://github.com/hexojs/hexo/issues/3564#issuecomment-509871765), by removing [this line](https://github.com/hexojs/hexo-theme-landscape/blob/5d82fd51c7dc2c7fc886413bae313fe0cef50b57/source/js/script.js#L95) from hexo-theme-landscape; or if you're using hexo-theme-next then [remove these lines](https://github.com/theme-next/hexo-theme-next/blob/c106425c7794bd137d89d64c2a7e5365505727c2/source/js/utils.js#L32-L34), and check whether the issue still persists.
> 
> The info that I requested so far from you is not on a whim, but to try to pinpoint the source of the issue and to confirm it. So far, I received no additional information/confirmation that is helpful to the cause.

Thank you for your attention to my question. I have uploaded my entire blog to my homepage. I hope that I have deleted all the privacy information, I will delete this project after 24 hours.

[project](https://github.com/siaimes/test)

[test page](https://blog.siaimes.me/test/2019/07/15/test.html)

**Comment by stevenjoezhang** [comment]
The bug is caused by `hexo-renderer-pandoc` and has nothing to do with theme NexT.
Try:
```
npm uninstall hexo-renderer-pandoc --save
npm install hexo-renderer-marked --save
```

**Comment by weyusi** [comment]
Anyone having similar issue, please refer to [this workaround](https://github.com/wzpan/hexo-renderer-pandoc/issues/34#issuecomment-512662876).

**Comment by stevenjoezhang** [comment]
Maybe we need to prompt `hexo-renderer-pandoc` users about this issue in the documentation.

**Comment by curbengh** [comment]
I just had a quick test with hexo-renderer-pandoc, figure it might be useful for the doc.
Assuming fancybox is disabled, if an image is preceded or followed by any characters or has a backslash at the end, caption would not be shown. Caption is only shown when the image has new line before _and_ after.

```
aaa
![alt text](https://postimgs.org/img/logo.png)

![alt text](https://postimgs.org/img/logo.png)
bbb

![alt text](https://postimgs.org/img/logo.png)\

![alt text](https://postimgs.org/img/logo.png)
```

![pandoc](https://user-images.githubusercontent.com/43627182/63903444-95bc9480-ca4c-11e9-9427-4bc171aae549.png)

**Comment by stevenjoezhang** [comment]
```
pandoc:
  extensions:
    - '-implicit_figures'
```

**Comment by raytroop** [comment]
@stevenjoezhang
 it no longer work in *hexo-renderer-pandoc 0.50*
