### ISSUE TITLE
很想知道是怎么做到主题和自己写的文章分离的？

### ISSUE THREAD

**Issue by kpper** [theme-next/hexo-theme-next#858]
jekyll搭建的md文章在post里，hexo写的文章部署后怎么做到分离的？clone的主题都看不到作者写的文章

**Comment by sli1989** [comment]
jekyll 也是写 md 渲染页面呀。源md文件只能找作者的源库。

**Comment by kpper** [comment]
> 
> 
> jekyll 也是写 md 渲染页面呀。源md文件只能找作者的源库。

我的意思是说这个主题下面我没有发现source/post之类放blog的文件夹，打开博客却能看到文章，这个主题是怎么外部引用文章的，如果可以，我就可以新建个仓库专门存储md文件，这样别人clone时就不会包含你写的文章了

**Comment by JiangTJ** [comment]
@kpper 
Emmm, 建议你尝试使用下hexo
https://hexo.io/zh-cn/docs/setup

以及切换NexT主题
https://theme-next.org/docs/getting-started/installation

**Comment by stevenjoezhang** [comment]
主题和文章当然是分离的？您可能对Hexo有一些误解。

**Comment by YazidLee** [comment]
:smirk:文章是放在博客根目录的source/_posts下的，和主题文件夹是分开的
