### ISSUE TITLE
Add indent for div "social_share" in Gemini

### ISSUE THREAD

**Issue by online** [theme-next/hexo-theme-next#859]
Hello.

When I use `mobile_layout_economy: true` in Gemini theme I see that need to add indent for block with social buttons (watch my screenshot below):

![vxUKVSLjMb](https://user-images.githubusercontent.com/722881/57011969-dc1ff500-6c0c-11e9-9bee-6908a760ab2b.gif)

In other themes didn't check.

**Comment by 1v9** [comment]
```yml
# Reduce padding / margin indents on devices with narrow width.
mobile_layout_economy: true
```
***Reduce padding / margin indents on devices with narrow width.***

It depends on your device width. So, not only `social_share` or `Gemini` will stay close to the left side of the screen, other elements or schemes too.

**Comment by stevenjoezhang** [comment]
Yes, no left-margin is expected behavior

**Comment by stevenjoezhang** [comment]
Yes, no left-margin is expected behavior
