### ISSUE TITLE
What's the meaning of site total number of readings is 14:06

### ISSUE THREAD

**Issue by shijiebei2009** [theme-next/hexo-theme-next#86]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. Here is a online example http://codepub.cn/  at the bottom of the page, there is a coffee cup and 14:06, I don't know what's the meaning of 14:06, It's more like a timestamp.

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

```
[X] Latest Master branch.
[X] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[X] Mist
[] Pisces
[] Gemini
```

#### NexT Configuration:

```yml

```

**Comment by wafer-li** [comment]
![image](https://user-images.githubusercontent.com/12459199/35322141-84d619b0-012c-11e8-8168-50bb8ac5dc41.png)

It means you need 14 hours and 6 minutes to totally read the posts

**Comment by shijiebei2009** [comment]
@wafer-li
But when I press F12 in chrome, I got this <span title="站点总阅读次数">14:06</span> is it right? or I can change this config manually.

**Comment by shijiebei2009** [comment]
this is a full code in chrome
`<div class="footer-inner">
        <div class="copyright">© 2015 — <span itemprop="copyrightYear">2018</span>
  <span class="with-love">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Wang Xu</span>

  
    <span class="post-meta-divider">|</span>
    <span class="post-meta-item-icon">
      <i class="fa fa-area-chart"></i>
    </span>
    <span title="站点总字数">846k</span>
    <span class="post-meta-divider">|</span>
    <span class="post-meta-item-icon">
      <i class="fa fa-coffee"></i>
    </span>
    
    <span title="站点总阅读次数">14:06</span>
  
</div>`

**Comment by wafer-li** [comment]
@shijiebei2009 

You use the old version.
Update to the latest release to fix the translate issue.

It should be 『站点总阅读时间』like the pic I posted above.

**Comment by aixiu** [comment]
我都忘记如何开启了，5.X时开启了更新到6.X就消失了，在哪开启？

**Comment by ivan-nginx** [comment]
@aixiu https://github.com/theme-next/hexo-theme-next/tree/master/docs/zh-CN

**Comment by tsanie** [comment]
@aixiu 
> 第三方插件 hexo-wordcount 被 hexo-symbols-count-time 所取代，因为 hexo-symbols-count-time 没有任何外部 nodejs 依赖、也没有会导致生成站点时的性能问题 language filter。

The [`hexo-wordcount`](https://github.com/willin/hexo-wordcount) is now replaced by [`hexo-symbols-count-time`](https://github.com/theme-next/hexo-symbols-count-time), so you need to follow the [usage](https://github.com/theme-next/hexo-symbols-count-time#usage) and adjust the configures.

**Comment by aixiu** [comment]
@tsanie @ivan-nginx It's already done. Have you ever add these settings into your Hexo's _config.yml (not only the theme NexT's)
```
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
```
It just forgot to set it up

**Comment by ivan-nginx** [comment]
@aixiu it's written in main plugin readme: https://github.com/theme-next/hexo-symbols-count-time
