### ISSUE TITLE
移动端如何不使用网页端同比缩小的版式

### ISSUE THREAD

**Issue by Jeffchal** [theme-next/hexo-theme-next#860]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x]  And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
![](https://ws1.sinaimg.cn/large/0068n1Fcgy1g2mxuzdt0nj30u01rcnju.jpg)

### Actual behavior 
![](https://ws1.sinaimg.cn/large/0068n1Fcgy1g2mxu4m5jdj30u01rcqlx.jpg)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by Jeffchal** [comment]
还有请教下大家，手机端一般怎么调试，应为没法在手机端直接改参数实时查看，每次都要hexo g -d，而且要等很久，假如每次微调太耗费精力了。

**Comment by stevenjoezhang** [comment]
手机端可以用hexo s调试，或者直接用Chrome的检查器

**Comment by Jeffchal** [comment]
> 手机端可以用hexo s调试，或者直接用Chrome的检查器
@stevenjoezhang 不好意思，不太明白，hexo s 手机端怎么查看，不能也调用localhost：4000端口吧。同比例缩小网页好像最小是25%，似乎与手机界面不太一样

**Comment by stevenjoezhang** [comment]
我一般是用主机运行`hexo s`，然后手机通过局域网访问4000端口，进行debug

**Comment by Jeffchal** [comment]
我傻逼了，f12自带手机模式。。ctrl+shift+m

**Comment by stevenjoezhang** [comment]
如果有其他疑问，欢迎提交新的issue
