### ISSUE TITLE
如果使用mermaid創建了一個比較多的信息的圖的話，字體會變很小

### ISSUE THREAD

**Issue by Soanguy** [theme-next/hexo-theme-next#863]
如果使用mermaid創建了一個比較多的信息的圖的話，字體會變很小，就像這樣
![image](https://user-images.githubusercontent.com/24608949/57125577-8b4efe80-6dbc-11e9-9c8f-2fead8e21a01.png)
我嘗試著把網頁放大，他的字反而被覆蓋掉了。就像這樣
![image](https://user-images.githubusercontent.com/24608949/57125698-e680f100-6dbc-11e9-9eaf-f0e6decd77d4.png)
所以可不可以在`_config.yml`內添加一個`生成svg`格式的選項，這樣的話圖片可以放大顯示。比較小的信息也可以被看到。

如果可以的話，請添加這項功能吧。謝謝。

**Comment by stevenjoezhang** [comment]
Maybe you can read the docs: https://mermaidjs.github.io/ or ask maintainers of mermaid for help: https://github.com/knsv/mermaid/issues

**Comment by stevenjoezhang** [comment]
@Soanguy could you please provide the source code of the mermaid graph or URL of the page?

**Comment by Soanguy** [comment]
> @Soanguy could you please provide the source code of the mermaid graph or URL of the page?

I'm sorry for the slow reply.my source code is following:

```
{% mermaid graph TD %} 
Z[だ] -->|簡体| A(だ) 
A -->|過去形| B(だった) 
A -->|否定形| C(ではない) 
B -->|否定形| D[ではなかった] 
C -->|過去形| D[ではなかった] 
A -->|推量形| K(だろう) 
D -->|疑問形| I[+か] 
Z -->|书面体|M[である] 
M -->|否定形| C(ではない) 
M -->|過去形| N[であった] 
M -->|仮定形| O[であれば] 
M -->|推量形| P[であろう] 
Z -->|敬体| E 
E[です] -->|過去形| F(でした) 
E -->|推量形| L(でしょう) 
E -->|否定形| G(ではありません) 
F -->|否定形| H[ではありませんでした] 
G -->|過去形| H[ではありませんでした] 
H -->|疑問形| J[+か] 
{% endmermaid %}
```

**Comment by stevenjoezhang** [comment]
> 所以可不可以在_config.yml內添加一個生成svg格式的選項，這樣的話圖片可以放大顯示。比較小的信息也可以被看到。

![屏幕快照 2019-09-09 下午4 18 35](https://user-images.githubusercontent.com/16272760/64514598-86c3c500-d31d-11e9-8ae0-92635b37020b.png)

It seems that the latest version of mermaid will generate diagrams in svg format by default?

**Comment by stevenjoezhang** [comment]
I checked the latest version of mermaid again, and it looks like that  svg image is generated and it scales correctly.

Will you write back if you solve the problem?

**Comment by Soanguy** [comment]
> I checked the latest version of mermaid again, and it looks like that svg image is generated and it scales correctly.
> 
> Will you write back if you solve the problem?

![image](https://user-images.githubusercontent.com/24608949/65780651-c4797800-e17c-11e9-89de-2e04e7fbc0e2.png)

it seems doesn't work on my computer., I try to update the CDN to mermaid 8.2.6. Maybe I ignore something?

**Comment by Soanguy** [comment]
![image](https://user-images.githubusercontent.com/24608949/65782166-aa8d6480-e17f-11e9-9dc3-07e8de64323b.png)

there is something wrong ，it is SVG exactly，but when I try to zoom in ，the characters will also be disappeared。

**Comment by stevenjoezhang** [comment]
Don't use <kbd>ctrl</kbd>/<kbd>command</kbd>+<kbd>+</kbd>/<kbd>-</kbd> to zoom in / out, but use two-finger swipe on the trackpad. The former method will change the relative font size of svg.

In general, theme-next can't do anything about it. I personally believe that the mermaid team will handle this issue properly: https://github.com/knsv/mermaid/issues/959
