### ISSUE TITLE
Can Gitalk support lazy loading like Gitment?

### ISSUE THREAD

**Issue by asdf2014** [theme-next/hexo-theme-next#871]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

Gitalk support lazy loading like Gitment.

### Actual behavior 

Gitalk has been loaded when pages were opened.

### Steps to reproduce the behavior 
Open any page with gitalk

* Link to demo site with this feature: https://yuzhouwan.com/posts/5845/
* Link(s) to source code or any usefull link(s): N/A

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by stevenjoezhang** [comment]
No. Please ask gitalk for this feature: https://github.com/gitalk/gitalk/issues

**Comment by asdf2014** [comment]
@stevenjoezhang OK, Thanks.
