### ISSUE TITLE
代码块中有<符号，生成时会报错ERROR Parse Error

### ISSUE THREAD

**Issue by louyaolong** [theme-next/hexo-theme-next#875]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
md笔记中有如下**代码块**：
```java
int i = 0
 if(i < 6 ){
   i++
 }
```
预期：hexo g，生成时正常
### Actual behavior 
生成时报错：ERROR Parse Error: < <span class="number">6</span> ){</span><br><span class="line">   i++</span><br><span class="line"> }

### Steps to reproduce the behavior 
很奇怪的问题，我把"<"换成其他任何符号或者文字都可以。就是"<"会报错。
换成这样也行：
```java
int i = 0
 if(i 小于啥都行 6 ){
   i++
 }
求解，不甚感激！
```
* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
node.js
v11.10.0
npm
6.7.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "gulp": "^4.0.2",
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^5.0.1",
    "gulp-minify-css": "^1.2.4",
    "hexo": "^3.8.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-deployer-git": "^1.0.0",
    "hexo-filter-github-emojis": "^2.0.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-neat": "^1.0.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus-plus": "^0.3.5",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.6.0",
    "hexo-wordcount": "^6.0.1"
  }
}

```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 17.7.0 darwin x64
node: 11.10.0
v8: 7.0.276.38-node.17
uv: 1.26.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 4
llhttp: 1.1.1
http_parser: 2.8.0
openssl: 1.1.1a
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml

```

**Comment by sli1989** [comment]
![](https://i.loli.net/2019/05/16/5cdd227b7a08f23017.png)
![](https://i.loli.net/2019/05/16/5cdd227b92a7d46715.png)

Can you provide u live demo?

**Comment by louyaolong** [comment]
Thank you for your reply！This is my MD note，I made an error while debugging locally. I haven't uploaded it to the line yet.

When I change < to something else, it's normal.




At 2019-05-16 16:43:36, "Alex LEE" <notifications@github.com> wrote:





Can you provide u live demo?

**Comment by louyaolong** [comment]
> ![](https://camo.githubusercontent.com/be82f3963fa40bab346c4a0d435e8078202af4fa/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30352f31362f3563646432323762376130386632333031372e706e67)
> ![](https://camo.githubusercontent.com/c690c0176b696f334290414ef9c8e182d42eee55/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30352f31362f3563646432323762393261376434363731352e706e67)
> 
> Can you provide u live demo?

Hello, when I use"& lt;", it works.
```java
{% codeblock lang:java%}
  int i = 0
  if(i &lt; 4){
    i++
  }
{% endcodeblock %}

```javascript
var i = 0
if(i &lt; 1){
  i++
}
```

**Comment by sli1989** [comment]
maybe test your hexo renderer? one by one.

**Comment by louyaolong** [comment]
Thank you, it can be sovled when I use "& lt;"  instead of "<"

> maybe test your hexo renderer? one by one.



> maybe test your hexo renderer? one by one.

**Comment by louyaolong** [comment]
> maybe test your hexo renderer? one by one.

hello,I downloaded next again without making any changes. It was the same mistake.

**Comment by stevenjoezhang** [comment]
Can you test it with another theme?

**Comment by louyaolong** [comment]
> Can you test it with another theme?

Thank you for your reply，I just tested it with the landscape theme, and I made the same mistake.

**Comment by stevenjoezhang** [comment]
This is an issue caused by the renderer, please ask its maintainers for help.
