### ISSUE TITLE
A bug on toc generation

### ISSUE THREAD

**Issue by ming71** [theme-next/hexo-theme-next#877]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I use the inserted toc function to generate toc , and a normal toc is expected.

### Actual behavior 
However , there is always a strange symbol in front of my generated head !!!!!
BTW,I have closed the auomatic  number choice .
![微信截图_20190518153727](https://user-images.githubusercontent.com/43720092/57966326-e3702e00-7982-11e9-9ade-a4406c06e87a.png)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
Need more information.

**Comment by stevenjoezhang** [comment]
Or can you use Hexo default theme - landscape, for more testing?

**Comment by stevenjoezhang** [comment]
@ming71 Can you provide more information? e.g. `package.json`

**Comment by jiangtj** [comment]
If you use marked, please execute the following command and provide the output to us.
```bash
hexo config marked
```
output like:
```json
{ gfm: true,
  pedantic: false,
  sanitize: false,
  tables: true,
  breaks: false,
  smartLists: true,
  smartypants: true,
  modifyAnchors: '',
  autolink: true }
```

**Comment by ming71** [comment]
soory , I've execute the command  , only to output as follow
` Total precache size is about 7.51 MB for 160 resources.`

**Comment by ming71** [comment]
> @ming71 Can you provide more information? e.g. `package.json`

`{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "eslint": "^4.19.1",
    "gitalk": "^1.5.0",
    "hexo": "^3.8.0",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-blog-encrypt": "^2.1.1",
    "hexo-deployer-git": "^1.0.0",
    "hexo-filter-github-emojis": "^2.0.1",
    "hexo-filter-optimize": "^0.2.5",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-calendar": "git://github.com/howiefh/hexo-generator-calendar.git",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-related-popular-posts": "^3.0.5",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-service-worker": "^1.0.1",
    "hexo-symbols-count-time": "^0.6.0",
    "live2d-widget-model-hijiki": "^1.0.5",
    "lodash": "^4.17.11",
    "markdown-it-emoji": "^1.4.0"
  }
}
`

**Comment by ming71** [comment]
> @ming71 Can you provide more information? e.g. `package.json`

This is my package contents:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "eslint": "^4.19.1",
    "gitalk": "^1.5.0",
    "hexo": "^3.8.0",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-blog-encrypt": "^2.1.1",
    "hexo-deployer-git": "^1.0.0",
    "hexo-filter-github-emojis": "^2.0.1",
    "hexo-filter-optimize": "^0.2.5",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-calendar": "git://github.com/howiefh/hexo-generator-calendar.git",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-related-popular-posts": "^3.0.5",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-service-worker": "^1.0.1",
    "hexo-symbols-count-time": "^0.6.0",
    "live2d-widget-model-hijiki": "^1.0.5",
    "lodash": "^4.17.11",
    "markdown-it-emoji": "^1.4.0"
  }
}

```

**Comment by stevenjoezhang** [comment]
Any URLs?

**Comment by stevenjoezhang** [comment]
It's caused by `header-anchor` generated by `hexo-renderer-markdown-it`.  See: https://github.com/hexojs/hexo-renderer-markdown-it/search?q=header-anchor&unscoped_q=header-anchor

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo-renderer-markdown-it/issues/102

**Comment by curbengh** [comment]
`¶` is added by default in hexo-renderer-markdown-it <4

In [v4](https://github.com/hexojs/hexo-renderer-markdown-it/releases/tag/4.0.0), the symbol is no longer added by default.

``` diff
markdown:
  anchors:
+   permalink: false
    permalinkClass: 'header-anchor'
    permalinkSymbol: '¶'
```

ref https://github.com/hexojs/hexo-renderer-markdown-it/issues/55#issuecomment-558662340
