### ISSUE TITLE
Menu order is incorrect

### ISSUE THREAD

**Issue by NanerLee** [theme-next/hexo-theme-next#878]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

### Expected behavior 

![image](https://user-images.githubusercontent.com/16791509/57970837-16cdaf80-79b9-11e9-9fb0-8cd2706007df.png)

### Actual behavior 

![image](https://user-images.githubusercontent.com/16791509/57970835-0e757480-79b9-11e9-899b-6de607b73deb.png)

### Node.js and NPM Information

```
$ node -v
v10.15.3

$ npm -v
6.4.1

```

### Package dependencies Information

```
$ cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^0.2.0",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.4.4",
    "hexo-tag-asciinema": "0.0.1"
  }
}

```

#### Hexo version

```
$ hexo -v
(node:14444) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17763 win32 x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
menu:
  home: / || home
  categories: /categories/ || th
  tags: /tags/ || tags
  archives: /archives/ || archive
  # schedule: /schedule/ || calendar
  about: /about/ || user
  sitemap: /sitemap.xml || sitemap
  # commonweal: /404/ || heartbeat
```

### Other Information 

The menu order is different from the order in config. 

What's more, old version v6.7 is normal.

**Comment by stevenjoezhang** [comment]
Have you tried to execute `hexo clean` and clear your web browser's cache?

**Comment by stevenjoezhang** [comment]
Are you using NexT data-file? Since lodash is using deep copy, even if you set the order of the menu items, they will follow the default order in `_config.yml`.

**Comment by stevenjoezhang** [comment]
See also: https://stackoverflow.com/questions/42539939/preserve-order-of-keys-when-merging-two-objects-in-javascript-lodash

**Comment by ivan-nginx** [comment]
I think data-files for NexT useless vs `theme_config` in Hexo. Peoples are confusing with this 2 ways and data-files was created when `theme_config` wasn't exists.

**Comment by stevenjoezhang** [comment]
Yes, it can be added to v8 roadmap.

**Comment by stevenjoezhang** [comment]
It's time to rethink this question. NexT's menu settings are `object` rather than `array`, which can cause problems when using deepmerge. See also https://github.com/hexojs/hexo/pull/3967

**Comment by stevenjoezhang** [comment]
Or set `override: true` in `_config.yml`

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/hexo-theme-next/commit/a527bfdf11d558ffd958cd0a0b05416fb1caaa33
