### ISSUE TITLE
next 主题木有官方的配置教程吗？

### ISSUE THREAD

**Issue by Michael728** [theme-next/hexo-theme-next#879]
之前有一个这样的教程：
- https://theme-next.iissnan.com/getting-started.html

但是发现这个教程中的有些内容已经过时了，请问现在是否有类似的教程呢？

**Comment by stevenjoezhang** [comment]
![屏幕快照 2019-05-19 上午11 16 56](https://user-images.githubusercontent.com/16272760/57977280-b2960480-7a27-11e9-8b22-948b1686b016.png)

https://theme-next.org
