### ISSUE TITLE
The word count at the bottom of the website is not displayed. The previous version 5.0 is available, and the 6.0 update will not be displayed.

### ISSUE THREAD

**Issue by iiskei** [theme-next/hexo-theme-next#88]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The bottom displays the word count information.

### Actual behavior 
The bottom  is blank.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

#### NexT Configuration:

```yml

```

**Comment by wafer-li** [comment]
Could you please provide some screenshots of it?

**Comment by iiskei** [comment]
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: true
  awl: 5
  wpm: 200
I don't know how to upload the screenshot. Is it wrong for me to do this? The word count in the article and the word count at the bottom are not displayed?

**Comment by iiskei** [comment]
I found something like this "  Site words total count: 43.4k"

**Comment by tsanie** [comment]
@iiskei just copy & paste the screenshots in the input box.

---

some partial configure need to be added into the Hexo's `_config.yml` like https://github.com/theme-next/hexo-theme-next/issues/86#issuecomment-360659508 that mentioned.

**Comment by iiskei** [comment]
So it means to upgrade 6.0, and the word count at the bottom is not displayed?

**Comment by iiskei** [comment]
![1](https://user-images.githubusercontent.com/18711960/35423132-38e95754-0287-11e8-8377-ae33444cfc06.jpg)
like this

**Comment by tsanie** [comment]
@iiskei the function is still here. but the word plugin have been replaced by another one, that fixed some [issues](https://github.com/willin/hexo-wordcount/issues/7). So need to adjust some configures and reopen this function. ([`Here`](https://github.com/theme-next/hexo-symbols-count-time) is the new plugin)

**Comment by iiskei** [comment]
I know that the statistical plug-in has been replaced, and my update is up to date, and the problem is that he still doesn't display the word count.

**Comment by iiskei** [comment]
![qq 20180126110342](https://user-images.githubusercontent.com/18711960/35423428-ac58fba8-0288-11e8-8c2d-0a0a9529689e.jpg)
![qq 20180126110410](https://user-images.githubusercontent.com/18711960/35423422-a88f0cba-0288-11e8-801e-189f25cfb5d7.jpg)

**Comment by iiskei** [comment]
What else do you need to configure?

**Comment by tsanie** [comment]
Have you ever add these settings into your **Hexo**'s `_config.yml` (not the theme NexT's)
```yml
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
```

**Comment by iiskei** [comment]
OK, I see. I'll try.

**Comment by iiskei** [comment]
According to what you said, it still doesn't show, the browser console did not report wrong, I hope you will test to see if there is this problem.

**Comment by iiskei** [comment]
Oh, god, this was supposed to be set twice. I was careless. I'm sorry.

**Comment by tsanie** [comment]
@iiskei That's really strange... The plugin runs well here.
![image](https://user-images.githubusercontent.com/980449/35424039-0b616c9a-028c-11e8-9786-65469d0739f4.png)
Did load the plugins by settings within the Hexo's `config.yml` (instead of the auto-detect mode)? like
```yml
plugins:
  ...
  - hexo-symbols-count-time
```
In that way, you should put the plugin into this parameter to ensure it will be loaded.
