### ISSUE TITLE
大家都是怎么比较next和next-reloaded之间的差异，完美地进行版本迁移的呢？为什么我的弄了一下直接一片空白

### ISSUE THREAD

**Issue by weidongzhou1994** [theme-next/hexo-theme-next#880]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md

**Comment by weidongzhou1994** [comment]
我知道这个文档，但是它写得有些模糊，“任何其它可能的附加自定义内容；为了定位它们，你可以通过某些工具在仓库间比较”，这一句话怎么理解，哪些工具能够做到这一点呢？

**Comment by stevenjoezhang** [comment]
只能手动merge了，毕竟很多配置都改了……你可以先通过`git diff`看看对老版本的修改，然后再看看能否将其应用到新版本上

工具就是`git diff`，或者一些文本编辑器自带的比较功能

**Comment by weidongzhou1994** [comment]
这么麻烦吗？相当于重新构建了吗？

**Comment by stevenjoezhang** [comment]
也不完全是重新构建……主要问题是`_config.yml`中的很多配置项的名称都改变了，所以只能手动改

**Comment by weidongzhou1994** [comment]
哦，真麻烦，不更新是不是也没什么问题？

**Comment by stevenjoezhang** [comment]
这个看你的需求了。新版加入了不少新功能，旧版本当然也可以继续用。

**Comment by weidongzhou1994** [comment]
主要添加的新功能是什么呢？我看文件里面写得比较简略。

**Comment by stevenjoezhang** [comment]
比如优化了样式表，增加了一些新的评论系统和第三方服务，修复了各种bug等等。具体可以看这里：https://theme-next.org

**Comment by sli1989** [comment]
自定义不多的话，建议升级。毕竟老版本暂停维护了。

**Comment by 1v9** [comment]
讲真外观没有什么显著的变化🤦‍♂️，主要就是配置项要更改

**Comment by weidongzhou1994** [comment]
我暂时不想改，怎么去除那个Attention呢？看着比较烦。
![image](https://user-images.githubusercontent.com/40510496/58062495-1d247d00-7bad-11e9-9ae1-e318014604c8.png)

**Comment by stevenjoezhang** [comment]
你在NexT的源代码中搜索`============`，然后把相关内容注释掉就行了

**Comment by weidongzhou1994** [comment]
小白一个，怎么把相关内容注释掉呢？能否给个简单的示例。

**Comment by stevenjoezhang** [comment]
打开`scripts/merge-configs.js`，删除22-30行
