### ISSUE TITLE
Got problems when change the color of "Link"

### ISSUE THREAD

**Issue by shawnleetttt** [theme-next/hexo-theme-next#888]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Set links' color in post like this 
![图片](https://user-images.githubusercontent.com/33088850/58400998-42265d80-808f-11e9-9da6-7b09962b9828.png)

### Actual behavior 
Only when links are in my site ( for example my blog is www.abc.com, only links are in www.abc.com/ then links will change color
![图片](https://user-images.githubusercontent.com/33088850/58401295-06d85e80-8090-11e9-9e7e-64e95b45efdd.png)

### Steps to reproduce the behavior 
1. add these in `themes\next\source\css\_common\components\post\post.styl`
```
.post-body p a{
  color: #0593d3;
  border-bottom: none;
  border-bottom: 1px solid #0593d3;
  &:hover {
    color: #fc6423;
    border-bottom: none;
    border-bottom: 1px solid #fc6423;
  }
}
```

2. hexo g
3. hexo s

* Link to demo site with this issue: https://www.shawnleetttt.xyz/posts/b9d23002/

### Node.js and NPM Information

```
v10.15.3
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-asset-image": "0.0.3",
    "hexo-autonofollow": "^1.0.1",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-leancloud-counter-security": "^1.4.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.4.4",
    "hexo-tag-aplayer": "^3.0.4",
    "list": "^2.0.18",
    "live2d-widget-model-hijiki": "^1.0.5",
    "hexo-generator-i18n": "0.0.7"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17763 win32 x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```
### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

**Comment by stevenjoezhang** [comment]
It's not the correct way. Try this:
Edit `source/css/_variables/custom.style`:
```
$link-hover-color             = $blue
$link-decoration-color        = $grey-light
$link-decoration-hover-color  = $blue
```

**Comment by shawnleetttt** [comment]
> 
> 
> It's not the correct way. Try this:
> Edit `source/css/_variables/custom.style`:
> 
> ```
> $link-hover-color             = $blue
> $link-decoration-color        = $grey-light
> $link-decoration-hover-color  = $blue
> ```

I do as you said , and here's the result

Before the mouse is placed
![图片](https://user-images.githubusercontent.com/33088850/58427271-b550c380-80d1-11e9-80cb-6696140bf937.png)
After
![图片](https://user-images.githubusercontent.com/33088850/58427290-c26db280-80d1-11e9-875d-da03d534fa1c.png)

But what I actully want is that : 
Before is blue
After is Orange

And one more thing , it seems like that "Menu" 's color is also influenced 
![图片](https://user-images.githubusercontent.com/33088850/58427512-69eae500-80d2-11e9-8459-6aba693db9cc.png)
![图片](https://user-images.githubusercontent.com/33088850/58427527-72dbb680-80d2-11e9-9f94-ccab622963f6.png)

Thx for u answer :D

**Comment by stevenjoezhang** [comment]
Or you can add these in `themes\next\source\css\_common\components\post\post.styl`
```
.post-body p a, .post-body p span.exturl {
  color: #0593d3;
  border-bottom: none;
  border-bottom: 1px solid #0593d3;
  &:hover {
    color: #fc6423;
    border-bottom: none;
    border-bottom: 1px solid #fc6423;
  }
}
```

**Comment by shawnleetttt** [comment]
Thx , that's work

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
2019年6月12日星期三凌晨12点19分，ᴍɪᴍɪ <notifications@github.com> 来信：
