### ISSUE TITLE
不能在public文件夹中生成archives和tags

### ISSUE THREAD

**Issue by CapAllen** [theme-next/hexo-theme-next#898]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
正常访问博客

### Actual behavior 
博客文章什么的都没问题，但是由于public文件夹下没有生成archives和tags文件夹，导致博客中的archives和tags访问失败。

### Steps to reproduce the behavior 
参照[Alex的教程](http://saili.science/2017/04/02/github-for-win/)一部部搭建的  
1. hexo clean
2. hexo g
3. hexo d

* Link to demo site with this issue: [Allen's Blog](https://www.capallen.top/)
* Link(s) to source code or any usefull link(s): [Github-blog](https://github.com/CapAllen/CapAllen.github.io)

不知道到底哪儿有问题，请求支援~ 万分感谢！

**Comment by 1v9** [comment]
移步我们的官网查看步骤

**Comment by sli1989** [comment]
Seems it works fine?

**Comment by CapAllen** [comment]
> 
> 
> 移步我们的官网查看步骤
> https://theme-next.org/docs/theme-settings/custom-pages
我再试试，感谢

**Comment by CapAllen** [comment]
> 
> 
> Seems it works fine?

But you'll get `404` when you click `category` or tag in `tag` page.

**Comment by JiangTJ** [comment]
@CapAllen Have to install plugins.
https://github.com/hexojs/hexo-generator-category
https://github.com/hexojs/hexo-generator-tag

**Comment by sli1989** [comment]
reinstall hexo maybe.

**Comment by CapAllen** [comment]
> 
> 
> @CapAllen Have to install plugins.
> https://github.com/hexojs/hexo-generator-category
> https://github.com/hexojs/hexo-generator-tag
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/6375567?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[hexojs/hexo-generator-category](https://github.com/hexojs/hexo-generator-category)**Category generator plugin for Hexo. Contribute to hexojs/hexo-generator-category development by creating an account on GitHub.
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/6375567?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[hexojs/hexo-generator-tag](https://github.com/hexojs/hexo-generator-tag)**Tag generator plugin for Hexo. Contribute to hexojs/hexo-generator-tag development by creating an account on GitHub.

It's WORKED!!! THX! :smile:

**Comment by CapAllen** [comment]
> 
> 
> reinstall hexo maybe.

Thx
