### ISSUE TITLE
Canvas-ribbon don't support Gemini scheme

### ISSUE THREAD

**Issue by Satomi12** [theme-next/hexo-theme-next#902]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this feature: N/A
* Link(s) to source code or any usefull link(s): N/A

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

**Comment by stevenjoezhang** [comment]
Emm...why? I'm just using canvas-ribbon with Gemini: https://zhangshuqiao.org

**Comment by Satomi12** [comment]
> Emm...why? I'm just using canvas-ribbon with Gemini: https://zhangshuqiao.org
> 
> > <img alt="" height="14" src="/images/favicon-16x16-next.png?v=7.1.2"> 米米的博客**[米米的博客](https://zhangshuqiao.org/index.html)**力电声光热，涵尽学海无涯

This is the _config.yml in theme-next:
<img width="386" alt="屏幕快照 2019-06-05 下午10 44 14" src="https://user-images.githubusercontent.com/43232897/58965786-baa1c280-87e3-11e9-9dcd-07f6a107a468.png">

**Comment by stevenjoezhang** [comment]
Seems that you are using an outdated version of NexT

**Comment by Satomi12** [comment]
> Seems that you are using an outdated version of NexT

Wow, that's true, thank you!
