### ISSUE TITLE
已经同时启用pangu与han，但只有pangu生效

### ISSUE THREAD

**Issue by shioko** [theme-next/hexo-theme-next#910]
如图，只有盘古加的空格，han部分的内容好像并没有生效
![](https://cmx.im/system/media_attachments/files/001/165/053/original/8d7bcbab0219451a.png?1542219355)
CSS文件似乎已经被读取了，但是js部分并没有？
![](https://cmx.im/system/media_attachments/files/001/165/056/original/d84e3610f6413cfd.png?1542219483)

**Comment by stevenjoezhang** [comment]
> CSS文件似乎已经被读取了，但是js部分并没有？

theme-next-han本身没有js部分。这是feature。
