### ISSUE TITLE
About theme-next-han

### ISSUE THREAD

**Issue by stevenjoezhang** [theme-next/hexo-theme-next#911]
Han，即「漢字標準格式」 印刷品般的漢字排版框架。（https://github.com/ethantw/Han）

该框架在 https://github.com/iissnan/hexo-theme-next/pull/1598 中被集成到NexT。不过值得注意的是，这只包含了css部分，而没有js部分。也就是说，它只产生了两个效果：
- 调整了一些margin、padding，以及blockquote等tag的样式
- 设置了中文的字体

对于第一条，Han对NexT原本样式的影响不小： https://github.com/iissnan/hexo-theme-next/issues/1645 ，事实上已经做出了一些妥协： https://github.com/iissnan/hexo-theme-next/blob/master/source/css/_common/components/third-party/han.styl
对于第二条，中文字体已经可以方便的通过`_config.yml`中的`font`定义。

另外，Han已经失去维护（上一个release已经是在4年之前）。

综上所述，从某种意义上讲，theme-next-han所导致的问题已经超出了Han所带来的正面效果——它并不适合NexT这种包含大量既定样式的主题。

是否需要考虑将其移除？

[![](https://api.gh-polls.com/poll/01DD2ZJN0TCAPE8Q707QXG0WJF/Remove)](https://api.gh-polls.com/poll/01DD2ZJN0TCAPE8Q707QXG0WJF/Remove/vote)
[![](https://api.gh-polls.com/poll/01DD2ZJN0TCAPE8Q707QXG0WJF/Remain)](https://api.gh-polls.com/poll/01DD2ZJN0TCAPE8Q707QXG0WJF/Remain/vote)

**Comment by 1v9** [comment]
Also see #910 & #800.

**Comment by jiangtj** [comment]
ethantw仍然在合并PR, 所以可以认为仍在维护. 但我支持移除.

---

ethantw is still merging PR, so it is still maintained. But I support remove.

**Comment by jiangtj** [comment]
Or consider integrating in a non-destructive way.
