### ISSUE TITLE
Comments that should exist in non-post pages disappear after refreshing the browser window

### ISSUE THREAD

**Issue by jingxinxin** [theme-next/hexo-theme-next#919]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
LiveRe can be used not only in posts, but also in pages. not work on pages，No comments. It only does work on posts

### Steps to reproduce the behavior 
1. Post comment
2. Refresh page
3. Comment disappear

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.15.3
6.9.0
```

### Package dependencies Information

```
"dependencies": {
    "hexo": "^3.8.0",
    "hexo-asset-image": "^1.0.0",
    "hexo-clean-css": "0.0.3",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-seo-friendly-sitemap": "0.0.25",
    "hexo-generator-tag": "^0.2.0",
    "hexo-related-popular-posts": "^3.0.6",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.6.0",
    "hexo-uglify": "0.0.5"
  },
  "devDependencies": {
    "babel-polyfill": "^6.26.0",
    "hexo-generator-sitemap": "^1.2.0"
  }
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.6.0 darwin x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
  # LiveRe comments system
  # You can get your uid from https://livere.com/insight/myCode (General web site)
  livere_uid: MTAyMC********TEg==
```

**Comment by stevenjoezhang** [comment]
Any URLs?

**Comment by jingxinxin** [comment]
@stevenjoezhang http://www.51201314.me/jacks/tags/
1. Post comment
2. Refresh page
3. Comment disappear

**Comment by jingxinxin** [comment]
@1v9 请问page页面可以支持liveRe评论吗？看你已经关闭了此问题

**Comment by 1v9** [comment]
@jingxinxin 你提供的页面 LiveRe 是正常工作的啊

**Comment by jingxinxin** [comment]
@1v9 参考一下前面说的呀，post页面是正常的，但是在pages页面下评论后刷新会消失，参考链接你可以测试一下

**Comment by jingxinxin** [comment]
@1v9 说的再清楚一点好了，文章页面下的评论没有问题，而什么标签页面啊，关于页面啊，分类页面啊下面的评论，页面刷新后就消失了，我检查过liveRe端评论都是写入了的，问题就出在这边

**Comment by jingxinxin** [comment]
@stevenjoezhang Can u speak Chinese ？(•‿•) U should understand what I mean. I saw someone leave a test message. It should be you.

**Comment by 1v9** [comment]
@jingxinxin 刷新后依然没问题

**Comment by 1v9** [comment]
@jingxinxin 我的，现在知道什么情况了

**Comment by 1v9** [comment]
@jingxinxin 已定位问题原因，等待我们修复。

**Comment by Accioy** [comment]
我用了最新版本的主题发现这个问题似乎仍然在，并没有解决，求助
