### ISSUE TITLE
Social icon not showing in site

### ISSUE THREAD

**Issue by ghost1372** [theme-next/hexo-theme-next#921]
hi i want to use icon but i cant see any icon in my site why?
```
social:
  GitHub: https://github.com || github

```

**Comment by 1v9** [comment]
No font-awesome dir in your [repo](https://github.com/ghost1372/ghost1372.github.io/tree/master/lib), so this [link](https://ghost1372.github.io/lib/font-awesome/css/font-awesome.min.css?v=4.6.2) is 404.

Done your deployment with proper operation or choose CDN to load fontawesome.

**Comment by ghost1372** [comment]
@1v9  tnx i installed fontawesome plugin in hexo but in deploy why fontawesome not included?
i use this command
```
hexo g
hexo d
```
can you help me to choose cdn and config in my site or deploy with best configuration?

**Comment by 1v9** [comment]
@ghost1372 It's not a plugin but a core dependency of NexT. Recently we updated .gitignore (see #832) to solve your issue. You can update your NexT and take a look. If not effect please tell us.

**Comment by ghost1372** [comment]
@1v9  tnx problem fixed
