### ISSUE TITLE
the label tag cannot work

### ISSUE THREAD

**Issue by yqsailor** [theme-next/hexo-theme-next#923]
I upgrade the next theme(version 7), but the label tag cannot word, for example:
```
<span class="label label-info">主题配置文件</span>
```

what should i do?

**Comment by 1v9** [comment]
Your format is wrong, NexT have built-in tag support.
See: https://theme-next.org/docs/tag-plugins/label
The following three formats are equivalent:
```
<span class="label warning">主题配置文件</span>
{% label warning@主题配置文件 %}
{% label warning @主题配置文件 %}
```

**Comment by stevenjoezhang** [comment]
@yqsailor The usage of `label` tag is here: https://theme-next.org/docs/tag-plugins/label
