### ISSUE TITLE
侧栏无论如何都不自动关闭

### ISSUE THREAD

**Issue by Monster0303** [theme-next/hexo-theme-next#933]
地址https://monster0303.github.io/

将侧栏移动到左边了，然后窗口缩小，侧栏也不自动隐藏了
  display: always
  onmobile: false

项目地址https://github.com/Monster0303/Monster0303.github.io
还需要提供什么配置文件吗

**Comment by stevenjoezhang** [comment]
> 然后窗口缩小，侧栏也不自动隐藏了

因为这不是常规的操作...如果是移动端的话，一开始就不会显示。

**Comment by Monster0303** [comment]
恩 不是移动端 是pc 在我把侧栏改到左侧之后这样的  我先不处理这个了  官方原生的支持Mist主题侧栏左置是不是不久之后就会出现了？

**Comment by stevenjoezhang** [comment]
曾经有这么一个PR：https://github.com/theme-next/hexo-theme-next/pull/164
但是没有人管了，最后不了了之...
未来应该会加上这个功能

**Comment by Monster0303** [comment]
> 曾经有这么一个PR：[＃164](https://github.com/theme-next/hexo-theme-next/pull/164)
> 但是没有人管了，最后不了了之... 
> 未来应该会加上这个功能

好的 看完 #164 我决定长期打开onmobile：true，不管以后会不会添加这个功能，至少还有关闭侧栏的按钮，多谢，时间就是金钱，地精朋友
