### ISSUE TITLE
About Gitment

### ISSUE THREAD

**Issue by stevenjoezhang** [theme-next/hexo-theme-next#936]
[Gitment](https://github.com/imsun/gitment)是一个评论系统，在 https://github.com/iissnan/hexo-theme-next/commit/87a4b6801b7deb1b0584aec133dd7bed2c114991 被集成到NexT中。

[Gitment](https://github.com/imsun/gitment) is a comment system which was integrated into theme NexT at https://github.com/iissnan/hexo-theme-next/commit/87a4b6801b7deb1b0584aec133dd7bed2c114991

然而，该项目已经停止维护，并带来了种种问题。原作者在代码中硬编码了一个代理服务器，由于证书过期且未更新，其官方版本已经无法使用：https://github.com/imsun/gitment/issues/170

However, the project has stopped maintenance and caused problems. The original author hardcoded a proxy server in the code, but the certificate of the server has expired. As a result, the official version is no longer available: https://github.com/imsun/gitment/issues/170

目前，NexT使用的版本更改了部分代码，暂时性地为Gitment续命：https://github.com/theme-next/theme-next-gitment

We temporarily modified some code to make it work: https://github.com/theme-next/theme-next-gitment

但这并不是长久之计——失去维护的同时还带来了一些潜在的风险：https://github.com/theme-next/theme-next.org/issues/49

But that is not a long-term solution - A lost maintenance project presents potential risks: https://github.com/theme-next/theme-next.org/issues/49

为此，一个较为可行的解决方案是迁移到[Gitalk](https://github.com/gitalk/gitalk)，两者都基于GitHub issue，迁移只需要修改标签即可：https://github.com/gitalk/gitalk/issues/39

Therefore, a more feasible solution is migrated to [Gitalk](https://github.com/gitalk/gitalk). Both of them are based on GitHub issue, so you just need to modify labels of the issue to migrate from Gitment to Gitalk: https://github.com/gitalk/gitalk/issues/39

是否需要将Gitment从NexT中移除？

Need to remove Gitment from NexT?

[![](https://api.gh-polls.com/poll/01DEEQSXKFBZNGHRVS12GHK5RW/Remove)](https://api.gh-polls.com/poll/01DEEQSXKFBZNGHRVS12GHK5RW/Remove/vote)
[![](https://api.gh-polls.com/poll/01DEEQSXKFBZNGHRVS12GHK5RW/Remain)](https://api.gh-polls.com/poll/01DEEQSXKFBZNGHRVS12GHK5RW/Remain/vote)

**Comment by BianChengNan** [comment]
has `next` integrated `gitalk` already?

**Comment by stevenjoezhang** [comment]
@BianChengNan yes, indeed
