### ISSUE TITLE
Use FontAwesome 5 or custom .svg files

### ISSUE THREAD

**Issue by maddovr** [theme-next/hexo-theme-next#94]
FontAwesome 5 has been released with many new icons even in the free version(e.g: discord icon was added which is quite good for the social bar). However I would also like to suggest the option to use custom .svg files specifying a path.

**Comment by ivan-nginx** [comment]
Is is paid version?

**Comment by maddovr** [comment]
No, it's in the free version https://fontawesome.com/icons?d=gallery&q=discord&m=free

**Comment by maddovr** [comment]
To update a bit, it's not possible to use the CDN version of FontAwesome5 either, so there must be some compatibility changes from 4.x to 5.x

**Comment by maddovr** [comment]
So, a bit of an update: I've looked into upgrading from version 4 to version 5 and a regular upgrade is as trivial as modifying the default `fa` prefix in the configuration files(I think only `next/layout` folder is relevant for this). However since new color schemes are in the timeline, I think a refactor of how fontawesome is being invoked should be taken into consideration due to the new features fontawesome 5 offers(more info here: https://fontawesome.com/how-to-use/svg-with-js#additional-styling), and that's not trivial. At least, I don't see an easy way to do so.

**Comment by maddovr** [comment]
Not a proper upgrade, but we could use the v4 shim as described [here](https://fontawesome.com/how-to-use/upgrading-from-4) as a temporary solution.

**Comment by ivan-nginx** [comment]
This issue will be closed in accordance with #505  issue.
