### ISSUE TITLE
Would you consider to add support for Google Adsense?

### ISSUE THREAD

**Issue by panqiincs** [theme-next/hexo-theme-next#942]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

I know nothing about the technical level of Hexo, so I want to ask if Google Adsense support can be implemented. 

Or it is easy, but you don't like the feature and won't implement it?

**Comment by 1v9** [comment]
We support [custom head](https://github.com/theme-next/hexo-theme-next/blob/v7.2.0/_config.yml#L20), just put your Google Adsense code snippet in it, it's not difficult.

**Comment by panqiincs** [comment]
@1v9 I get it, many thanks.

**Comment by qzi** [comment]
> @1v9 I get it, many thanks.

I created the 

> We support [custom head](https://github.com/theme-next/hexo-theme-next/blob/v7.2.0/_config.yml#L16-L20), just put your Google Adsense code snippet in it, it's not difficult.

I add <script></scriprt> to /source/_data/header.swig, it got failed
