### ISSUE TITLE
The problem of picture path 

### ISSUE THREAD

**Issue by dalaizhao** [theme-next/hexo-theme-next#956]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
use this way showing  my picture on blog.
`post_asset_folder: true`  and `npm install hexo-asset-image --save`, 

but picture generate path is wrong. 

### Actual behavior 

i want to show picture on my theme next, when  ' hexo g'  , the picture path is 
···
update link as:-->/p/2bc5.htm/1.PNG
update link as:-->/p/2bc5.htm/2.PNG
update link as:-->/p/2bc5.htm/3.PNG
update link as:-->/p/2bc5.htm/4.PNG
update link as:-->/p/2bc5.htm/5.PNG
···
it is more generate '.htm' , resulting in after "hexo d" the picture path is not showing 

i am clear ?

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
Is this plugin working in other themes (e.g. default theme `landscape`)?
If not, please ask maintainers of `hexo-asset-image` for help.

**Comment by dalaizhao** [comment]
> Is this plugin working in other themes (e.g. default theme `landscape`)?
> If not, please ask maintainers of `hexo-asset-image` for help.

ok, i will asking maintainers of hexo-asset-image for help , please do not close issue until it solve

**Comment by dalaizhao** [comment]
i get it , is hexo-asset-image fault , 
make hexo-asset-image directory  file index.js  
number 24  set`  var endPos = link.length-1;` change `var endPos = link.length-1;` , it work.
