### ISSUE TITLE
Should be abolished    border-bottom:1px solid #eee

### ISSUE THREAD

**Issue by aixiu** [theme-next/hexo-theme-next#962]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this feature: N/A
* Link(s) to source code or any usefull link(s): N/A

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

All .post-body h2  and .post-body h2 and so on
Should be abolished    border-bottom:1px solid #eee
If you use too much, the whole article will have too many horizontal lines. It affects beauty.

**Comment by stevenjoezhang** [comment]
You can use custom css file to set `border-bottom: none;`

**Comment by aixiu** [comment]
ok thx.
