### ISSUE TITLE
提个问题：侧栏中添加网易云音乐的歌单

### ISSUE THREAD

**Issue by yltx** [theme-next/hexo-theme-next#972]
我提个建议：我用的是NexT.Mist v7.0.0，然后在侧边栏手动添加了一个网易云音乐的歌单，结果是现在挡住了一部分阅读进度数字，建议把阅读进度的数字向上调一点

![](https://i.loli.net/2019/07/13/5d297de55811f98233.png)

网址：yltx.cf

English:

A suggestion

Here's a suggestion: I used Next. Mist v7.0.0, and then manually added a song list of Netease Cloud Music to the sidebar. The result was
Now that some of the reading progress figures are blocked, it is suggested that the reading progress figures be raised a little.

![](https://i.loli.net/2019/07/13/5d297de55811f98233.png)

Website:yltx.cf

**Comment by ouuan** [comment]
I think the problems caused by custom changes should be solved by yourself.

**Comment by yltx** [comment]
> I think the problems caused by custom changes should be solved by yourself.

In fact, I would like to remind you that there was a problem in your blog before. Your Hitokoto blocked the reading progress bar, which was more serious than mine, but I haven't found a solution yet.

P.S.: Please don't try to use English unwisely with me. I am a student of a foreign language school and I have taken the English level examination.

**Comment by yltx** [comment]
> I think the problems caused by custom changes should be solved by yourself.

And the Internet is a public area. If a person can't solve his own problems, he can ask others on the Internet. The biggest advantage of the Internet is that people will help each other.

**Comment by ouuan** [comment]
> > I think the problems caused by custom changes should be solved by yourself.
> 
> In fact, I would like to remind you that there was a problem in your blog before. Your Hitokoto blocked the reading progress bar, which was more serious than mine, but I haven't found a solution yet.
> 
> P.S.: Please don't try to use English unwisely with me. I am a student of a foreign language school and I have taken the English level examination.

I think there is no problem with Hitokoto in my blog. Automatically hiding when reading the blog is a great feature. You can focus on the blog (and the table of contents) in this way.

I didn't get your P.S, were you suggesting me to speak Chinese or did you forget to point out my grammar mistake?

**Comment by ouuan** [comment]
> > I think the problems caused by custom changes should be solved by yourself.
> 
> And the Internet is a public area. If a person can't solve his own problems, he can ask others on the Internet. The biggest advantage of the Internet is that people will help each other.

Your are "making a suggestion" in an issue, that means you are suggesting make a change because of your personal problem, am I right? If you only want to get some help, why is the title "
提个建议"?

**Comment by 1v9** [comment]
Keep calm everybody 😉

**Comment by stevenjoezhang** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

**Comment by yltx** [comment]
> > > I think the problems caused by custom changes should be solved by yourself.
> > 
> > 
> > And the Internet is a public area. If a person can't solve his own problems, he can ask others on the Internet. The biggest advantage of the Internet is that people will help each other.
> 
> Your are "making a suggestion" in an issue, that means you are suggesting make a change because of your personal problem, am I right? If you only want to get some help, why is the title "提个建议"?

Sorry, I forgot to save the screenshot, so I can't accurately describe the problem of your blog I saw before. Because Hitoko in your blog really blocked part of the progress bar, so I think it may be a bug. Then I opend this issue to make a suggestion if it is a real bug. Why are you seemed to be angry?

And I added the Non-English tag,why are we talking in English?

**Comment by stevenjoezhang** [comment]
加一行自定义CSS就行
```
#music163player { margin-top: 30px; }
```

**Comment by yltx** [comment]
> 加一行自定义CSS就行
> 
> ```
> #music163player { margin-top: 30px; }
> ```

在哪里加啊

**Comment by yltx** [comment]
> #music163player { margin-top: 30px; }

OK，自己找到在哪儿加了……谢谢

**Comment by stevenjoezhang** [comment]
在`_config.yml`或`next.yml`中，设置
```
custom_file_path:
  style: source/_data/styles.styl
```
然后，创建`source/_data/styles.styl`，把这行代码加进去即可

**Comment by yltx** [comment]
> 在`_config.yml`或`next.yml`中，设置
> 
> ```
> custom_file_path:
>   style: source/_data/styles.styl
> ```
> 
> 然后，创建`source/_data/styles.styl`，把这行代码加进去即可

然而好像没什么用？

**Comment by stevenjoezhang** [comment]
清空Hexo和浏览器的缓存，然后重新生成

**Comment by yltx** [comment]
> 清空Hexo和浏览器的缓存，然后重新生成

清空过了，然而还是没用啊

**Comment by jiangtj** [comment]
https://github.com/theme-next/hexo-theme-next/issues/973 这个issue的评论可能对你有帮助

**Comment by yltx** [comment]
> #973 这个issue的评论可能对你有帮助

窝用的v7.0.0的，所以这个貌似不适用我

**Comment by stevenjoezhang** [comment]
7.0.0就把自定义CSS加到`source/css/_custom/custom.styl`中

**Comment by stevenjoezhang** [comment]
NexT主题不再对旧版本提供技术支持。
请诸位友善讨论，共同维护良好的社区环境。
