### ISSUE TITLE
Can we use a language.yml file in Hexo's source folder for custom translation

### ISSUE THREAD

**Issue by lei2rock** [theme-next/hexo-theme-next#974]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

Use a `language.yml` file (such as `zh-CN.yml`) in site directory `/source/_data/` folder for custom translation, just like the existing custom files in site directory `source/_data` for custom styles and layout. Then we do not need to edit the language files in theme directory `/themes/next/language/` for custom translation any more (keep theme folder unchanged).

### Actual behavior 

Edit the language files in theme directory `/themes/next/language/` for custom translation.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this feature: N/A
* Link(s) to source code or any usefull link(s): N/A

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by lei2rock** [comment]
Solved with the script in [jiangtj/blog](https://github.com/jiangtj/blog)

**Comment by jiangtj** [comment]
> Solved with the script in [jiangtj/blog](https://github.com/jiangtj/blog)

??? This is part of NexT's ability to merge external i18n files, I don't seem to have any modifications.

**Comment by lei2rock** [comment]
> > Solved with the script in [jiangtj/blog](https://github.com/jiangtj/blog)
> 
> ??? This is part of NexT's ability to merge external i18n files, I don't seem to have any modifications.

LOL, but it really works for me! 😂😂

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/3595

**Comment by jiangtj** [comment]
😂 NexT has this feature, but it doesn't seem to be written in the documentation.
