### ISSUE TITLE
Unexpected broken picture appears in sidebar.

### ISSUE THREAD

**Issue by Liam0205** [theme-next/hexo-theme-next#975]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

![image](https://user-images.githubusercontent.com/3348485/61260977-d6b95c00-a7b2-11e9-825c-8eeb4398d2a5.png)

### Actual behavior 

![image](https://user-images.githubusercontent.com/3348485/61260995-e042c400-a7b2-11e9-9384-fb06ae76eb0c.png)

### Steps to reproduce the behavior 
1. merge latest commits (#971 ) into local NexT theme directory.
2. execute `hexo s` to run local server.
3. check the side bar.

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
$ node -v && npm -v
v10.13.0
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "dtrace-provider": "^0.8.7",
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "hexo-symbols-count-time": "^0.4.4"
  }
}
```

#### Hexo version

```
$ hexo -v
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.8.0
node: 10.13.0
v8: 6.8.275.32-node.36
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0i
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

See #658 .
```yml

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

Note: I didn't test for other schemes.

#### NexT Configuration:

See #658 .
```yml

```

### Other Information 

Browser: Chrome 75.0.3770.142
System: macOS 14, Windows7

**Comment by jiangtj** [comment]
I can't reproduce. Orz
![image](https://user-images.githubusercontent.com/15902347/61263769-c4442000-a7bc-11e9-8b63-64e8dbfcbd11.png)
![image](https://user-images.githubusercontent.com/15902347/61263844-f786af00-a7bc-11e9-82c2-68750e94b721.png)
What's this? avatar?

**Comment by Liam0205** [comment]
@jiangtj 

It seems to be a custom logo image.

![image](https://user-images.githubusercontent.com/3348485/61263933-46ccdf80-a7bd-11e9-9dd6-874fe4409e35.png)

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/61264079-c490eb00-a7bd-11e9-85e7-41fe852c0315.png)

This maybe work well.

Can you check `custom_logo` in theme config.
![image](https://user-images.githubusercontent.com/15902347/61264122-f86c1080-a7bd-11e9-805a-8b3a4f04de4a.png)

**Comment by Liam0205** [comment]
Hmmmm...

I've figured it out. This is because the incompatibility introduced by #965 . mimi refactored the theme config file, and the relative part of `custom_logo` was changed from

```
custom_logo:
  enbale: false
  image: 
```

to 

```
custom_logo: # invalid path
```

however, I copied the following snippet into `source/_data/next.yml`, which eventually causes the problem.

```
custom_logo:
  enbale: false
  image: 
```

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/61264214-45e87d80-a7be-11e9-9b3d-57617e3ab3ef.png)
https://github.com/theme-next/hexo-theme-next/pull/965  Yeah, breaking change in here.

**Comment by Liam0205** [comment]
Based on the above discussion, this issue could be closed.
