### ISSUE TITLE
文章底部的前一篇显示位置出现在右边、下一篇的显示位置出现在左边。发生了反转。求复原。谢谢！

### ISSUE THREAD

**Issue by dhengyi** [theme-next/hexo-theme-next#983]
- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

根据人们的使用习惯来说，文章底部通往前一篇的快捷链接应出现在左侧，通往下一篇的快捷链接应出现在右侧。

### Actual behavior 

实际出现的情况与人们的惯用习惯相反，文章底部通往前一篇的快捷链接出现在右侧，通往下一篇的快捷链接出现在左侧。

* Link to demo site with this issue: [出现问题的网站](https://blog.dhengyi.name/2018/10/03/Java%E5%B9%B6%E5%8F%91-%E5%8E%9F%E5%AD%90%E5%8F%98%E9%87%8F%E7%B1%BB%E7%9A%84%E4%BD%BF%E7%94%A8/)。

### Node.js and NPM Information

```
$ node -v
v10.1.0

$ npm -v
5.6.0
```

### Package dependencies Information

```
$ cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "fullpage.js": "^3.0.4",
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-leancloud-counter-security": "^1.3.3",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.4.4",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-tag-dplayer": "^0.3.3"
  }
}
```

#### Hexo version

```
$ hexo -v
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.1.0
v8: 6.6.346.27-node.6
uv: 1.20.2
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.29.0
napi: 3
openssl: 1.1.0h
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [X] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by stevenjoezhang** [comment]
这个和wordpress中的方向是一致的。之前在iissnan的repo中就有讨论过这个问题，最终认为这是满足大部分人习惯的。

**Comment by dhengyi** [comment]
> 这个和wordpress中的方向是一致的。之前在iissnan的repo中就有讨论过这个问题，最终认为这满足大部分人的习惯。
> 
> 如果需要的话，可以手动改这一部分：
> https://github.com/theme-next/hexo-theme-next/blob/d0e52164b8ae0f66014f7f1465284ea04903a97d/layout/_macro/post.swig#L420-L438

thanks，问题已解决，但是提出一点不同的观点哈，，，我还是觉得上一篇在左，下一篇在右的显示方式，符合大众的习惯，也许只是我个人的错觉吧，哈哈~~~

**Comment by Raincal** [comment]
由于文章排列方式是倒序，你所指的下一篇其实就是上一篇，这么想就能接受了

**Comment by dhengyi** [comment]
thanks！

**Comment by stevenjoezhang** [comment]
Superseded by https://github.com/theme-next/hexo-theme-next/commit/14172486dfb480aa80d467592963f57cc0bb734d
