### ISSUE TITLE
Mist主题页脚文本不会居中！

### ISSUE THREAD

**Issue by suyin-long** [theme-next/hexo-theme-next#992]
Mist主题页脚上的文本默认不是居中的，但是在除Google浏览器以外的浏览器使用半屏浏览网页的时候，页脚文本会居中。
问题是在Google浏览器上不会居中的话，有时会遮挡页脚信息！希望默认是页脚内容居中显示！
如图：是在Google浏览器中的问题演示！
![2](https://user-images.githubusercontent.com/49554285/61610352-7d0dd180-ac8b-11e9-89d5-095ca461fa29.png)

**Comment by stevenjoezhang** [comment]
> 希望默认是页脚内容居中显示！

Mist主题设计风格就是左对齐……

这个确实没有什么好办法，目前是通过按钮的透明度来防止遮挡

**Comment by stevenjoezhang** [comment]
另见：https://github.com/iissnan/hexo-theme-next/pull/1981
