### ISSUE TITLE
网页半屏显示问题！

### ISSUE THREAD

**Issue by suyin-long** [theme-next/hexo-theme-next#993]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this feature: N/A
* Link(s) to source code or any usefull link(s): N/A

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [x] Gemini

Pisces和Gemini这两个主题在Windows上以半屏显示的时候目录占了1/2的屏幕，正文占了1/2，由于目录一般要短于正文，所以屏幕的1/2空间都处于浪费状态，这也导致半屏阅读非常不舒服，体验较差！
希望可以在半屏的状态下可以把目录自动隐藏手动可以调出来！类似Mist和Muse的效果！
如图：
![1](https://user-images.githubusercontent.com/49554285/61631959-4f8e4b80-acbe-11e9-8393-21abef2e5f1f.png)
![2](https://user-images.githubusercontent.com/49554285/61631968-53ba6900-acbe-11e9-8e50-9f117c9f5aa4.png)
![3](https://user-images.githubusercontent.com/49554285/61631974-561cc300-acbe-11e9-8455-f5f5636a72d1.png)

**Comment by stevenjoezhang** [comment]
你用的是什么浏览器？由于主题是响应式设计，半屏显示的时候进入移动端的页面就没有这个问题了

**Comment by suyin-long** [comment]
Chrome浏览器，在pc上半屏显示就会出现这个问题！
经过测试只有在Chrome上才这样，其他浏览器半屏显示都是正常的！

**Comment by suyin-long** [comment]
| |
suyin_long
|
|
suyin_long@163.com
|
Chrome的浏览器，在PC上半屏显示就会出现这个问题！
经过测试只有在Chrome浏览器上才这样，其他浏览器半屏显示都是正常的！
签名由网易邮箱大师定制
在2019年7月23日 10:24，ᴍɪᴍɪ<notifications@github.com> 写道：

你用的是什么浏览器？由于主题是响应式设计，半屏显示的时候进入移动端的页面就没有这个问题了

**Comment by stevenjoezhang** [comment]
> 经过测试只有在Chrome上才这样，其他浏览器半屏显示都是正常的！

所以这不是NexT的锅？建议直接向chrome/chromium维护者报告此问题。
