### ISSUE TITLE
希望可以给Muse 和 Mist主题添加主题背景！

### ISSUE THREAD

**Issue by suyin-long** [theme-next/hexo-theme-next#994]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this feature: N/A
* Link(s) to source code or any usefull link(s): N/A

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

问题：
Muse 和 Mist两个主题正文部分没有单独浮于网站页面的背景，这导致如果启用了页面2d或3d动画会对阅读正文造成干扰，希望可以给Muse 和 Mist两个主题添加一个类似于Pisces 和 Gemini的正文背景。
如图所示：
![1](https://user-images.githubusercontent.com/49554285/61633095-eb20bb80-acc0-11e9-9773-23d21f03453c.png)
![2](https://user-images.githubusercontent.com/49554285/61633099-ed831580-acc0-11e9-8bd2-32a0e87ae22c.png)

**Comment by stevenjoezhang** [comment]
Pisces 和 Gemini正文背景颜色和body背景颜色不同，形成一个层次上的分界，所以看上去没有问题。
如果要给Muse 和 Mist加背景，那么用什么颜色呢？
- 白色，会破坏2d或3d动画背景的层次
- 其它颜色，会破坏Muse 和 Mist本身的设计

所以个人建议通过其它方式减少对阅读正文造成的干扰，例如设置透明度。

**Comment by suyin-long** [comment]
好的！那个我可以自己给正文部分添加一个白色的背景吗？


| |
suyin_long
|
|
suyin_long@163.com
|
签名由网易邮箱大师定制
在2019年7月22日 22:24，ᴍɪᴍɪ<notifications@github.com> 写道：

Pisces 和 Gemini正文背景颜色和body背景颜色不同，形成一个层次上的分界，所以看上去没有问题。
如果要给Muse 和 Mist加背景，那么用什么颜色呢？

白色，会破坏2d或3d动画背景的层次
其它颜色，会破坏Muse 和 Mist本身的设计

所以个人建议通过其它方式减少对阅读正文造成的干扰，例如设置透明度。

**Comment by stevenjoezhang** [comment]
当然可以！这样设置就行了：
```
.container .main-inner {
  background-color: white;
}
```

**Comment by suyin-long** [comment]
ok，学到了
